### ISSUE TITLE
Null StoreMediaOptions.Directory and StoreMediaOptions.Name Generates ArgumentNullException

### ISSUE THREAD

**Issue by Rhipeus** [jamesmontemagno/MediaPlugin#100]
In version 2.6.0, the new regular expression code filter out invalid characters in StoreMediaOptions.Name and StoreMediaOptions.Directory in MediaImplementation.VerifyOptions, throws an ArgumentNullException when those properties are null on Android (maybe others?).  Should be able to use the StoreMediaOptions without having to specify the Name and Directory properties when calling TakePhotoAsync and TakeVideoAsync.

Workaround is to set them to an empty string.

**Comment by jamesmontemagno** [comment]
Yes, will fix right now, I think null sets it to the default. Let me clean up.  and release a new beta

**Comment by jamesmontemagno** [comment]
beta 3 will be out in like 5 minutes with fix only impacts android
