### ISSUE TITLE
[Feature Request] Max Width/Height for pictures

### ISSUE THREAD

**Issue by Glabenwitt** [jamesmontemagno/MediaPlugin#103]
Actualliy we can only specify a percent of the original image size we want. It would be great to have the ability to set a max Width and Max Height to have an image size independant of device camera resolution.

PS: Sory for my english but I think you will understand my request ;)

Thanks

**Comment by hbraasch** [comment]
Also, specify the image size as the max of file size (in bytes), or max width/max height

**Comment by xeterixon** [comment]
We have somewhat the same requirements for our apps, that is setting a max height or width of the resulting image. I forked the repo and had a go at it. It seems to work rather well on iOS and Droid, but currently not on UWP. I'm not ready to do a pull request yet, but you can have a look at the diff, if that helps.
[https://github.com/jamesmontemagno/MediaPlugin/compare/master...xeterixon:master]

**Comment by mikece** [comment]
+1 This would be a useful feature!

**Comment by kshnbd** [comment]
Is this too difficult to implement this feature? PhotoSize in percentage how this has been implemented in this plugin is totally useless when all the phones have different megapixel cameras.
