### ISSUE TITLE
iOS orientation changes automatically

### ISSUE THREAD

**Issue by gmeredith** [jamesmontemagno/MediaPlugin#104]
## Bug 

Version Number of Plugin: 2.3.0 & 2.6.0 beta3
Device Tested On: iPhone 6s 9.3.4
Simulator Tested On: none - can't take picture on  MacInCloud

### Expected Behavior
When a picture is taken it will be in same orientation that phone was in

### Actual Behavior
Take a portrait orientation picture, when displayed on phone it is still portrait. When saved to DB/display on separate website picture is 90 degrees counterclockwise.

### Steps to reproduce the Behavior
just using the sample code + saving to DB

This feature works correctly on Droid, specifically a Motorola Droid. The picture orientation is the same throughout the entire process, even viewing on separate website. The picture is correct, just rotated 90 degrees left. I tried it with 2.3 and with the above beta3 version - same results.

Any help/direction is appreciated.
Thanks,
Glen

**Comment by jamesmontemagno** [comment]
This could just have to do with the EXIF information an how your phone is taking it. I have tested it on iPads and iPhones and haven't really seen any issues at all as the iOS library doesn't perform any rotation.

**Comment by gmeredith** [comment]
James,
Thanks. I understand your point. However, any other photo I take on my camera straight up doesn’t rotate. How do I solve it? Do I have to add logic to rotate 90 right if an iPhone took the picture?

Glen Meredith
