### ISSUE TITLE
Video Recorder Not working on Samsung Galaxy S7 w/ External SD Card

### ISSUE THREAD

**Issue by chrisdiaz** [jamesmontemagno/MediaPlugin#107]
Launching the camera is fine, recording seems fine, but the final result (mp4 file) is not fine. What is happening instead of recording a video, is the first file (whether it's a video or image) you have in the device's Camera Gallery is being copied and placed in the output file you specify in code.

Version Number of Plugin: 2.3.0, 2.6.0.4-beta
Device Tested On: Samsung Galaxy S7 w/ External SD Card (Android 6.0.1)
Simulator Tested On:

### Expected Behavior
Record a video and the file output is the video you just recorded.

### Actual Behavior
The last file (whether it's an image or video) in the Camera Gallery is **copied** to the file destination you specified, not the video you actually recorded.  So if the last file in the Gallery is a JPG image and you use this library to record ai video, it takes that JPG and coverts it to an mp4.

### Steps to reproduce the Behavior

1. Create a simple app or even use the example app provided in Media Plugins repo. 
2. Take a video. 
3. Press OK to confirm and use video you just recorded. 
4. Go to the directory you specified where to save the output video file.
5.  Notice that it's not the video you just recorded, but instead, it's a copy of the last file you have in the Camera Gallery.

NOTE: Taking a picture is working as expected.

**Comment by jamesmontemagno** [comment]
I wasn't able to reproduce this at all on my devices here (Nexus 6P (7.0) and Nexus 6 (6.0.1)). They don't have external SD cards though and I don't own anything that does, but by default they use emulated sd storage so it should be the same. 

I would debug through the code and check, but it was working fine on both of my devices.
