### ISSUE TITLE
Cannot call CrossMedia.Current.Initialize(); in Shared Project

### ISSUE THREAD

**Issue by NhatHo** [jamesmontemagno/MediaPlugin#108]
I'm trying to use camera in Shared Project, the README file only mentions PCL so I'm not sure if I can use this plugin in Shared Project in the same way or not.

## Bug 
I got this exception when I try to call CrossMedia.Current.Initialize()

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

I already include this plugin in all of my platform specific projects (testing on iOS right now). Do I need to set it up specifically in iOS project at all? If yes, then how can I do that?

Version Number of Plugin: 
Device Tested On: iPad Mini 4

### Expected Behavior
Able to start Camera and take a picture

### Actual Behavior
Cannot initialize CrossMedia

### Steps to reproduce the Behavior
Use takePhoto.Clicked function in https://github.com/jamesmontemagno/MediaPlugin/blob/master/samples/MediaSample/MediaSample/MediaPage.xaml.cs

## Feature Request:
If you have any instruction on how to set it up in Shared Project it would be great.

**Comment by jamesmontemagno** [comment]
It works fine shared projects. Perhaps something went wrong with your NuGet install? See what your iOS project is referencing it should be from the Xamarin.iOS10 folder.

**Comment by MetaFight** [comment]
I have this issue with my Android client as well.  I checked the references after the NuGet install and everything seems to be pointing to the right place.  I'll try reinstalling the NuGet package.

**Comment by Saccomani** [comment]
same issure here...on android n

**Comment by protokovich** [comment]
Just looked at Path of Plugin.Media and Plugin.Media.Abstractions References:
packages\Xam.Plugin.Media.3.0.0.62-alpha\lib\netstandard1.0\Plugin.Media.dll
packages\Xam.Plugin.Media.3.0.0.62-alpha\lib\netstandard1.0\Plugin.Media.Abstractions.dll

netstandard1.0 ??

wtf ?) i'm using shared code approach. not pcl, and not netstandard

**Comment by protokovich** [comment]
if i manually add "normal" path (MonoDroid), then:
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Xamarin.Android.Support.Core.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Xamarin.Android.Support.Core.Utils.dll'

downgrade to 2.6.3.30

**Comment by jamesmontemagno** [comment]
So @protokovich you should open a new issue, but really what is happening here is that you now need to compile against Android 7.0+ to use the new pre-release nugets. I am fixing up my nuget currently as there is a weird issue if you aren't targeting 7.0 where it installs the wrong libraries. I am having a new release in a few minutes here to fix it up, but essentially Compile against 7.0 and then re-install the NuGet
