### ISSUE TITLE
Taken picture rotates incorrectly sometimes. (STILL in 2.6.0.9)

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/MediaPlugin#112]
media plugin : 2.6.0.9 beta
Device : LG G3 Android 6.0

## Bug 

Taken picture rotates incorrectly sometimes. 
I know it's been fixed. 
And I saw it's fixed on my Galaxy S4.
Today, I bought used LG G3 for test and took some picture. 

I took photos in Portrait mode. (I'm sure)
But some photos went landscape, some of them did not.
It's not only shown on LG G3.

**Comment by allbdeveloper** [comment]
It's reproduced on 2.4.0 on LG G3 android 6.0. (on Sample App)
Even if I pick photo from gallery, 
It will be rotated 90 degree.

**Comment by jamesmontemagno** [comment]
This most likely means that the photo has no Exif data and there is no way for me to know how to rotate it, so I don't: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs#L641-L661

This is where I get the rotation and then here is where I rotate it based on the matrix: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs#L460-L479

I only do this when you take the photo, not when you pick from the gallery... I will adjust it to also attempt to rotate when it comes from the gallery. Try 2.6.0.12-beta. That is the only thing I can do if there is no Exif data available. The best thing to do is try to debug through the code using the "test" folder project, which allows you to debug the source code with the sample on your device.

**Comment by allbdeveloper** [comment]
Thanks for your guide. I really appreciate.
