### ISSUE TITLE
Crashes after taking/capturing 3 images

### ISSUE THREAD

**Issue by abdulkhn8** [jamesmontemagno/MediaPlugin#113]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Gionee P3 4.4.2,
Simulator Tested On:  Visual studio emulator 5" kitkat 4.4

### Expected Behavior
  should take/capture images as much user want to take.
### Actual Behavior
  After capturing or taking 3 images, on capturing 4th image, as i click ok button, some it crashes the app some time it navigates back. 

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
You will want to ensure that you dispose of the images after taking them. 

Also I would suggest trying the latest beta packages as I haven't seen this in a while as it contains  a lot of fixes.

**Comment by FredBesterwitch** [comment]
James, 
Thanks For the plugin.

I'm still getting this error in 2.7.0.50..
Take more than 2-3 images it crashes on IOS & Android.

My C# Code


`  private async void btn_Take_Photo_Clicked(object sender, EventArgs e)
        {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
                return;
            }

            try
            {
                using (var photo = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions()
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                }))
                {
                    if (photo != null)
                    {
                        Debug.WriteLine(photo.Path);
                        PhotoImage.Source = null;
                        PhotoImage.Source = ImageSource.FromStream(() => { return photo.GetStream(); });
                    }
                }
            }
            catch (Exception ex)
            {

            }

        }

`XAML
`  <Image x:Name="PhotoImage" />
                <Button x:Name="btn_Take_Photo" Text="Take Photo" Clicked="btn_Take_Photo_Clicked" Grid.Row="1" />`
