### ISSUE TITLE
CustomOverlay

### ISSUE THREAD

**Issue by balivo** [jamesmontemagno/MediaPlugin#114]
It's possible use a custom overlay (PNG) file?

**Comment by jamesmontemagno** [comment]
On iOS you can I have a sample in the Test folder you can look at. It is in the beta version.

**Comment by jamesmontemagno** [comment]
Specifically here https://github.com/jamesmontemagno/MediaPlugin/blob/master/tests/MediaTest/MediaTest.iOS/ViewController.cs

**Comment by balivo** [comment]
Tks @jamesmontemagno for fast reply!

I see iOS version...

Pull Requests are welcome? I can help with Android... Or something... It's a really important feature for some projects here...

**Comment by jamesmontemagno** [comment]
For Android/Windows we just launch the external camera and they don't support overlays at all.

You will most likely need to go with custom implementations to really control it such as:

**Comment by nicotp80** [comment]
I've a custom overlay image to use in Ios, but i don't see when camera is open. Maybe i wrong something, can you help me? I create a dependecy injection interface for use overlay func : 

`    public interface IPhotoOverlay
    {
        object GetImageOverlayAsync();
    }`

On pcl i use this method for call camera : 

`        private async void TakePhoto(object sender, EventArgs e)
        {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                DisplayAlert("No Camera", ":( No camera available.", "OK");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                OverlayViewProvider = DependencyService.Get<IPhotoOverlay>().GetImageOverlayAsync,
                AllowCropping = true,
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                SaveToAlbum = false,
                RotateImage = true
                
            });

            if (file == null)
                return;

            using (var ms = new MemoryStream())
            {
                var stream = file.GetStreamWithImageRotatedForExternalStorage();

                byte[] img = GetImageStreamAsBytes(stream);
            }
        }

        public byte[] GetImageStreamAsBytes(Stream input)
        {
            var buffer = new byte[16 * 1024];
            using (MemoryStream ms = new MemoryStream())
            {
                int read;
                while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                {
                    ms.Write(buffer, 0, read);
                }
                return ms.ToArray();
            }
        }
`

And on iOS project : 

`using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Foundation;
using MyNameSpace.iOS;
using MyNameSpace.Services;
using UIKit;
using Xamarin.Forms;

[assembly: Dependency(typeof(PhotoOverlayiOS))]
namespace MyNameSpace.iOS
{
    public class PhotoOverlayiOS : IPhotoOverlay
    {

        public object GetImageOverlayAsync()
        {
            Func<object> func = CreateOverlay;

            return func;
        }

        public object CreateOverlay()
        {
            var imageView = new UIImageView(UIImage.FromBundle("OverlayNew"));
            imageView.ContentMode = UIViewContentMode.ScaleAspectFit;

            var screen = UIScreen.MainScreen.Bounds;
            imageView.Frame = screen;

            return imageView;
        }
    }
}`

OverlayNew is a png file 1024x683.

I'm hope you can help me.
