### ISSUE TITLE
Translation of picker

### ISSUE THREAD

**Issue by matll42** [jamesmontemagno/MediaPlugin#115]
Hi,

I'm actually developing an application which language is French with your Library and I'm having an issue with the Media Plugin with all Pick or Take functions (either Video or Photo).
So I want to know how can I translate those English buttons if it's possible.

Did someone ever done it ?

Mathieu

**Comment by matll42** [comment]
My bad, I see that this ticket is finally a duplicate of #41 
No solution found since August ?

**Comment by jamesmontemagno** [comment]
As #41 says the library itself doesn't actually hard code any strings. It launches the default camera pickers on each platform, which would be translated if the device was in a specific language as far as I understand.

**Comment by matll42** [comment]
so sad, no tricks

thanks for your very quick answer and for your geat job with all your xamarin plugins
