### ISSUE TITLE
SaveToAlbum = true stores image in DCIM and Pictures folder (twice)

### ISSUE THREAD

**Issue by ericbrunner** [jamesmontemagno/MediaPlugin#117]
Hi,

When I set SaveToAlbum = true and specify a Directory I noticed that the taken picture is store in location ... /DCIM/Kamera/... and .../Pictures/MyFolder. So I have the image twice. What can I do to only store the picture in my folder at ../Pictures/MyFolder?

Version Number of Plugin: 2.6.0.12-beta
Device Tested On: HTC Desire 510 API LEVEL 19

`File = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        PhotoSize = PhotoSize.Medium,
                        CompressionQuality = 92,
                        SaveToAlbum = true,
                        Directory = "MyFolder",
                        Name = $"{DateTime.Now}_documenttypeXYZ.jpg"
                    })`

thanks
Eric

**Comment by jamesmontemagno** [comment]
What happens when SaveToAlbum is set to false?

**Comment by ericbrunner** [comment]
@jamesmontemagno
When set to false the image is store in .../DCIM/Kamera/.... but not in my folder .../Pictures/MyFolder

I referred to #89 because it is similar but not the same.

**Comment by jamesmontemagno** [comment]
So that seems to be working correct...

Where is the ../DCIM/Kamera folder? Is that in your app folder? The more information you can give me the better.

When you set SaveToAlbum it literally saves 2 files to disc. One in private and one in public so the gallery can access it.

**Comment by jamesmontemagno** [comment]
You could manually delete the folder if you don't want it in the private folder as there is no API to do that today.

**Comment by ericbrunner** [comment]
@jamesmontemagno 

Version Number of Plugin: 2.6.0.12-beta
Device Tested On: LENOVO TABLET Tab2A7-20F Android 4.4. - API LEVEL 19
Here the debug output:

```
SelectedMedia?.File
{Plugin.Media.Abstractions.MediaFile}
    AlbumPath: "/storage/emulated/0/Pictures/TruckerAppPhotos/27.10.2016 171045_documenttypeXYZ.jpg"
    Path: "/storage/emulated/0/Android/data/com.rolsped.TruckerApp/files/Pictures/TruckerAppPhotos/27.10.2016 1…"
SelectedMedia?.File.Path
"/storage/emulated/0/Android/data/com.rolsped.TruckerApp/files/Pictures/TruckerAppPhotos/27.10.2016 171045_documenttypeXYZ.jpg"
```

for code:

```
SelectedMedia = new TruckerAppMediaFile
                    {
                        Type = MediaType.Photo,
                        File =  await CrossMedia.Current.TakePhotoAsync(new    Plugin.Media.Abstractions.StoreCameraMediaOptions
                                {
                                    PhotoSize = PhotoSize.Medium,
                                    CompressionQuality = 92,
                                    SaveToAlbum = true,
                                    Directory = "TruckerAppPhotos",
                                    Name = $"{DateTime.Now}_documenttypeXYZ.jpg"
                                })
                    };
```

Version Number of Plugin: 2.6.0.12-beta
Device Tested On: HTC Desire 510 Android 4.4 - API LEVEL 19

Here the debug output:

```
SelectedMedia?.File
{Plugin.Media.Abstractions.MediaFile}
    AlbumPath: "/storage/emulated/0/Pictures/TruckerAppPhotos/27.10.2016 172614_documenttypeXYZ.jpg"
    Path: "/storage/emulated/0/Android/data/com.rolsped.TruckerApp/files/Pictures/TruckerAppPhotos/27.10.2016 1…"
SelectedMedia?.File.Path
"/storage/emulated/0/Android/data/com.rolsped.TruckerApp/files/Pictures/TruckerAppPhotos/27.10.2016 172614_documenttypeXYZ.jpg"
```

for same code as above.

**Comment by jamesmontemagno** [comment]
This is the correct output and as expected.

Regardless of the SaveToAlbum it saves a copy locally in your Android/data/packagename.

If you set SaveToAlbum = true then it will also copy it to public photos directory and tell the gallery to index it.
