### ISSUE TITLE
PickVideoAsync on UWP doesn't copy the file to app local storage so can't be accessed

### ISSUE THREAD

**Issue by Lomster** [jamesmontemagno/MediaPlugin#119]
## Bug 

Version Number of Plugin: 2.6.0.12-beta
Device Tested On: Windows 10 14955
Simulator Tested On: Visual Studio Debugger and on device

### Expected Behavior

Should copy the selected file to the application's local storage directory so it can be accessed.
PickPhotoAsync does this, but PickVideoAsync does not.

### Actual Behavior

PickVideoAsync returns the actual path of the file

### Steps to reproduce the Behavior

Call PickVideoAsync, check the path returned in the MediaFile

**Comment by jamesmontemagno** [comment]
Check: 2.6.0.13-beta

Also fixed a bug in the PickPhotoAsync :)
