### ISSUE TITLE
Getting Exif info sometimes Undefined but sometimes CORRECT.

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/MediaPlugin#121]
Media plugin version : 2.6.0.20
Android SDK : 6.0

Origin problem was, on LG G3, it does not give exif info when took camera.

As you guide before, 
I debug it on test project.

```
var orientation = (Orientation)ei.GetAttributeInt(ExifInterface.TagOrientation, (int)Orientation.Normal);
					System.Diagnostics.Debug.WriteLine("ORIENTATION : " + orientation);
```

I found very weird result. 
It sometimes gives me correct exif info especially when I wait like 5 seconds on camera picker View, and then took a picture.
Mostly, it gives "Undefined" on LG G3.

Any clue or hint? 
Please let me know If you have any idea.

**Comment by allbdeveloper** [comment]
Yes! I found solution. 

```
                        //already on background task
                        BitmapFactory.DecodeFile(filePath, options);

                        rotation = GetRotation(filePath);
```

Please do GetRotation again after DecodeFile(...).
It gives correct exif info on LG G3.

**Comment by allbdeveloper** [comment]
And Plus, 
I had to use "Smaller" option.

**Comment by jamesmontemagno** [comment]
Will take a look. This may be the issues have had with rotation. Decide file is extremely quick as it isn't having to load stuff into memory.

**Comment by jamesmontemagno** [comment]
I have implemented this, but used InJustDecode so you don't load the bitmap into memory, that is why you were having an issue. the latest beta has the fix so you can test that out and you don't have to worry about the smaller stuff

**Comment by allbdeveloper** [comment]
I understand. That's why I said "weird". 
And "Smaller" if I don't use it, 
"Full" option && "Undefined" return without image processing.

**Comment by allbdeveloper** [comment]
Thanks for your help though.

**Comment by allbdeveloper** [comment]
Can you share how you use "nuget pack ~~~"? 
I tried your nuspec file on mac.
But I had to change some like this to pack
![screen shot 2016-10-30 at 12 17 02 am](https://cloud.githubusercontent.com/assets/14910356/19830605/39ae83c8-9e36-11e6-9783-57f18ea2b5d2.png)

**Comment by jamesmontemagno** [comment]
You most likely have to change the slashes, because I publish from Windows.

**Comment by allbdeveloper** [comment]
Thanks for your work. I tried beta 22. Everything works as expected. 
Cool.
