### ISSUE TITLE
cancelling CrossMedia.Current.PickPhotoAsync() crashes the app

### ISSUE THREAD

**Issue by andyroelandt** [jamesmontemagno/MediaPlugin#123]
## Bug 

Version Number of Plugin: **id="Xam.Plugin.Media" version="2.6.0"**
Device Tested On: /
Simulator Tested On: **Marshmallow, Android 6.0 API 23**

### Expected Behavior
When I pick a photo, I can cancel it by click the "back"-button in the toolbar located at the bottom of the screen which takes me back to my previous screen.

### Actual Behavior
When I click that button, the app crashes.

Error in Visual Studio 2015:
 "System.Threading.Tasks.TaskCanceledException: A task was canceled."
Output : 
"...
11-02 15:46:19.949 E/mono    ( 3066): 
11-02 15:46:19.949 E/mono    ( 3066): Unhandled Exception:
11-02 15:46:19.949 E/mono    ( 3066): System.Threading.Tasks.TaskCanceledException: A task was canceled.
11-02 15:46:19.949 E/mono-rt ( 3066): [ERROR] FATAL UNHANDLED EXCEPTION: System.Threading.Tasks.TaskCanceledException: A task was canceled.
..
"
![android_crossmediacrash](https://cloud.githubusercontent.com/assets/11957590/19933798/e97570d8-a114-11e6-8486-ed3d8267ec5e.png)

### Steps to reproduce the Behavior
Having a button with an action bound to that exectues following code:

...
 Device.BeginInvokeOnMainThread(
                    async () =>
                    {
                        await CrossMedia.Current.Initialize();

                        var file = await CrossMedia.Current.PickPhotoAsync(); // at this point, I will "cancel" the picking by hitting the 'back'-button causing the crash
                        if (file == null) return; 
                  
                        ....

                        file.Dispose();
                    });
...

**Comment by andyroelandt** [comment]
This is only a problem in Android. UWP & IOS working fine.

**Comment by jamesmontemagno** [comment]
I am unable to reproduce here on the same exact emulator. It returns null when I hit the back button.

http://screencast.com/t/LsZKKZZ4Mv7


Perhaps it has something to do with your:
Device.BeginInvokeOnMainThread(
async () =>
{

try to remove that?
