### ISSUE TITLE
Save Files in Own directory in Android Platform

### ISSUE THREAD

**Issue by KathirveluM** [jamesmontemagno/MediaPlugin#125]
## Feature Request:

How to save the Application (Images & Videos) in external storage and if not to save in internal storage with Own Directory with Android platform?

Version Number of Plugin: 2.6.0
Device Tested On: Samsung S5, Moto e  (2nd gen),Lenovo a6000 plus

**Comment by jamesmontemagno** [comment]
You would have to copy them out yourself. This is out of the scope of the plugin and don't plan to add in currently.
