### ISSUE TITLE
Get photo album path url 

### ISSUE THREAD

**Issue by cipu** [jamesmontemagno/MediaPlugin#127]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.0
Device Tested On: iOS 

### Actual Behavior
I would like store on database url path of photo, after call TakePhotoAsync. I used AlbumPath and it returned an url like assets-library://asset/ ecc. How can I get path url of the photo to store it in database and view on page? 
SaveToAlbum set to true

(I'm sorry for my english)

**Comment by jamesmontemagno** [comment]
So the URL that is returned is the URL returned by iOS/Android where it is stored in the public galleries. So in this instance you would load the image view a UIImage or I think Xamarin.Forms could load it, haven't tried it. Pretty good thread to read through here: https://forums.xamarin.com/discussion/62772/uiimagepicker-get-path-from-selected-image-from-gallery
