### ISSUE TITLE
App Crash at start load applying steps to Nougat with Xamarin Forms Targeted to 19 (and 15)

### ISSUE THREAD

**Issue by softclickbr** [jamesmontemagno/MediaPlugin#129]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: Lastest
Device Tested On: Galaxy S7
Simulator Tested On: Nexus 5

### Expected Behavior

Load application

### Actual Behavior

Crash at start

### Steps to reproduce the Behavior

Execute the steps to ANDROID N:
"If your application targets Android N (API 24) or newer, you must use version 2.6.0+.
You must also add a few additional configuration files to adhere to the new strict mode:"
...

## Feature Request:
GIVE A WARNING!

Please fill in what you would like
I lose 1 week to remounting the project to discover that was this procedure thats crashes our project.

We follower exactly what asked in XAMARIN FORMS and crashed. But we installed thinking: if one day our project targets to Android N! But our project targets to Android 4.4 and this can be the cause. If is the cause, please, alert to not do the procedure to targets <7. Another possibilty is the Xamarin trying parse the XML as layout, we would go try putting in values/strings.xml or just inside values but the headache is too big that we have fear to try and compromisses our project again.

Thank you to develop this project, I earned 1 month of developing with that, but actually I lose 1 week :-)

**Comment by jamesmontemagno** [comment]
I am not sure what your actual crash is or what your reproduction steps are.

The readme.txt opens to tell you any new changes to read through.

I have updated the Sample to 2.6.1 which uses the latest forms packages and working well. Tested targeting 24 and also 19. https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples

**Comment by softclickbr** [comment]
Just try to the file_path.xml file and will crash!

**Comment by jamesmontemagno** [comment]
Did you add information to you AndroidManifest file? I followed the instructions and it is working perfect in the sample.
