### ISSUE TITLE
[Third Party Library] Calling Page (popup page plugin) closes when closing the camera view with "Use photo" or "Cancel"

### ISSUE THREAD

**Issue by LeoJHarris** [jamesmontemagno/MediaPlugin#130]
## Bug 

This bug is concerning use of the popup plugin found here https://github.com/rotorgames/Rg.Plugins.Popup

Version Number of Plugin: v2.6.1
Device Tested On: iPad

### Steps to reproduce the Behavior: From the Popup page invoke await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions{ ...
Press cancel or use photo (after photo taken).
Popup page that invoked the above code is gone/popped 

## Feature Request:
Ability to invoke camera using popup pages and return to the popup page that invoked the camera view

**Comment by jamesmontemagno** [comment]
I would need a small repo sample to test this on. Is it only an iPad issue?

**Comment by LeoJHarris** [comment]
Hi James, I have attached a zip of the Forms Xaml pages I couldn't add the visual studio project for size restrictions. The Package is included for the popup as well.

I wasn't able to test on an iPhone device, but once I can I will get back you.

If you need anything more let me know.

[Sample.zip](https://github.com/jamesmontemagno/MediaPlugin/files/593220/Sample.zip)

**Comment by jamesmontemagno** [comment]
if you delete all of the bin and obj folders then it will be really small in each of the folders.

**Comment by LeoJHarris** [comment]
Here is as described VS sample project. Cheers

[PopupMediaCamera.zip](https://github.com/jamesmontemagno/MediaPlugin/files/593597/PopupMediaCamera.zip)

**Comment by Roli4711** [comment]
No, also on Android. 

In UWP and WP 8.1 it works (in WP 8.1, the thumbnail is not showing)

**Comment by jamesmontemagno** [comment]
Marking this as a low priority for now as it is a third party plugin and has low impact on the actual plugin. Issue may be in the actual pop up plugin and not in media plugin. Time investment is too large for me currently. Suggestion is to pull down the test sample and attempt to repro it against the real code and debug through.

**Comment by jamesmontemagno** [comment]
2.6.2.16-beta
