### ISSUE TITLE
Camera button is not displayed.

### ISSUE THREAD

**Issue by jaypatel04** [jamesmontemagno/MediaPlugin#131]
Hello,
I am facing an issue with Xamarin media plugin xam.plugin.media framework version 2.6.1 (the issue persists with previous versions as well)
While taking photo using media plugin in Xamarin for WinPhone 8 development, the camera capture button is not displayed. The button is still there, we can tap there and capture the photo. When we touch in the bottom space, the camera button is being visible.
Any idea?

Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: Nokia Lumia 650
Simulator Tested On: Win Mobile Simulator 10.0.*

### Expected Behavior
The capture button is not displayed

### Actual Behavior
The photo capture button should be displayed.

### Steps to reproduce the Behavior
Launch the app, tap on the button which will open camera to capture photo. Camera is launched but the capture image button is not displayed. On touching at the center of bottom space, the camera capture icon becomes visible. User can tap on that area and image is captured. The only issue is, the icon is not displayed.

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Is this a Windows Phone 8 Silverlight project?

**Comment by jamesmontemagno** [comment]
Can you create a small repo that I can test?

**Comment by jamesmontemagno** [comment]
Need more information about the project.

**Comment by jaypatel04** [comment]
Hi James,

I learnt what was the issue. As I mentioned earlier, that the capture button is not displayed on the screen but it is there when you tap and drag on it it is displayed.

I was trying to fix this for last few days with lots of permutations with new projects, new versions.

The issue was, the requested theme of native windows app.
i.e. in App.xml, in the xml file the requesttheme was light. I removed that and the issue fixed.
i.e.  <Application
    x:Class="MyApp.WinPhone.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"  
    xmlns:local="using:FixiHandler.WinPhone" RequestedTheme="Light">

This is Native App.xml.

I am not sure, this should be treated as an issue or not. If you feel you have any solution for this, please provide one.

But, Thank you very much for follow up.
