### ISSUE TITLE
Showing the selected Gallery Image/Take photo image in PCL

### ISSUE THREAD

**Issue by KathirveluM** [jamesmontemagno/MediaPlugin#132]
Hi,
How to show the selected Gallery Image/Take photo image from PCL project. 
Do we need to work as dependency service for showing the same?
Kindly advise on this.

**Comment by jamesmontemagno** [comment]
Depends on what you are using. I have an example of Xamarin.Forms. else you would need to load the image location into an image view or UIImage.

**Comment by KathirveluM** [comment]
Thanks for the response James.

Could you please provide the sample app link for using in xamarin forms..

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples

**Comment by KathirveluM** [comment]
Thanks for the response James.

Actually what i have asked is, after picking the photo using the "PickPhoto,TakePhoto" Event in Xamarin Forms Core Project, we will get the Location Path of the Image in device. 

After getting the Device Image URL, how to load the picked image to open in device default apps like "Gallery,Photos,ES file Explorer ,etc.." through Core Project.

**Comment by jamesmontemagno** [comment]
So you would need to implement that in each project natively and then call via dependency service. We are adding it into the Share Plugin sometime down the road.
