### ISSUE TITLE
Android: Zero byte image is getting saved in the device when Home is pressed

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#133]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Nexus 9 Tablet Android 5.1.1

### Expected Behavior

Should not have saved the captured image with zero bytes

### Actual Behavior
In the camera screen, when home button is tapped then then it will save a zero byte image in the device.

### Steps to reproduce the Behavior
Load the application.
Tap on CameraCapture Button -> Loads the camera -> Select **home** button in the android device.
Now zero byte image is getting stored in the device.

Note:
Load the application.
Tap on CameraCapture Button -> Loads the camera -> When we select **back** button in the android device, no image is getting stored in the device. This is as per the expected behaviour

## Feature Request:
It should not save the zero byte image to device if **home** button is selected in the Camera Screen.

**Comment by jamesmontemagno** [comment]
Did you try 2.6.0?

**Comment by pradeeparutla** [comment]
I am sorry. I have tried the latest release 2.6.0. The issue is fixed when 'back button' is tapped in the camera screen.
 But the issue is reproducible when 'home' button is tapped in the camera screen.

**Comment by jamesmontemagno** [comment]
Ah that makes sense. Different bug.

**Comment by jamesmontemagno** [comment]
2.6.2.16-beta
