### ISSUE TITLE
WP 8.1 takes no photo

### ISSUE THREAD

**Issue by Roli4711** [jamesmontemagno/MediaPlugin#134]
## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: 
Simulator Tested On: WP 8.1 Emulator 1080P 5.5 inch

### Expected Behavior
Stream is filled

### Actual Behavior
Stream is empty

### Steps to reproduce the Behavior
I've implemented the source code of this main page in my software. If I use UWP (Simulator or Device), the stream is filled after I take a picture and press the OK sign. On WP 8.1, I can take a Picture (camera will be started), but there is no OK (or cancel) sign and it returns immediatly after take the photo to the calling page. The stream is now empty (file.GetStream()).

Best regards,
Roland

**Comment by jamesmontemagno** [comment]
Are you creating a WP 8.1 silverlight app or RT app?

**Comment by jamesmontemagno** [comment]
Also, did you do this:

```
Windows Phone 8.1 RT:

Set Webcam permission.

In your App.xaml.cs you MUST place the following code inside of the OnLaunched method:

protected override void OnActivated(IActivatedEventArgs args)
{

    Plugin.Media.MediaImplementation.OnFilesPicked(args);

    base.OnActivated(args);
}
```
