### ISSUE TITLE
Java.Lang.IllegalStateException when picking picture from gallery

### ISSUE THREAD

**Issue by NVentimiglia** [jamesmontemagno/MediaPlugin#136]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: LG G3
Simulator Tested On: LIVE

### Expected Behavior
I can pick a picture from the gallery

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/125889/20550118/74be8e18-b0e7-11e6-916d-7760de085ea3.png)

### Steps to reproduce the Behavior

Pick a picture without exception.
[MediaPicker.zip](https://github.com/jamesmontemagno/MediaPlugin/files/608046/MediaPicker.zip)

**Comment by jamesmontemagno** [comment]
So, what you are doing is not best practice. The issue is very clear that your user interface has not returned yet from the external activity so when you try to navigate back your UI isn't back yet and blows up. 

```
 private async void Button_OnClicked(object sender, EventArgs e)
        {
            await CrossMedia.Current.Initialize();

            var file = await CrossMedia.Current.PickPhotoAsync();
            
           //THIS RIGHT HERE IS BAD!
            await Navigation.PopAsync(true);

            _callback(file);
        }
```

In the new beta i have put a small artificial delay into the library before returning, but I can not guarantee full success. You should loop into the onappearing first before poping async or simply do this:

```
 private async void Button_OnClicked(object sender, EventArgs e)
        {
            await CrossMedia.Current.Initialize();

            var file = await CrossMedia.Current.PickPhotoAsync();
            
            await Task.Delay(100); //ensure we are back on UI
            await Navigation.PopAsync(true);

            _callback(file);
        }
```

**Comment by jamesmontemagno** [comment]
2.6.2.16-beta

**Comment by NVentimiglia** [comment]
Just a heads up to anyone implementing this, on IOS OnAppearing is called before the callback. So if you dont want an arbitrary wait in your code you will need to track state and make sue both events are complete.
