### ISSUE TITLE
Calling Page (and Main Calling Page / Navigation.PushModalAsync) closes when closing camera view with "use photo" or "cancel"

### ISSUE THREAD

**Issue by Roli4711** [jamesmontemagno/MediaPlugin#137]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: UWP (CORRECT) Android, WP8.1, iOS
Simulator Tested On: WP8.1, Android, UWP (CORRECT)

### Expected Behavior
Last page (in which plugin will be called) should be displayed

### Actual Behavior
It goes back to the first page, which call with Navigation.PushModalAsync

### Steps to reproduce the Behavior
Make a MainPage. Craete a new page and call it from MainPage with Navigation.PushModalAsync(SubPage1) (and/or create a second page and call it also with Navigation.PushModalAsync(SubPage2)). In my code, SubPage2 calls the Media-Plugin.

Take a Picture. 

After you "use photo" all will go through (without WP8.1 (see Bug #134), I can see the byte in the media stream), but at the end, the first page (in this case MainPage) will be displayed. Only in UWP, the SubPage2 will be displayed and it works fine.

It's nearly the same bug like in #130 but with normal Xamarin.Forms utilities and not with a 3rd Party product.

**Comment by jamesmontemagno** [comment]
I am not able to reproduce with your exact steps.

See video: http://screencast.com/t/RfR7FMkZa1

**Comment by jamesmontemagno** [comment]
2.6.2.16-beta

**Comment by Roli4711** [comment]
2.6.2.16-beta not works. And I've created an example with the same "test Environment" I had in my original Code. There, it works. But not in my original Code. I don't know how I can find the problem.

But it will be OK, if this task will be closed.

**Comment by jamesmontemagno** [comment]
You will have to give me a small sample that I can reproduce else I can't really help.

**Comment by Roli4711** [comment]
Hi James,
I found the issue. I have in the App.cs in the OnResume function a code, which refresh the datas and call the start page (with the new datas). On UWP, after taking a photo, the OnResume function will not be called. On other plattforms OnResume will be called and of course, I'm losing the original page on which I take the photo.

Perhaps, there is a solution. Otherwise, I change my code and it will work.

Roland
