### ISSUE TITLE
Option to select which Photo source to pick image from

### ISSUE THREAD

**Issue by zanesc** [jamesmontemagno/MediaPlugin#138]
## Feature Request:
The ability to select other photo sources when picking an image. On Android it is ok because you can change defaults but on iOS you can not. So I can not select an image from my Google Photos library which is the only library I use.

**Comment by jamesmontemagno** [comment]
I actually don't think this is possible as the API only opens the default camera roll. You would have to implement an iOS extension file picker, which your app would need to do. Sorry.
