### ISSUE TITLE
App not taking and picking video on android 

### ISSUE THREAD

**Issue by jmdee** [jamesmontemagno/MediaPlugin#139]
## Bug Key Not Found Exception: , Exception: System.Collections.Generic

Version Number of Plugin: 2.0.1
Device Tested On: Windows 10 mobile phone , Android API 19
Simulator Tested On: Win 8.1

### Actual Behavior It's working fine for all windows platforms i have tested it on ,but its not taking a video on android and allowing me to pick the video. When I click the pick video button on android i get a 
Key Not Found Exception and when i click the take video button , my app crushes and i get a Unhandled Exception: System.Collections.Generic. KeyNotFoundException: The given key was not present in the dictionary.

**Comment by jamesmontemagno** [comment]
Have you tried the latest version 2.6.1?

Can you post a stack trace on http://gist.github.com

**Comment by jmdee** [comment]
2.6.1 will update my Xamarin forms which caused android resource errors

**Comment by jmdee** [comment]
Let me do this James , i am going to try upgrade my Xamarin To the latest version then install 2.6.1 , if i still get the same problem , will get back to you

**Comment by jamesmontemagno** [comment]
2.6.1 does not have any dependencies at all on Forms, so that shouldn't have been an issue.  I'll take a look though.

**Comment by jamesmontemagno** [comment]
If you can give me a stack trace I can try to re-produce. Using my simple sample app I didn't have any issues though.

**Comment by jmdee** [comment]
when i install 2.6.1 it updates a couple of nuget packages on my android
project including xamarin forms

**Comment by jamesmontemagno** [comment]
Are you sure you are only selecting the single Media Plugin and not accidentally hitting update all?

**Comment by jamesmontemagno** [comment]
I guess if you are on a really old version of Xamarin.Forms you would have 23.0.x of support plugins and you will now need 23.3.0 which was a requirement of Forms: 2.2.0.31

**Comment by jmdee** [comment]
ok James , but if yesterday i removed my Xamarin for vs and intsalled the
latest version which installed Xamarin.Forms 2.2.0.45 but each time i
created a new solution for Xamarin.Forms PCL and try debug on android
before i even change any code i would get a popup on vs reuesting me to
look for naigationpagerenderer.cs file and eventually get this exception
Xamarin.Android.Support.v4 missing and if i checked inside my packages
folder i only saw Xamarin.forms 2.2.0.45 and no other packages like
Xamarin.Android.Support.v7.AppCompat , Xamarin.Android.Support.v4. I had to
remove the Latest Xamarin and install the version i had before. Now i am
really stuck , please help me out really need to finish this app.

**Comment by jamesmontemagno** [comment]
if you have a sample app you can share it with me and I can take a look, but I am not sure exactly what is going on with your machine sorry.

**Comment by jmdee** [comment]
ok please find the attached sample​
 FTrial.zip
<https://drive.google.com/file/d/0B0jt2BoyHoztWTZUY3poOW5xQ1k/view?usp=drive_web>
​

**Comment by jamesmontemagno** [comment]
I opened your project. 
Right clicked on Solution and hit "Manage Nuget Packages"
Under Install went to Media Plugin and Clicked on it
Select 2.6.0 and hit install

Everything updated fine.


I then did the same for xamarin.forms to update to 2.2.0

2.6.1 requires a few new files and the readme.txt opens so I did that.

I hit compile -> Debug-> everything worked fine on my Nexus 6P for picking video.

For taking a video there was a crash because you added:
<uses-permission android:name="android.permission.CAMERA" />

You don't need that. Removing it fixes any crash taking a video.
[FTrial.zip](https://github.com/jamesmontemagno/MediaPlugin/files/626314/FTrial.zip)

**Comment by jmdee** [comment]
Thank you James , will try that. Sorry but i think you didnt finish this
statement "For taking a video there was a crash because you added:" im a
bit lost there

**Comment by jamesmontemagno** [comment]
Updated comment see above.

**Comment by jamesmontemagno** [comment]
I also uploaded the updated sample.

**Comment by jmdee** [comment]
Ok thank you James

**Comment by jmdee** [comment]
Thank you James my app is now working perfectly. Is there a frame for holding the uploaded viseo on xamarin.forms ? just like when you take an image ?

**Comment by jamesmontemagno** [comment]
There is not, you would need a custom control to playback video.

**Comment by jmdee** [comment]
Hi James ,I’m trying to make a shopping cart where by a user can click a
list view item and it is added to the shopping cart. Do you have any idea
on how I can do that?
