### ISSUE TITLE
Android 6.0 only Media issue

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#14]
_From @michaeldimoudis on April 15, 2016 4:23_

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: latest
Device Tested On: Android 6 devices
Simulator Tested On: Android 6

### Expected Behavior
When I click on a button to load a photo gallery, I get asked for permission, and the photo gallery should pop up.

### Actual Behavior
After you give permission for Android 6 to access the camera, the photo gallery doesn't pop up. Even after you press the button multiple times. If you navigate away from the page, and go back in to the page with the button to pop up the gallery, it then starts working as expected and pops up.

### Steps to reproduce the Behavior
See above.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#283_

**Comment by jamesmontemagno** [comment]
Unable to reproduce on Nexus 6p

**Comment by michaeldimoudis** [comment]
No problem👍🏼. I experienced it on 2 devices, but if anyone else runs into this problem, the way I fixed it is by using the permissions plugin and requesting permission first before calling the media plugin. This issue was only limited to the first run of the app on android 6 device.

**Comment by jamesmontemagno** [comment]
@michaeldimoudis Did you add this code to your app in the main activity?

It would make sense on first run it would have this issue if you didnt:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
    PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}
```
