### ISSUE TITLE
insert new page before returning from taking photo

### ISSUE THREAD

**Issue by asafHorvitz** [jamesmontemagno/MediaPlugin#140]
I want after taking photo to open a new page with the photo and some text box.

the problem is that after returning from taking a photo i am returning to my previous page in the stack and it takes time to present the new page with the photo.

Is there a way to add an event after the photo has been taken and before the screen of approving the photo disappears ?

is there another method of doing it ?

**Comment by jamesmontemagno** [comment]
Not that I know of as the activity must be finished first. You can save the Task off, navigate, and then await on the task in the new page maybe?

**Comment by marthinch** [comment]
I got similar issue, how to prevent the new inserted page after taking photo ?
