### ISSUE TITLE
[Feature Request] Select multiple images

### ISSUE THREAD

**Issue by Jose7777** [jamesmontemagno/MediaPlugin#141]
Now the user can only select one image.
It would be nice to be able to select multiple images, limiting the total selection to a certain number.

Thank your very much

**Comment by chadgruka** [comment]
This would be highly welcomed. Being able to select multiple images would be a huge benefit!

**Comment by jamesmontemagno** [comment]
I have already posted I have no plans to implement this.

**Comment by chadgruka** [comment]
Is there a technical limitation preventing this? Or something else?
