### ISSUE TITLE
[Feature Request] automate photos based on a time interval

### ISSUE THREAD

**Issue by klint01** [jamesmontemagno/MediaPlugin#143]
## Feature Request:
I am looking for the capability to trigger a still image to be automatically taken via the front-facing camera on a set interval (to be determined by the user).  No need to click a button to take a picture and no previews of the photo once taken.

I've found an example for building this capability directly in the iOS layer, but would love to see it available via this package. 
https://forums.xamarin.com/discussion/9640/automatically-take-image-with-meta-data

My application (Xamarin.Forms PCL) is currently being tested on an iOS phone but eventually, I would look for this same capability on Android as well.

Thanks!

**Comment by jamesmontemagno** [comment]
This is out of the scope for the library and wouldn't be available on all platforms. It doesn't seem to be integreated well with the picker so is best kept to the platform specific implementation that the user implements.
