### ISSUE TITLE
How can I use this PickMediaOptions with PickPhotoAsync 

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/MediaPlugin#145]
I am trying to resize image while uploading using PickPhotoAsync  and also trying to PickMediaOptions this option with PickPhotoAsync  like the code below on my pcl project:

var file = await CrossMedia.Current.PickPhotoAsync (new PickMediaOptions 
{
    PhotoSize = PhotoSize.Medium,
});

but PickMediaOptions  and PhotoSize doesn't work here. How can use this or has any alternative opiton?

**Comment by jamesmontemagno** [comment]
That works fine as I have in my tests and will reduce the photo size in half.

I am not sure what your issue is or what version of the app you are using.

**Comment by justinkneff** [comment]
Mine is also not resizing. I've tried multiple types of combinations. Using a Galaxy Tab A(SM-T350). Image dimensions are 2592x1944.
Using 2.6.1 from a NuGet.
`
var media = await this.mediaService.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    DefaultCamera = CameraDevice.Rear,
                    Name = fileName,
                    CustomPhotoSize = 10, //doesn't affect the photo size no matter what its set to
                    CompressionQuality = 50, //doesn't affect the quality or image size no matter what it's set to.
                    SaveToAlbum = true
                });
`
What's interesting is the media file itself on the device is approximately 1.7mb. When I render it on a native implementation to look at the image and covert it to a bitmap it actually is compressed. 

`
public async Task<ImagePathString> RetrieveImages(MediaFile image)
{
Bitmap bitmapImage = await BitmapFactory.DecodeFileAsync(image.Path);
...
`

**Comment by jamesmontemagno** [comment]
@justinkneff  You need to set the PhotoSize = PhotoSize.Custom else it default to full size

Compression quality literally compresses it down to 50% of original when saving.

The one in the album is full size.
