### ISSUE TITLE
Can I specify a photo overlay for Android? 

### ISSUE THREAD

**Issue by owlstack** [jamesmontemagno/MediaPlugin#146]
## Feature Request:

I want to use the camera api used here but I want to have a custom camera page with specific buttons and overlap on top of the camera page of the MediaPlugin. Can I do that currently for Android?

**Comment by jamesmontemagno** [comment]
It is not possible because it launches an external app and there is no api do to that.

You will have to look into the Camera2 api's to embed it into your app.
