### ISSUE TITLE
Cannot access a disposed object.

### ISSUE THREAD

**Issue by Crem78** [jamesmontemagno/MediaPlugin#147]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: Huawei P8 Lite - Android 5.0.1
Simulator Tested On: iPhone 7 - iOS 10.1 / 9.3 / 9.2

### Expected Behavior
I have a section on my app where users can change the picture, save it and edit it even after leaving and returning from the same section

### Actual Behavior
as I enter the section, select the picture and sound, no problem. When I get back in that section, I choose a new photo from the library and back on my page I get this error: System.ObjectDisposedException: Cannot access a disposed object.
The error is there in both Android and iOS

## Note:
I use the method PickPhotoAsync

               var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                {
                    PhotoSize = PhotoSize.Medium,
                    CustomPhotoSize = 90 //Resize to 90% of original
                });

                if (file == null)
                    return;

                Photo = ImageSource.FromStream(() =>
                {
                    var stream = file.GetStream();
                    file.Dispose();
                    return stream;
                });

**Comment by jamesmontemagno** [comment]
I can not reproduce this with my samples and tests that I have. Can you run my sample from this repo? Most likely there is something else happening in your code that something is getting garbage collected.

Also:

You must set the PhotoSize to Custom for the CustomPhotoSize to actually take effect, when you set it to Medium it uses medium.

**Comment by Crem78** [comment]
Hi James, I am attaching my code if you can help.
[Code.zip](https://github.com/jamesmontemagno/MediaPlugin/files/645498/Code.zip)

NB: use MVVM Light

Thank you

**Comment by Crem78** [comment]
Hi James, I am attaching my code if you can help.
[Code.zip](https://github.com/jamesmontemagno/MediaPlugin/files/645512/Code.zip)

NB: use MVVM Light
Thank you

**Comment by jamesmontemagno** [comment]
My assumption is because you already getting the stream in your code after you check for null and something is disposing of it. Hard to say. 

My code literally only does: () => File.OpenRead(path);

I would try to maybe safe the stream out ahead of time and then set it.
