### ISSUE TITLE
Setting PhotoSize to Small on a Samsung Galaxy Alpha causes the camera to report an error

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/MediaPlugin#148]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: Samsung Galaxy Alpha
Simulator Tested On:

### Expected Behavior
Camera does not report an error and allows photo capture

### Actual Behavior
Camera reports error and does not allow photo capture

### Steps to reproduce the Behavior
Set the PhotoSize of the StoreCameraMediaOptions to PhotoSize.Small, pass in StoreCameraMediaOptions to TakePhotosAsync, camera reports error.

**Comment by pauldiston** [comment]
After further testing this might be a red herring as an uninstall/reinstall of the application allowed for the setting to work as expected.

**Comment by jamesmontemagno** [comment]
Will close if not reproducible
