### ISSUE TITLE
[Feature Request] Choosing album when taking photo or video.

### ISSUE THREAD

**Issue by mazhlekov** [jamesmontemagno/MediaPlugin#149]
Hi James,
First I want to congratulate you for the excellent library. 
I decided to write this feature request because I think that it's important and I know several people who are interested in it.
Please let me know what do you think.

## Feature Request:
Allow choosing album when taking photo or video.
Include property Album or AlbumName in StoreCameraMediaOptions and StoreVideoOptions and store the picture/video in this album.

```cs
var pic = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
    Name = "Picture",
    SaveToAlbum = true,
    Album = "MyAlbum"
});

var vid = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
{
    Name = "Video",
    SaveToAlbum = true,
    Album = "MyAlbum"
});
```

**Comment by bastianbecker21** [comment]
It's not implemented yet?

**Comment by EeKay** [comment]
@jamesmontemagno is this implemented? I'd really love to be able to save photos into an album for my app. 

The creation of the albums themselves are out of scope for this plugin I presume. Is that correct?

**Comment by jamesmontemagno** [comment]
No new features.
