### ISSUE TITLE
Camera preview on iOS has buttons with white background and white text

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/MediaPlugin#150]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: iPhone SE

### Expected Behavior
Cancel, Take Photo and Switch Camera buttons should have white text and transparent background, similar to the flash button

### Actual Behavior
Cancel, Take Photo and Switch Camera buttons have white text and white backgrounds.

### Steps to reproduce the Behavior
1. Call TakePhotoAsync
2. Notice buttons have white text and white backgrounds

**Comment by jamesmontemagno** [comment]
Are you setting any custom appearances?

These have default black background and white text.

**Comment by pauldiston** [comment]
Yes, sorry about that, I was setting the UIButton.Appearance.BackgroundColor as part of my apps theme.

**Comment by jamesmontemagno** [comment]
:) You will need to adjust that before and after it as I don't save those values out at all and display the defaults.
