### ISSUE TITLE
PickVideoAsync doesn't set AlbumPath

### ISSUE THREAD

**Issue by cipu** [jamesmontemagno/MediaPlugin#152]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: iOS 10.1

### Expected Behavior
var file = await CrossMedia.Current.PickVideoAsync();
file has AlbumPath

### Actual Behavior
AlbumPath is null, it works fine when I use PickPhotoAsync

**Comment by jamesmontemagno** [comment]
Good catch, fixed up now, try the new beta package I just published
