### ISSUE TITLE
[Feature Request] Feature Request - Select Multiple pics from gallery.

### ISSUE THREAD

**Issue by Pinox** [jamesmontemagno/MediaPlugin#153]
Option to select multiple pictures from photo gallery.

![photobox-android-upload](https://cloud.githubusercontent.com/assets/5297255/21486082/7af7b694-cbb6-11e6-95e2-b33264d0864f.jpg)

**Comment by petesmc** [comment]
This would be incredibly useful

**Comment by palla89** [comment]
+1 for this feature!

**Comment by js-ka** [comment]
+1 great feature!

**Comment by Obvious1992** [comment]
+1 for this idea!

**Comment by shixu** [comment]
+1 for this feature! If you need help, let me know!

**Comment by gaurav-lucemorker** [comment]
+1 for this feature!

**Comment by alitalvez** [comment]
+1 for this feature!

**Comment by lwijdeveld** [comment]
+1 for this feature!

**Comment by Wombel70** [comment]
+1 for this feature!

**Comment by PetrVobornik** [comment]
It would be very useful feature. When you are planning to implement it? 
If I can wait with launching of my project or I must looking for an other solution.

**Comment by jamesmontemagno** [comment]
I am not currently planning on implementing this as it isn't supported natively out of the box. However I will leave it around for legacy.

**Comment by xuezhen** [comment]
+1 for this feature!

**Comment by XtN** [comment]
+1 for this feature

**Comment by vksuman** [comment]
+1 for this feature

**Comment by shivsuthanmhub** [comment]
How to achieve this activity? Anyone could you please explain ?

**Comment by dkarzon** [comment]
Just putting it out there, if anyone who has +1'd this issue wants to take a look at my open PR (#355) and comment on the direction and if the implementation for iOS and Android works for them that would be great.

**Comment by Diviercadavid** [comment]
+1 for this feature!

**Comment by dberroa** [comment]
+1 as well as I'm also in great need of this for iOS, Android, and UWP.

**Comment by stephenmante** [comment]
+1 for this feature! Please 👍

**Comment by starking1017** [comment]
+1 for this feature! Please ...

**Comment by bastianbecker21** [comment]
+1 for this feature! Please~~~

**Comment by CesareSoldani** [comment]
+1 please

**Comment by Bohirjon** [comment]
+1 please

**Comment by AwsomeCode** [comment]
+1 please

**Comment by abdu292** [comment]
+1 please

**Comment by tylerAWIS** [comment]
+1 this would be great!

**Comment by kormemis** [comment]
+1 would be great, there is no any other option because ELCImagepicker is no longer supported. there is no option except this.

**Comment by hernandoz** [comment]
+1 Please . Thanks

**Comment by aaronclausen** [comment]
+1 please!!!

**Comment by simader** [comment]
+1 Any news, when the feature pull request could be available?

**Comment by Trevonious** [comment]
+1 @jamesmontemagno The pull request is waiting to be merged in! #612

**Comment by WagnerMattei** [comment]
Please merge, i need to keep my job

**Comment by aismaniotto** [comment]
+1 for this feature!

**Comment by jensbrobak** [comment]
+1 Please. Thanks.

**Comment by atxy2k** [comment]
+1 Please.

**Comment by nguyenthanhliemfc** [comment]
Please release this feature. Thank!

**Comment by abdu292** [comment]
I guess this feature is already released in the beta/preview version. (use PickPhotosAsync - the plural -instead of PickPhotoAsync). thanks!

**Comment by nguyenthanhliemfc** [comment]
> I guess this feature is already released in the beta/preview version. (use PickPhotosAsync - the plural -instead of PickPhotoAsync). thanks!

Great, I'll try it!
Thank you!

**Comment by mnidhk** [comment]
+1
Please make it out of beta

**Comment by arccosinus** [comment]
Crashes with "Object reference not set to an instance of an object."
at Plugin.Media.MediaImplementation+<PickPhotosAsync>d__20.MoveNext () [0x0011b] in D:\a\1\s\src\Media.Plugin\Android\MediaImplementation.cs:128

**Comment by hernandoz** [comment]
I am having the same problem on the latest Beta 

"Crashes with "Object reference not set to an instance of an object."
at Plugin.Media.MediaImplementation+d__20.MoveNext () [0x0011b] in D:\a\1\s\src\Media.Plugin\Android\MediaImplementation.cs:128
When I don't select anything and tap back button"

**Comment by JhonFerleyGiraldo** [comment]
Como puedo usar el beta para usar multiples fotos?

**Comment by haxor211** [comment]
im using PickPhotosAsync() and well the gallery opens but Im still only able to select 1 photo even if I pass `await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions
                    {
                        CompressionQuality = 80,
                        SaveMetaData = true,
                    }, new MultiPickerOptions
                    {
                        MaximumImagesCount = 3,
                    });`

**Comment by shehrozeee** [comment]
> 
> 
> im using PickPhotosAsync() and well the gallery opens but Im still only able to select 1 photo even if I pass
> `await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions { CompressionQuality = 80, SaveMetaData = true, }, new MultiPickerOptions { MaximumImagesCount = 3, }); `
> 
> Please help me out how do I get this working?

@haxor211 
some galleries support picking multiple files and some dont.
For example, Samsung gallery does not support picking multiple files but Google Photos supports picking multiple files.

**Comment by jamesmontemagno** [comment]
Was just fixed in latest beta, closing as this is implemented.

**Comment by abdul-wasey** [comment]
> > im using PickPhotosAsync() and well the gallery opens but Im still only able to select 1 photo even if I pass
> > `await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions { CompressionQuality = 80, SaveMetaData = true, }, new MultiPickerOptions { MaximumImagesCount = 3, }); `
> > Please help me out how do I get this working?
> 
> @haxor211
> some galleries support picking multiple files and some dont.
> For example, Samsung gallery does not support picking multiple files but Google Photos supports picking multiple files.

I am also facing this issue

**Comment by tam892007** [comment]
> > > im using PickPhotosAsync() and well the gallery opens but Im still only able to select 1 photo even if I pass
> > > `await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions { CompressionQuality = 80, SaveMetaData = true, }, new MultiPickerOptions { MaximumImagesCount = 3, }); `
> > > Please help me out how do I get this working?
> > 
> > 
> > @haxor211
> > some galleries support picking multiple files and some dont.
> > For example, Samsung gallery does not support picking multiple files but Google Photos supports picking multiple files.
> 
> I am also facing this issue

I think it's relevant: https://stackoverflow.com/questions/51780105/picking-multiple-images-on-clicking-from-gallery  I'm gonna switch to some other plugin to deal with this issue.

**Comment by tjakopovic** [comment]
Has anybody got it working on Android? I use PickPhotosAsync, but the when I select photo in gallery, it immediately picks it(not selects it). I use latest pre-release version.

**Comment by tam892007** [comment]
> Has anybody got it working on Android? I use PickPhotosAsync, but the when I select photo in gallery, it immediately picks it(not selects it). I use latest pre-release version.

Yes it does work. However on some devices, in my case is a Galaxy Edge, the default Photo Picker by the OEM does not support multiple pick. We have to ask our users to set Google Photo as default app when dealing with this problem and everything works fine.
