### ISSUE TITLE
[Android] Application restarted

### ISSUE THREAD

**Issue by zonkzen** [jamesmontemagno/MediaPlugin#155]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.1
Device Tested On: Samsung S4/S5

### Expected Behavior 
Application continues to work after taking picture or choosing an image.

### Actual Behavior
Application is restarted.

### Steps to reproduce the Behavior
On any phone, in Developer options, set application to be killed if enters background ( one of the last options ) and run any sample app with camera selection on the second page.

I think it doesn't have to be a bug of this plugin, but I'm out of options. I have a Forms app with several pages (the camera selector is not on the first one). After choosing the camera (or camera library) and once I'm done selecting the image, the code continues (I can see that with breakpoints) to consume the result, but my app is being effectively killed - I never get to see anything because the app shows the first screen.

Not exceptions is thrown. I would say this somehow make sense - Android kills my app because it's in the background and Camera is an Intent (also an app). But how can I stop this behaviour?

**Comment by jamesmontemagno** [comment]
This is because of the options you are choosing. The app goes into the background and receives an intent when it comes back. This makes sense as you are telling the developer options to kill it. It launches the app. This is intended if you have that setting.

**Comment by zonkzen** [comment]
@jamesmontemagno as I wrote, this is on purpose to simulate behaviour on some phones.
