### ISSUE TITLE
Set default image

### ISSUE THREAD

**Issue by arifinWM** [jamesmontemagno/MediaPlugin#156]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Question 

Version Number of Plugin: 
Device Tested On: iOS 10
Simulator Tested On: IOS 10.1

Hi James,

I would like to set the imagesource default from image in gallery. Please advise how to convert it to media file from url given in take photos.

I'm using below method to load it, but still no luck.

private async void pickPhotoDefault(string imagesource)
        {
            if (imagesource.Trim() != "")
            {
                System.Uri uri;

                System.Uri.TryCreate(imagesource, UriKind.Absolute, out uri);
                Task<ImageSource> result = Task<ImageSource>.Factory.StartNew(() => ImageSource.FromUri(uri));
                imgprofileuser.Source = await result;
            }
        }

Thanks

Best Regards,
Afin

**Comment by jamesmontemagno** [comment]
It is as easy as just creating it from From:

```
var file = await CrossMedia.Current.PickPhotoAsync();
            if (file == null)
                return;

            MainImage.Source = ImageSource.FromFile(file.Path);
```
