### ISSUE TITLE
Feature Request - Crop to rectangle

### ISSUE THREAD

**Issue by jherby2k** [jamesmontemagno/MediaPlugin#158]
## Feature Request:
I would like to be able to specify a "crop to rectangle" option which both provides a viewfinder overlay (like [card.io](https://www.card.io) and then returns a cropped image from inside that box.

**Comment by jamesmontemagno** [comment]
This is out of the scope for the plugin as it launches the default camera for taking photos and this is not available on all devices. iOS/UWP do offer a crop which the flag was added.
