### ISSUE TITLE
System.IO.FileNotFoundException iOS Camera Take Picture

### ISSUE THREAD

**Issue by NVentimiglia** [jamesmontemagno/MediaPlugin#159]
## Bug 
Xam.Plugin.Media version="2.6.1" targetFramework=xamarinios10
Device Tested On: iOS Simulator, iPad Mini 2

### Expected Behavior
When taking a picture, it would return a physical path.

### Actual Behavior
When taking a picture, it would return a temp path.
This causes  System.IO.FileNotFoundException when accessing the image at a slightly later time.

### Steps to reproduce the Behavior

- Take a picture
- Cache its location
- Get Lunch
- Try to open and read the bytes from the temp file

## Feature Request:
https://github.com/jamesmontemagno/Xamarin.Plugins/issues/47

**Comment by jamesmontemagno** [comment]
Are you calling TakePhotoAsync or PickPhotoAsync? The reference to 47 has something to do with Pick, but you are referencing Take which is impossible to use on a simulator. Please specify and show code you are using too if possible.

**Comment by NVentimiglia** [comment]
Sorry, not an emulator. My associate was on a Iphone 6s.

Sorry for the mistake.

**Comment by NVentimiglia** [comment]
Also, this was with take picture. Gallery select worked fine.

**Comment by NVentimiglia** [comment]
Small correction, this is PickPicture, not TakePicture

**Comment by jamesmontemagno** [comment]
So, from legacy when you used PickPhoto and called Dispose it would delete the photo. This was just something from Xamarin.Mobile legacy.

I don't like this at all and the developer should be in control.

I have changed this functionality in 2.3.0-beta: https://www.nuget.org/packages/Xam.Plugin.Media/2.6.3-beta

Give it a go :)

**Comment by NVentimiglia** [comment]
Sharing violation on path /var/mobile/Containers/Data/Application/4615CBE9-C20E-41BB-B2CA-220F827F8E54/Documents/temp/IMG_20170110_225214.jpg

**Comment by jamesmontemagno** [comment]
Did you set up proper permissions: https://github.com/jamesmontemagno/MediaPlugin#android-n

You need to give me more information, devices, version of android, etc.

**Comment by jamesmontemagno** [comment]
Also encourage to look at output and help with posting to Gist the stack trace

**Comment by NVentimiglia** [comment]
We have proper permission set up, this has not changed.

Ill look into getting a repo up

**Comment by NVentimiglia** [comment]
Closing this. Found the issue related in my code related to a lingering file stream.

**Comment by ericbrunner** [comment]
@jamesmontemagno Version 2.6.3.6-beta solved that issue on iOS in my app.
