### ISSUE TITLE
EXIF Rotation with FFImage

### ISSUE THREAD

**Issue by NVentimiglia** [jamesmontemagno/MediaPlugin#160]
## Bug 

Xam.Plugin.Media version="2.6.1" targetFramework=xamarinios10
Device Tested On: LG G3

### Expected Behavior

Portrait photos from pick picture and from take picture should include correct metadata.

### Actual Behavior

Portrait photos from pick picture and from take picture should include correct metadata.

### Steps to reproduce the Behavior

Take a photo using Media Picker, use FFImage as an image presenter.

Full disclosure, I originally felt that FFImage was at fault as I could not replicate this issue with a default image control. The full outline of my issue is here:

https://github.com/luberda-molinet/FFImageLoading/issues/442

If you could chime in here or there, that would be helpful.

**Comment by jamesmontemagno** [comment]
Try out 2.6.3.1-beta for me and let me know.

**Comment by NVentimiglia** [comment]
**Take Photo**

-  Landscape, Held 90 right,  Image is upside down
-  Landscape, Held  90 left,  Image is correct
-  Portrait, Held 0,  Image is 90 degrees left
-  Portrait, Held 180, Image is 90 right

**Pick Photo**
- Always correct

**Comment by jamesmontemagno** [comment]
Is this on iOS or Android? Additionally, what if you use the non-ffimage stuff?

**Comment by NVentimiglia** [comment]
Android LG G3. Has not been a problem on iOS yet.

regular Image control works fine.

**Comment by allbdeveloper** [comment]
@NVentimiglia 
Would you like to try with this code?
And could you share result?

```
MediaFile mediafile = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
{
PhotoSize = PhotoSize.Medium
});
```

**Comment by NVentimiglia** [comment]
Here is my code, not sure what your getting at.

```
 file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    Directory = "Sample",
                    Name = "img_" + Guid.NewGuid() + ".jpg",
                    PhotoSize = PhotoSize.Medium,
                });
```

**Comment by allbdeveloper** [comment]
@NVentimiglia 
Oh, I wanted to know if rotation problem would be gone when you use Photosize option.
But it seems like that you're already using it, and problem is not resolved, isn't it?

**Comment by NVentimiglia** [comment]
@allbdeveloper 

No =(

**Comment by allbdeveloper** [comment]
OK Thanks.
@NVentimiglia

**Comment by shayo** [comment]
Is there any news on this? @NVentimiglia ,  how did you solve this problem?
I have a similar scenario. It only happens for images taken with iOS. Weirdly enough, they appear correctly (with FFImageLoading) on other iOS devices, but 90 deg rotated on Android devices.

**Comment by NVentimiglia** [comment]
@shayo =(

**Comment by shayo** [comment]
I just tried the PhotoSize option (set to medium) and I think it solved it for my case.

**Comment by pauldiston** [comment]
@NVentimiglia Has this issue been resolved?

**Comment by EaranMaleasi** [comment]
just tried the newet beta (2.6.3.8-beta) and this issue is still there on a Samsung Galaxy Tab E (SM T560) the same way @NVentimiglia described it on 10. Jan

**Comment by EaranMaleasi** [comment]
Forget what I said. It is fixed.

**Comment by jamesmontemagno** [comment]
:) yay! We have a lot more enhancements coming too.

**Comment by L3xer** [comment]
Hi all,

**Comment by L3xer** [comment]
I'm also having this issue. Photos taken in iOS rotated on android devices.

![untitled-1](https://user-images.githubusercontent.com/8818052/29213085-5e7ad1a2-7eaa-11e7-81c0-a4f7da205bf6.jpg)

(Android - top, iOS-bottom)

Xam.Plugin.Media - 3.0.1
Xamarin.FFImageLoading - 2.2.10-pre-408

**Comment by jamesmontemagno** [comment]
You should look at the actual image and validate that it has accurate metadata and rotation.

**Comment by arash01** [comment]
Problem still exists :(

**Comment by L3xer** [comment]
@arash01  In my case iOS rotated the photo. 
![chrome_2017-08-28_10-40-38](https://user-images.githubusercontent.com/8818052/31000901-020b8dda-a4e8-11e7-901b-ed946b4e6199.png)

I've fixed it by rotating it according to the metadata at my backend.

**Comment by bentmar** [comment]
same for me, ios portraits has 90 CW orientation in exif data..

**Comment by pettenstein** [comment]
Same problem here. When I create an UIImage with the Picture I get with MediaPlugin, the Rotation Property returns an incorrect value (Up).
When I do this with exactly the same image added as project resource (not picked with MediaPlugin) it does return the correct rotation (Right).

Note: This started with iOS11.

Tested with image:
![img_0075](https://user-images.githubusercontent.com/2462241/31441173-a9f9a262-ae92-11e7-9495-f08bcc647972.JPG)

**Comment by pettenstein** [comment]
@jamesmontemagno is this something that is still looked at? Or should I create a new issue for this problem?

**Comment by worawutt** [comment]
Same for me, v3.0.1 take portraits photo on iOS 11 after sync and open on Android, the picture rotate CW 90.  Change back to v2.6.2 the issue is gone.

![ios11_portrait_rotate_v301](https://user-images.githubusercontent.com/15317912/31804777-f7074736-b585-11e7-84b5-b3345209bb62.jpg)

**Comment by shayo** [comment]
Same here.
Tried all possible combinations of RotateImage and SaveMetaData
and I always get rotated image when I load it on Android with FFImageLoading

**Comment by kikutano** [comment]
Same problem with **3.1.3** everything works fine, but if I try to catch a photo with iOS Camera, on Android ( and **_only_** on Android ) is rotate -90CW, on iOS is ok. The problem occur only when I take a photo on iOS and i view the Photo on an Android device.

**Comment by bentmar** [comment]
@kikutano  same. If anyone has some goodies on imagehandling on serverside plz share or pm

**Comment by kikutano** [comment]
@bentmar You should use **_GetStreamWithImageRotatedForExternalStorage()_** instead of **_GetStream()_** and everything works great!

**Comment by antontereshko** [comment]
@kikutano It`s not work for me.

**Comment by antontereshko** [comment]
I can repeat this bug on Sumsung S8

**Comment by weerachate** [comment]
@kikutano  I try to fix same issue here with GetStreamWithImageRotatedForExternalStorage() but I got the error in iOS show bellow 

{System.InvalidOperationException: The underlying NSMutableData changed while we were consuming data
  at Foundation.NSData+UnmanagedMemoryStreamWithMutableRef.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x0001b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.8.0.20/src/Xamarin.iOS/Foundation/NSData.cs:177 
  at System.IO.Stream.InternalCopyTo (System.IO.Stream destination, System.Int32 bufferSize) [0x00012] 

my code:

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                Directory = "Sample",
                RotateImage = true,
                Name = DateTime.Now.ToString()
            });

if (file != null)
                    {
                        String imagedata;

                        using (var memoryStream = new MemoryStream())
                        {
                           _file.GetStreamWithImageRotatedForExternalStorage().CopyTo(memoryStream);

                            _file.Dispose();
                            _file = null;

                            imagedata = Convert.ToBase64String(memoryStream.ToArray());
                        }
}

What should I do more for fix this?

**Comment by AdelaPetrut** [comment]
Hello,

Have you been able to resolve this problem?
The rotation happens for me also, on IOS 11 on Iphone. The image taken is presented as flipped with 90 degrees.

I already tried RotateImage = false and updated to latest version: 3.1.3

Thank you
