### ISSUE TITLE
No exif data on android

### ISSUE THREAD

**Issue by bpater-tp** [jamesmontemagno/MediaPlugin#161]
## Bug 

Version Number of Plugin: 2.6.2 and 2.6.3.1-beta
Device Tested On: LG Nexus 4, android 5.1.1
Simulator Tested On:

### Expected Behavior
After taking photo via application and storing it there should be exif data on all platforms. Preferably they would contain date and time of photo and gps localisation.

### Actual Behavior
No exif data at all on android. There are some (very few) data when photo is taken on iOS. After sending the pic from application to computer I've checked with exif tool and got the following:

> exif IMG_20170112_111326.jpg 
Corrupt data
The data provided does not follow the specification.
ExifLoader: The data supplied does not seem to contain EXIF data.

Also macos Preview does not show exit tab.

### Steps to reproduce the Behavior
create a photo like described in API usage, store it on the phone, read it back and discover missing exif. alternatively send it to computer.

**Comment by NVentimiglia** [comment]
https://github.com/jamesmontemagno/MediaPlugin/issues/160

**Comment by jamesmontemagno** [comment]
I believe perhaps I need to copy the old exif data to the copy of the file.. Will look into it, although the exif data must exist because that is how I get the rotation... hmmmm

**Comment by jamesmontemagno** [comment]
@bpater-tp do you have a small sample of the code you are using to read the exif data? Would be interested.

**Comment by bpater-tp** [comment]
haven't check that on phone yet. I plan to use ExifLib.PCL ( https://www.nuget.org/packages/ExifLib.PCL ), but that part is not implemented yet... 

Right now I checked only on pc after sending the image from within app.

I might be doing something wrong but the code to capture image is quite simple:

```
if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
{
     //custom alert code here
     return null;
}
var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
     Directory = "images",
});
await SaveStreamToFile(photoFileName, file.GetStream());  //store stream using PCLStorage.FileSystem

```

**Comment by bpater-tp** [comment]
a-ha! so if I would use filename for `StoreCameraMediaOptions` and copy temp file that should contain exif metadata?

**Comment by jamesmontemagno** [comment]
@bpater-tp  I believe so, let me know.

**Comment by bpater-tp** [comment]
Ok, I was now able to read some metadata on both ios and android. But it's not the one I was looking for - only dimensions are there and orientation. Any idea when other things like date & time of photo, gps location etc could be implemented?
