### ISSUE TITLE
Image Picker Performance is Slow

### ISSUE THREAD

**Issue by hardcodet** [jamesmontemagno/MediaPlugin#162]
## Env

Version Number of Plugin: Current NuGet
Device Tested On: Galaxy S6, XF 2.3.3

## Feature Request:

```
                var options = new PickMediaOptions {PhotoSize = PhotoSize.Full};
                MediaFile media = await CrossMedia.Current.PickPhotoAsync(options);
```

The snippet above takes around 5 seconds to complete after I picked a photo from my device, while all subsequent work (crop, resize and transform through the FFImageLoading library) is extremely fast. 
Is this the expected behavior due to initial I/O, or is the plugin doing optimizations that I might be able to skip otherwise?

Thanks for your advice
Philipp

**Comment by jamesmontemagno** [comment]
It would all be IO copying locally. I have items on my device 6P and works pretty quick. Usually there is some delay in copy items to disk. When you do Full it is only 1 copy and doesn't have to do much unless it has to rotate it then it is another rotation.

Most likely taking a photo in a few seconds is fine. If you need super crazy fast like instagram or snapchat then you should look into using embedded camera controls like Camera2 in Android.

**Comment by hardcodet** [comment]
That was quick! I can live with the delay - it's only a profile picture selection - I was mainly wondering whether I'm seeing buggy behavior there.

Thanks! Philipp
