### ISSUE TITLE
Open Camera Crash in Sample code with Moto G3

### ISSUE THREAD

**Issue by Dan27F** [jamesmontemagno/MediaPlugin#163]
I Download the sample code but not working with Moto g3.

## Bug 

Version Number of Plugin: 2.6.1 & 2.6.2
Device Tested On: Moto G3
Simulator Tested On:

### Expected Behavior
Take photo and display.
### Actual Behavior
Crashes

### Steps to reproduce the Behavior
Open the sample code in device moto g3

## Feature Request:
so it works

**Comment by jamesmontemagno** [comment]
I will need more information about the "sample" code... do you mean the sample folder?

**Comment by jamesmontemagno** [comment]
Also, you should give an output of what actually happened. Did it take a photo? What was the crash?

**Comment by jamesmontemagno** [comment]
Made it so the images size is set to medium. Read through your logs and actually try to see what is going on. You probably had a bitmap too large issue on your specific device and need to shrink the image.

**Comment by Dan27F** [comment]
Hi! James. Yes the code is your sample folder this library. When the camera is opened the application closes. But I followed your advice and configure the photosize in medium and work!! Thank!
