### ISSUE TITLE
Camera Render Options and Settings

### ISSUE THREAD

**Issue by spatrickgreensboroaa** [jamesmontemagno/MediaPlugin#164]
## Feature Request:
How can I access the camera to take away options and set specific settings for my users?

**Comment by jamesmontemagno** [comment]
Not possible.

**Comment by spatrickgreensboroaa** [comment]
James, How does your plugin access the camera?

**Comment by jamesmontemagno** [comment]
Depending on each platform it launches and takes a photo a bit different. The code is all their to browse through. For iOS there is a photo picker, Android I launch an Intent, and UWP has a different camera API. Essentially each launches the app or window to take a photo and it is the default. If you want fine granular control you would want to go through embedding camera controls on each platform.

**Comment by spatrickgreensboroaa** [comment]
Ok. Thanks so much!
