### ISSUE TITLE
Permission for opening the camera is not asking during run time in android 6.0 devices

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#165]
## Bug 

Version Number of Plugin: 2.6.0
Device Tested On: Android Nexus 6 
Simulator Tested On:

### Expected Behavior
 Should ask the permissions for accessing the camera during run time in android devices using Marshmallow OS.

### Actual Behavior
It is not popping the permissions during run time. And Camera application is accessible and is not getting opened.

### Steps to reproduce the Behavior
I have added the below code in my mainactivity.cs as well. But still it is not prompting for permissions during runtime.

public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
{
    PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
}

Pluging.permisssions dll is also added in references in android project after installing the plugin.

## Feature Request:

Please fill in what you would like

**Comment by jamesmontemagno** [comment]
Did you make sure you set your Target to 6.0+? https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code

**Comment by pradeeparutla** [comment]
I have already followed 2 steps mentioned in the above link. But still it is not prompting for required permissions during run time. 
As a temporary solution, I was opening the application settings in the device manually and providing the required permissions.(Settings -> Application -> permissions -> provided the required permissions)

**Comment by jamesmontemagno** [comment]
You can also manually request it by using the Permission Plugin which is the recommended approach: https://github.com/jamesmontemagno/PermissionsPlugin
