### ISSUE TITLE
Rotation on Android works correctly only when I use Photosize option.

### ISSUE THREAD

**Issue by allbdeveloper** [jamesmontemagno/MediaPlugin#166]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: LG G3 (android 6.0)
Simulator Tested On:

### Expected Behavior
Rotation should be correct always when I pick photos.

### Actual Behavior
Rotation on Android works correctly only when I use Photosize option.

### Steps to reproduce the Behavior

Month ago, I filed a issue and you fixed at
https://github.com/jamesmontemagno/MediaPlugin/commit/af2ce331fbfc203d3b9b40f450581ac7e7004b29

But it seems it's working only when I set photosize option.

I suspect this behavior is happening because of 
https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs#L376-L377

Could you check this?

Since I always set photosize as medium, so no problem to use it.
But I was told other person this.
https://forums.xamarin.com/discussion/comment/248469#Comment_248469

**Comment by jamesmontemagno** [comment]
That line of code says....
```
if (rotation == 0 && photoSize == PhotoSize.Full && quality == 100)
```

This means the photo doesn't need to be rotated, resized, and quality doesn't need to be adjusted at all.


What code were you calling to repro this.

**Comment by allbdeveloper** [comment]
Yes. I understand what that code says.

But the problem is actually photo needs to be rotated on some device or sometimes. 
Don't you have experienced this? 

Please look this case.
https://forums.xamarin.com/discussion/comment/248469#Comment_248469

**Comment by jamesmontemagno** [comment]
Well then the "rotation" wouldn't be 0 and then it would be rotated in this instance.

**Comment by jamesmontemagno** [comment]
have you tried the 2.6.3 beta?

**Comment by allbdeveloper** [comment]
No I didn't yet, 
I will try it and share the result later.

Thanks.

**Comment by bpater-tp** [comment]
I have checked both 2.6.2 and 2.6.3-latest-beta. Orientation is fine as long as you pass something to PickPhotoAsync. If you pass null it is wrong and the pictures are rotated in wrong way. 2.6.3-beta does not change things here. It makes orientation more human readable (TopLeft instead of 0, etc) but works the same way.

**Comment by bpater-tp** [comment]
The problem is that when one calls PickPhotoAsync with new PickMediaOptions() as parameter the exif metadata are lost.

**Comment by jamesmontemagno** [comment]
@bpater-tp thanks... i will look into that, the null could the issue.
