### ISSUE TITLE
[Bug] Windows Phone 8.1: Strange bars on right and left side of photo

### ISSUE THREAD

**Issue by Dobowicz** [jamesmontemagno/MediaPlugin#168]
## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Nokia Lumia 520
Simulator Tested On: none

### Expected Behavior
Photo taken with camera should have good quality.

### Actual Behavior
Photo sometimes (even half of attempts to take a photo) 
has strange bars on right and left side with changed colors (look at attachments). It is not the fault of the device, because photos taken with system camera application look good.

![29012017143754](https://cloud.githubusercontent.com/assets/14074524/22404414/e13b4b3e-e630-11e6-9f3a-db926df36a93.jpg)
![29012017143728](https://cloud.githubusercontent.com/assets/14074524/22404419/ea0f4a94-e630-11e6-9304-93aa6810c118.jpg)
![29012017143704](https://cloud.githubusercontent.com/assets/14074524/22404420/ecb28784-e630-11e6-9ea1-ef25594d8c63.jpg)

### Steps to reproduce the Behavior
1. Use TakeAPhotoAsync() method with Directory and Name options properties set and phone being held vertically.
2. Check saved photo.
3. Sometimes photo has bars.

**Comment by jamesmontemagno** [comment]
Unable to repo. Can't start to attempt to fix with out a 100% repo
