### ISSUE TITLE
Media - Camera images taken in portrait behaving weird.

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#17]
_From @highplains on March 28, 2016 21:53_

Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [X] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [X ] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.4.0-beta3
Device Tested On: iPhone 6s+
Simulator Tested On: iPhone 6s

### Expected Behavior
Take a photo in portrait, photo is saved/displays in correct dimensions.

### Actual Behavior
Photo looks like its been stretched into landscape

### Steps to reproduce the Behavior
Take a photo in portrait, same photo in landscape. Load in to a ImageView AspectFit

Stable Version.
![screen shot 2016-03-28 at 3 38 57 pm](https://cloud.githubusercontent.com/assets/1825076/14091379/2b9e11f0-f4fd-11e5-9d95-844ee1d8c13e.png)

Latest Beta
![screen shot 2016-03-28 at 3 39 06 pm](https://cloud.githubusercontent.com/assets/1825076/14091380/2f50cce8-f4fd-11e5-8eaa-7e24806a89d9.png)

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#263_

**Comment by jamesmontemagno** [comment]
_From @lima66 on April 13, 2016 14:33_

I have the same problem the image are rotate of 90° with Iphone 6 os: 9.3 , Iphone 5 os: 9.2 and i have update the plugin to the beta 3

**Comment by jamesmontemagno** [comment]
_From @highplains on April 26, 2016 16:33_

bump

**Comment by jamesmontemagno** [comment]
_From @highplains on June 5, 2016 16:31_

Had to downgrade to last stable release to get this to work properly. But now the android rotation is messed up again.

**Comment by jamesmontemagno** [comment]
I believe I have fixed this now in the latest. Please test it out in the latest beta! Thanks.

If still an issue, please re-open with repro steps again.

**Comment by deckertron9000** [comment]
Testing this out with 2.5.1-beta40 on an iOS iPad Mini 2 with iOS 9.3.5 seems to result in the stretching issue. 

Portrait (stretching occurs horizontally)
![thumb_img_0009_1024](https://cloud.githubusercontent.com/assets/10391684/18100236/b9422100-6eaf-11e6-9444-21ab7649a04c.jpg)

Landscape (no stretching)
![thumb_img_0010_1024](https://cloud.githubusercontent.com/assets/10391684/18100243/c2f5cf12-6eaf-11e6-81fb-7ce9f97dfd8c.jpg)
