### ISSUE TITLE
PickVideoAsync & TakeVideoAsync on iOS10 doesn't copy file to local storage ?!

### ISSUE THREAD

**Issue by Pav3l** [jamesmontemagno/MediaPlugin#170]
## Bug 
Pick video or record video, returned video does not get copied to the storage folder
Version Number of Plugin: 2.6.1
Device Tested On: iPhone 6S
Simulator Tested On: --- 

### Expected Behavior
Copied file to exist under provided path
### Actual Behavior
File not copied, returned path is not correct as NSFileManager.Default.FileExists returns false
### Steps to reproduce the Behavior
Use sample app on iOS

## ** Edit**
After some investigation, I have discovered that library in fact copies the file but to the tmp directory, and after a while it is deleted from there. Just copy it as soon as possible to normal directory.
Someone please close this issue. Sorry for the inconvenience.

**Comment by jamesmontemagno** [comment]
Weird that it gets moved. Where are you moving it too I should go into your app documents folder and should remain. Will close, but can you comment.
