### ISSUE TITLE
DateTime.ToString() and neutral calendar

### ISSUE THREAD

**Issue by FrancoisM** [jamesmontemagno/MediaPlugin#171]
[That line:](https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.iOS/MediaPickerDelegate.cs#L425) should be called with a neutral calendar as for some of my users it throw an exception as per that [discussion](https://forums.xamarin.com/discussion/42899/datetime-tostring-throws-argumentoutofrangeexception-in-thai-locale).

**Comment by jamesmontemagno** [comment]
Are you sure it actually throws an exception? As I pass in an actual value for the format. Which is different then what they are doing in that thread.

**Comment by FrancoisM** [comment]
Actual HockeyApp Crash Trace:
```
Parameter name: value
System.Globalization.DateTimeFormatInfo.set_Calendar(Calendar value)
System.Globalization.DateTimeFormatInfo.DateTimeFormatInfo(CultureData cultureData, Calendar cal)
System.Globalization.CultureInfo.get_DateTimeFormat()
System.Globalization.CultureInfo.GetFormat(Type formatType)
System.Globalization.DateTimeFormatInfo.get_CurrentInfo()
System.DateTime.ToString(string format)
Plugin.Media.MediaPickerDelegate.GetOutputPath(string type, string path, string name)
Plugin.Media.MediaPickerDelegate.<GetPictureMediaFile>d__24.MoveNext()
Plugin.Media.MediaPickerDelegate.<FinishedPickingMedia>d__9.MoveNext()
Social.iOS.Application.Main(string[] args)
```

**Comment by jamesmontemagno** [comment]
I'll integrate this in, however it should be in bugzilla as it is clearly a mono bug

**Comment by FrancoisM** [comment]
I don't know which calendar caused the issue. I don't know how to report crashes with userid on HockeyApp (but that's another issue) in order to find out.
I'll compile my iOS project with Properties>iOSBuild>Advanced>Internalization>all boxes checked and hopefully the issue will disapear (I read some calendars where not linked otherwise).
But you could make your ToString() using invariant culture as it doesn't matter in the case where you call it.

**Comment by jamesmontemagno** [comment]
Cool, thanks for info.

Will do this: 

                var now = DateTime.Now;
                string timestamp = $"{now.Year}{now.Month}{now.Day}_{now.Hour}{now.Minute}{now.Second}";

**Comment by FrancoisM** [comment]
You already done it! Great!
But why not just ?

`DateTime.Now.ToString("yyyMMdd_HHmmss", CultureInfo.InvariantCulture)`

**Comment by jamesmontemagno** [comment]
Maybe... do we know for sure it would work?

**Comment by FrancoisM** [comment]
For sure? No. It should though. UnitTest?

**Comment by jamesmontemagno** [comment]
teheh
well pushing it out
