### ISSUE TITLE
Cropping-view acting strange in UWP Desktop

### ISSUE THREAD

**Issue by Brosten** [jamesmontemagno/MediaPlugin#172]
## Bug 
When taking a photo from a desktop device, with windows 10 (UWP), the crop-selection is acting strange. (See attached images)

Version Number of Plugin: 2.6.2.0
Device Tested On: HP Laptop with Windows 10

### Expected Behavior
Sake as with the Camara-app from Windows 10

### Actual Behavior
The proposed crop area defaults to areas outside the photo.

### Steps to reproduce the Behavior
call CrossMedia.Current.TakePhotoAsync(...)

![step1](https://cloud.githubusercontent.com/assets/10629345/22593881/ed271f9c-ea20-11e6-82c6-4ae83c0502b6.png)
![step2](https://cloud.githubusercontent.com/assets/10629345/22593882/ed28db0c-ea20-11e6-93c1-e2a33a172198.png)

**Comment by jamesmontemagno** [comment]
It uses the default camera, out of my control and you can turn it off.
