### ISSUE TITLE
Media plugin doesn't work on iPad Mini

### ISSUE THREAD

**Issue by softsan** [jamesmontemagno/MediaPlugin#173]
## Bug 
I used Media plugin for Xamarin.Forms app.  It works fine on **iPhone** and **android** phones.  but `CrossMedia.Current.TakePhotoAsync` and `CrossMedia.Current.TakeVideoAsync` does not work on **iPad**. Whenever i tried to access camera on iPad it gives me following error in application output:
```
<Error>: CGContextAddPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
<Error>: clip: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
<Error>: CGContextSetFillColorWithColor: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
 <Error>: CGContextFillRects: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
 <Error>: CGContextAddPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
 <Error>: clip: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
 <Error>: CGContextDrawLinearGradient: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.
```

I used following code:
```
MediaFile file = null;
try
{
	await CrossMedia.Current.Initialize();
       if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
      {
		await DisplayAlert("no Camera", "Camera not available","OK");
		return;
     }
     file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
     {
		Directory = "Sample",
		Name = "img_" + Guid.NewGuid() + ".jpg",
		PhotoSize = PhotoSize.Medium,
	});
}
catch (Exception ex)
{
	Debug.WriteLine("MediaUpload"+ ex);
}
```
However, `CrossMedia.Current.PickPhotoAsync` method works fine on all devices.

Version Number of Plugin:2.6.3.1-beta
Device Tested On:iPAD Mini - iOS 10.11
Simulator Tested On:N/A

### Expected Behavior
It should show Camera view on iPAD.
### Actual Behavior
It doesn't show Camera and throws above mentioned error in Application output (also see the same error in Device logs)
### Steps to reproduce the Behavior
Use above method in Xamarin.forms project and invoke the method on button click.

## Feature Request:
N/A

Also set environment variable like this:
![envvariable](https://cloud.githubusercontent.com/assets/7391319/22628738/675bc120-ebff-11e6-856c-efaf44db6557.png)

**Comment by jamesmontemagno** [comment]
It works just fine, you are most likely hitting a bug with the UI slider:
http://stackoverflow.com/questions/41256528/application-freezes-when-trying-to-present-rear-camera-on-ipad

if you set any of this:

```
UISlider.Appearance.MinimumTrackTintColor = UIColor.Red.ColorWithAlpha(100);
```

iOS has an issue with it and will throw an exception when displaying the camera.

There is no fix for this but to remove it. Even if I save out the original and then set it to null it will still throw the exception.

See open radar: https://openradar.appspot.com/30396879

**Comment by jamesmontemagno** [comment]
Ran it on test cloud to prove working fine: https://testcloud.xamarin.com/test/mediatest-ios_49f7861d-1e11-4c6c-9908-8588d8034efa/

**Comment by softsan** [comment]
Oh okay. We are using Xamarin.forms Slider control but not in the same page, but in other page. So is that the slider shouldn't be anywhere in the app?

**Comment by jamesmontemagno** [comment]
I tried my sample app with a slider and it worked just fine. You usually find those in your app delegate somewhere.

If you open up the "tests" folder of this app there are two test apps that I have ran against iPad and working well.

**Comment by softsan** [comment]
Found that and remove it and its working like a charm!

Thanks and appreciate your support and help!
👍
