### ISSUE TITLE
Feature Request - Option to set camera flash to be ON when camera open in iOS.

### ISSUE THREAD

**Issue by gaurav-lucemorker** [jamesmontemagno/MediaPlugin#174]
## Feature Request:
Would like an option in settings to set the camera flash to be always on. Right now when the camera open flash mode is auto. 

Please let me know if there are any workaround for this currently.

**Comment by jamesmontemagno** [comment]
I would recommend: https://github.com/kphillpotts/Xamarin.Plugins/tree/master/Lamp

Too much code for this library.
