### ISSUE TITLE
Not working on iOS with Xamarin.Forms 2.3.4.184 pre1 after awaiting ActionSheet

### ISSUE THREAD

**Issue by nonlin** [jamesmontemagno/MediaPlugin#177]
Picker Does not work after awaiting ActionSheet in Xamarin.Forms 2.3.4.184 pre 1 on iOS only. 

## Bug 
Picker will open the Take or Pic prompt after awaiting for an Action Sheet on iOS
Version Number of Plugin: 2.6.2
Device Tested On:  
Simulator Tested On: 10.2

### Expected Behavior
Selecting pic after awaiting for action sheet should show the media picker on iOS 
### Actual Behavior
Nothing happens, no error, no crash, no iOS selection window.
### Steps to reproduce the Behavior
Install Forms 2.3.4.184 and the latest MediaPlugin await for the action sheet and then await for Crossmedi Take or Pic video or picture. 

Currently I'm using a hack that involves wrapping the ActionSheet call into a Task that I can cancel.

**Comment by nonlin** [comment]
Scratch that it has something to do with our helper class. 
Using it directly works just fine.

**Comment by nonlin** [comment]
After further research I can confirm this is an issue and the cause is awaiting for an ActionSheet before awaiting for the TakePhotoAsync or TakeVideoAsync.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/MediaPlugin/issues/169
