### ISSUE TITLE
[Bug] Asus zendfone 2: cannot update image after capturing by camera

### ISSUE THREAD

**Issue by quangtranniit** [jamesmontemagno/MediaPlugin#179]
## Bug 

Version Number of Plugin: 2.6.0
Device Tested On: Asus Zendphone 2 (android 5.0)
Simulator Tested On:

### Expected Behavior
When I capture image, or pick image from gallery, the image should be updated to the image view.

### Actual Behavior
Nothing was updated because the content page was reinitialized.

### Steps to reproduce the Behavior
1. Create a screen, then add a button, a image view to the screen. Add these below codes after in the constructor of the content page.
2. Run or debug program to device, then press capture button, or pick button to get image.
```
takePhoto.Clicked += async (sender, args) =>
{
    await CrossMedia.Current.Initialize();

    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
    {
        DisplayAlert("No Camera", ":( No camera available.", "OK");
        return;
    }

    var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
    {
        Directory = "Sample",
        Name = "test.jpg"
    });

    if (file == null)
        return;

    await DisplayAlert("File Location", file.Path, "OK");

    image.Source = ImageSource.FromStream(() =>
    {
        var stream = file.GetStream();
        file.Dispose();
        return stream;
    }); 

    //or:
    //image.Source = ImageSource.FromFile(file.Path);
    //image.Dispose();
};
```

**Comment by jamesmontemagno** [comment]
Unable to validate as this works fine here. I do not solve phone specific problems. I would try to change the resolution/size of the photo coming in as it might be too big for your image.

**Comment by quangtranniit** [comment]
@jamesmontemagno If I set <Image x:Name="image" Source="/storage/emulated/0/Pictures/JPEG_20170129_165616_.jpg" />, it will be display on the screen. But if I choose it by Picker or capture image, the content page will be restart, so there won't be happen.

**Comment by jamesmontemagno** [comment]
The content page should not get restarted and this works fine in my sample app. 

Did you change the MainActivity attributes at all?

**Comment by quangtranniit** [comment]
@jamesmontemagno no, here is my MainActivity

~~~.javascript
[Activity(Label = "App2", Icon = "@drawable/icon", Theme = "@style/MainTheme", MainLauncher = true, ConfigurationChanges = ConfigChanges.ScreenSize | ConfigChanges.Orientation)]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            global::Xamarin.Forms.Forms.Init(this, bundle);
            
            LoadApplication(new App());
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    }
~~~

**Comment by quangtranniit** [comment]
@jamesmontemagno even I run your sample, it still doesn't work

[https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples/MediaSample](https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples/MediaSample)

**Comment by jamesmontemagno** [comment]
Are you sure you don't have kill activity on in your developer options?

Or try to add this line in your MainActivity:
https://github.com/xamarinhq/app-evolve/blob/master/src/XamarinEvolve.Android/MainActivity.cs#L38

**Comment by quangtm1** [comment]
To be able to debug on devices, I have to turn off **Use share Runtime**. That's all !. I added your line, but it still doesn't work.
![Uploading image.png…]()

**Comment by quangtm1** [comment]
This is output when I clicked on Capture button

02-18 12:47:53.560 D/Mono    (17276): Unloading image System.Threading.Tasks.dll [0xf4125b00].
02-18 12:47:53.560 D/Mono    (17276): Image addref System.Threading.Tasks[0xda3bf6a0] -> System.Threading.Tasks.dll[0xee896f00]: 5
02-18 12:47:53.560 D/Mono    (17276): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
02-18 12:47:53.560 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
02-18 12:47:53.560 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> System.Threading.Tasks[0xeb9f74c0]: 3
02-18 12:47:53.560 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> Plugin.Permissions.Abstractions[0xeb9f4d00]: 2
02-18 12:47:53.562 D/Mono    (17276): Unloading image System.Collections.dll [0xf4125b00].
02-18 12:47:53.562 D/Mono    (17276): Image addref System.Collections[0xda3bf6a0] -> System.Collections.dll[0xee897900]: 7
02-18 12:47:53.562 D/Mono    (17276): Config attempting to parse: 'System.Collections.dll.config'.
02-18 12:47:53.562 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Collections/System.Collections.config'.
02-18 12:47:53.562 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> System.Collections[0xeb9f7580]: 5
02-18 12:47:53.562 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> Plugin.Media.Abstractions[0xeb9f4b20]: 2
02-18 12:47:53.565 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> Plugin.Media[0xeb9f4c40]: 2
02-18 12:47:53.565 D/Mono    (17276): Assembly Ref addref Plugin.Media[0xeb9f4c40] -> Plugin.Media.Abstractions[0xeb9f4b20]: 3
02-18 12:47:53.566 D/Mono    (17276): Unloading image System.Threading.Tasks.dll [0xf4125b00].
02-18 12:47:53.566 D/Mono    (17276): Image addref System.Threading.Tasks[0xda3bf6a0] -> System.Threading.Tasks.dll[0xee896f00]: 6
02-18 12:47:53.566 D/Mono    (17276): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
02-18 12:47:53.566 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
02-18 12:47:53.566 D/Mono    (17276): Assembly Ref addref Plugin.Media.Abstractions[0xeb9f4b20] -> System.Threading.Tasks[0xeb9f74c0]: 4
02-18 12:47:53.567 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> Plugin.Permissions[0xeb9f4dc0]: 2
02-18 12:47:53.567 D/Mono    (17276): Assembly Ref addref Plugin.Permissions[0xeb9f4dc0] -> Plugin.Permissions.Abstractions[0xeb9f4d00]: 3
02-18 12:47:53.568 D/Mono    (17276): Unloading image System.Threading.Tasks.dll [0xf4125b00].
02-18 12:47:53.568 D/Mono    (17276): Image addref System.Threading.Tasks[0xda3bf6a0] -> System.Threading.Tasks.dll[0xee896f00]: 7
02-18 12:47:53.568 D/Mono    (17276): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
02-18 12:47:53.568 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
02-18 12:47:53.568 D/Mono    (17276): Assembly Ref addref Plugin.Permissions.Abstractions[0xeb9f4d00] -> System.Threading.Tasks[0xeb9f74c0]: 5
02-18 12:47:53.570 D/Mono    (17276): Unloading image System.Collections.dll [0xf4128800].
02-18 12:47:53.570 D/Mono    (17276): Image addref System.Collections[0xda3bf6a0] -> System.Collections.dll[0xee897900]: 8
02-18 12:47:53.570 D/Mono    (17276): Config attempting to parse: 'System.Collections.dll.config'.
02-18 12:47:53.570 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.Collections/System.Collections.config'.
02-18 12:47:53.570 D/Mono    (17276): Assembly Ref addref Plugin.Permissions.Abstractions[0xeb9f4d00] -> System.Collections[0xeb9f7580]: 6
02-18 12:47:53.573 D/Mono    (17276): Unloading image System.IO.dll [0xf4128d00].
02-18 12:47:53.573 D/Mono    (17276): Image addref System.IO[0xda3bf6a0] -> System.IO.dll[0xee897400]: 6
02-18 12:47:53.573 D/Mono    (17276): Config attempting to parse: 'System.IO.dll.config'.
02-18 12:47:53.573 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.IO/System.IO.config'.
02-18 12:47:53.573 D/Mono    (17276): Assembly Ref addref Plugin.Media.Abstractions[0xeb9f4b20] -> System.IO[0xeb9f7520]: 4
02-18 12:47:53.574 D/Mono    (17276): Unloading image System.IO.dll [0xf4128d00].
02-18 12:47:53.574 D/Mono    (17276): Image addref System.IO[0xda3bf6a0] -> System.IO.dll[0xee897400]: 7
02-18 12:47:53.575 D/Mono    (17276): Config attempting to parse: 'System.IO.dll.config'.
02-18 12:47:53.575 D/Mono    (17276): Config attempting to parse: '/Users/builder/data/lanes/3511/501e63ce/source/monodroid/builds/install/mono-x86/etc/mono/assemblies/System.IO/System.IO.config'.
02-18 12:47:53.575 D/Mono    (17276): Assembly Ref addref App2[0xeb9f45e0] -> System.IO[0xeb9f7520]: 5
02-18 12:47:53.587 D/Mono    (17276): Assembly Ref addref Mono.Android[0xeb9f7d00] -> System.Xml[0xdb5689a0]: 5
02-18 12:47:53.599 D/Mono    (17276): Assembly Ref addref Plugin.Permissions[0xeb9f4dc0] -> Mono.Android[0xeb9f7d00]: 17
02-18 12:47:53.599 D/Mono    (17276): Assembly Ref addref Plugin.Permissions[0xeb9f4dc0] -> Plugin.CurrentActivity[0xeb9f4940]: 3
02-18 12:47:53.599 D/Mono    (17276): Assembly Ref addref Plugin.Permissions[0xeb9f4dc0] -> Xamarin.Android.Support.v4[0xeb9f4f40]: 4
02-18 12:47:53.603 D/Mono    (17276): Assembly Ref addref Plugin.Permissions[0xeb9f4dc0] -> System.Core[0xdb568580]: 7
02-18 12:47:53.611 D/Mono    (17276): DllImport searching in: '__Internal' ('(null)').
02-18 12:47:53.611 D/Mono    (17276): Searching for 'java_interop_jnienv_get_object_field'.
02-18 12:47:53.611 D/Mono    (17276): Probing 'java_interop_jnienv_get_object_field'.
02-18 12:47:53.611 D/Mono    (17276): Found as 'java_interop_jnienv_get_object_field'.
02-18 12:47:53.617 D/Mono    (17276): DllImport searching in: '__Internal' ('(null)').
02-18 12:47:53.617 D/Mono    (17276): Searching for 'java_interop_jnienv_get_object_array_element'.
02-18 12:47:53.617 D/Mono    (17276): Probing 'java_interop_jnienv_get_object_array_element'.
02-18 12:47:53.617 D/Mono    (17276): Found as 'java_interop_jnienv_get_object_array_element'.
02-18 12:47:53.641 D/Mono    (17276): Assembly Ref addref Plugin.Media[0xeb9f4c40] -> Plugin.Permissions.Abstractions[0xeb9f4d00]: 4
02-18 12:47:53.643 D/Mono    (17276): Assembly Ref addref Plugin.Media[0xeb9f4c40] -> Plugin.Permissions[0xeb9f4dc0]: 3
02-18 12:47:53.649 D/Mono    (17276): Assembly Ref addref Plugin.Media[0xeb9f4c40] -> System[0xeb9f7dc0]: 13
02-18 12:47:53.726 D/Mono    (17276): Assembly Ref addref Plugin.Media[0xeb9f4c40] -> Xamarin.Android.Support.v4[0xeb9f4f40]: 5
02-18 12:47:53.730 V/Monotype(17276): SetAppTypeFace- try to flip, app = App2.Droid
02-18 12:47:53.730 V/Monotype(17276):     Typeface getFontPathFlipFont - systemFont = default#default
02-18 12:47:54.148 D/Mono    (17276): Assembly Ref addref Xamarin.Forms.Platform.Android[0xeb9f7220] -> System.Xml[0xdb5689a0]: 6

**Comment by quangtm1** [comment]
**This is output when image was capture, and turn back to mainpage**

02-18 12:48:34.608 D/Mono    (17276): [0xdb393380] worker finishing
Thread finished: <Thread Pool> #4
The thread 'Unknown' (0x4) has exited with code 0 (0x0).
02-18 12:48:43.758 V/Monotype(17276): SetAppTypeFace- try to flip, app = App2.Droid
02-18 12:48:43.758 V/Monotype(17276):     Typeface getFontPathFlipFont - systemFont = default#default
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
02-18 12:48:43.836 D/Mono    (17276): [0xda65c600] worker starting
02-18 12:48:43.838 W/Resources(17276): Converting to string: TypedValue{t=0x1/d=0x10304f1 a=1 r=0x10304f1}
02-18 12:48:43.839 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=1 r=0x10203ba}
02-18 12:48:43.842 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=1 r=0x10203bb}
02-18 12:48:43.842 W/Resources(17276): Converting to string: TypedValue{t=0x1d/d=0xff161616 a=1 r=0x106013d}
02-18 12:48:43.843 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=1 r=0x10203bc}
02-18 12:48:43.843 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3801 a=1 r=0x10500c9}
02-18 12:48:43.845 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=1 r=0x1050108}
02-18 12:48:43.846 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=1 r=0x10203bd}
02-18 12:48:43.846 W/Resources(17276): Converting to string: TypedValue{t=0x1d/d=0xff161616 a=1 r=0x106013d}
Thread started: <Thread Pool> #8
02-18 12:48:43.863 D/Mono    (17276): [0xdaa47e00] worker starting
Thread started:  #9
02-18 12:48:43.972 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=1 r=0x1050107}
02-18 12:48:43.972 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=1 r=0x10500d0}
02-18 12:48:43.972 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1 a=1 r=0x1050106}
02-18 12:48:43.999 V/Monotype(17276): SetAppTypeFace- try to flip, app = App2.Droid
02-18 12:48:43.999 V/Monotype(17276):     Typeface getFontPathFlipFont - systemFont = default#default
02-18 12:48:44.002 W/Resources(17276): Converting to string: TypedValue{t=0x1/d=0x7f0a0111 a=-1 r=0x7f0a0111}
02-18 12:48:44.002 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070099}
02-18 12:48:44.002 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1 a=2 r=0x7f06001b}
02-18 12:48:44.002 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1 a=2 r=0x7f06001a}
02-18 12:48:44.003 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3801 a=1 r=0x10500c9}
02-18 12:48:44.005 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070055}
02-18 12:48:44.007 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070056}
02-18 12:48:44.105 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x2401 a=1 r=0x10500ce}
02-18 12:48:44.105 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=1 r=0x10500d0}
02-18 12:48:44.454 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070055}
02-18 12:48:44.456 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070056}
02-18 12:48:44.460 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070046}
02-18 12:48:44.461 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070047}
02-18 12:48:44.461 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070048}
02-18 12:48:44.461 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1801 a=2 r=0x7f06002f}
02-18 12:48:44.461 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1201 a=2 r=0x7f060030}
02-18 12:48:44.461 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1801 a=2 r=0x7f06002f}
02-18 12:48:44.465 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070049}
02-18 12:48:44.468 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004a}
02-18 12:48:44.469 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004b}
02-18 12:48:44.469 W/Resources(17276): Converting to string: TypedValue{t=0x1c/d=0x1f000000 a=2 r=0x7f0b0035}
02-18 12:48:44.487 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004c}
02-18 12:48:44.490 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1801 a=2 r=0x7f06002f}
02-18 12:48:44.490 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1201 a=2 r=0x7f060030}
02-18 12:48:44.490 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x1801 a=2 r=0x7f06002f}
02-18 12:48:44.492 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004d}
02-18 12:48:44.493 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004e}
02-18 12:48:44.493 W/Resources(17276): Converting to string: TypedValue{t=0x1c/d=0x1f000000 a=2 r=0x7f0b0035}
02-18 12:48:44.494 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f07004f}
02-18 12:48:44.494 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070050}
02-18 12:48:44.498 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070044}
02-18 12:48:44.499 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=2 r=0x7f06000c}
02-18 12:48:44.502 W/Resources(17276): Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f070045}
02-18 12:48:44.502 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=2 r=0x7f06000c}
02-18 12:48:44.504 W/Resources(17276): Converting to string: TypedValue{t=0x5/d=0x3001 a=2 r=0x7f06000c}

**Comment by quangtm1** [comment]
@jamesmontemagno Thank you, I resolved this problem. It because I checked on Kill Activity on Developer Option as you said before :)
