### ISSUE TITLE
iOS: Gallery cancel button

### ISSUE THREAD

**Issue by js-ka** [jamesmontemagno/MediaPlugin#180]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
The galleries cancel-button is not visible on iOS.
Version Number of Plugin: 2.6.2
Device Tested On: iPhone 6, iPhone 7+
Simulator Tested On:

### Expected Behavior
A cancel-button that is visible for the user.

### Actual Behavior
The galleries cancel-button is not visible on iOS since it has white text color on nearly white background.

### Steps to reproduce the Behavior
Open the gallery with CrossMedia.Current.PickPhotoAsync

## Feature Request:
In addition, it would be great if the text ("cancel") would be localizable.

**Comment by jamesmontemagno** [comment]
Most likely you have some UIAppearance set in your app delegate causing this issue. as you can see from the default implementation it works fine:
![image](https://cloud.githubusercontent.com/assets/1676321/23070268/8ca8d65a-f4f8-11e6-8a51-40bf25760e95.png)

**Comment by js-ka** [comment]
Hello James,

thanks for your quick response.
It's not a problem with the camera view (looks the same as in your 
example), but a problem with the image gallery (called with 
PickPhotoAsync) that has a cancel-button in the upper toolbar with white 
text on a nearly white background.

Another problem is, that your plugin is not localized on iOS.
On android it shows all captions in german (OS language) but on iOS all 
captions are in english although the OS is set to german language.

Best regards
Juergen

Am 17.02.2017 um 16:05 schrieb James Montemagno:

**Comment by jamesmontemagno** [comment]
Please open the translations as a feature request. I will look into the pick photo to be sure, but haven't seen it.

**Comment by jamesmontemagno** [comment]
This is because you are setting the 

UIBarButtonItem.Appearance.TintColor = UIColor.White;

You need to change that before opening the picker.

**Comment by bpater-tp** [comment]
@js-ka for camera/gallery UI to be localised on iOS you need to add localisations to your iOS project. You need `CFBundleLocalizations` in your `Info.plist`. It is iOS-specific thing not an issue with this plugin.
