### ISSUE TITLE
PickPhotoAsync PhotoSize,CompressionQuality and CustomPhotoSize not working in UWP 

### ISSUE THREAD

**Issue by Heshanp** [jamesmontemagno/MediaPlugin#181]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
var file =  await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                    {
                        PhotoSize = PhotoSize.Custom,
                        CustomPhotoSize = 80
                    });

The above code does not apply the mentioned settings to the picked photo. The output is same as the original picture (Dimensions and Size).

Version Number of Plugin: 2.6.1
Device Tested On: WIndows 10 PC (1607-14393.693)
Simulator Tested On:

### Steps to reproduce the Behavior
Use the above code I've mentioned. 

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
That is correct, they are not supported, only iOS and Android

**Comment by jamesmontemagno** [comment]
Only photo size is supported and adjusts the resolution: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.WindowsStore/MediaImplementation.cs#L144

**Comment by Heshanp** [comment]
Thanks James for the clarification. Is UWP support coming or is it left out?

**Comment by jamesmontemagno** [comment]
I have no plans currently, however anyone can add support for the features.
