### ISSUE TITLE
Xamarin Forms and Xam.Plugin.Media warning

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/MediaPlugin#182]
Hi guys,
in my app, developed by Xamarin Forms, I have a picture gallery: a user can take a photo or pick up one from the album. When a user select or take one or more picture, I save all images in memory and when the user press _Save_ I save all images on the file system.

For now I noticed on an iPad mini with iOS 9.3.5 a warning about memory:

> Feb 28 09:37:02  myAppOS[440] <Error>: CGAffineTransformInvert:
> singular matrix. 

> 2017-02-28 09:37:03.168 myAppOS[440:111223]
> Snapshotting a view that has not been rendered results in an empty
> snapshot. Ensure your view has been rendered at least once before
> snapshotting or snapshot after screen updates.

> 2017-02-28 09:37:06.702 myAppOS[440:111223] Received memory warning.

Apart from a warning the app seems working fine.

**Comment by jamesmontemagno** [comment]
Wouldn't have anything to do with the library, maybe post over on the forums.
