### ISSUE TITLE
Java.Lang.IllegalArgumentException while taking photo

### ISSUE THREAD

**Issue by igofed** [jamesmontemagno/MediaPlugin#183]
## Bug 
Java.Lang.IllegalArgumentException while taking photo on Android 6

Version Number of Plugin: 2.6.2 + latest beta
Device Tested On: Motorola XPlay
Simulator Tested On:

### Expected Behavior
Photo taken

### Actual Behavior
Java.Lang.IllegalArgumentException
Failed to find configured root that contains /storage/emulated/0/Android/data/PACKAGE_NAME/files/Pictures/IMG_20170301_002408.jpg
[mono] 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/PACKAGE_NAME/files/Pictures/IMG_20170301_005154.jpg
[mono-rt]   --- End of managed Java.Lang.IllegalArgumentException stack trace ---
[mono-rt] java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/PACKAGE_NAME/files/Pictures/IMG_20170301_005154.jpg
[mono-rt] 	at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
[mono-rt] 	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
[mono-rt] 	at md501ec2dd094f7efcfb6398153f1cfefa5.MediaPickerActivity.n_onCreate(Native Method)
[mono-rt] 	at md501ec2dd094f7efcfb6398153f1cfefa5.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)
[mono-rt] 	at android.app.Activity.performCreate(Activity.java:6010)
[mono-rt] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1129)
[mono-rt] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
[mono-rt] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
[mono-rt] 	at android.app.ActivityThread.access$800(ActivityThread.java:155)
[mono-rt] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
[mono-rt] 	at android.os.Handler.dispatchMessage(Handler.java:102)
[mono-rt] 	at android.os.Looper.loop(Looper.java:135)
[mono-rt] 	at android.app.ActivityThread.main(ActivityThread.java:5343)
[mono-rt] 	at java.lang.reflect.Method.invoke(Native Method)
[mono-rt] 	at java.lang.reflect.Method.invoke(Method.java:372)
[mono-rt] 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
[mono-rt] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)

### Steps to reproduce the Behavior
Target is Android 7.1
Call TakePhoto and have the exception

**Comment by jamesmontemagno** [comment]
Did you add: https://github.com/jamesmontemagno/MediaPlugin#android-n

Looks like you still have "PACKAGE_NAME" in there somewhere...

**Comment by igofed** [comment]
@jamesmontemagno  I have replaced  package with my package name

**Comment by igofed** [comment]
My mistake, thx. path has wrong package name.
