### ISSUE TITLE
Exif data are missing when taking photos

### ISSUE THREAD

**Issue by bpater-tp** [jamesmontemagno/MediaPlugin#184]
## Bug 
Exif data are missing when taking photos

Version Number of Plugin: 2.6.2
Device Tested On: iphone 5, iphone 6, iphone 6s, iphone 7, lg nexus 4, lg nexus 5, samsung galaxy j5, samsung galaxy s7
Simulator Tested On: iOS and Android

### Expected Behavior
jpeg file returned from TakePhotoAsync should have exif metadata, f.e. orientation, camera model, maker, gps location, date, time, etc

### Actual Behavior
the exif chunk is very limited, and provides only orientation and dimensions. photos saved to album have more metadata (still without gps) but it is useless for app that allows to take photo and use it.

### Steps to reproduce the Behavior

call TakePhotoAsync and examine the resulting photo (f.e. with exiflib.pcl)

**Comment by bpater-tp** [comment]
here is very basic app that shows the bug: https://github.com/bpater-tp/mediaexif

**Comment by js-ka** [comment]
+1

**Comment by jamesmontemagno** [comment]
Now integrated in 2.7.0
