### ISSUE TITLE
Exif data are not available for pictures from gallery

### ISSUE THREAD

**Issue by bpater-tp** [jamesmontemagno/MediaPlugin#185]
## Bug 
Exif data are missing when photo is selected from phone gallery

Version Number of Plugin: git-master
Device Tested On: iphone 5, iphone 6, iphone 6s, iphone 7, lg nexus 4, lg nexus 5, samsung galaxy j5, samsung galaxy s7
Simulator Tested On: iOS and Android

### Expected Behavior
jpeg file returned from PickPhotoAsync should have exif metadata, f.e. orientation, camera model, maker, gps location, date, time, etc

### Actual Behavior
After d30e672512e4e114cfa908acc96528476b22800d the metadata are gone because plugin re-compress the selected photo. Also previously it worked only on android, on iOS there were no metadata.

### Steps to reproduce the Behavior

call PickPhotoAsync and examine the resulting photo (f.e. with exiflib.pcl)

**Comment by bpater-tp** [comment]
here is very basic app that shows the bug: https://github.com/bpater-tp/mediaexif

**Comment by jamesmontemagno** [comment]
Now integrated in 2.7.0
