### ISSUE TITLE
Empty thumbnails on phone

### ISSUE THREAD

**Issue by raulbastian** [jamesmontemagno/MediaPlugin#187]
## Bug 
Images aren't showing correctly in the application nor camera roll.

Version Number of Plugin: 2.6.2 and 2.3.0

Device Tested On:
     Huawei P8 Lite: (Not working, photos are taken but not showing in application and appear as empty  thumbnails in the camera roll.)
   Samsung A3:  Working correctly.
   Emulators: Working correctly..

### Expected Behaviour
Images should appear in the camera roll and show in the application.

### Actual Behavior
Images aren't showing and appear as empty thumbnails.

### Steps to reproduce the Behavior
I implemented the exact sample code from the Readme.md usage section with SaveToAlbum=true. When running the aplicacation (on Huawei P8 lite)  for the first time I concede permissions to access the SD Card.

![emptythumbnails](https://cloud.githubusercontent.com/assets/381878/23551491/2d82f4ba-0017-11e7-9c59-7b56a231c14c.jpg)

**Comment by jamesmontemagno** [comment]
I don't fix device specific bugs
