### ISSUE TITLE
Filepaths.xml improvement

### ISSUE THREAD

**Issue by williamdmsi** [jamesmontemagno/MediaPlugin#188]
## Feature Request:
Suggest using external-files-path xml declaration in android filepaths.xml to remove the need to hardcode app name. This would only be possible when using Android support libraries >= 24.2.0 due to [this android bug](https://code.google.com/p/android/issues/detail?id=61170).

The filepaths would go from looking like this:
```
<external-path name="my_images" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Pictures"/>
<external-path name="my_movies" path="Android/data/YOUR_APP_PACKAGE_NAME/files/Movies" />
```
To looking like this:
```
<external-files-path name="my_images" path="Pictures"/>
<external-files-path name="my_movies" path="Movies"/> 
```
Of course this is dependent on the support library and Forms just removed the hard dependency on 23.3.0 (I assume many people using this plugin are using Forms as well). So this might be something for down the road.

**Comment by jamesmontemagno** [comment]
In the future when I update I will make this improvement :)

**Comment by jamesmontemagno** [comment]
Integrating into 3.0 now
