### ISSUE TITLE
Panning Around Image when AllowCropping is On.

### ISSUE THREAD

**Issue by landrzz** [jamesmontemagno/MediaPlugin#189]
## Bug 
Version Number of Plugin: 2.6.2
Device Tested On: iPhone 7+
Simulator Tested On: (No Cam on Simulator)

### Expected Behavior
Cropping Should allow panning to all corners of the photo as long as the image is still filling the crop-square.

### Actual Behavior
Top 5th and bottom 5th of the photo seem to be in an "out-of-bounds state" where you can drag the photo to any of the far corners but when you release from the gesture, the photo jumps/pans back to center. Zooming in to crop and dragging to the corner produces same behavior. Basically... you can't set the crop-square to any of the photo's corners. 

I know we're using iOS's default camera and the cropping feature is something built in, correct? So this may not be related to the plugin at all. It's very possible it's all out of your control. If so, disregard this. I just want to make record of it.

**Comment by jamesmontemagno** [comment]
I have no control over this. It uses the default camera controls.
