### ISSUE TITLE
Android 6.0 asking for wrong permissons (no Camera request)

### ISSUE THREAD

**Issue by faceoffers28** [jamesmontemagno/MediaPlugin#192]
## Bug 

Version Number of Media Plugin: 2.3.0
Version Number of Permissions Plugin: 1.1.7
Version Number of Current Activity: 1.0.1
Target Android version: Android 6.0 (API 23)
Compile using Android version: Android 6.0 (Marshmallow)
Minimum Android target: 4.0.3 (API 15)
Device Tested On: Galaxy S6 Edge running 6.0.1 and Galaxy Tab E running 6.0.1
Simulator Tested On:

### Expected Behavior

The Media Plugin should prompt with a "Allow APPNAME to take pictures and record video" message.

### Actual Behavior

The Media Plugin prompts with a "Allow APPNAME to access photos, media and files on your device" message. 

If I use the Permissions Plugin, with the following code (see below), it prompts the Allow "APPNAME to take pictures and record video" message, but it also prompts the "Allow APPNAME to access photos, media and files on your device" message when it gets to the CrossMedia.Current.TakePhotoAsync method. 

```
var current = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);

                if (current != PermissionStatus.Granted)
                {
                    var rationale = await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(Permission.Camera);

                    if (rationale)
                    {
                        await DisplayAlert("Permissons request", "We need access to your camera to take a picture.", "OK");
                    }

                    var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera });

                    current = results[Permission.Camera];
                }
```

Added to the OnRequestPermissionsResult method in the MainActivity

`PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
`

As a work around, is there a way to stop the CrossMedia.Current.TakePhotoAsync method from prompting the "Allow APPNAME to access photos, media and files on your device" message?

Thanks in advance!

**Comment by jamesmontemagno** [comment]
It doesn't need the camera permission because it just launches an external camera. It only need external document writes.

**Comment by faceoffers28** [comment]
@jamesmontemagno Thanks for the quick reply. The Take Picture button won't work without the "Allow APPNAME to take pictures and record video" permissions. I figured this out because the Camera only works in my app, running Android 6.0, if I first access the ZxingScanner Page, which gives the proper permissions. If I just click on the Take Picture button, I am prompted with the "Allow APPNAME to access photos, media and files on your device" permissions and the Camera view does not display. It works perfectly on every other Android version below 6.0. I've already selected Write External Storage in the manifest. Is this what you were referring to?

**Comment by jamesmontemagno** [comment]
Again, that permission isn't needed because the application doesn't actually embed the camera at all, trust me this is how it works and the sample app works just fine on all of my devices.

**Comment by faceoffers28** [comment]
@jamesmontemagno I trust you. I'm just telling you that it is not working for me. For whatever reason, it is not working correctly on the two devices that I've tested with that are both running Android 6.0+. At this stage, I have no other choice than to make these two permissions requests if I'm going to make my app work on devices running Android 6.0+. I really don't want to do that. I just re-read the ReadMe file and I'm not missing any permissions. I'm Building the app using Visual Studio Enterprise 2015 with the Xamarin 4.0.4.4 extension and Xamarin.Android 6.0.4 plugin.

**Comment by jamesmontemagno** [comment]
You could always add the permission plugin to your projects and request the camera permission if you think that is the cause.

**Comment by jamesmontemagno** [comment]
Additionally, the work around for having the plugin asking for the permission is for you to check and ask for the permission itself. the storage permission

Perhaps you are running into some weird permission issue scenario with ZXing and the media plugin combined... would need a repo.
