### ISSUE TITLE
PickPhotoAsync, iOS image removed from temp folder when MediaFile is disposed

### ISSUE THREAD

**Issue by FinitelyFailed** [jamesmontemagno/MediaPlugin#194]
## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: iPhone 5s

### Expected Behavior
```
await CrossMedia.Current.Initialize();

    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
    {
        DisplayAlert("No Camera", ":( No camera available.", "OK");
        return;
    }

    var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
    {
        Directory = "Sample",
        Name = "test.jpg"
    });

    if (file == null)
        return;

    await DisplayAlert("File Location", file.Path, "OK");

    image.Source = ImageSource.FromStream(() =>
    {
        var stream = file.GetStream();
        file.Dispose();
        return stream;
    }); 
```

After that code has run the image should be in the file.Path location. 

### Actual Behavior
When file.Dispose(); has been computed the image if gone. On Android the image is not removed. If I remove file.Dispose(); the image remains in temp and works as intended.

### Steps to reproduce the Behavior
Run the code above on an iPhone (I have only a iPhone 5s). And check the temp folder in the Document folder:

```
private void PrintListDocumentFiles()
        {
            NSError error;
            string documentPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
            string[] contents = NSFileManager.DefaultManager.GetDirectoryContentRecursive(documentPath, out error);

            foreach (string content in contents)
            {
                Debug.WriteLine(content);
            }
        }
```

**Comment by ericbrunner** [comment]
Do you experience that issue on PickPhotoAsync or TakePhotoAsync or both on iOS?  If that is true I am in big trouble, too because in my app I store the file path to upload pending selected photos to the cloud, even if the app user closes and restarts the app.

**Comment by ericbrunner** [comment]
I curently tested it on my iPhone 4s with Media Plugin Version: `2.6.3.6-beta` for both `PickMediaAsync `and `TakeMediaAsync`. 

I stored that `file.Path` in a File, closed my app and restored the 2 images from that to path to upload them. 

Both photos were found / uploaded. 

But if you have that issue on the iPhone 5 maybe that is helpful: https://github.com/jamesmontemagno/MediaPlugin/issues/63#issuecomment-243805187

Copy the image to  your own app folder. 

Thanks for pointing that out . I will try to test it on a iPhone 5s, too.

**Comment by FinitelyFailed** [comment]
I ended up moving the file from the temp path to an other location. And than dispose the MediaFile. Which works great. :)
