### ISSUE TITLE
An unhandled exception occured. (permission problem?)

### ISSUE THREAD

**Issue by wegascee** [jamesmontemagno/MediaPlugin#195]
Xamarin.Forms app crashes on iOS and Android because of path or permission issue. I'm able to write a file to the same location without problems, but the plugin throws an exception. Permissions should be ok, because I tried everything mentioned in the docs for Android.

## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Samsung SM-T360 (5.1.1)
Simulator Tested On: -

### Expected Behavior
Camera starts and it is possible to take a photo.

### Actual Behavior
App crashes with

> An unhandled exception occured.

on `TakePhotoAsync()` call. I don't get a further description or stacktrace. Using `Directory = "Sample",` does work without a problem.

### Steps to reproduce the Behavior
`Directory = "/storage/emulated/0/Documents/AppName/SomeFolder";`
`Directory = Path.Combine(Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDocuments).AbsolutePath, "AppName", "SomeFolder");`

[TestMediaPlugin.zip](https://github.com/jamesmontemagno/MediaPlugin/files/841220/TestMediaPlugin.zip)

**Comment by jamesmontemagno** [comment]
Did you follow: https://github.com/jamesmontemagno/MediaPlugin#android-n and the rest of the readme?

**Comment by wegascee** [comment]
Yes, I tried that without success. Now I'm using a relative path, but before the Xamarin update, it worked with an absolute one too ...

**Comment by jamesmontemagno** [comment]
So things are good then?

**Comment by wegascee** [comment]
Should it work with absolute paths like `/storage/emulated/0/Documents/AppName/SomeFolder` or not? Has something changed since the Xamarin update?

**Comment by jamesmontemagno** [comment]
Not sure to be honest, haven't had any issues. Closing now.

**Comment by wegascee** [comment]
Correct me if I'm wrong, but with the MediaPlugin one can only use the default picture path of the camera on the platform. For Android it is the [DIRECTORY_PICTURES](https://developer.android.com/reference/android/os/Environment.html#DIRECTORY_PICTURES), which you can retrieve with [GetExternalFilesDirs](https://developer.xamarin.com/api/member/Android.Content.Context.GetExternalFilesDirs/p/System.String/).  Though I didn't found this in your open source code, but the returned path seems to indicate this. Especially I thought one could use any path (internal, external, cache, ...), but it seems that isn't possible. Perhaps you could include that information in your Readme. Thanks.

**Comment by jamesmontemagno** [comment]
The newer versions use the file provider: https://developer.android.com/reference/android/support/v4/content/FileProvider.html and then copies things into the external directories. Things are a bit more complicated based on the version of android that you are running on. I will try to add to readme
