### ISSUE TITLE
[iOS]PickPhotoAsync with Xamarin.Forms 2.3.4-preX

### ISSUE THREAD

**Issue by hadhoryth** [jamesmontemagno/MediaPlugin#197]
## Bug 
Can't peek photo when the PickPhotoAsync is calling. 

```
await CrossMedia.Current.Initialize ();
var file = await CrossMedia.Current.PickPhotoAsync (new Plugin.Media.Abstractions.PickMediaOptions {
	PhotoSize = PhotoSize.Medium
});
```
Version Number of Plugin: 2.6.3-8beta
Device Tested On: iPhone 5
Simulator Tested On: iPhone 7

### Expected Behavior
The phone photo library appears. 

### Actual Behavior
Does nothing.

**Comment by ericbrunner** [comment]
Have you added those keys in your Info.plist file:https://github.com/jamesmontemagno/MediaPlugin/blob/master/README.md#ios ?

**Comment by ericbrunner** [comment]
Take a look that a gist I posted in relation to an issue I reported yesterday. That code works on iOS / Android: https://gist.github.com/ericbrunner/5a4c76cb5cbabc3a992c5a97a216c81c
