### ISSUE TITLE
Allow to specify the maximum picture size in pixels

### ISSUE THREAD

**Issue by gentledepp** [jamesmontemagno/MediaPlugin#200]
## Feature Request:

We would like to switch to this plugin to allow our users to take pictures.
However, we would like to specify (e.g.) that a picture be at max 2048 x 2048 pixels in size.
As the resolutions of the cameras out ther differs very much, specifying the size in "Medium" or "Small" could yield very different results.

```
var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
    PhotoSize = PhotoSize.Custom,
    MaxPictureSize= new Size(2048,2048)
});
```

**Comment by kyurkchyan** [comment]
This is crucial to me as well. It is possible to pic small images from library - and you can not guarantee what will be the outcome. E.g. - if the original image size is 200x200 pixels, and I specify Medium photo size the result would be 100x100 - this is absolutely wrong. the ideal solution is specifying what should be the maximum image size, and only reduce the image size if it's larger than that.

**Comment by jamesmontemagno** [comment]
What you want seems like a "MaxWidthOrHeight" property... I find the current Width or Height (whichever is largest) and reduce it down to your set property an reduce the other by the same percent. Yes?

**Comment by jamesmontemagno** [comment]
Fill in more info in #103 as this is a duplicate
