### ISSUE TITLE
iOS 10.2 PickPhoto Image is never loaded

### ISSUE THREAD

**Issue by Jake-Barrow** [jamesmontemagno/MediaPlugin#203]
Selected Image from Photo Gallery is never loaded into the Image object - works fine on Android 5, 6 and 7.1

Version Number of Plugin: 2.6.2
Simulator Tested On: iPhone 6s iOS 10.2 

### Expected Behavior
Photo is selected and returned, and when the Image source is set and added to the ContentView the image then loads

### Actual Behavior
Photo is selected and returned correctly (as far as I can tell) but when the Image source is set and added to the ContentView, the image never loads. Waited a total of 5 minutes (to ensure it wasn't a slow loading image)

### Steps to reproduce the Behavior
```
        async void PickPhotoTapped(object sender, EventArgs e)
        {
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                await DisplayAlert("Gallery Unavailable", "Picking a photo is not supported on this device", "Ok");
                return;
            }

            var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                PhotoSize = PhotoSize.Medium
            });

            if (file == null)
                return;

            var path = file.Path;
            file.Dispose();

            _attachments.Children.Add(new Image
            {
                WidthRequest = 80,
                HeightRequest = 80,
                Aspect = Aspect.AspectFill,
                Source = path
            });
        }
```

In the above code I'm using the file.Path to display the image, this is a requirement as we will be passing this image through to multiple other pages before we are done with it, and attempting to pass Streams before caused some problems.

Am I doing something wrong here or is there a bug?

**Comment by jamesmontemagno** [comment]
Did you try not disposing?

**Comment by Jake-Barrow** [comment]
@jamesmontemagno 

That's really weird, removing the file.Dispose(); fixes it, however I then pass a list of filepaths for the attachments through to a new page and on this new page the image doesn't display again. Is there something specific to do to show iOS images from the gallery in the Image object? Other than just using the filepath as the ImageSource?

**Comment by jamesmontemagno** [comment]
You may want to try the new beta as I am pretty sure it is fixed there.

**Comment by Jake-Barrow** [comment]
@jamesmontemagno 
I can confirm this is working okay on the new 2.6.3.8-beta package. Thanks :)
