### ISSUE TITLE
Selecting and taking photo is not working on Marshmallow

### ISSUE THREAD

**Issue by ruchi12l** [jamesmontemagno/MediaPlugin#204]
Version Number of Plugin:2.6.2
Device Tested On:Moto G4 Plus

1.I have set both WRITE_EXTERNAL_STORAGE & READ_EXTERNAL_STORAGE permissions.
2.Also added OnRequestPermissionsResult this to Main Launcher Activity.
3.Minimum Android Target set to 4.0.3
4.Target Android version set to 6.0
5.Compile version set to 6.0
6.[assembly: UsesFeature("android.hardware.camera", Required = false)]
[assembly: UsesFeature("android.hardware.camera.autofocus", Required = false)]
have done this in assemblyinfo file.

Plugin.Media.CrossMedia.Current.PickPhotoAsync() returns null.
Plugin.Media.CrossMedia.Current.TakePhotoAsync() returns null On marshmallow.

Anything else I need to do?

**Comment by jamesmontemagno** [comment]
Be sure to read through all of this: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information including the new xml files that need to be added.
