### ISSUE TITLE
TakePhotoAsync ignores "Directory" 

### ISSUE THREAD

**Issue by gentledepp** [jamesmontemagno/MediaPlugin#205]
## Bug 

Version Number of Plugin: "Xam.Plugin.Media": "2.6.2",
Device Tested On: Visual Studio Android 6.1 Emulator 10" 
Simulator Tested On: x

### Expected Behavior
when calling TakePhotoAsync with the options

 ```
               var options = new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "inspections/20170302_algadia/,
                    Name = "mypicturename1234.jpeg"
                };
```
it should (on Android) store the picture in:

/storage/emulated/0/Android/data/my.Superduper.App/files/inspections/20170302_algadia/mypicturename1234.jpeg

### Actual Behavior
it takes "Directory" as a single directory name and **always** prefixes it with a "Pictures" folder
Also note that "inspections/20170302_algadia" is not two folders - it is merged into one single folder:

/storage/emulated/0/Android/data/my.Superduper.App/files/**Pictures**/inspections20170302_algadia/mypicturename1234.jpeg

### Steps to reproduce the Behavior
Just call it with the options above on android.

**Comment by jamesmontemagno** [comment]
This is due to changes in the file settings in the xml, you must specify it there

**Comment by gentledepp** [comment]
Oh... now I see. Thanks for clarifying and sorry for wasting your time.

However (;-)) it would be nice, if 
1) you could make it a little more clear in your documentation (which is already super duper shiny by the way)
2) or your plugin could be so smart that it figures out where the API user wants the image to be stored and simply move it automatically? (because this is what we do now as kind of a 'workaround')
