### ISSUE TITLE
Rotation of images not working

### ISSUE THREAD

**Issue by pauldiston** [jamesmontemagno/MediaPlugin#206]
## Bug 
Version Number of Plugin: 2.6.3.8-beta
Device Tested On: LG-K350
Simulator Tested On: N/A

### Expected Behavior
Image should be rotated according to the method FixOrientationAndResizeAsync  at line 175 of the MediaImplementation.

https://github.com/jamesmontemagno/MediaPlugin/blob/d30e672512e4e114cfa908acc96528476b22800d/src/Media.Plugin.Android/MediaImplementation.cs#L175

### Actual Behavior
Image remains rotated 90 to the left.

### Steps to reproduce the Behavior
Call TakePhotoAsync, load resulting image into an Xamarin.Forms Image control.

**Comment by jamesmontemagno** [comment]
I don't fix device specifics. You will need to debug the code in the tests and see if your photo is returning exif data back as that is what I parse.
