### ISSUE TITLE
Getting System.IO.FileNotFoundException exception while uploading file in android

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/MediaPlugin#209]
I am trying to pick an image file but getting exception below:

System.IO.FileNotFoundException: Could not find file "/storage/sdcard0/Android/data/com.x.x/files/Pictures/temp/IMG_20170315_181955.jpg"

I am using android device 5.1 and 6.0.1 and happening same exception.

can any one suggest what should I do now?

**Comment by jamesmontemagno** [comment]
Did you dispose of the image, it may have deleted it when you did this. You may want to copy it somewhere first or not dispose of it.

**Comment by ShahriatHossain** [comment]
@jamesmontemagno I am not disposing or deleting the image but not sure why this is happening. Can you suggest what should I do now?

**Comment by jamesmontemagno** [comment]
do you have a code sample?

**Comment by jamesmontemagno** [comment]
Maybe look at the resolution here; https://github.com/jamesmontemagno/MediaPlugin/issues/195
