### ISSUE TITLE
iOS iPad - small photo select screen

### ISSUE THREAD

**Issue by alexpetin** [jamesmontemagno/MediaPlugin#211]
## Bug 

Version Number of Plugin: 2.6.2, 2.6.3.8-beta
Device Tested On:
Simulator Tested On: iPad Pro - iOS 9.1, iPad Pro (12.9 inch) - iOS 10.3

### Expected Behavior
CrossMedia.Current.PickPhotoAsync() shows full screen photo select.

### Actual Behavior
![simulator screen shot 30 mar 2017 21 55 46](https://cloud.githubusercontent.com/assets/19589320/24511885/294bec4a-1597-11e7-83af-8a78bd48619c.png)

### Steps to reproduce the Behavior
Invoke CrossMedia.Current.PickPhotoAsync()

**Comment by Jake-Barrow** [comment]
I am also getting this, works fine on iPhone and Android but not on iPad.

**Comment by jamesmontemagno** [comment]
This is correct implementation as a popover and is as designed.
