### ISSUE TITLE
StoreVideoOptions Quality Ignored on Android

### ISSUE THREAD

**Issue by ozzy1873** [jamesmontemagno/MediaPlugin#213]
## Bug 

Version Number of Plugin: 2.6.3.8-beta
Device Tested On: Nexus 6p

### Expected Behavior
Selecting Low quality should create smaller MP4 files when taking videos. 

### Actual Behavior
The MP4 files produced on Android are quite large; many megabytes for even the shortest video. For example, an 8 second video produces a 17 MB file.

### Steps to reproduce the Behavior
Take a short video on Android and examine the size of the file produced. Taking a short video on UWP with Low quality results in a much smaller file.

**Comment by jamesmontemagno** [comment]
I pass through the video quality flag: https://developer.android.com/reference/android/provider/MediaStore.html#EXTRA_VIDEO_QUALITY

It is up to the camera app to respect it.
