### ISSUE TITLE
feature-request - Cropping interface

### ISSUE THREAD

**Issue by gutierrezralph** [jamesmontemagno/MediaPlugin#214]
Allowing us to manipulate or modify cropping interface like draggable cropping indicator to any sides of screen and have option on what color of overlay when cropping. Eg.

Enum CroppingShape
{
     CIRCLE,
     TRIAGLE,
     SQUARE
}

var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
    AllowCropping = true;
    OverlayColor = Gray; //Color of Overlay
    OverlayOpacity = 5; //Opacity of Overlay
    CroppingShape = CroppingShape.CIRCLE; //Shape of Cropper
    IsMovable = true; //Allow user to move Circle shape cropper to select which part og image to crop
});

**Comment by jamesmontemagno** [comment]
No plans on implementing this as it should be done in a different app since it is not available out of the box on all platforms.
