### ISSUE TITLE
Feature Request: AllowCropping should work on Android devices as well

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#215]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: Any Version
Device Tested On: Any Device

### Expected Behavior
Allow Cropping should allow the image to crop in preview screen. It is working in iOS devices. 
My Request is to work for android devices as well.

### Actual Behavior
Cropping is not working on android devices.

## Feature Request:
AllowCropping should work on Android devices as well in image preview screen

**Comment by jamesmontemagno** [comment]
Not possible as we launch the default Android camera and out of control from the library.
