### ISSUE TITLE
Wrong style in Android on background when open default gallery 

### ISSUE THREAD

**Issue by michaelluconi** [jamesmontemagno/MediaPlugin#217]
## Bug 
Version Number of Xamarin Forms: 2.3.4.224
Version Number of Plugin: v2.6.3.8-beta
Device Tested On: samsung galaxy tab s2
Simulator Tested On: - 

### Expected Behavior
When I open default gallery with PickPhotoAsync I expect the gallery opened over my app OR in a different activity but with same style

### Actual Behavior
My app has white background and orange primary and primarydark colours, PickPhotoAsync open a page with black background and blue primary and darkprimary colours

### Steps to reproduce the Behavior
Simply call PickPhotoAsync on a tablet, it doesn't happened in phones, it seems that sometimes the gallery doesn't open fullscreen

### Notes
following a couple of screenshots, how the app looks like:
![bar_correct](https://cloud.githubusercontent.com/assets/26960376/24747647/5af742aa-1abd-11e7-9651-3c3a85aeb68a.jpg)
how the background behind the gallery looks like
![bar_behind_gallery](https://cloud.githubusercontent.com/assets/26960376/24747648/5af80a64-1abd-11e7-9cb7-4ad22447aed8.jpg)

**Comment by jamesmontemagno** [comment]
The library launches the default gallery, we have no control over the color scheme.
