### ISSUE TITLE
After about 20 pictures the app crashes

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/MediaPlugin#218]
Hi James,
I have a problem when I take more than 20 pics in an app. After the latest update of `Xamarin.Forms` ver. 2.3.4.224 and `MediaPlugin` ver. 2.6.2, my app crashes after taking about 20 photos.

I think the error is generated is

> CGAffineTransformInvert: singular matrix.

## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: iPad Pro, iPad Air

### Expected Behavior
I can take as much photos as I want

### Actual Behavior
After taking about 20 photos the app crashes

### Steps to reproduce the Behavior

```
public async Task ExecuteCameraCommand()
{
    IsBusy = true;

    await _semaphoreSlim.WaitAsync();
    try
    {
        if (!initialized)
            await InitMedia();

        // with this command the app crashes
        var file = await CrossMedia.Current.TakePhotoAsync(
                        new Plugin.Media.Abstractions.StoreCameraMediaOptions());

        if (file == null)
            return;

        byte[] imageAsBytes = null;
        using (var memoryStream = new MemoryStream())
        {
            file.GetStream().CopyTo(memoryStream);
            file.Dispose();
            imageAsBytes = memoryStream.ToArray();
        }

        IsLoading = true;

        var resizer = DependencyService.Get<IImageResize>();
        imageAsBytes = resizer.ResizeImage(imageAsBytes);

        var imageSource = ImageSource.FromStream(() => new MemoryStream(imageAsBytes));
        _images.Add(new GalleryImage { Source = imageSource }); // , OrgImage = imageAsBytes

        IsLoading = false;
        IsBusy = false;
    }
    catch (Exception ex)
    {
        // send to Mobile Center
    }
    finally
    {
        ChangeMediaButtonEnableState(enable: true);
        _semaphoreSlim.Release();
    }
}
```

**Comment by jamesmontemagno** [comment]
Are you sure it is with the core logic of the plugin, you are doing a lot of other things in there. Strip it down to it's core without doing any manipulation to the image that is returned or setting any image source.

**Comment by erossini** [comment]
I tried to simplified the code like that:

```
public async Task ExecutePickCommand()
{
	await _semaphoreSlim.WaitAsync();
	try
	{
		ChangeMediaButtonEnableState(enable: false);

		if (!initialized)
			await InitMedia();

		var file = await CrossMedia.Current.PickPhotoAsync();

		if (file == null)
			return;

		_images.Add(new GalleryImage { 
			Source = ImageSource.FromFile(file.Path), FilePath = file.Path });
		}
	catch (Exception ex)
	{
	}
	finally
	{
		ChangeMediaButtonEnableState(enable: true);
		_semaphoreSlim.Release();
	}
}
```

but the problem is there. I took a [quick video](https://youtu.be/jy4C3BEc4x0) to  show you better in the device side what the behaviour is.

**Comment by jamesmontemagno** [comment]
The problem here is that you are still interacting with your app in some way and who knows what it is doing. To boil it down to see if it is the library or a memory leak on your end you need to do a blank app and just do this:

```
var file = await CrossMedia.Current.PickPhotoAsync();

		if (file == null)
			return;

```

Which I just did and loaded 100 different photos up with no issues.

**Comment by jamesmontemagno** [comment]
If you can create a repo that can be shared with minimal code then open a new issue please with a link to a GitHub repo featuring the code.

**Comment by LabEG** [comment]
I have same problem. After 30-40 photos app will be crash.
My code:
`
            NSThread.MainThread.InvokeOnMainThread(async () =>
            {
                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    await this.messageBoxHelper.Alert("Камера не доступна");
                    return;
                }

                StoreCameraMediaOptions cameraOptions = new StoreCameraMediaOptions
                {
                    PhotoSize = PhotoSize.Custom,
                    CustomPhotoSize = this.config.PhotoSize,
                    CompressionQuality = this.config.PhotoQuality,
                    SaveToAlbum = true,
                    AllowCropping = false,
                    DefaultCamera = CameraDevice.Rear
                };

                byte[] Bytes;
                
                using (MediaFile mediaFile = await CrossMedia.Current.TakePhotoAsync(cameraOptions))
                {
                    if (mediaFile == null)
                    {
                        return;
                    }

                    using (Stream pictureStream = mediaFile.GetStream())
                    {
                        using (MemoryStream memoryStream = new MemoryStream())
                        {
                            pictureStream.CopyTo(memoryStream);
                            Bytes = memoryStream.ToArray();
                        }
                    }
                };

                // TempMedia newMedia = new TempMedia()
                // {
                //     Media = Bytes,
                // };
                // 
                // this.ViewModel.MediaArray.Add(newMedia);
                // this.ViewModel.RaisePropertyChanged(() => this.ViewModel.MediaArray);
            });
`
I'm also looking for a solution for native IOS. In native IOS you can also get the same problem. The problem in UIImagePickerController , it leak.
