### ISSUE TITLE
await CrossMedia.Current.PickPhotoAsync() breaks my app with sample code

### ISSUE THREAD

**Issue by erossini** [jamesmontemagno/MediaPlugin#219]
Sorry to bother you again. I can replicate the error for you. I created a simple [project here](https://github.com/erossini/XamarinCameraTest). I recorded a short video for that on [YouTube](https://youtu.be/l1bo6dh5t7s).

If you execute the code and you try to take some pictures, you can see the problem after 20 pictures. The number of pictures depend from the device:

- iPad Air 32
- iPhone 6s 86
- iPad Pro 9" 34

## Bug 

Version Number of Plugin: Plugin.Media 2.6.2
Device Tested On: iPadAir, iPhone 6s, iPad Pro

### Expected Behavior
Take unlimited number of pictures

### Actual Behavior
After taking some pictures, the app crashes and no error is reported in the debugger. You can see my test code https://github.com/erossini/XamarinCameraTest

No output is stored, or processes or allocated in any way. Still, the app crashes and the debug sessions closes without any messages after taking 30 pictures. At this stage I am confident that the issue lies within the plugin for this platform.

I tried to check the code adding `Media.Plugin`, `Media.Plugin.Abstractions`, `Media.Plugin.iOS` and `Media.Plugin.Shared` in my solution but there is an error:

![screen shot 2017-04-08 at 22 56 31](https://cloud.githubusercontent.com/assets/9497415/24832763/dba682ba-1cae-11e7-98a0-31774d958eb7.png)

### Profiler
If I try to use `Xamarin Profiler` is also crashed with this error:

![screen shot 2017-04-09 at 01 20 07](https://cloud.githubusercontent.com/assets/9497415/24833511/e199c4f2-1cc2-11e7-97e3-96a3f1dcb53c.png)

**Comment by jamesmontemagno** [comment]
You need to install the nuget into all projects. Make sure to clean and rebuild

**Comment by erossini** [comment]
Already done. There are three days I'm doing tests on that.

**Comment by erossini** [comment]
If I didn't install the nuget into all project, how can the app work for few photos?

**Comment by jamesmontemagno** [comment]
I'll take a look, your issue was just very confusing as to what the problem what and what you posted here. 

You can look at how the test projects are setup to pull in the source code for yourself and test it out.

**Comment by jamesmontemagno** [comment]
I as and did 50+ photos taken and picked using just the code from the plugin:


```
 int count = 0;
        void UpdateCount()
        {
            count++;
            CountLabel.Text = $"{count} times";
        }

        private async void TapGestureRecognizer_StartCameraTapped(object sender, EventArgs e)
        {
           
            UpdateCount();
			var file = await CrossMedia.Current.PickPhotoAsync();

            if (file == null)
                return;
        }

private async void TapGestureRecognizer_StartCameraTakeTapped(object sender, EventArgs e)
{
           

            UpdateCount();

            var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
            {
            });

    	if (file == null)
    		return;
        }
    }
}

```

and worked flawless on my iPhone 6: https://youtu.be/LNYeMUQC0jc

**Comment by erossini** [comment]
Hi James,
first of all, thank you for your time. 

I changed my [test project](https://github.com/erossini/XamarinCameraTest) with your code. Unfortunately, I have the same issue. With my iPad Air or iPad Pro after about 30 photos (https://youtu.be/od0Qx5YdMo0). 

I'm so sorry to bother you with this issue. I have a lot of people in my company with my apps with the same problem (all with iPad Pro or Air) and they can't work properly. I know with an iPhone it's working fine or it's so difficult to replicate this behaviour.

**Comment by erossini** [comment]
Now I created a new project called `cameratesteasy`. In this project I don't add `Refractored.MvvmHelpers`. Without it I don't have issue with photos!

**Comment by erossini** [comment]
If I use `Refractored.MvvmHelpers` ver 1.0.0 the error doesn't occur.

**Comment by erossini** [comment]
Correction: in iPad Pro after taking 42 photos the app crashes.

**Comment by erossini** [comment]
I tried to remove `Refractored.MvvmHelpers` from my app and still have the same issue after about 45 images. In attach you find the log of the device, my app is called `myInspection.iOS` (namespace `com.portico.myInspection`).

[console ipad pro.txt](https://github.com/jamesmontemagno/MediaPlugin/files/910096/console.ipad.pro.txt)

**Comment by erossini** [comment]
This is the log report from `XCode` for `**camaratest**`

![screen shot 2017-04-10 at 15 21 13](https://cloud.githubusercontent.com/assets/9497415/24866201/5d0d7db0-1e01-11e7-87ca-9102f2b4ec8f.png)

At the end of the log you can see 

> Apr 10 15:18:57 Enricos-iPad mediaserverd(VirtualAudio)[25] <Notice>: 678: Client request to start IO proc ID 0x1003c5f10 on VAD 124.
> Apr 10 15:18:57 Enricos-iPad SpringBoard(UIKit)[51] <Notice>: Received memory warning.
> Apr 10 15:18:57 Enricos-iPad UserEventAgent(ADEventListenerPlugin)[20] <Notice>: low memory session log
> Apr 10 15:18:57 Enricos-iPad mediaserverd(VirtualAudio)[25] <Notice>: 561: Starting IO type 0 on AggregateDevice 278.

I took 52 photos before.

[cameratest log crash.txt](https://github.com/jamesmontemagno/MediaPlugin/files/910347/cameratest.log.crash.txt)

**Comment by erossini** [comment]
Consideration. I created my app last August and from it I've never had this error. Today I copied the August version on my MacBook and I compiled and deployed it on my iPad: now the app has the same issue.

Then I'm thinking something change on Xcode or something like that. With the same project and the same packages now this kind of error occurs, what is it changed? The OS and Xcode.

**Comment by erossini** [comment]
I tried to compile my camera test project with four iMac but same Xcode and the result is the same.

**Comment by erossini** [comment]
I decided to implement a native function for taking photo.

**Interface**

	public interface ICamera
	{
		void TakePicture();
	}

**Implementation**
```
using System;
using cameratest.iOS;
using Foundation;
using UIKit;
using Xamarin.Forms;

[assembly: Xamarin.Forms.Dependency(typeof(Camera_iOS))]
namespace cameratest.iOS
{
	public class Camera_iOS : ICamera
	{
		static UIImagePickerController picker;
		static Action<NSDictionary> _callback;

		static void Init()
		{
			if (picker != null)
				return;

			picker = new UIImagePickerController();
			picker.Delegate = new CameraDelegate();
		}

		class CameraDelegate : UIImagePickerControllerDelegate
		{
			public override void FinishedPickingMedia(UIImagePickerController picker, NSDictionary info)
			{
				var cb = _callback;
				_callback = null;

				picker.DismissModalViewController(true);
				cb(info);
			}
		}

		public static void TakePicture(UIViewController parent, Action<NSDictionary> callback)
		{
			Init();
			picker.SourceType = UIImagePickerControllerSourceType.Camera;
			_callback = callback;
			parent.PresentModalViewController(picker, true);
		}

		public static void SelectPicture(UIViewController parent, Action<NSDictionary> callback)
		{
			Init();
			picker.SourceType = UIImagePickerControllerSourceType.PhotoLibrary;
			_callback = callback;
			parent.PresentModalViewController(picker, true);
		}

		public void TakePicture()
		{
			var rc = UIApplication.SharedApplication.KeyWindow.RootViewController;
			TakePicture(rc, (obj) =>
			{
				var photo = obj.ValueForKey(new NSString("UIImagePickerControllerOriginalImage")) as UIImage;
				var documentsDirectory = Environment.GetFolderPath(Environment.SpecialFolder.Personal);

				// hardcoded filename, overwritten each time
				string jpgFilename = System.IO.Path.Combine(documentsDirectory, "Photo.jpg");
				NSData imgData = photo.AsJPEG();
				NSError err = null;
				if (imgData.Save(jpgFilename, false, out err))
				{
					Console.WriteLine("saved as " + jpgFilename);
				}
				else
				{
					Console.WriteLine("NOT saved as " + jpgFilename + " because" + err.LocalizedDescription);
				}
			});
		}
	}
}
```

With this code after about 30 photos, the app crashes. The only difference is with this code I can receive some alert from `ReceiveMemoryWarning`.

**Comment by jamesmontemagno** [comment]
So in this instance I have to assume that maybe it has something to do with:

```
// hardcoded filename, overwritten each time
				string jpgFilename = System.IO.Path.Combine(documentsDirectory, "Photo.jpg");
				NSData imgData = photo.AsJPEG();
				NSError err = null;
				if (imgData.Save(jpgFilename, false, out err))
```

Are you properly disposing of all the images? Your app size might just keep growing perhaps?

**Comment by erossini** [comment]
I think so https://github.com/erossini/XamarinCameraTest/blob/master/cameratesteasy/cameratesteasy/iOS/Dependencies/Camera_iOS.cs#L74

Exactly, the app size keep growing.

**Comment by jamesmontemagno** [comment]
I'm asking the team to see if they see anything weird.

**Comment by erossini** [comment]
Thanks. This morning I opened a bug on bugzilla https://bugzilla.xamarin.com/show_bug.cgi?id=55010

**Comment by erossini** [comment]
Today I updated `Xamarin.Forms` ver. 2.3.4.231 but the problem is still there.

**Comment by xamarinuser** [comment]
One of the users complained that the camera keeps stopping in "LGE" and the version of the android is 8.0.0

**Comment by AlexLemusDev** [comment]
@erossini lograste resolver este problema??
Hasta esta fecha yo sigo teniendo el mismo error.

**Comment by AlexLemusDev** [comment]
@erossini  did you manage to solve this problem ??
Until this date I still have the same error.

**Comment by jpd21122012** [comment]
@jamesmontemagno Thanks for your time, I have the same trouble with old Ipad devices, could you provide us the solution?

**Comment by yalamandarao** [comment]
@jamesmontemagno Thank so much for your reply. I'm also facing same issue. The problem occurs after taking about 30 0r 40 photos iPad Air (iOS 12.4.1). Xamarin Forms (4.2.0.8). Plugin.Media(4.0.1.5)

iPad mini 3 ( iOS 12.4.3 ) - App getting crash

iPad (6th Generation ) ( iOS 13.23) - No crash 

Could you please provide me the solutions.
