### ISSUE TITLE
You must call Initialize() before calling any properties

### ISSUE THREAD

**Issue by MelbourneDeveloper** [jamesmontemagno/MediaPlugin#220]
## Bug 
This error occurs when I call CrossMedia.Current.IsCameraAvailable.

### Expected Behavior
I don't get an error

### Actual Behavior
I do get an error

### Steps to reproduce the Behavior
Run this code on UWP with the NuGet Package installed:

```
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await App.MainMasterDetailPage.DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                Directory = "Sample",
                Name = "test.jpg"
            });

            if (file == null)
                return;

            await App.MainMasterDetailPage.DisplayAlert("File Location", file.Path, "OK");

            var stream = file.GetStream();
            file.Dispose();
```

I'd be happy to call the Initialize method which is in the class MediaImplementation. But, I don't have access to this class in the NuGet package. 

I've also tried on Android, but I get this compilation error before I can run the app:
Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Media.Abstractions, Version=2.6.2.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

## Feature Request:
The bug to be fixed

**Comment by MelbourneDeveloper** [comment]
I don't get this. I ditched the NuGet package and referenced the DLLs directly. On Android, I get this:

System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

**Comment by MelbourneDeveloper** [comment]
I managed to get this working by deleting all the references in my Android project and directly referencing the binaries that are outputted from the library Media.Plugin.Android. I shouldn't have to do this. I should be able to just directly consume the NuGet package on Android, and NuGet should figure out which platform specific DLLs I need.

**Comment by jamesmontemagno** [comment]
Yes, you can install it directly into just the Android app and it would work just fine, that is how I test it.

Perhaps NuGet messed something up. You must call initialize it is part of the Interface.

**Comment by jamesmontemagno** [comment]
I just tried that and got:
![image](https://cloud.githubusercontent.com/assets/1676321/24917800/22b5f092-1e93-11e7-83e2-0be6eb0c3b49.png)

All referenced correctly. What did NuGet do when you added them?

**Comment by protokovich** [comment]
i have same error:
  at Plugin.Media.CrossMedia.get_Current () [0x0000d] in C:\projects\mediaplugin\src\Media.Plugin\CrossMedia.cs:28 

This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

Plugin.Media
and
Plugin.Media.Abstractions 
exists in Android project References

**Comment by protokovich** [comment]
https://github.com/jamesmontemagno/MediaPlugin/issues/108#issuecomment-311453203
