### ISSUE TITLE
PickPhotoAsync() does not work on Android 5.0.1 Lollipop

### ISSUE THREAD

**Issue by peppe130** [jamesmontemagno/MediaPlugin#222]
## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Samsung Galaxy S4 - Android 5.0.1 Lollipop

Hi,

I'm experiencing two problems:
1) After calling PickPhotoAsync() nothing happens. The code works fine on my other devices.
2) When a photo is picked from Gallery, sometimes, it happens that it gets rotated.

Any solution? Thank you in advance.

**Comment by nbaua** [comment]
It says,

You MUST set your Target version to API 23+ and Compile against API 23+: 
That's why I guess.
