### ISSUE TITLE
iOS no Take/Pick UI Appearing after XamForms 2.3.4 upgrade

### ISSUE THREAD

**Issue by ianjonesau** [jamesmontemagno/MediaPlugin#228]
A bug appears to exist on iOS only, for Xam.Plugin.Media 2.6.2 under XamForms 2.3.4
Calls to "await CrossMedia.Current.TakePhotoAsync(...)" and "await CrossMedia.Current.PickPhotoAsync(null)" no longer show the expected UI for take or pick.
All setup is correct.
Rollback to XamForms 2.3.3.193 working again :)

Version Number of Plugin: 2.6.2
Device Tested On: iPhone 6 (take & pick)
Simulator Tested On: iPhone 7 iOS 10.3 (pick only)

### Expected 
Expected respective take/pick forms to appear on relevant Async calls.

### Actual
Calls just disappear into the await method. 
Subsequent calls give the expected error indicating only one (1) active call at a time is allowed.

### Steps to reproduce the Behavior
Upgrade a working iOS app to XamForms 2.3.4
Downgrade to XamForms 2.3.3.x and all happy again.

**Comment by valdetero** [comment]
We are having the exact same issue. This is the line that is throwing the error: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.iOS/MediaImplementation.cs#L240.

**Comment by aer127** [comment]
Same here

**Comment by aer127** [comment]
Found a workaround. See here: https://github.com/xamarin/Xamarin.Forms/pull/848
I am displaying an action sheet before calling the media plugin. Adding a 100ms in between prevents the issue for now. Looks like a fix will be in place with the next version of Xamarin.Forms

`
string choice = await this.CoreMethods.DisplayActionSheet(null, "Cancel", null, TAKE_TEXT, CHOOSE_TEXT);
            await Task.Delay(100);
            MediaFile mediaFile = null;
PickMediaOptions options = new PickMediaOptions();
                options.CompressionQuality = COMPRESSION_QUALITY;
                options.PhotoSize = PhotoSize.Medium;
                mediaFile = await CrossMedia.Current.PickPhotoAsync(options);
`

**Comment by jamesmontemagno** [comment]
Fixed here: https://github.com/jamesmontemagno/MediaPlugin/issues/186

**Comment by ianjonesau** [comment]
Thanks for the 'fix' - much appreciated!
