### ISSUE TITLE
Call crossmedia.current on iOS

### ISSUE THREAD

**Issue by saarthchitale** [jamesmontemagno/MediaPlugin#231]
### Expected Behavior
On iOS, I expect the Camera to work as it is working on Android for me currently. I have added all the required permissions for the iOS project. 

### Actual Behavior
When I tap on click photo button, I get the message "No Camera" that was set in the code. I am unable to find any documentation for how to call crossmedia.current on iOS (On android, I just add await crossmedia.current.Initialize(); in MainActivity.cs). It would be great if I could get some help on how to call the crossmedia plugin in iOS (I am a complete novice in the coding world).

**Comment by jamesmontemagno** [comment]
Did you try to prompt for permissions? Calling take photo will do it first, you may be running into a permission miss match. Try calling the take photo without the checks.

**Comment by saarthchitale** [comment]
I did try doing that. It is still not working for me. I am correct in calling the plugin from AppDelegate.cs using crossmedia.current.Initialize(); inside - public override bool FinishedLaunching(UIApplication app, NSDictionary options)?

**Comment by jamesmontemagno** [comment]
Are you running on device or simulator?

**Comment by saarthchitale** [comment]
Hey James! I tried running on both emulator and device. I am getting to the same message on both.

**Comment by saarthchitale** [comment]
Alright! So I re-installed the plugin and its working now on my device. However, I am getting a NullReference exception on the first line of the following snippet:
image.Source = ImageSource.FromStream(() =>
					{
						var stream = file.GetStream();
						file.Dispose();
						return stream;
					});
and when clicked "ok" the app just crashes after the following line:
await DisplayAlert("File Location", file.Path, "OK");

**Comment by saarthchitale** [comment]
Finally I succeeded in getting it to work! Thanks for the wonderful plugin James! 
One quick question, is there a way to pick multiple images/videos or click multiple images using the same button as yet?

**Comment by davispolito** [comment]
How did you fix it?
