### ISSUE TITLE
Invoke dialog that allows access to camera or gallery 

### ISSUE THREAD

**Issue by atkinsonline** [jamesmontemagno/MediaPlugin#232]
## Feature Request:
Hi, first thank you for a great plugin.  This is not really a feature request, it's a request to know if this is possible with the plugin. All android at present. When I tap a button for a photo at a website running in the Chrome browser, a dialog appears at the bottom of the screen allowing access to the camera or documents (file system). The dialog contains the text "Choose an action" Is it possible to use that feature in the plugin?  With the plugin, I can call a function to take a photo or call another function to load a photo.  I wondered if there is one function I could call that displays the Choose an action dialog. My task is to wrap a website into an app and that website has just one camera button and I'd like it to optionally allow access to photo or gallery. I expect I could create my own dialog in Xamarin but I wondered if this was already an option.  Thank you.

**Comment by jamesmontemagno** [comment]
You can control this just by using standard android dialog pop ups to prompt the user, or if using xamarin.forms the actionsheet that is built in.

**Comment by atkinsonline** [comment]
Thank you James.  As you can tell, I'm quite new to Xamarin!
Yes, it's Forms so I'll investigate actionsheets.
