### ISSUE TITLE
Black screen while loading large video

### ISSUE THREAD

**Issue by sprezat** [jamesmontemagno/MediaPlugin#234]
Hi,
I have a long black screen after picking a large video (100mo). The black screen is a about 1 minute long and after I can use my video.
I use file =await this.mediaPicker.PickVideoAsync();
Is there a solution to have a loader instead of black screen?

Thanks 

## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Android 5.0
Simulator Tested On:

**Comment by jamesmontemagno** [comment]
Pretty sure this is a duplicate as it just taking time to copy the file.

**Comment by prashantvc** [comment]
Because we have not received a reply to our request for more information, I am marking this issue as closed. If you are still encountering this issue on the latest version of the plugin, please don’t hesitate to reopen the ticket with the requested information. Thanks!
