### ISSUE TITLE
Is there any chance to get gps location data for a picked image?

### ISSUE THREAD

**Issue by js-ka** [jamesmontemagno/MediaPlugin#236]
## Bug 

Version Number of Plugin: 2.6.2
Device Tested On: Honor 5X, iPhone 6, iPhone 7+
Simulator Tested On:

### Expected Behavior

receive image with gps data from CrossMedia.Current.PickPhotoAsync

### Actual Behavior

image with no gps location data received

### Steps to reproduce the Behavior

just call CrossMedia.Current.PickPhotoAsync and check the exif data of the picked image

**Comment by jamesmontemagno** [comment]
Yes, it is in an incoming metadata pull request.
