### ISSUE TITLE
[iOS] Freeze app when open camera for record video

### ISSUE THREAD

**Issue by futurify-tanhoang** [jamesmontemagno/MediaPlugin#237]
## Bug 
It works fine with Xamarin.Forms (1.3.3.193) but not work on 1.3.4.231

Version Number of Plugin: 2.6.2
Device Tested On: iPhone 7

### Expected Behavior

When using
"await CrossMedia.Current.TakeVideoAsync"
I expect to open the camera and record video

### Actual Behavior

Freezing app after I choose record video option or select from gallery

### Steps to reproduce the Behavior

`var action = await DisplayActionSheet(AppResources.Change_Video, AppResources.Cancel, null, AppResources.Take_a_video, AppResources.Choose_from_gallery);

                await CrossMedia.Current.Initialize();
                MediaFile file = null;
                if (action == AppResources.Take_a_video)
                {
                    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakeVideoSupported)
                    {
                        await DisplayAlert(AppResources.Error, AppResources.No_camera_available, AppResources.OK);
                        return;
                    }

					try
					{
                        file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
	                    {
	                        Directory = "jobhop",
	                        Name = "video.mp4", 
	                        Quality = VideoQuality.Medium,
                            //SaveToAlbum = true
	                    });
					}
					catch (Exception ex)
					{
						string message = ex.Message;
					}
                }
                else if (action == AppResources.Choose_from_gallery)
                {
                    if (!CrossMedia.Current.IsTakeVideoSupported)
                    {
                        await DisplayAlert(AppResources.Error, AppResources.Pick_video_is_not_supported, AppResources.OK);
                        return;
                    }

                    file = await CrossMedia.Current.PickVideoAsync();
                }`

**Comment by jamesmontemagno** [comment]
See https://github.com/jamesmontemagno/MediaPlugin/issues/228
