### ISSUE TITLE
stream camera to a control within the app

### ISSUE THREAD

**Issue by sowsan** [jamesmontemagno/MediaPlugin#238]
Hello Team - 

Looking for the similar feature mentioned here for android using xamarin forms.

https://developer.xamarin.com/recipes/android/other_ux/textureview/display_a_stream_from_the_camera/

Is it possible to use the MediaPlugin and implement the concept of taking photo staying within the app instead of switching to the camera app ?

Regards,
Sowmyan

**Comment by jamesmontemagno** [comment]
It is not part of this plugin. It takes and picks photos and videos. You would need to implement on each platform.
