### ISSUE TITLE
[feature request] Media Picker Option to set image size

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#24]
_From @rd09 on February 4, 2016 16:59_

It would be very helpful to have the option in StoreCameraMediaOtions of setting an image size.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#210_

**Comment by jamesmontemagno** [comment]
Can you try out https://www.nuget.org/packages/Xam.Plugin.Media/2.4.0-beta2

I added a "PhotoSize" for small, medium, and large for scaling 25, 50, and 75% for iOS and Android;

**Comment by jamesmontemagno** [comment]
_From @rd09 on March 1, 2016 16:14_

Thanks, that is awesome!

**Comment by jamesmontemagno** [comment]
_From @LogicMate on March 10, 2016 21:12_

Thanks for the PhotoSize, it works like a charm.   We are really looking for a solution to specify custom sizes so we can keep pictures in a specific ratio.  for example we want to capture 640x480, 800x600 etc. and keep the aspect ration to 4:3.  Would this be possible? 

thanks

**Comment by jamesmontemagno** [comment]
_From @LogicMate on March 10, 2016 21:19_

Also would we be able to force the orientation of the camera?

**Comment by jamesmontemagno** [comment]
I have thought about doing a custom ratio and may change it in the future, but wanted to get some feedback. Just need to add a lot of logic. A scale was easier to implement that would cover most use cases.

**Comment by jamesmontemagno** [comment]
_From @marcojak on March 22, 2016 18:20_

When I set PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small, the image become a square. If I don't set the PhotoSize property, the image is fine.
This happens on iOS. I tested it on an iPad mini but a colleague with an iphone 5 told me the same.

**Comment by jamesmontemagno** [comment]
_From @AvBrenk on June 16, 2016 11:34_

@jamesmontemagno First of all, I have been using your Media plugin for a while now. It works great, thanks for making this available for us.

Is there any news on this feature? I have been following it, and I see there is a beta version available. Is that version "safe" to use in a production app? I would like to use the plugin for another app, but I need the resizing and auto-rotate functionality for that one. Any idea on when this will be in a production version?

Thanks in advance.

**Comment by jamesmontemagno** [comment]
Check out: 2.5.1-beta35

**Comment by IeuanWalker** [comment]
Hi, I was just wondering if you are pursuing the option to be able to capture images at a specific ratio, for example, we want to capture 640x480, 800x600 etc. and keep the aspect ratio to 4:3. as @LogicMate mentions above

**Comment by xamarinuser** [comment]
Hi are you planning on enhancing it further to take multiple pictures or pick multiple pictures from gallery ?
