### ISSUE TITLE
[Feature Request/Breaking Change] Optimize Image Resizing

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#241]
Currently there are too many options and more coming with manual sizing option coming in. Need to figure out how to handle this best.

**Comment by NikolaiTsepalov** [comment]
Hi James,
I'd like to have a MaxSize resizing option.
Resize the image only if it larger than MaxSize on any side. 
Thanks!

**Comment by jamesmontemagno** [comment]
I think I am fine with the implementation for now.
