### ISSUE TITLE
App goes to background

### ISSUE THREAD

**Issue by kostadinSpiridonov** [jamesmontemagno/MediaPlugin#244]
## Bug 
App stops (goes to backgroud) without exception or crash message.

Version Number of Plugin: 2.6.0
Device Tested On: Android 6.0.1

When I try to open more tha 10 images consequently with PickPhotoAsync, the Xamarin Android app goes to background without exception or message. 
This is the code snippet.

         ` var imageFile = await CrossMedia.Current.PickPhotoAsync();
            if (imageFile == null)
            {
                return;
            }  

            var pinImageDTO = new PinImageDTO()
            {
                MediaFile = imageFile,
                ImageSource = ImageSource.FromStream(() =>
                {
                    var stream = imageFile.GetStream();
                    return stream;
                }),
                Id = Guid.NewGuid().ToString()
            };`

**Comment by jamesmontemagno** [comment]
Update to 2.6.2 or latest beta for enhance memory management

**Comment by charlielaunchlabs** [comment]
@jamesmontemagno I've already updated it to the latest beta and still not working. Do you have any other solutions?

**Comment by chanti-github** [comment]
Hi @jamesmontemagno  i am facing same problem can you please suggest ...
