### ISSUE TITLE
Taken pictures deleted after app update

### ISSUE THREAD

**Issue by ThatGoodVince** [jamesmontemagno/MediaPlugin#245]
## Bug (?)

Version Number of Plugin: 2.6.2
Device Tested On: Various (iOS)

### Expected Behavior
Taking pictures, storing their path in the model will reference them for further use.

### Actual Behavior
Taking pictures, storing their path in the model references them for further use... until you update the app!
When i update the App via direct deployment OR apples testflight, everything stays as it should.
- Database survives
- Database-content survives
- Settings stay the same
But the taken pictures seem to get deleted

What am i missing?

**Comment by ThatGoodVince** [comment]
Yeah, actually that bug was not directly related to the Media Plugin. It could basically be removed, its nonsense ;)

Von meinem iPhone gesendet

**Comment by jamesmontemagno** [comment]
Thanks :)
