### ISSUE TITLE
[Android] Permission conflict when CAMERA is added to manifest

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#247]
If you manually add the CAMERA permission, which you do NOT need to do at all, then the permission must be requested. This is some weird thing with 23+ targeting.

**Comment by BillyMartin1964** [comment]
I changed my targeting back to lollipop and the camera works fine, so I'm thinking the issue must be what you're mentioning here. What exactly do I need to do? I'm using your permissions plugin.

takePhoto.Clicked += async (sender, args) =>
            {
                await Permissions.CheckPermissions(Permission.Camera);
                await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    DisplayAlert("No Camera", ":( No camera available.", "OK");
                    return;
                }

                var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Fish",
                    Name = $"{DateTime.UtcNow}.jpg",
                    DefaultCamera = CameraDevice.Front,
                    //SaveToAlbum = true,
                    //CompressionQuality = 75,
                    //CustomPhotoSize = 50,
                    //PhotoSize = PhotoSize.MaxWidthHeight,
                    //MaxWidthHeight = 2000
                });

                if (file == null)
                    return;

                DisplayAlert("File Location", file.Path, "OK");

                image.Source = ImageSource.FromStream(() =>
                {
                    var stream = file.GetStream();
                    file.Dispose();
                    return stream;
                });
            };
