### ISSUE TITLE
[iOS] 2.7.0.41-beta crashes during TakePhotoAsync

### ISSUE THREAD

**Issue by alanspires** [jamesmontemagno/MediaPlugin#250]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.7.0.41-beta
Device Tested On: iPhone 7 Plus
Simulator Tested On: (NA cant use camera on simulator)

### Expected Behavior
After taking a photo and hitting "Use Photo" app doesn't crash.

### Actual Behavior
App locks, then crashes. No insight reports, no error logs, try-catch doesn't capture it.

### Steps to reproduce the Behavior
Take a pic, hit use photo. Crash.

## Feature Request:
Please fill in what you would like

This code works perfect in 2.6.3.30-beta, but not in latest.

        public static Task<string> TakePictureAsync(int compressionQuality)
        {
            var tcs = new TaskCompletionSource<string>();

            Device.BeginInvokeOnMainThread(async () =>
            {
                string path = null;
                try
                {
                    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                        await DialogHelper.DisplayAlertAsync(Strings.OopsVerbiage, "your device does not support choosing photos, please verify your security settings");
                    else
                    {
                        var options = new StoreCameraMediaOptions
                        {
							PhotoSize = PhotoSize.Medium,
                            CompressionQuality = compressionQuality,
                            //MaxWidthHeight = 760
                        };

                        using (var file = await CrossMedia.Current.TakePhotoAsync(options))
                            path = file?.Path;
                    }
                }
                catch (Exception ex)
                {
        #if DEBUG
                    throw ex;
        #else
                    Xamarin.Insights.Report(ex);
        #endif
                }

                tcs.SetResult(path);
            });

            return tcs.Task;
        }

**Comment by jamesmontemagno** [comment]
There are a lot of changes in that version, will test out. Might be new metadata support. Thanks for the report.

**Comment by jamesmontemagno** [comment]
So, out of the box I didn't experience a crash, but I did optimize the code
can you checkout the new beta.

**Comment by alanspires** [comment]
Same result.

**Comment by jamesmontemagno** [comment]
Hmmm, i will need a stack trace and more information.

What device, OS level, and IDE/Xamarin.iOS version you are using.

Additionally, I will need the logs from the devices.

**Comment by alanspires** [comment]
I'll clone this repo and track it.

**Comment by jamesmontemagno** [comment]
If you run the test project for iOS that is what I used. And it worked great even before I modified anything.

**Comment by alanspires** [comment]
Its a NRE at this line...

https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.iOS/MediaPickerDelegate.cs#L302


We need a null check on options.Location

**Comment by alanspires** [comment]
Odd I would think the sample should have crashed as well considering Location is always null unless set.

**Comment by alanspires** [comment]
Side note... This does crash from the same error using your iOS test project on a device.

**Comment by Bobisback** [comment]
can anyone confirm that the null check on location fixes this issue? I am having the same issue right now.

**Comment by Bobisback** [comment]
I tried to download dev and put it into my project and now I am getting missing refreance issues on Plugin.Media namespace.

Will this fix it? I need a solution asap. When I downgrade I run into an issue where select photo just does not work at all. Any ideas?

**Comment by alanspires** [comment]
You need to add Media.Plugin, Media.Plugin.Abstractions to your PCL project.
Media.Plugin.Abstractions, Media.Plugin.iOS to your iOS project.

Also make sure you bring in all these projects to build. Media.Plugin.Shared, Media.Plugin.Abstractions,Media.Plugin.iOS, Media.Plugin

If your still having issues regarding missing ref start a new issue.

**Comment by Bobisback** [comment]
Ya I am more interested if adding the null ref check actually fixes the issue.

**Comment by alanspires** [comment]
Wait for James to patch it. Then test it out. I know this fixes that exception but regarding your original issue I couldnt tell you.

**Comment by jamesmontemagno** [comment]
Oh kinda funny. I actually forgot to check in this code lol i had added that null check. Weird maybe yours went down a different code path somehow.

**Comment by jamesmontemagno** [comment]
new release going up. :)

**Comment by alanspires** [comment]
fixed! thanks!

**Comment by jamesmontemagno** [comment]
Yay!

**Comment by Bobisback** [comment]
Awesome it is working now all around. Thanks!!
