### ISSUE TITLE
Instantiate MediaFile from Byte[]

### ISSUE THREAD

**Issue by pparmentier** [jamesmontemagno/MediaPlugin#252]
Version Number of Plugin: 2.6.3.14-beta

Hi, 
I'm trying to get a MediaFile from a Byte array.
Is there any way I can instantiate it from this ?
Thank you for the great plugin !

## Feature Request:

If it does not exist, a constructor from Byte[].

**Comment by jamesmontemagno** [comment]
You are not supposed to create a media file, the plugin does that and returns a stream and file location. From that you can do whatever you would like.
