### ISSUE TITLE
Feature Request: When setting the Video DesiredLength, it should show a count down rather than count up 

### ISSUE THREAD

**Issue by mattleibow** [jamesmontemagno/MediaPlugin#254]
I am forwarding a feature request from [bugzilla #13123](https://bugzilla.xamarin.com/show_bug.cgi?id=13123)

When the `DesiredLength` is set, it would be nice if the calling code had also the option to specify whether to show a count _down_ rather than a count _up_. This would make it easier for users to know when the video recording is about to stop.

    picker.TakeVideoAsync (new StoreVideoOptions {
        Directory = "Xamovies",
        DefaultCamera = CameraDevice.Front,
        DesiredLength = TimeSpan.FromMinutes (5)
    })

**Comment by jamesmontemagno** [comment]
Is this supported by the default camera controls?

**Comment by mattleibow** [comment]
I just noticed that on my Android Nexus 5 device, the counter IS counting down. but this is not the same for iOS. I am thinking that Android supports this, and is cool, but iOS does not just yet?

**Comment by jamesmontemagno** [comment]
Each device is a bit different, and we just set the property on the control :)
