### ISSUE TITLE
[iOS] RotateImage has no effect, Portrait images always rotate to landscape

### ISSUE THREAD

**Issue by alanspires** [jamesmontemagno/MediaPlugin#255]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.7.0.46-beta
Device Tested On: iPhone 7 Plus
Simulator Tested On: (NA Camera not available in simulator)

### Expected Behavior
When taking a portrait photo with RotateImage true the image should display as such

### Actual Behavior
RotateImage value is ignored (true or false) and image is oriented in landscape.

### Steps to reproduce the Behavior
Take a portrait pic and display it in a Image control.

**Comment by alanspires** [comment]
public static Task<string> TakePictureAsync(int compressionQuality)
        {
            var tcs = new TaskCompletionSource<string>();

            Device.BeginInvokeOnMainThread(async () =>
            {
                string path = null;
                try
                {
                    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                        await DialogHelper.DisplayAlertAsync(Strings.OopsVerbiage, "your device does not support choosing photos");
                    else
                    {
                        var options = new StoreCameraMediaOptions
                        {
							PhotoSize = PhotoSize.MaxWidthHeight,
                            CompressionQuality = compressionQuality,
                            MaxWidthHeight = 760
                        };

                        using (var file = await CrossMedia.Current.TakePhotoAsync(options))
                            path = file?.Path;
                    }
                }
                catch (Exception ex)
                {
                    throw ex;
                }

                tcs.TrySetResult(path);
            });

            return tcs.Task;
        }

**Comment by jamesmontemagno** [comment]
I believe there is a PR already in for this

**Comment by RollRandom** [comment]
Looks like that could be it. From the description though he mentions equals false. I see the behavior regardless. Didn't peek at the code though, hope it fixes it! Thanks!

**Comment by jamesmontemagno** [comment]
You can also test out those fixes by trying the appveyor nuget feed: CI NuGet Feed: https://ci.appveyor.com/nuget/mediaplugin

**Comment by alanspires** [comment]
Ill check that out in the morning for sure.

**Comment by bpater-tp** [comment]
That's exactly the problem I was trying to solve. It appears when one is using PhotoSize != Full. It works for me when I use code from PR #251 . @alanspires please check if it works for you as well. And yes - problem exists regardless RotateImage value. Sorry, somehow I've missed it in the first PR.

**Comment by alanspires** [comment]
This does seem to fix the orientation issue. 

I am noticing now though that whether using PhotoSize.Large or a custom MaxWidthHeight the resolution is pretty bad (not using any compression). Before these features were introduced image quality was much better.

**Comment by alanspires** [comment]
Actually looking at it side by side they look about the same.

**Comment by jamesmontemagno** [comment]
My assumption here is that the new logic in the PR may be causing the image quality issues. I assume that the current Stable is just fine?

**Comment by jamesmontemagno** [comment]
So, the issue here seems to be the saving of the metadata to the file. Investigating a bit more here. Assumption is the wrong metadata is being added in.

**Comment by jamesmontemagno** [comment]
I think I have a fix without the PR actually, we just need to make sure we set the orientation in the newly saved metadata :)

**Comment by alanspires** [comment]
Latest App Veyor (49) doesnt fix this.

**Comment by jamesmontemagno** [comment]
I am still looking. It all has to do with metadata. I have to re-write all of the logic for resizing the image.

**Comment by jamesmontemagno** [comment]
Should really be fixed now from my testing :)

**Comment by alanspires** [comment]
The orientation is correct but the scaling seems wrong. 

Scenario. 
MaxWidthHeight = 1080
Portrait picture, iPhone 7+

After taking a picture the width is 1080 and Height is 810, that seems to be reversed and the image is stretching horizontally.

**Comment by alanspires** [comment]
Should I open a new issue for that?

**Comment by jamesmontemagno** [comment]
hmmmmmm, interesting. I just scale it.
I will test it out, but open a new issue.

**Comment by jamesmontemagno** [comment]
Also, i can't repro that. This is actually correct as the orientation is "right" by default on the phone when it takes a photo. So it will be rotated correctly.

I just tested in the test app and it is perfect output.
