### ISSUE TITLE
Pull and save content from my server to shared location on device or push to device somehow ?

### ISSUE THREAD

**Issue by stephenhauck** [jamesmontemagno/MediaPlugin#257]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
I would like to be able to push training videos to my devices in the field and some MDM systems can do this but I want to just do it weekly or something so the videos can be expired and updated and such from a central location.

Any advice on how to implement this using this control or should I look elsewhere ?

I see that I can save video to the shared location but is there a better way to sync data to the shared location then pulling over TCP/IP then saving it with this control ?

**Comment by alanspires** [comment]
You should look at https://www.nuget.org/packages/Plugin.MediaManager/

**Comment by jamesmontemagno** [comment]
Closing as this does not relate to this plugin.
