### ISSUE TITLE
[iOS] MaxWidthHeight Portrait Scaling incorrect

### ISSUE THREAD

**Issue by alanspires** [jamesmontemagno/MediaPlugin#258]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.7.0.50-beta
Device Tested On: iPhone 7+
Simulator Tested On: NA

### Expected Behavior
When setting MaxWidthHeight to 1080 and taking a portrait picture the image should scale with height > width.

### Actual Behavior
Image scales width to 1080 opposed to adjusting height which stretches image.

### Steps to reproduce the Behavior
Snap a pic, check the dimensions. I've commented the code I use to get the dimensions just in case there is an error in that.

**Comment by alanspires** [comment]
public Size GetImageSize(string path)
        {
            if (File.Exists(path))
            {
                // use ImageIO so we can get the dimensions without loading the image into RAM
                var imageFileUrl = new NSUrl(path, false);
                var imageSource = CGImageSource.FromUrl(imageFileUrl);
                if (imageSource != null)
                {
                    var imageProperties = imageSource.CopyProperties(new CGImageOptions(), 0);
                    if (imageProperties != null)
                    {
                        NSObject widthRaw;
                        NSObject heightRaw;

                        imageProperties.TryGetValue(ImageIO.CGImageProperties.PixelWidth, out widthRaw);
                        imageProperties.TryGetValue(ImageIO.CGImageProperties.PixelHeight, out heightRaw);

                        if (widthRaw != null && heightRaw != null)
                        {
                            var widthNum = widthRaw as NSNumber;
                            var heightNum = heightRaw as NSNumber;

                            return new Size(widthNum.DoubleValue, heightNum.DoubleValue);
                        }
                    }
                }
            }

            return Size.Zero;
    }

**Comment by jamesmontemagno** [comment]
This is actually correct as the orientation is "right" by default on the phone when it takes a photo. So it will be rotated correctly.

I just tested in the test app and it is perfect output.

You need to take into consideration the orientation of the actual picture.

**Comment by alanspires** [comment]
Ahhh.

**Comment by jamesmontemagno** [comment]
Yeah, in no way to do rotate the photo at all, (we only do that in Android when things are all messed up). So you just need that property to be read in which is in the top metadata and also in the exif dictionary.
