### ISSUE TITLE
Not compatible with latest xamarin forms release on ios..?

### ISSUE THREAD

**Issue by KyleTraynor** [jamesmontemagno/MediaPlugin#259]
After upgrading to the latest version of Xamarin.Forms, this plugin does not appear to work for iOS? Just nothing comes up for take photo or pick photo. Downgrading to previous xamarin forms version and it seems to work again.

**Comment by jamesmontemagno** [comment]
Not sure what you mean. Which version of the plugin, which version of forms, what does it do? Any code snippet? You gotta help me out here :)

**Comment by silenceway** [comment]
Hello.
I upgrade my project to work with Visual Studio 2015 in Mac, Xamarin Forms to 2.3.4.247 and Media Plugin 2.6.2.
When I click on button to pick photo does not work and if i click it again shows an error: "Only one operation can be active at at time"
Thanks.

**Comment by jamesmontemagno** [comment]
This would mean that you already have an active operation. You would need a code snippet or some example to show me.

**Comment by KyleTraynor** [comment]
The issue silenceway is having is the same one i have. It is only upgrading to Xamarin Forms 2.3.4.247 that it no longer works. First click does nothing - second click has the active operation error. Before this xamarin forms update, the first click would bring up the camera (or the photo picker)

On my button click, I simply run
SelectedImage = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
            {
                Directory = "Sample",
                Name = "test.jpg",
                CompressionQuality = 90,
                PhotoSize = PhotoSize.Medium
            });

**Comment by silenceway** [comment]
I'm using same code that your MediaSample. (It was working with 2.3.3 version but Visual Studio needs 2.3.4 version)
Thanks.

**Comment by RollRandom** [comment]
Try wrapping it in begininvokeonmainthread

**Comment by jamesmontemagno** [comment]
It may also be fixed specifically in: 2.6.3.14-beta

sound familiar to something from the past. I can't repro it at all here.

**Comment by silenceway** [comment]
Tested with Device.BeginInvokeOnMainThread and works as expected.
Thanks.

**Comment by RollRandom** [comment]
Cheers

**Comment by RollRandom** [comment]
Side note though James can you just main thread it so we don't have to do that?

**Comment by jamesmontemagno** [comment]
No, when you interact with the UI or anything like that you would have to be on the main thread.

**Comment by KyleTraynor** [comment]
Just confirming that updating to Xam.Plugin.Media 2.7.0.50-beta does fix this problem.
