### ISSUE TITLE
Metdata(EXIF,TIFF,GPS etc..) stripped off from the saved temp image

### ISSUE THREAD

**Issue by jackie-raichandani** [jamesmontemagno/MediaPlugin#262]
Version Number of Plugin: 2.6.2.
Device Tested On: Iphone 6 IOS 10.0
Simulator Tested On: IOS Simulator
Version of VS: VS 2015
Version of Xamarin: 4.5

When we try to save the Image after picking it from the Camera Roll using PickPhotoAsync(), the photo is created in the temp directory of the device but the Metadata is stripped off during that save, which should not happen, it should maintain all of the metadata of the original image.

To fix it I replaced the following line of code in the MediaPickerDelegate.cs for the Media.Plugin.IOS project:

Method Name : **SaveImageWithMetadata**

I replaced : 

```
destination.AddImageAndMetadata(cgImageFromJpeg, cgImageMetadata, destinationOptions);
	            var success = destination.Close();
	            if (success)
	            {
	                imageWithExif.Save(path, true);
	            }
                return success;`

with :              
 ```
                  var imgSrc = ImageIO.CGImageSource.FromData(image.AsJPEG());
                 var outImageData = new NSMutableData();
                using (var d = ImageIO.CGImageDestination.Create(outImageData, imgSrc.TypeIdentifier, 1, new ImageIO.CGImageDestinationOptions()))
                {
                    d.AddImage(imgSrc, Convert.ToInt32(imgSrc.ImageCount - 1), meta);
                    d.Close();
                }
                NSError writeError;
                var success = outImageData.Save(path, NSDataWritingOptions.Atomic, out writeError);                
                  
                return success;

It did work but I still wanted to know why the previous code the you had was not working.

thanks

**Comment by jamesmontemagno** [comment]
These are in the 2.7.0 beta
