### ISSUE TITLE
[iOS] auto closure of blank Photo Gallery dialog when user selects not to allow access to photos

### ISSUE THREAD

**Issue by tonyhudson** [jamesmontemagno/MediaPlugin#263]
On the iOS platform, when the Plugin.Media.Abstractions.IMedia.PickPhotoAsync() method is called for the first time, the blank Photo Gallery dialog appears with the cancel button followed by  a modal dialog informing the user that the application needs access to photos.  If the user selects not to allow access to photos the blank Photo Gallery dialog is left on the screen and requires the user to press the Cancel button in order to remove it.  This is a nuisance in that it requires the user to make an additional key press.  It would be better if the blank Photo Gallery dialog was closed automatically if the user selects not to allow access to photos.

**Comment by jamesmontemagno** [comment]
It is recommended that you implement permissions yourself such as: https://github.com/jamesmontemagno/MediaPlugin#permission-recommendations

I will look into this though and close it if so.
