### ISSUE TITLE
Plugin.Media.CrossMedia.Current.PickPhotoAsync() does not works in iOS using Xamarin.Forms

### ISSUE THREAD

**Issue by shkar62** [jamesmontemagno/MediaPlugin#265]
I want to allow user to select image  from Photos in iOS, but nothing happens.
` 

                          var action = await DisplayActionSheet("Add Photo", "Cancel", null, "Choose 
                              Existing", "Take Photo");
				if (action == "Choose Existing")
				{
                                         await CrossMedia.Current.Initialize();
					if (!CrossMedia.Current.IsPickPhotoSupported)
					{
						await  DisplayAlert("Photos Not Supported", "Permission not granted 
                                        to photos", "OK");
						return;
					}
					var file =   Plugin.Media.CrossMedia.Current.PickPhotoAsync(new 
                                      Plugin.Media.Abstractions.PickMediaOptions
					{
						PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small
					});
					if (file == null)
						return;
					imageProfile.Source = ImageSource.FromStream(() =>
					{
						var stream = file.Result.GetStream();
						file.Result.Dispose();
						return stream;
					});
}
`

**Comment by msatish89** [comment]
PickPhotoAsync is not working.when i click a button gallery open i choose the picture,but nothing will happen

**Comment by shkar62** [comment]
@msatish89 you need to add delay before calling PickPhotoAsync or TakePhotoAsync for iOS. Use the following code :
`if (Device.RuntimePlatform.Equals("iOS"))
{
        await Task.Delay(100);
}`

**Comment by msatish89** [comment]
> @msatish89 you need to add delay before calling PickPhotoAsync or TakePhotoAsync for iOS. Use the following code :
> `if (Device.RuntimePlatform.Equals("iOS")) { await Task.Delay(100); }`

Andriod itself not working

**Comment by shkar62** [comment]
Which version of Xamarin.Forms and Plugin Media package are you using ? I am using the same package currently and it works

**Comment by msatish89** [comment]
> Which version of Xamarin.Forms and Plugin Media package are you using ? I am using the same package currently and it works

Xamarin.Forms 2.5.0.2 and Xam.Plugin.Media 4.0.1.1

**Comment by altaf-navalur** [comment]
Hi, 
I am trying to pick multiple files, this is my code,

public async void OnClick_Pick(object sender, System.EventArgs e)
        {
            if(!mIsUploading)
            {
                if(!CrossMedia.Current.IsPickPhotoSupported)
                {
                    await DisplayAlert("Photos Not supported", "Permission not granted", "Okay");
                    return;
                }
                else
                {
                    List<MediaFile> files = await CrossMedia.Current.PickPhotosAsync(new Plugin.Media.Abstractions.PickMediaOptions
                    {
                        PhotoSize = PhotoSize.Full
                    });
                    if(files == null || files.Count == 0)
                    {
                        Console.WriteLine("No files selcted");
                        return;
                    }
                    else
                    {
                        Console.WriteLine($"SELECTED FILE : {files.Count}");
                        files.ForEach((MediaFile obj) => Console.WriteLine(obj.Path));
                    }
                }
            }
        }

After I select the files, I dont see any log on how many files are selected. What am I missing here. 
Selecting a single file using **CrossMedia.Current.PickPhotoAsync** works.

Thanks,
  Altaf
