### ISSUE TITLE
[iOS] TakePhotoAsync Pushes Down Tab Bar After Taking Photo (Can't see Tab Item Text)

### ISSUE THREAD

**Issue by aherrick** [jamesmontemagno/MediaPlugin#267]
## Bug Information

Version Number of Plugin: 2.7.0.50-beta
Device Tested On: iPhone 6s iOS 11 Beta 1
Simulator Tested On:
Version of VS: 4.5
Version of Xamarin: 10.10
Versions of other things you are using:

### Steps to reproduce the Behavior

Call TakePhotoAsync and take a photo from a List inside of a Tab Bar. Photo successfully takes but pushes Tab Bar down so Tab Text can't be read.

However, I have found if I rotate the device and rotate back the view gets reset and text is visible.

### Expected Behavior

Tab Bar doesn't get pushed down.

### Actual Behavior

Tab Bar does get pushed down.

### Screenshot

See bottom Tab Bar. Text is gone.

![image-1](https://user-images.githubusercontent.com/586671/26884664-251f567c-4b55-11e7-91a6-8493474a99b2.jpg)

**Comment by jamesmontemagno** [comment]
Do you have a small sample app I can test?

**Comment by prashantvc** [comment]
Because we have not received a reply to our request for more information, I am closing this issue. If you are still encountering this issue on the latest version of the package, please don’t hesitate to reopen the issue with the requested information. Thanks!
