### ISSUE TITLE
how to return a List<Image> after Pick some from Gallery?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [jamesmontemagno/MediaPlugin#269]
Hi!
How to return a List<Image> after Pick some from Gallery?
Thank you!

**Comment by jamesmontemagno** [comment]
Not sure what you are asking, please fill out a full report.

**Comment by nguyenthanhliemfc** [comment]
I mean picker 2 or 3 image from Gallery in 1 time and show it in a ListView
