### ISSUE TITLE
[Feature Request] Option to return Picked Media's original Album Path

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#27]
_From @Jazzeroki on December 18, 2015 7:6_

Just tested so far with Android but the Path extension is returning a path inside of a temp directory.  If I use AlbumPath when taking a photo that is working great.  My trouble currently is when I pick a photo that photo path isn't usable to pass to another application like say an image cropper or exif reader.  Album path parameter be changed to also work when picking a photo not just saving one.  Might also be good to do with video I just haven't needed that yet.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#164_

**Comment by jamesmontemagno** [comment]
Ah, I see, yeah let me see what I can do as we copy a version locally that can be modified as you probably shouldn't actually touch the original.

What would need to happen is on the selection a copy needs to be created and also I need to update the "AlbumPath" for the original.

**Comment by jamesmontemagno** [comment]
_From @Jazzeroki on January 22, 2016 16:30_

Let me add this issue relates back to 156.  I didn't say anything about iOS because I hadn't tested it yet at the time.  Not having a value in Album Path for iOS was preventing me from getting some needed Exiff info.  I've attached a file I worked with another developer on to get the album path in there for iOS.  
[MediaPickerDelegate.cs.txt](https://github.com/jamesmontemagno/Xamarin.Plugins/files/101108/MediaPickerDelegate.cs.txt)

**Comment by CrimsonKyle** [comment]
@jamesmontemagno We are working on a project and need our app to store the photos after PickPhotoAsync to Application/Documents/(non temp directory)/ if possible are there any available work arounds or samples to allow us to store the image in a  similar fashion as TaskPhotoAsync stores it.  I noticed you made some commits but have not released an update. We are having our images aggressively garbage collected within the temp folder on Android and iOS.  Thank You.

**Comment by jamesmontemagno** [comment]
By default it will move the files into your apps directory so they are always there. 

It now also returns the public location in the beta builds: https://www.nuget.org/packages/Xam.Plugin.Media/2.5.1-beta40

However, if the user deletes them they are gone. So you would want to copy them somewhere you would like to save them.

**Comment by CrimsonKyle** [comment]
Right it does move it into my apps directory but under the path "/temp" correct me if I am not understanding this right but are you are recommending that we then copy that file from the "/temp" directory into a different one if we intend to access the file long term?

**Comment by jamesmontemagno** [comment]
Hmmmm. I think a feature request here is to be able to set the directory that "PickPhotos" are copied to. Can you create that for me?

**Comment by CrimsonKyle** [comment]
Sure thing man! 👍
