### ISSUE TITLE
Media Plugin crashes with Panoramic, Depth Effect,Live Photos, Bursts etc

### ISSUE THREAD

**Issue by MsXam** [jamesmontemagno/MediaPlugin#273]
## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: iPhone 7 Plus 
Simulator Tested On: iPhone 6 iOS 10.3
Version of VS:  VS 2017 v 15.2 (26430.13)
Version of Xamarin: 4.5.0.486
Versions of other things you are using:

### Steps to reproduce the Behavior

I have downloaded the MediaPlayer sample and deployed 'as is' to an iPhone 7 Plus.

When the plugin is used and it shows a list of photos in these categories :- 

Moments
Camera Roll
Selfies
Live Photos
Panoramas
Depth Effect
Bursts
Screenshots
My Photo Stream

I simply select one of the above which then shows me the photos in that category, selecting the photo crashes the app.

This happens with photos of these types -  Panoramic, Depth Effect, Live Photos, Bursts

### Expected Behavior

Expect the chosen picture to be returned to the app without crashing.

### Actual Behavior

App crashes. Stack trace via HockeyApp is :- 

MediaPickerDelegate+<GetPictureMediaFile>d__25 MoveNext()]
System.NullReferenceException: Object reference not set to an instance of an object
Plugin.Media.MediaPickerDelegate.<GetPictureMediaFile>d__25.MoveNext()<7b2449ddd77f440f8438d8f2ed8ba9bd>:0
Plugin.Media.MediaPickerDelegate.<FinishedPickingMedia>d__9.MoveNext()<7b2449ddd77f440f8438d8f2ed8ba9bd>:0
UIKit.UIKitSynchronizationContext.<Post>c__AnonStorey0.<>m__0()UIKitSynchronizationContext.cs:24
Foundation.NSAsyncActionDispatcher.Apply()NSAction.cs:163
UIKit.UIApplication.UIApplicationMain(int, string[], intptr, intptr)(wrapper managed-to-native)
UIKit.UIApplication.Main(string[] args, IntPtr principal, IntPtr delegate)UIApplication.cs:79
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName)UIApplication.cs:63

### Code snippet

As per the MediaSample on github - issue can be found from the existing sample.

### Screenshotst

No screenshot as app crashes.

**Comment by prashantvc** [comment]
@MsXam Could you share a detailed steps to reproduce and test case? I am not able to reproduce this issue with new version of plugin.

**Comment by jamesmontemagno** [comment]
unable to reproduce on iPhone 7
