### ISSUE TITLE
Photo/Video gallery picker popover position incorrectly on screen in iOS >= 9.

### ISSUE THREAD

**Issue by philmoz** [jamesmontemagno/MediaPlugin#274]
## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: iPad Air 2, iOS 10.3.2
Simulator Tested On: iPad Air, iOS 10.3.1, 9.3, 8.4
Version of VS: Mac 7.0.1 (build 24)
Version of Xamarin: 2.3.4.247

### Steps to reproduce the Behavior
Create app using CrossMedia.Current.PickPhotoAsync or CrossMedia.Current.PickVideoAsync on an iPad where the picker displays as a PopOver instead of fullscreen.
- If app is started in Landscape mode, PopOver is positioned incorrectly on iOS >= 9.
- If device is rotated, PopOver is re-positioned incorrectly on iOS >= 9.

### Expected Behavior
PopOver appears in the center of the display.

### Actual Behavior
PopOver is positioned bottom/left in Landscape orientation, or top/right in Portrait mode.

### Code snippet
The following change to DisplayPopover method in the iOS MediaPickerDelegate.cs file appears to resolve the problem (at line 134).
            ...
            double x, y;
            if (orientation == UIDeviceOrientation.LandscapeLeft || orientation == UIDeviceOrientation.LandscapeRight)
            {
                x = (Math.Max(swidth, sheight) - width) / 2;
                y = (Math.Min(swidth, sheight) - height) / 2;
            }
            else
            {
                x = (Math.Min(swidth, sheight) - width) / 2;
                y = (Math.Max(swidth, sheight) - height) / 2;
            }
            ...

**Comment by jamesmontemagno** [comment]
Is it only on iOS 9+ that is is the issue? have you tested iOS 8? I can wrap it around a version check if needed.

**Comment by philmoz** [comment]
I tested 8, 9 & 10 in the simulator and 10 on an iPad Air 2.
My code change appears to work in all cases I tested.

**Comment by jamesmontemagno** [comment]
cool thanks! will throw that in there, or you can do a PR if you want to be faster on it.
