### ISSUE TITLE
Apply some design

### ISSUE THREAD

**Issue by Emixam23** [jamesmontemagno/MediaPlugin#275]
Hi !

I have a stupid issue but, I can't find how to deal with it..

So, I have the camera that I can launch from `await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions...`, but how to use it as an XAML element?

Because I would like to add some controls onto the camera view.. Also, how can I close the process if the user is pressing one of these controls?

Thank !

**Comment by jamesmontemagno** [comment]
It only launches the default camera application to take/pick a photo. There isn't XAML element required for it at all. You can put it in an Image after that to display in your app.
