### ISSUE TITLE
TakePhotoAsync Crashing after two or three photos.

### ISSUE THREAD

**Issue by FredBesterwitch** [jamesmontemagno/MediaPlugin#276]
## Bug Information
When using the TakePhotoAsync method, the photo works well, but If I use it more than 2-3 times, the App shuts down in IOS 10.3.2 and in Android emulator.

Version Number of Plugin:2.7.0.50
Device Tested On:Iphone 6 PLUS
Simulator Tested On: Genymotion Custom Tablet
Version of VS: 2017
Version of Xamarin:4.4.0.34(3f99c5a)
Versions of other things you are using:

### Steps to reproduce the Behavior
Take Photo, Select to use, click on take photo again select to use on third time it crashes, try catch does not trap the error
### Code snippet
 private async void btn_Take_Photo_Clicked(object sender, EventArgs e)
{
if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
{
await DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
return;
}

        try
        {
            using (var photo = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions()
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
            }))
            {
                if (photo != null)
                {
                    Debug.WriteLine(photo.Path);
                    PhotoImage.Source = null;
                    PhotoImage.Source = ImageSource.FromStream(() => { return photo.GetStream(); });
                }
            }
        }
        catch (Exception ex)
        {

        }

    }

**Comment by jamesmontemagno** [comment]
I don't have this issue nor can I reproduce as I can take 50+ photos without any issues at all. Woul dneed a sample app, stack trace, and need more.

**Comment by FredBesterwitch** [comment]
James, Thanks for your quick response.
i have attached my project, only has one button on the mainpage.

take 2-3 photos after that it crashes

[App5.zip](https://github.com/jamesmontemagno/MediaPlugin/files/1086948/App5.zip)

**Comment by jamesmontemagno** [comment]
Please use 2.6.2 until fixed.

**Comment by jamesmontemagno** [comment]
Actually, this is your code, you are wrapping it in a Dispose.. you can't do that as the photo is already disposed and you are trying to access properties on it.

Change your code to:

```
var photo = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions()
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                });

                
                if (photo != null)
                {
                    Debug.WriteLine(photo.Path);
                    PhotoImage.Source = ImageSource.FromStream(() =>
                    {
                        var stream = photo.GetStream();
                        photo.Dispose();
                        return stream;
                    });
                }
```

**Comment by FredBesterwitch** [comment]
Thanks James, That has fixed it.
