### ISSUE TITLE
Windows 10: MediaOptions property CompressionQuality is not respected

### ISSUE THREAD

**Issue by dstblue** [jamesmontemagno/MediaPlugin#277]
## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: Windows 10 (10.0.14393) mobile and tablet/desktop
Simulator Tested On: None
Version of VS: 2015 Update 3 (14.0.25431.01)
Version of Xamarin: Xamarin Forms 2.3.3.193
Versions of other things you are using:

### Steps to reproduce the Behavior

1) Configure "Photo and Video settings" (StoreCameraMediaOptions or PickMediaOptions) property CompressionQuality.
2) Use either "TakePhotoAsync" or "PickPhotoAsync"

### Expected Behavior

I would expect compression of the photo.

### Actual Behavior

The photo is not compressed; as far as I can see in the code (WindowsStore/MediaImplementation) the property CompressionQuality is never used.

**Comment by jamesmontemagno** [comment]
This is not supported in UWP only iOS & Android
