### ISSUE TITLE
Windows 10: PickMediaOptions property PhotoSize is not respected

### ISSUE THREAD

**Issue by dstblue** [jamesmontemagno/MediaPlugin#278]
## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: Windows 10 (10.0.14393) mobile and tablet/desktop
Simulator Tested On: None
Version of VS: 2015 Update 3 (14.0.25431.01)
Version of Xamarin: Xamarin Forms 2.3.3.193
Versions of other things you are using:

### Steps to reproduce the Behavior

1) Configure PickMediaOptions property PhotoSize to e.g. Small.
2) Use "PickPhotoAsync"

### Expected Behavior

I would expect the picked photo to be resized to about 25% of the original.

### Actual Behavior

The photo is not resized; as far as I can see in the code (WindowsStore/MediaImplementation) the property is never used within the method "PickPhotoAsync".

**Comment by jamesmontemagno** [comment]
This is not supported and the media scales down to different sizes. Will ensure documented
