### ISSUE TITLE
Why is PhotoSize a percentage of original size?

### ISSUE THREAD

**Issue by bruzkovsky** [jamesmontemagno/MediaPlugin#281]
I am curios to know why you chose percentage to resize images based on their original size. As far as I looked into it, there is no platform-specific advantage to it, nor is it needed anywhere, if I am not mistaken. Why not just take some default-values, like UWP does it with its SmallVga, MediumXga, Large3M, ... values (see: [MSDN docs](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.cameracaptureuimaxphotoresolution)).

Something like:

```
public enum PhotoSize
{
    /// <summary>
    /// Maximium of 320 x 240.
     /// </summary>
     Small,
    /// <summary>
    /// Maximum of 1024 x 768.
    /// </summary>
    Medium,
    /// <summary>
    /// Maximum of 1920 x 1080.
    /// </summary>
    Large,
    /// <summary>
    /// Untouched
    /// </summary>
    Full,
    /// <summary>
    /// Custom size between 1-100
    /// Must set the CustomPhotoSize value
    /// Only applies to iOS and Android
    /// Windows will auto configure back to small, medium, large, and full
    /// </summary>
    Custom
}
```

Just wanted to know if you are open for discussion, because I like to keep things as simple as possible. I would be very happy to commit a PR regarding this.

Cheers

**Comment by jamesmontemagno** [comment]
You are able to specify a percentage to make it easy peasy or you can set a max width/height.

Just legacy
