### ISSUE TITLE
Camera-View not visible on iOS when using Prism PageDialogService

### ISSUE THREAD

**Issue by DNF-SaS** [jamesmontemagno/MediaPlugin#284]
I'm not sure if it's really a bug in this plugin, but maybe anybody else has an similar topic.
If the application lets the user decide whether to select an image from the gallery or take a new photo using Prism Form's PageDialogService (via DisplayActionSheetAsync()), the camera-view is not visible on iOS.
Android and UWP is fine.
Using CrossMedia.Current.TakePhotoAsync directly (without DisplayActionSheet() before) works good.
Does anybody else have the same issue?

## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: iOS 10
Simulator Tested On: iOS 10
Version of VS: VS 2015
Version of Xamarin: 10.10.0.37

**Comment by jamesmontemagno** [comment]
Update to 2.7+

**Comment by DNF-SaS** [comment]
It seems that you like "prereleases" pretty much. 👎

**Comment by jamesmontemagno** [comment]
It is hitting stable this week actually. That is how I put out bug fixes.
