### ISSUE TITLE
Take & Pick Photo or Video

### ISSUE THREAD

**Issue by mjrichards91** [jamesmontemagno/MediaPlugin#288]
I have looked through the options and closed issues and I am not seeing any configuration to either take or pick both photo and video using one action. I.e. a pick media option that allows me to pick either a photo or video from the camera roll. Same with take photo/video. Is there a platform limitation on this or am I missing something? I am specifically implementing this on iOS currently.

**Comment by jamesmontemagno** [comment]
It is one or the other unfortunately as this is how the native out of the box components work.
