### ISSUE TITLE
[Feature Request] Abstract Image Metadata & Return in MediaFile

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#29]
_From @jamesmontemagno on December 4, 2015 19:10_

Originally from #76, what is requested is a way to abstract the metadata form the files into a common class that is returned with the file location in the Media File.

Things such as:
- Size
- Dimensions
- Date
- Exposure
- Camera Make
- Camera Model
- Etc..

For discussion on missing metadata please see #156 

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#155_

**Comment by jamesmontemagno** [comment]
_From @lodev09 on December 4, 2015 19:22_

This has been implemented in Xlabs media that stores metadata to a common class ([see my comment](https://github.com/jamesmontemagno/Xamarin.Plugins/issues/82#issuecomment-162055685)). It needs some tweak though since in iOS, when the source is from camera, GPS info is not included (not sure about this) so you have to create your own and include it in the `JpegInfo` property.

It would be awesome if you can implement it to this plugin :)

**Comment by jamesmontemagno** [comment]
_From @Jazzeroki on December 5, 2015 6:6_

personally I would think reading exif data should be in it's own seperate plugin.  There is a plugin out there that supports reading exif data, and can get things like dimensions, exposure, camera and the like.  My problem with it was it would never return gps data.  There's also inconsistencies about being able to get such data.  iOS is really good about having GPS unless it's cast as a UImage.  Android in my experience doesn't like to add gps.  Have tried winphone yet.  I'd like to make this into a plugin but here's some ways I read exif data for GPS in iOS and Android.

public class GeoCoordinatesAndroid : IGeoCoordinates
	{
		public string GetLatitude(string filepath)
		{
			var exif = new ExifInterface(filepath);
			string lat = ExifInterface.TagGpsLatitude;
			string lat_data = exif.GetAttribute(lat);
			return FormatAsCoordinate(lat_data);
		}

		public string GetLongitude(string filepath)
		{
			var exif = new ExifInterface(filepath);
			string lon = ExifInterface.TagGpsLongitude;
			string lon_data = exif.GetAttribute(lon);
			return FormatAsCoordinate(lon_data);
		}
		public string FormatAsCoordinate(string unformattedCoordinate)
		{
			if (string.IsNullOrEmpty(unformattedCoordinate))
				return "";
			else
			{
				char divider = '/';
				char divider2 = ',';
				var strings = unformattedCoordinate.Split(divider);
				var strings1 = strings[1].Split(divider2);
				var strings2 = strings[2].Split(divider2);
				var numSeconds = (Convert.ToDouble(strings1[1]) * 60 + Convert.ToDouble(strings2[1]));
				double seconds = 0;
				try
				{
					seconds = numSeconds / 3600;
					seconds = Math.Round(seconds, 6, MidpointRounding.AwayFromZero);
				}
				catch
				{
					seconds = 0;
				}
				var coordinate = (Convert.ToDouble(strings[0])) + seconds;
				return (coordinate -1).ToString();
            }

		}

for iOS

public GeoCoordinatesiOS()
		{
		}

		public string GetLatitude(string filepath)
		{
			var fetchResult = PHAsset.FetchAssets(new [] { NSUrl.FromString(filepath) }, null);
			if (fetchResult.Count == 1)
			{
				var result = (PHAsset)fetchResult[0];
				if (result.Location != null)
					return result.Location.Coordinate.Latitude.ToString();
			}
			return "0";
		}

		public string GetLongitude(string filepath)
		{
			var fetchResult = PHAsset.FetchAssets(new [] { NSUrl.FromString(filepath) }, null);
			if (fetchResult.Count == 1)
			{
				var result = (PHAsset)fetchResult[0];
				if (result.Location != null)
					return result.Location.Coordinate.Longitude.ToString();
			}
			return "0";
		}

**Comment by jamesmontemagno** [comment]
_From @Axel3232 on December 9, 2015 15:57_

See my PR : https://github.com/XLabs/Xamarin-Forms-Labs/pull/953

Get all Exif Tags on iOS and Android

**Comment by jamesmontemagno** [comment]
Based on some of this feedback, i wonder if it would be better if this was it's own plugin to be honest, why put it in this plugin and add more complexity to it? There should be a simple Exif plugin to handle this.

Then technically this plugin could rely on that plugin to return the meta data back if needed.

**Comment by jamesmontemagno** [comment]
_From @Axel3232 on December 10, 2015 15:28_

Yes it could, but the plugin has it is was when I did the PR did not fullfill the need since it did not retreive all the ExifTags, and introduce coupling : 

>The main problem regarding coupling is that the MediaInfo class has a JpegInfo prop wich is defined  >inside ExifLib and wrap some metadata but not all...so we are stuck with this external implementation...
>For me, that is bad coupling.
>
>That's why I decided to include the ExifLib implementation in the XLab code this way ExifBinary reader >only expose a generic method to get any Exif tags using an Enum Key.
>
>And it is the responsability to the platform project to wrap metadata in more "friendly shortcut object" >that implement the IJpegInfo interface

**Comment by jamesmontemagno** [comment]
_From @Jazzeroki on December 18, 2015 6:53_

I've been thinking about writing an exif plugin especially since I'm already using the code above in a project.  James thanks for the AlbumPath extension when taking photo's.  Can you extend that to also work when picking photos?

**Comment by jamesmontemagno** [comment]
_From @brandon21486 on April 13, 2016 12:54_

> Based on some of this feedback, i wonder if it would be better if this was it's own plugin to be honest, why put it in this plugin and add more complexity to it? There should be a simple Exif plugin to handle this.

> Then technically this plugin could rely on that plugin to return the meta data back if needed.

Wouldn't you have to change the way you are handling the image anyway when choosing a gallery image? The way it is now the metadata gets stripped off when you copy it over to the App library. I used your code as a base and was able to grab the whole image with the metadata using the ALAssetLibrary and copying it to the path instead of the UIImage.

`                var imageURL = info[UIImagePickerController.ReferenceUrl];
                asset = SynchronousGetAsset(imageURL.ToString());

                long size = asset.DefaultRepresentation.Size;
                byte[] imgData = new byte[size];
                NSError nsError;

                IntPtr buffer = Marshal.AllocHGlobal(imgData.Length);
                asset.DefaultRepresentation.GetBytes(buffer, 0, (uint)size, out nsError);
                Marshal.Copy(buffer, imgData, 0, imgData.Length);
                NSData nsData = NSData.FromArray(imgData);
                using (FileStream fs = File.OpenWrite(path))
                using (Stream s = new NSDataStream(nsData))
                {
                    s.CopyTo(fs);
                    fs.Flush();
                }`
 I am still trying to figure out how to grab the location and add it to an image from the camera because for some reason it doesn't add it to the photo even when saving to the Gallery.

**Comment by jamesmontemagno** [comment]
_From @AlmaJensen on April 13, 2016 22:0_

I've started an exiff reader plugin.  I could use some help getting the other platforms added and some testing.  [https://github.com/AlmaJensen/XamPlugin-Exiff-Reader](url)

**Comment by LostBalloon1** [comment]
FYI @jamesmontemagno There is a pull request #62 which adds the metadata, including the GPS to the final file (it was being lost in the process before)

I know I'm late to the party, but I think extracting metadata should be it's own plugin, simply because it will allow anyone to read the metadata of images at anytime they want in their project and not just when capturing/importing. I can see use cases for it. (ex: a picture that has been downloaded by the app). That said, I still think that the metadata should remain in the picture's binary after an import/capture using this plugin.

If you are implementing an exif reader, note that GPS data is sometimes only found in it's own dictionary. I would honestly prefer to see an "Image metadata extractor" plugin than just an exiff one. (tiff, exif, gps, etc.)

**Comment by adrian-cy** [comment]
FYI @jamesmontemagno There is a pull request #62 which adds the metadata, including the GPS to the final file (it was being lost in the process before)

I know I'm late to the party, but I think extracting metadata should be it's own plugin, simply because it will allow anyone to read the metadata of images at anytime they want in their project and not just when capturing/importing. I can see use cases for it. (ex: a picture that has been downloaded by the app). That said, I still think that the metadata should remain in the picture's binary after an import/capture using this plugin.

If you are implementing an exif reader, note that GPS data is sometimes only found in it's own dictionary. I would honestly prefer to see an "Image metadata extractor" plugin than just an exiff one. (tiff, exif, gps, etc.)

**Comment by Troto** [comment]
@jamesmontemagno Just wondering if anything is happening with either the pull request or this being added separately. I've discovered today that I'll need location coordinates from the exif data.

**Comment by jamesmontemagno** [comment]
I have not yet decided on metadata at this point and the best way to handle it.

**Comment by Troto** [comment]
@jamesmontemagno OK thanks for the reply. I've spent the day trying out different exif reading options that I could find and nothing worked for location perhaps because of the newer android versions? So if you want to be a hero making something that works for pictures taken on the camera app in new android versions would be amazing.

**Comment by kyluke** [comment]
@jamesmontemagno great library man, thanks for all the hard work you've put into this. I'm currently also exploring the exif data issue right now. Has there been any progress on this yet?

**Comment by jamesmontemagno** [comment]
I am not currently working on this to be honest. It is on the back burner for now.

**Comment by ShahriatHossain** [comment]
@jamesmontemagno is it possible to add some text or meta data on image while taking photo from camera and add those meta data with image ?

**Comment by jamesmontemagno** [comment]
No new features.
