### ISSUE TITLE
PickPhotoAsync in iOS throws Exception when trying to pick some pictures (for example screenshots)

### ISSUE THREAD

**Issue by davspan** [jamesmontemagno/MediaPlugin#290]
## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: iPhone 6
Simulator Tested On: -
Version of VS: 2017 (15.0.0+ 26288.9)
Version of Xamarin: 4.3.0.784
Versions of other things you are using: Xamarin.iOS 10.4.0.123

### Steps to reproduce the Behavior

1) Take a screenshot on the iPhone by pressing Home + Standby buttons

2) Call the method PickPhotoAsync:

`var mediaFile = await CrossMedia.Current.PickPhotoAsync();`

3) Select the screenshot picture on the gallery

### Expected Behavior
Get the picture file
### Actual Behavior
Exception thrown: System.Exception: Invalid parameters to context
[https://gist.github.com/davspan/d4a7592416f5118e9573566c1db4d8ee](url)

It works properly with other pictures (taken from the camera)

### Code snippet
`var mediaFile = await CrossMedia.Current.PickPhotoAsync();`

**Comment by jamesmontemagno** [comment]
This looks to be in your code: at MY_APP_NAMESPACE.PictureUtils.ResizePictureiOS

**Comment by davspan** [comment]
Hi,

I replaced my namespaces by editing the stack trace before posting it. The information about how I named my namespaces / classes was not relevant in this case. This has nothing to do with the bug. 

Has anyone tried to reproduce the issue? It occurs only by using the PickPhotoAsync method. It works properly with camera Folder but not with screenshot Pictures. 

Thanks,

David

**Comment by jamesmontemagno** [comment]
What I was mentioning here is that the crash is in your code of resizing looking at the stack trace.

**Comment by davspan** [comment]
Oh, sorry, I didn't understand. Thank you so much! I'll check it :D

David

**Comment by jamesmontemagno** [comment]
That is at least what it looks like to me from that crash that I can determine

**Comment by davspan** [comment]
Again my apologies. It occurs when I try to create a CGBitmapContext of 337 x 600. With 450 x 600 there is no problem. I'll try to figure out why. 

Thank you so much for your help. 

David

**Comment by jamesmontemagno** [comment]
You probably want.something like my first method in here. https://github.com/jamesmontemagno/MediaPlugin/blob/3-0-standard/src/Media.Plugin.iOS/UIImageExtensions.cs

**Comment by davspan** [comment]
Yes! I have tried it a couple of minutes ago and it works perfectly. 

Now is everything solved. Top support.

Thanks a lot and best regards. 

David
