### ISSUE TITLE
Original photo is overwrited instead copy to temp folder.

### ISSUE THREAD

**Issue by Atomico001** [jamesmontemagno/MediaPlugin#292]
## Bug Information

Version Number of Plugin: 2.6.2.0
Device Tested On: Nexus 5 with Nougat 
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
Install app called PICTURES from play store
Pick a foto from this gallery

### Expected Behavior
The photo is copied in temp folder and resized/used
### Actual Behavior
The original photo is overwrited (resized it permanently)
### Code snippet
`file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
                            {
                                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Large,
                                CompressionQuality = 92
                            });`

**Comment by jamesmontemagno** [comment]
Unable to reproduce this at all. Stepping through the code on my Nougat device it clearly grabs the photo, copies, resizes it. My original picture I took remained 2448x3264 the entire time.

**Comment by Atomico001** [comment]
Tnx for answer, you used this gallery app? https://play.google.com/store/apps/details?id=com.diune.pictures&hl=it

**Comment by jamesmontemagno** [comment]
I use the stock galleries. I can not support random galleries if they act different.
