### ISSUE TITLE
[Android] Bug OnAppearing

### ISSUE THREAD

**Issue by emilyotov** [jamesmontemagno/MediaPlugin#294]
## Bug Information

Version Number of Plugin: 3.0.0.66-alpha
Device Tested On: Samsung Galaxy S8, Samsung Galaxy S6
Simulator Tested On:
Version of VS:  2017 Update 2
Version of Xamarin: Xamarin Forms 2.3.4.247
Versions of other things you are using:

### Steps to reproduce the Behavior
Make Form1 and Navigate to Form2. On Form2 set default code to take image. 
On Form1 set this code:

protected override void OnAppearing()
 {
            base.OnAppearing();
            string s = "test";
}

Set debug point to "string s = "test";". After take photo on Form2, OnAppearing in Form1 is automatically executed before navigate back. When navigate back, OnAppearing is not executed on previous form (Form1).

**Comment by jamesmontemagno** [comment]
This is most likely a Xamarin.Forms bug and not a bug with this library at all.
