### ISSUE TITLE
[iOS] ActionSheet or AlertController with blank line when pushing out from bottom screen .

### ISSUE THREAD

**Issue by 7934345** [jamesmontemagno/MediaPlugin#295]
## Bug Information

Version Number of Plugin: v3.0.1
Device Tested On: iOS 10.1.1
Simulator Tested On: N/A
Version of VS: vs2017
Version of Xamarin: (Xamarin.Forms) 2.3.4.247
Versions of other things you are using:

Look the [screenshot](https://s3.postimg.org/xcphya64j/IMG_2010.png) for detail.

### Screenshotst
![Detail](https://s3.postimg.org/xcphya64j/IMG_2010.png)

**Comment by jamesmontemagno** [comment]
Not sure what you code looks like... I assume that is the title.... The plugin doesn't have anything built in at all here that pops it up, so that would be in your code somewhere.
