### ISSUE TITLE
Dependancy causing issue in Managed-Java Type mapping

### ISSUE THREAD

**Issue by thedjnova** [jamesmontemagno/MediaPlugin#296]
## Bug Information

Version Number of Plugin: 3.0.1
Version of VS: 2017 (2) Version 15.2(26430.14)
Version of Xamarin: 2
Versions of other things you are using:

### Steps to reproduce the Behavior
Install Xamarin Forms to projects, install Media Plugin 3.0.1

### Expected Behavior
Should build
### Actual Behavior
Doesn't build

### Code snippet
https://gist.github.com/thedjnova/59d003865ee67ff6cc51d992c4fff561

**Comment by thedjnova** [comment]
Further investigation show this to be an issue with Plugin.Permissions, this requires closing

**Comment by jamesmontemagno** [comment]
You probably need to make sure you compile against 7.0 Android and make sure ALL of your nugets for android support are updated to 25.3.1 and clean/rebuild.

**Comment by thedjnova** [comment]
Hi James,

Yea it was the fact we arent targeting 7 yet, when i updated any package that depends on Permissions it pulls im newer support libs. Permissions was only one needing newer support things so maybe something to look at? (would mean Media v3 use on non 7 targeting projects).

 Reverted everything to versions which use permissions v1 and all is well again.

Thanks,

Graham

Sent from my iPhone

On 5 Jul 2017, at 17:31, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:


You probably need to make sure you compile against 7.0 Android and make sure ALL of your nugets for android support are updated to 25.3.1 and clean/rebuild.

**Comment by jamesmontemagno** [comment]
Yes, you would want to use the latest permissions plugins though. 

I recommend reading: http://motzcod.es/post/162402194007/plugins-for-xamarin-go-dotnet-standard

I have a guide on updating your support libs.

**Comment by thedjnova** [comment]
Thanks, Ill check it out.

Targeting 7 is in our roadmap but we target devices built specially for client and didnt want to pollute builds with libraries that werent needed yet, but this could give me some ammunition to push for targeting 7 now 🤗

Sent from my iPhone

On 5 Jul 2017, at 17:44, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, you would want to use the latest permissions plugins though.

I recommend reading: http://motzcod.es/post/162402194007/plugins-for-xamarin-go-dotnet-standard

I have a guide on updating your support libs.

**Comment by jamesmontemagno** [comment]
You just need to Compile against 7, you can still target older versions of it. :)
