### ISSUE TITLE
[ANDROID] MaxWidthHeight in portrait rotates to landscape

### ISSUE THREAD

**Issue by ClausElmann** [jamesmontemagno/MediaPlugin#297]
using PhotoSize=PhotoSize.Medium works as expected.

Using PhotoSize = PhotoSize.MaxWidthHeight, MaxWidthHeight = 2048, Rotates the image, regardless of using 
RotateImage = false,

**Comment by jamesmontemagno** [comment]
Please fill out a full bug report and submit again.

**Comment by ClausElmann** [comment]
Hi James

If I download your sample app - run it in VS Android emulator - images are rotated, is that intended?

![sampleapp1](https://user-images.githubusercontent.com/13468666/28008875-884fe14e-6559-11e7-9235-59bf645db7d8.png)
![sampleapp2](https://user-images.githubusercontent.com/13468666/28008876-8855b90c-6559-11e7-8f6e-b5ca7bc2ff4d.png)
