### ISSUE TITLE
Feature: Pick/Take Video and Photo at same time

### ISSUE THREAD

**Issue by fasihi-zhuoxiu** [jamesmontemagno/MediaPlugin#298]
Hi James,

thank you very much for your great work! We like it very much and really reduce many repeative Jobs. 
I wonder if it is possible to pick Video and Photo at same time. 
As long as i know if the Mime type is set as "image/* video/*" it is OK in android OS.
I have no Idea how they are in iOS and other platform.
But at least just for Android will be a great help. ( A simple Galary menu as 2 separate "Pick video" "Pick Image" menu is already reduce some Redundanz)
Further if the library can give a chance to Take Video and Video with one action(function) will be perfect!

Best regards!

**Comment by prashantvc** [comment]
@fasihi-zhuoxiu 

> Further if the library can give a chance to Take Video and Video with one action(function) will be perfect!

Could you elaborate this feature request? How it should work?
What are the use cases where you want to access Video and Photo at the same time?

**Comment by fasihi-zhuoxiu** [comment]
@prashantvc 
Hi, i have only idea about this in Android Platform:
`Intent intent = new Intent(Intent.ACTION_PICK, Media.EXTERNAL_CONTENT_URI);
    intent.setType("video/*,image/*");`
With this intent it give user a chance to pick image and video together(if there are app support this feature).

In this way we could reduce 1 button in UI.

**Comment by jamesmontemagno** [comment]
Will not implement as the default controls don't work this way.
