### ISSUE TITLE
iOS devices can't recognize if there are no camera permission 

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#3]
_From @Brosten on June 15, 2016 9:52_

Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [] Bug
- [x] Feature Request

Which plugin does this impact:
- [] Battery
- [] Connectivity
- [] Contacts
- [] DeviceInfo
- [] ExternalMaps
- [] Geolocator
- [x] Media
- [] Permissions
- [] Settings
- [] Text To Speech
- [] Vibrate
- Other:

## Bug

Version Number of Plugin: 2.3
Device Tested On: ipad air 2
Simulator Tested On: 

## Feature Request:
There should be a property telling whatever the app has permission to use the camera or not. For the moment I have to implement this in my own iOS code. Should be nice if it were included in the CrossMedia

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#332_

**Comment by jamesmontemagno** [comment]
Have you tried to use the Permissions plugin?

**Comment by jamesmontemagno** [comment]
_From @Brosten on June 16, 2016 6:9_

Ahh, ok. No I havn’t.

I’ll have a look at it. Thank you.

 

And, by the way, thanks for the great Xamarin Evolve event!

 

// Andreas

 

Från: James Montemagno [mailto:notifications@github.com] 
Skickat: den 15 juni 2016 22:46
Till: jamesmontemagno/Xamarin.Plugins <Xamarin.Plugins@noreply.github.com>
Kopia: Brosten <andreas@brosten.com>; Author <author@noreply.github.com>
Ämne: Re: [jamesmontemagno/Xamarin.Plugins] iOS devices can't recognize if there are no camera permission (#332)

 

Have you tried to use the Permissions plugin?

**Comment by Brosten** [comment]
Dear! 

Look a  those great things  I've just found, they are  just amazing, you'll love'em! Here, check it out  <http://four.jimsautoelectric.net/e4toei>

Best Wishes, andreas

**Comment by Brosten** [comment]
Hello, 

I've  just  found some new methods to  solve the problem you're facing, read more here <http://main.visqst.net/e4jlrbux>


Be well, andreas

**Comment by Brosten** [comment]
Hey, 

I thought this information  regarding my  favourite stuff may be usefull for you too, just take a look here <http://ngel.allamericandeadbeats.com/e4xus/584>

Yours sincerely, andreas
