### ISSUE TITLE
[Android] TakePhotoAsync returns null with MobileIron

### ISSUE THREAD

**Issue by strombringer** [jamesmontemagno/MediaPlugin#300]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Samsung Galaxy S3 (Android 4.4.4), Nexus 5 (Android 7.1.2)
Simulator Tested On: n/a
Version of VS: 15.2 (26430.16)
Version of Xamarin: 25.3.1
Versions of other things you are using:
* MvvmCross 4.4.0
* MobileIron 7.8.0 Gen2

### Steps to reproduce the Behavior
* Create APK in Release mode and wrap it with MobileIron wrapper
* Call IMedia.TakePhotoAsync(new StoreCameraMediaOptions())
* Camera App opens
* Take picture in opened Camera App and confirm

### Expected Behavior
* TakePhotoAsync returns the MediaFile with the taken photo

### Actual Behavior
* TakePhotoAsync returns null

### Code snippet
```
// Option 1 returns null
//var opt = new StoreCameraMediaOptions
//{
//	Directory = "temp",
//	Name = "temp_photo"
//};
//var photo = await _media.TakePhotoAsync(opt);

// Option 2 also returns null
var photo = await _media.TakePhotoAsync(new StoreCameraMediaOptions());

if (photo == null)
{
	Mvx.Trace("Couldn't take photo! Result is null"); // this is visible in the logfile
	return null;
}
```
### Comment
The Expected Behavior is observed when I use the APK without wrapping it with the MobileIron wrapper. With the wrapper the Actual Behavior is observed.
Using the `PickMediaAsync` method works fine in both instances.

I don't know what the reason for the different behaviors is. Both PickMediaAsync and TakePhotoAsync use 
`private Task<MediaFile> TakeMediaAsync(string type, string action, StoreMediaOptions options)` 
internally and the only way I see to return null at that point is if the event was cancelled.

Do you have any idea what could be the cause of this?

**Comment by jamesmontemagno** [comment]
You may have to try to debug the code. Perhaps they don't allow app to app communication. I don't work with MobileIron at all so I have no insight here.

**Comment by strombringer** [comment]
Debugging is unfortunately not possible (at least I don't know how). The APK has to be wrapped with the MobileIron wrapper before the functionality can be used and then it can't be debugged any more.

By adding lots of log output to the relevant MediaPlugin classes I at least tracked the problem down to the OnActivityResult method in MediaPickerActivity, or rather the camera app's call after taking the picture. OnActivityResult receives Result.Canceled, even after confirming the taken photo.

The reason for that seems to be that the camera app can't access the provided file path for writing. But even without the MediaPlugin, and just vanilla Android calls in Xamarin (based on https://developer.android.com/training/camera/photobasics.html), Result.Canceled is returned. I think it's a general problem.

I will keep digging.

**Comment by jamesmontemagno** [comment]
Assumption here is that Mobile Iron doesn't allow any app to app sharing of files. In this case it is out of my hands and is the reason you are wrapping it in MI.

**Comment by strombringer** [comment]
I found out what the problem is: the FileProvider doesn't grant the permission to write the photo.

The FileProvider documentation (https://developer.android.com/reference/android/support/v4/content/FileProvider.html#Permissions)
mentions that the GrantReadUriPermission and/or GrantWriteUriPermission flags should be set to grant the permission when getUriForFile() is used.

I'm not sure why it works in regular apps and not when it's wrapped for MobileIron but I added the following lines to the MediaImplementation.CreateMediaIntent method and with this change it works :-)

`
pickerIntent.AddFlags(ActivityFlags.GrantReadUriPermission);
pickerIntent.AddFlags(ActivityFlags.GrantWriteUriPermission);
`

https://github.com/jamesmontemagno/MediaPlugin/blob/4b747cdf545719da3a264c9415d061ce1f4eac9b/src/Media.Plugin.Android/MediaImplementation.cs#L399-L400

I assume it should be differentiated between Read and Write permission based on the Pick or Take media but I haven't handled this case yet.

I will try to prepare a pull request in the next few days but because of several weddings and a holiday I'm not sure how long it will take me. It will also be my first pull request, which may factor in the delay ;-).

**Comment by jamesmontemagno** [comment]
It does that here: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaPickerActivity.cs#L236

**Comment by jamesmontemagno** [comment]
will loook a bit into it though

**Comment by jamesmontemagno** [comment]
try: 3.0.2-beta82

**Comment by strombringer** [comment]
3.0.2-beta82 works! 👍👍
Thank you for the quick fix.
