### ISSUE TITLE
Cannot pick photo having location info

### ISSUE THREAD

**Issue by varadha-raj** [jamesmontemagno/MediaPlugin#302]
**Bug Information**

Version Number of Plugin:3.0.1
Device Tested On: IPad with iOS 10.1
Simulator Tested On:
Version of VS: 
Version of Xamarin: 6.1.5(build 0)
Versions of other things you are using:
Version of Xamarin forms: 2.3.4.247

**Steps to reproduce the Behavior**
Selecting some photo(which are having location info) from photo library, App getting crash. Error hitting on Main.cs of iOS project.
Project created in PCL.
 **Expected Behavior**
When I Click Photo library option from display action sheet to choose a photo I expect the photo library to open to choose my photo. On choosing photo, selected photo to be displayed in the app.
**Actual Behavior**
On Selecting some photo(which are having location info) from photo library, App getting crash. Error hitting on Main.cs of iOS project. I also can not catch the exception in my try catch.

**Comment by jamesmontemagno** [comment]
I can't really determine what you bug is here or what is going on. you will need to upload a sample or some source code

**Comment by prupleCode** [comment]
Maybe you should add the plugin for you iOS andr android project,, it's not only add forms

**Comment by prashantvc** [comment]
@varadha-raj 
>  App getting crash. Error hitting on Main.cs of iOS project. 
I believe this due to missing Privacy Text in your info.plist file, you find more information on this post 
https://blog.xamarin.com/new-ios-10-privacy-permission-settings/

Please attach crash log and reopen this issue if you continue to have an issue
