### ISSUE TITLE
[Android] TakePhotoAsync() not working as expected when inside Xamarin.Forms.Command

### ISSUE THREAD

**Issue by 12michel34** [jamesmontemagno/MediaPlugin#303]
Hi James,

i've tried to implement the TakePhotoAsync() method inside a Xamarin.Forms.Command. But unfortunately the method does not work on Android. On iOS and UWP everything is ok.
On Android the method gives back a file and i can convert it to my Base64 String (Wich i use to save it to a database), but after the command is finished the generated string is empty. The same happens to my HasImage property (bool) wich i set inside the command.

Maybe i am doing something wrong here.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Samsung Galaxy A300
Simulator Tested On: - 
Version of VS: 2017 v15.2
Version of Xamarin: 2.3.4.247
Versions of other things you are using: Geolocator 4.0.1

### Steps to reproduce the Behavior

1.Call the CrossMedia.Current.TakePhotoAsync() method inside a Xamarin.Forms.Command
2. Convert the generated file into Base64 string
3. Set a property inside the viewmodel wich contains the Command to the generated Base64 string;

### Expected Behavior

A Image should be shown, when i bind this Base64 string property (over a converter) to an Image on a ContentPage on Android, iOS and UWP.

### Actual Behavior

The Image is shown on iOS and UWP but not on Android.
(I saved the generated Base64 and set it manually inside the command without the TakePhotoAsync then everything works as expected.)
(I tried a method call to TakePhotoAsync() on the ContentPage, generated the Base64 string and give it to the property of the viewmodel and everything works as it should.)

### Code snippet

The Xamarin.Forms.Command

` async Task ExecuteTakePhotoCommand()
        {
            if (IsBusy)
                return;

            IsBusy = true;

            try
            {
                await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    MessagingCenter.Send(new MessagingCenterAlert
                    {
                        Title = "Error",
                        Message = "No camera available.",
                        Cancel = "OK"
                    }, "loadError");

                    return;
                }

                var file = await CrossMedia.Current.TakePhotoAsync(
                    new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        PhotoSize = PhotoSize.Custom,
                        CustomPhotoSize = 25,
                        Directory = "sample",
                        Name = "test.jpg"
                    });

                if (file == null)
                    return;

                Byte[] bytes = File.ReadAllBytes(file.Path);

                Item.ImageDataUrl = Convert.ToBase64String(bytes);

                //Item.ImageDataUrl = "/9j/4YavRXhpZgAASUkqAAg......."

                Item.HasImage = true;

                File.Delete(file.Path);
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex);
                MessagingCenter.Send(new MessagingCenterAlert
                {
                    Title = "Error",
                    Message = "Unable to take photo.",
                    Cancel = "OK"
                }, "loadError");
            }
            finally
            {
                IsBusy = false;
            }
        }`

**Comment by jamesmontemagno** [comment]
If the file is created and you can generate the string something else is going on . The plugin is doig what it should. not sure I can help at all.

**Comment by 12michel34** [comment]
No problem. I use the click event on the page and give the result to the viewmodel. It is'nt clean but it works. btw: You do a great job with this plugins.

**Comment by sagarmp02** [comment]
i need to implement auto capture image that is without user interaction ? how to implement it in xamarin.android?
