### ISSUE TITLE
PhotoSize.MaxWidthHeight not working on iOS [PickPhoto]

### ISSUE THREAD

**Issue by lores3000** [jamesmontemagno/MediaPlugin#305]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On:
Simulator Tested On: iOS Simulator iPhone 7 iOS 10.3
Version of VS: 7.0.1
Version of Xamarin: Xamarin.10.8.0.175
Versions of other things you are using:

### Steps to reproduce the Behavior
Pick photo with media Plugin, with PhotoSize set to MaxWidthHeight

### Expected Behavior
photo is maximum 1024x1024 pixels 

### Actual Behavior
photo is larger

### Code snippet
var photo = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions {
						PhotoSize = PhotoSize.MaxWidthHeight,
						MaxWidthHeight = 1024,
						CompressionQuality = 60
					});

### Screenshots
-

### Additional information
in the Medhod PickPhotoAsync of MediaImplementation, a new instance of StoreCameraMediaOptions is created, but the MaxWidthHeight and CustomPhotoSize are not being set so PhotoSize.MaxWidthHeight is ignored in the MediaPickerDelegate. 

Also implementations on iOS and Android differ in that Android has no default values set.

fixed version:

/// <summary>
        /// Picks a photo from the default gallery
        /// </summary>
        /// <returns>Media file or null if canceled</returns>
        public Task<MediaFile> PickPhotoAsync(PickMediaOptions options = null)
        {
            if (!IsPickPhotoSupported)
                throw new NotSupportedException();

            CheckPhotoUsageDescription();

			var cameraOptions = new StoreCameraMediaOptions
			{
				PhotoSize = options?.PhotoSize ?? PhotoSize.Full,
				CompressionQuality = options?.CompressionQuality ?? 100,
				MaxWidthHeight = options?.MaxWidthHeight,
				CustomPhotoSize = options?.CustomPhotoSize ?? 100
            };

            return GetMediaAsync(UIImagePickerControllerSourceType.PhotoLibrary, TypeImage, cameraOptions);
        }

**Comment by mateuszSawa** [comment]
@jamesmontemagno it will be fixed in newest release?

**Comment by jamesmontemagno** [comment]
It is still marked as open
