### ISSUE TITLE
Feature Request : Is it possible to add photo overlay for Android/UWP?

### ISSUE THREAD

**Issue by devapalanisamy** [jamesmontemagno/MediaPlugin#306]
Please add photo overlay for Android and UWP?

**Comment by jamesmontemagno** [comment]
This is not supported by the out of the box controls on those platforms.

**Comment by devapalanisamy** [comment]
Any suggestions how I can achieve this on Android ?  Can I customise MediaPickerActivity to add overlay? Thanks

**Comment by jamesmontemagno** [comment]
This is not supported by the out of the box controls on those platforms and you need to use embedded camera controls into your app.
