### ISSUE TITLE
Plugin doesnt respect Plugin.Media.Abstractions.CameraDevice.Front setting

### ISSUE THREAD

**Issue by HelgeKeck** [jamesmontemagno/MediaPlugin#307]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Samsung Galaxy Tab 10.1
Version of VS: 2015
Version of Xamarin: 2.3.4.247

### Steps to reproduce the Behavior
try to use Front Camera as Default

### Expected Behavior
Plugin should use Front Camera as Default

### Actual Behavior
even if i setup Plugin.Media.Abstractions.CameraDevice.Front, the Plugin uses the Rear Camera as default.

### Code snippet
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                Directory = "Photos",
                Name = photo.FileName,
                DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Front
            });

**Comment by jamesmontemagno** [comment]
It is not guaranteed on Android to work as very little cameras support it.

**Comment by WebDucer** [comment]
It's true, each anroid device have a different behaviour for the front calera intent (dependent on the installed camera app).

@jamesmontemagno In you code use use only the extra `android.intent.extras.CAMERA_FACING` to request the front camera. With the code below (more extras) we could get the front camera for the most of our old and new android devices (including Nexus und Pixel (2) devices) - origin idea from <https://stackoverflow.com/questions/9686203/how-to-launch-front-camera-with-intent>:

```kotlin
private fun takeRearPhoto() {
    val intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
    intent.putExtra("android.intent.extras.LENS_FACING_BACK", 1);
    intent.putExtra("android.intent.extras.CAMERA_FACING", android.hardware.Camera.CameraInfo.CAMERA_FACING_BACK)
    intent.putExtra("android.intent.extra.USE_FRONT_CAMERA", false)

    startActivityForResult(intent, 100)
}

private fun takeFrontPhoto() {
    val intent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
    intent.putExtra("android.intent.extras.LENS_FACING_FRONT", 1);
    intent.putExtra("android.intent.extras.CAMERA_FACING", android.hardware.Camera.CameraInfo.CAMERA_FACING_FRONT)
    intent.putExtra("android.intent.extra.USE_FRONT_CAMERA", true)

    startActivityForResult(intent, 200)
}
```

The explicit setting of extras for the rear camera is needed for some devices, becase their camera open always the last used camera, if nothing defined.

Should I create a pull request for this change / woraround?

**Comment by jamesmontemagno** [comment]
If you can do a PR that would be great @WebDucer 

I do it here: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaPickerActivity.cs#L133
