### ISSUE TITLE
Cannot Find Videos in Gallery when Setting "SaveToAlbum" to True

### ISSUE THREAD

**Issue by WorkingCreed** [jamesmontemagno/MediaPlugin#310]
## Bug Information

Hi! I'm getting an issue in which I can't find videos in an Android phone's gallery when I set "SaveToAlbum" to true. When I look at the Album path in the debugger I see this path: "Content//PACKAGE.fileProvider/my_movies/..."

 Please note that I have only seen this issue on Android. I currently do not have a way to test this for iOs at work. I can test this at home, and update the issue for iOs, if I see it.

I used Xamarin.Forms (pcl) to create a button to make the call to TakeVideoAsync instead of using the native Android project.

I also wanted to not that in the file_paths.xml I have also tried the "Android/data/PACKAGE/files/Movies" for the path for name="my_movies" and I still get "Content://PACKAGE.fileProvider/my_movies/..." issue for the Album Path.

Version Number of Plugin: 3.0.1
Devices Tested On: Samsung Galaxy S7 (API 24),  TCL Alcatel One Touch (API 19)
Simulators Tested On: Nexus 6 (API 25), Nexus 6 (API 24)
Version of VS:  Visual Studio 2015 Professional
Version of Xamarin: 4.6.0.279
Versions of other things you are using:
 * Xamarin.Android: 7.4.0.13
 * Xamarin.Forms: 2.3.4.247
 * Windows: Windows 7 Professional

### Steps to reproduce the Behavior
1. Setup StoreVideoOptions() { SaveToAlbum = true } 
2. Set TakeVideoAsync() to a variable {videoFile}
3. Start Visual Studio in Debug Mode and place a breakpoint after the call to TakeVideoAsync
4. Record a Video on the test device
5. When Visual Studio hits the breakpoint, hover over the variable {videoFile}, to get AlbumPath
6. Observe the strange path
### Expected Behavior

Like TakePhotoAsync's AlbumPath "/storage/emulated/0/Pictures/FOLDER/PICTURE"  I'm expecting to see "/storage/emulated/0/Movies/FOLDER/MOVIE" when creating a new video.

### Actual Behavior

What I see instead is "Content://PACKAGE.fileProvider/my_movies/FOLDER/VIDEO" for the AlbumPath. The video is not stored anywhere publicly on the phone

### Code snippet

private async void RecordOnClicked(object sender, EventArgs e)
    {

      await CrossMedia.Current.Initialize();
      if (CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakeVideoSupported)
      {
        StoreVideoOptions mediaOptions = new StoreVideoOptions()
        {
          Directory = "FOLDER",
          Name = $"{DateTime.Now.ToString("yyyyMMdd_HHmmssffff")}.mp4",
          DefaultCamera = CameraDevice.Front,
          SaveToAlbum = true,
          CompressionQuality = 92
        };

        MediaFile file = await CrossMedia.Current.TakeVideoAsync(mediaOptions);
        string albumPath = file.AlbumPath;
        await DisplayAlert("Album Path", albumPath, "Ok");
      }
    }

### Screenshots

TakeVideoAsync
![image](https://user-images.githubusercontent.com/30443210/28587855-62b8bd90-712d-11e7-89a2-6e546798ffe8.png)

TakePhotoAsync
![image](https://user-images.githubusercontent.com/30443210/28588174-8fba59b0-712e-11e7-8783-062766f07963.png)

**Comment by jamesmontemagno** [comment]
This is correct as it actually isn't supported and Saving to Album is only available on Photos.

**Comment by pengx** [comment]
Thanks James.
I have the same issue with Android 7.0 SavetoAlbum when saving videos. On iOS, it works like breeze, but nothing saved to Gallery/Album. Would appreciate if you can make a workaround for now.

**Comment by pengx** [comment]
I just worked out a workaround, I just save the videos after taking to the Album  manually, no longer an issue now. Thanks.
