### ISSUE TITLE
Location Information is not correctly stored with Photo

### ISSUE THREAD

**Issue by vksuman** [jamesmontemagno/MediaPlugin#311]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6S
Simulator Tested On:
Version of VS: 
Version of Xamarin: 6.3 (build 864) for Mac
Versions of other things you are using:

### Steps to reproduce the Behavior
      Take Photo with Location

### Expected Behavior
       Photo Should be saved with below GPS location (Coordinates)
       Latitude: 52° 1’ 30.11” N
       Longitude: 0° 46’ 5.172” W

### Actual Behavior
     Photo is Stored with below GPS location
      Latitude: 52° 1’ 30.11” N
      Longitude: 0° 0’ -0” E

### Code snippet
Location location = new Location();
location.Latitude = 52.0271723411551;
location.Longitude = -0.764563267810425;
location.Altitude = 84;
location.HorizontalAccuracy = 165;
location.Speed = -1;
location.Direction = -1;
 var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
			{
				PhotoSize = Plugin.Media.Abstractions.PhotoSize.Full,
				SaveToAlbum = true,
				Location = location
			});

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jamesmontemagno/MediaPlugin/issues/309
