### ISSUE TITLE
[Android 4.4.4 + NETStandard] TakePhotoAsync throws exception

### ISSUE THREAD

**Issue by opcodewriter** [jamesmontemagno/MediaPlugin#312]
## Bug Information

Version Number of Plugin: 3.0.1 (latest stable)
Device Tested On: Google Nexus 10
Simulator Tested On: (tested it on real device, see above)
Version of VS: Visual Studio 2017
Version of Xamarin:  Xamarin Android 7.3.1.2
Versions of other things you are using: 

### Steps to reproduce the Behavior
call `TakePhotoAsync`

### Expected Behavior
No app crash

### Actual Behavior
App crashes with following call stack. Before migrating my core project from PCL to .NETStandard 1.6, it worked fine I think.

```
07-26 16:35:19.644 I/MonoDroid(13349): UNHANDLED EXCEPTION:
07-26 16:35:19.684 I/MonoDroid(13349): Java.Lang.NullPointerException: Exception of type 'Java.Lang.NullPointerException' was thrown.
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <bd30a18775d94dc8b6263aecd1ca9077>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <d855bac285f44dda8a0d8510b679b1e2>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at Android.Support.V4.Content.FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file) [0x00078] in <3e239b9681084d42bb949c1e01ef500e>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at Plugin.Media.MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x0023f] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaPickerActivity.cs:162 
07-26 16:35:19.684 I/MonoDroid(13349): --- End of stack trace from previous location where exception was thrown ---
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at Plugin.Media.MediaImplementation+<TakePhotoAsync>d__16.MoveNext () [0x000c7] in C:\projects\mediaplugin\src\Media.Plugin.Android\MediaImplementation.cs:119 
07-26 16:35:19.684 I/MonoDroid(13349): --- End of stack trace from previous location where exception was thrown ---
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <3fd174ff54b146228c505f23cf75ce71>:0 
07-26 16:35:19.684 I/MonoDroid(13349):   at MyApp.Services.Impl.FilePicker+<TakePhotoAsync>d__1.MoveNext () [0x0005b] in XXX
```

**Comment by opcodewriter** [comment]
Oh, I think I know what's going on.
In my Android project I have "Target Android Version" set to Android 7.1 (Level 25). 

I need this because I am using anther plugin of yours, Permissions, which requires it, as you also noted in the readme:
> You MUST set your Target version to API 24+ and Compile against API 24+:

But why does the Media plugin crashes when Target Android Version is set to Android 7.1? 
It seems like it hits an API which is not available on Android 4.4

**Comment by jamesmontemagno** [comment]
Works fine on my sample app that I have included in this repo on my 4.4 device just fine.

Ensure you follow all the setup with xml files on android for file permissions.

**Comment by opcodewriter** [comment]
Thanks.
I'm 100% sure is because of setting "Target Android Version" set to Android 7.1 (Level 25).
If I leave it to the default "Use Compile using SDK version", it doesn't crash.

I don't understand, why would this have to do with setting Android file permissions, since it works when using "Use Compile using SDK version", ?

**Comment by opcodewriter** [comment]
To be clear, right now, I am not even using Permissions plugin. I was actually preparing to use it.
I am only using the Media plugin.

**Comment by opcodewriter** [comment]
To summarize:

- I am only using the Media plugin. Everything works great on all Android versions.
- If I set Android project to have "Target Android Version" to Android 7.1 (Level 25), it crashes on all Android below 7.0

**Comment by jamesmontemagno** [comment]
Did you do all this: https://github.com/jamesmontemagno/mediaplugin#android-n ?

**Comment by opcodewriter** [comment]
Arghhhh! Thanks! Sorry!!
But I have one question:

In step #2, you instruct to have the `file_paths.xml` with the following content:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="my_images" path="Pictures" />
    <external-files-path name="my_movies" path="Movies" />
</paths>
```
and you mention
> YOUR_APP_PACKAGE_NAME must be set to your app package name!

But note there's no `YOUR_APP_PACKAGE_NAME ` in your XML content.

However, going to https://developer.android.com/training/camera/photobasics.html they suggest a different `name` attribute:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path name="my_images" path="Android/data/**com.example.package.name**/files/Pictures" />
</paths>
```
Which one is correct?

**Comment by jamesmontemagno** [comment]
That is their package name...

Whatever your package name is in the android manifest is what you should put in there.

Usually it is.... "com.business.company"

It creates a private area that can be shared between apps for security reasons.
