### ISSUE TITLE
Android - Saved file doesn't have the given size constraints

### ISSUE THREAD

**Issue by opcodewriter** [jamesmontemagno/MediaPlugin#313]
## Bug Information

Version Number of Plugin: Latest stable
Device Tested On: Moto G5
Simulator Tested On: 
Version of VS:  2017
Version of Xamarin: Android Latest stable
Versions of other things you are using:

### Steps to reproduce the Behavior

Call TakePhotoAsync() with the parameters in the picture below. 
I highlighted those to emphasize that `PhotoSize` property is set to `PhotoSize.MaxWidthHeight` so that the `MaxWidthHeight` property is taken into account.

![snip_20170630195532](https://user-images.githubusercontent.com/15019084/28743006-889a0434-7447-11e7-8346-ec77c6338988.jpg)

### Expected Behavior

The image saved in the given directory (`Directory` property) should meet the given size constraint (`MaxWidthHeight = 1024`).

### Actual Behavior

The saved image in the location given by the `Directory` property has size of 2340 x 4160. It does not meet the given constraint (`MaxWidthHeight = 1024`).

**Comment by jamesmontemagno** [comment]
Just tested this and working fine. What directory are you looking in?

**Comment by jamesmontemagno** [comment]
The photo saved to gallery is full sized, which is what I am assuming you are looking at, the file in your private data is compressed.
