### ISSUE TITLE
Nuget Package Issue with AppCompat

### ISSUE THREAD

**Issue by hatimnagarwala** [jamesmontemagno/MediaPlugin#317]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On:
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 2.3.4.247
Versions of other things you are using:

### Steps to reproduce the Behavior
installing nuget package, asks for dependency Appcompat
creates a problem with all the support nugets and doesn't run after that, shows issue with the compatibility of the other packages

**Comment by jamesmontemagno** [comment]
See: http://motzcod.es/post/162402194007/plugins-for-xamarin-go-dotnet-standard

Time to update!

**Comment by hatimnagarwala** [comment]
Thanks @jamesmontemagno You rock!!
