### ISSUE TITLE
Very interesting bug - easy to produce

### ISSUE THREAD

**Issue by Pirate911** [jamesmontemagno/MediaPlugin#318]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On:IPAD Pro 10.5
Simulator Tested On:none 
Version of VS: Visual Studio Community 2017 for Mac
Version of Xamarin:none 
Versions of other things you are using:ios.10.3.3 (i think all ios 10)

### Steps to reproduce the Behavior
Create new cross platform XF , add the xam.plugin.media plugin , add button to trigger the TakeCamera view , add the code you posted on how to use the plugin.
then add this code in AppDelegate.cs 
` public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();

            UISlider.Appearance.MinimumTrackTintColor = UIColor.Red; //bug
            UISlider.Appearance.MaximumTrackTintColor = UIColor.Blue; //bug

			LoadApplication(new App());

            return base.FinishedLaunching(app, options);
        }`
### Expected Behavior
Open the camera
### Actual Behavior
the app freezes
### Code snippet
` <StackLayout Padding="40" HorizontalOptions="CenterAndExpand">
	   
        <Button Text="Open Camera" Clicked="Handle_Clicked" HorizontalOptions="CenterAndExpand" BorderColor="Blue" BorderWidth="1"/>
        
    </StackLayout> `

code behind 
`async void Handle_Clicked(object sender, System.EventArgs e)
        {
            await OpenCam();
        }

        private async Task OpenCam()
        {

            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await DisplayAlert("No Camera", ":( No camera available.", "OK");
                return;
            }
            else
            {
                string fileName = Guid.NewGuid().ToString().Replace("-", "") + ".jpg";

                var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Large,
                    CompressionQuality = 90,
                    Directory = "Attachements",
                    Name = fileName,
                });

                if (file == null)
                    return;
                else
                {
                    //do stuff
                }
            }

        }`
### Screenshotst
the app freezes

**Comment by jamesmontemagno** [comment]
This is an apple bug: https://github.com/jamesmontemagno/MediaPlugin/issues/173
