### ISSUE TITLE
Skip the preview screen upon taking a picture

### ISSUE THREAD

**Issue by jkalanda** [jamesmontemagno/MediaPlugin#32]
Hey there

I'm wondering if there's a way to skip the preview once the a picture is taken.
What i'm trying to accomplish once the picture is taken return to the original screen without prompting the user to "Save" or "Cancel" the picture.

Thanks  much in advance 

## 42

Version Number of Plugin:
Device Tested On: Samsung API and Asus API 21
Simulator Tested On:

## Feature Request:
Please fill in what you would like

**Comment by jamesmontemagno** [comment]
We launch the external camera app and this is the functionality that is provided by it. Nothing that can be done.
