### ISSUE TITLE
iOS video trimming/cropping facility not available in landscape mode

### ISSUE THREAD

**Issue by malcolmcg** [jamesmontemagno/MediaPlugin#320]
The video trimming facility (along the top of the screen) is not available after taking a video on iOS devices in landscape mode.  It is available if taking a video in portrait mode or if the device is rotated to portrait mode after creating the video in landscape mode.
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

## Bug Information

Version Number of Plugin: 3.01
Device Tested On: iPad Pro 10.5
Simulator Tested On: None
Version of VS: 10.3.3
Version of Xamarin: Forms 2.3.4.247
Versions of other things you are using: As pulled down by MediaPlugin

### Steps to reproduce the Behavior
Take a video in portrait mode.  After recording, but before using the video, a bar appears across the top of the video allowing the video to be trimmed.  Do the same in landscape mode and the "trim" bar doesn't appear.  Rotate the device to portrait mode and the "trim" bar appears.

### Expected Behavior
The "trim" bar should appear in both landscape and portrait mode.

### Actual Behavior
See Steps to reproduce above

### Code snippet

var storeVideoOptions = new StoreVideoOptions
{
    DefaultCamera = CameraDevice.Rear,
    DesiredLength = new TimeSpan(0, 0, 10),
    Quality = tempVideoQuality,
};
storeVideoOptions.AllowCropping = true;
var file = await CrossMedia.Current.TakeVideoAsync(storeVideoOptions);

### Screenshots
Landscape (without trim)
![landscape_no_trim_bar](https://user-images.githubusercontent.com/30825291/29062319-1f2f9df4-7c19-11e7-834e-402a51960f18.jpg)

Portrait (with trim)
![portrait_with_trim_bar](https://user-images.githubusercontent.com/30825291/29062318-1f0d1b6c-7c19-11e7-9175-69fba357b51a.jpg)

**Comment by jamesmontemagno** [comment]
Unable to reproduce on iOS 10/11 iPhone6 and iPad Pro.

This is the default controls so out of my control anyways.

**Comment by malcolmcg** [comment]
Thanks for investigating James.  Much appreciated.
