### ISSUE TITLE
Saving to album and uploading to amazon s3

### ISSUE THREAD

**Issue by hashimks** [jamesmontemagno/MediaPlugin#321]
Media plugin is having issues with respect to recording video and saving it to album. The recorded video is in the internal path and if i upload the same to amazon s3 storage, I can only play the audio of the uploaded file and not the video in any browsers.

**Comment by hashimks** [comment]
Hello,

Any help on this? This has become a stopper for my dev.

**Comment by jamesmontemagno** [comment]
It is possible that the codec isn't on the browsers. Have you downloaded it form s3 and attempted to play it?

**Comment by hashimks** [comment]
Hello James,

I tried a normal video taken through my camera app and uploaded same in S3 and I am able to play that. However when I tried to record video using the plugin and uploaded this issue is occurring.

Below is my code for recording using plugin

MediaFile _mediaFile;
await CrossMedia.Current.Initialize();

_mediaFile = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
{
    DesiredLength = TimeSpan.FromMinutes(3),
    Name = "test.mp4",
    SaveToAlbum = true,
});

Below are the samples
https://s3.amazonaws.com/hashimsbucket/hashvideos.mp4  - record through camera app and uploaded to S3, this will play in browsers

https://s3.amazonaws.com/hashimsbucket/1131469035833291410bd.mp4 - this is through media plugin and uploaded to S3. This is only playing audio in chrome and video not working.

If i download and play using windows media player, it will play. But the issue is the video not playing in browser for the one shot through plugin. I checked using android only as I am not able to do it through iPhone simulator.

Thanks,
Hashim

**Comment by jamesmontemagno** [comment]
Running the two videos through media info: https://mediaarea.net/en/MediaInfo/Download
![image](https://user-images.githubusercontent.com/1676321/29243252-4d84b9f8-7f4f-11e7-8f82-aea797ea91cf.png)

![image](https://user-images.githubusercontent.com/1676321/29243260-5a6aaa6a-7f4f-11e7-91c8-68c0b69eb858.png)


The difference here is the video codec that is being used.

Plugin: MPEG-4
"Camera App": AVC


I also have no idea that device you took this on as you did not supply any information or what version of the plugin either.

Ideally what you would do though is take this video and run it through a media service to encode into correct formats for specific devices: https://azure.microsoft.com/en-us/services/media-services/encoding/

**Comment by hashimks** [comment]
James, Thanks for your quick analysis. Here the device I am using is a Lenovo K50a40 and plugin version is 2.6.3.14-beta. I tried upgrading the plugin also and got the same issue. 

Please note that I cannot use Azure media service as I am directly uploading the recorded video to Amazon S3. Can you please help me other possibilities to solve this? It will be really helpful.

Thanks,
Hashim

**Comment by jamesmontemagno** [comment]
This most likely has nothing to do with uploading the image at all, you can just copy it off of the device and test it there. It seems as though the camera that is being used is recording in a different format. I would just try to implement the base functionality of recording video yourself via the intent or with embedding camera2 control into your app.

It is a bit out of my hand as to what the camera is recording in, i just launch it.

**Comment by hashimks** [comment]
Hello James,

As i told I am using the built in camera of the mobile. Also as mentioned previously, the locally recorded video uploaded to S3 is playing properly but through the plugin this is there. I will try with one more android device and confirm.

**Comment by hashimks** [comment]
i have checked in other android devices and is working properly. However i could see issues only in Lenovo K3, K4 series. Initially I thought it is specific to Lenovo brand. But it is working with Lenovo vibe.

Is there anything specific to these devices? Can we do anything for this?

**Comment by jamesmontemagno** [comment]
Hard to say, just how mobile devices are sometimes on Android and what apps are being used. Kinda of out of my hands or the libraries hands as it is doing standard stuff. You can't rely that every of the 25K+ android devices are going to do the same thing.
