### ISSUE TITLE
Will iOS 11's HEIF image format affect this plugin?

### ISSUE THREAD

**Issue by cwjbowler** [jamesmontemagno/MediaPlugin#324]
This isn't a bug, just a question about the impact of the future iOS version.

With iOS 11 they are changing the default image format used on iOS devices to HEIF (High Efficiency Image Format) instead of JPEG's. Currently when we call your plugin to get a picture from the camera or the library, we are given a JPEG file (and you add GPS location to the EXIF data within the JPEG if provided with it).

What will happen when the default format is HEIF? I believe Apple have said that when you share a picture online (like a social media app), then it will convert the image to a JPEG. Does that apply in general to the native camera/library pickers your plugin uses, or will the plugin simply provide the raw HEIF image when used on iOS 11?

Thanks

**Comment by jamesmontemagno** [comment]
Confirmed that it will not from what I have seen.
