### ISSUE TITLE
DesiredLength not working

### ISSUE THREAD

**Issue by rodrigommacedo** [jamesmontemagno/MediaPlugin#325]
Video Recording is not automatically stopping at the time set in DesiredLength

var file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions { Directory = "CameraAppVideos", DesiredLength = TimeSpan.FromMinutes(1) })

Version Number of Plugin: 3.0.1
Device Tested On: Nexus 5

**Comment by jamesmontemagno** [comment]
Most likely device specific or camera that you are using doesn't support the feature. Works on my Nexus 6 without any issues and the default camera app.
