### ISSUE TITLE
TakePhotoAsync is not working on Android

### ISSUE THREAD

**Issue by js-ka** [jamesmontemagno/MediaPlugin#326]
TakePhotoAsync is not working on Android.
There are no problems with calling the method PickPhotoAsync.
And there are no problems at all on iOS. Even TakePhotoAsync is working as expected.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Several devices with Android 6.0 and 7.1
Simulator Tested On: Google Android Emulator
Version of VS: Visual Studio 2017 15.3
Version of Xamarin: 2.3.4.247
Versions of other things you are using:

### Steps to reproduce the Behavior

Use a button.
Bind it to a command within the view model.
Call TakePhotoAsync.

### Expected Behavior

Camera dialog will be opened to take a picture

### Actual Behavior

Code works fine until the call of TakePhotoAsync.
After that nothing more happens.
The camera dialog has not been opened.
An exception was not thrown.

Only this messages was displayed in the output window:
"Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"

### Code snippet

await CrossMedia.Current.Initialize();
if(CrossMedia.Current.IsTakePhotoSupported && CrossMedia.Current.IsCameraAvailable)
{
	var oOptions = new StoreCameraMediaOptions()
	{
		AllowCropping = false,
		SaveToAlbum = true,
		PhotoSize = ePhotoSize,
		CompressionQuality = nCompressionQuality
	};
	MediaFile oImageFile = await CrossMedia.Current.TakePhotoAsync(oOptions);

	(...)

**Comment by higher-faster-better** [comment]
hi

I am trying to use this package in my app and added this code for permission
```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
		{
			PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
		}
```

But it says "PermissionsImplementation does not exist in current context"
How can I fix it?

Thanks.

**Comment by js-ka** [comment]
This issue can be closed.
The problem got solved.

**Comment by mehmetavsar** [comment]
what was the cause?

**Comment by js-ka** [comment]
It was my own fault.
I had to change the package identifier because of google restrictions.
And I forgot to update the AndroidManifest's attribute "android:authorities".
