### ISSUE TITLE
iPad Potential Memory Leak of Delegate (never disposed).

### ISSUE THREAD

**Issue by LSMadsen** [jamesmontemagno/MediaPlugin#327]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPad mini
Version of VS: 2017 (15.3.1)
Version of Xamarin: 4.6.0.295
Versions of other things you are using: Xamarin.Forms v. 2.3.4.267

### Steps to reproduce the Behavior
Choose a picture on an iPad with popover

### Expected Behavior
I expected the app to show up a prompt, where the user can enter a filename for the currently selected file

### Actual Behavior
I choose the picture, but nothing else happens

I was looking in the code, and I think it has to do with this line in `MediaImplementation.cs` in the `Media.Plugin.iOS` namespace

    if (popover != null)

On line 254

As popover is never declared, it will always be false, so it has to be either 

    if (ndelegate.Popover!= null)
    {
       ndelegate.Popover.Dispose();
       ndelegate.Popover= null;
    }

On line 254 - 258 or 

    ndelegate.Popover = popover = new UIPopoverController(picker);

On line 239

**Comment by jamesmontemagno** [comment]
This doesn't actually cause any issues at all looking through the original code:
https://github.com/xamarin/Xamarin.Mobile/blob/master/MonoTouch/Xamarin.Mobile/Media/MediaPicker.cs

I don't know what you mean by entering a name at all as your expected behavior.

**Comment by LSMadsen** [comment]
When the user has choosen a picture, the app asks the user for a filename for the new file (before it is uploaded). The prompt is shown based on Acr.UserDialogs and works fine other places in the app (also on iPad), but not when the user has choosen a file on iPad (it works fine on iPhone)

**Comment by jamesmontemagno** [comment]
You need to give me a sample to reproduce.
