### ISSUE TITLE
[Android] TakePhotoAsync - IllegalArgumentException: failed to find configured root

### ISSUE THREAD

**Issue by Knots23** [jamesmontemagno/MediaPlugin#329]
Hey James,

I'm running into issues with the TakePhotoAsync method. 
They don't occur on iOS, nor on Android with Target SDK 23.

**Note**: all 'MY_PACKAGE_NAME' found below are actually containing the correct package. ;)

I've read both:
- [issue 312](https://github.com/jamesmontemagno/MediaPlugin/issues/312)
  - Settings the external path in file_paths.xml to 'Pictures' as specified in the readme throws the exception.
  - Settings the external path in file_paths.xml to 'Android/data/MY_PACKAGE_NAME/files/Pictures' throws the exception.
- [issue 326](https://github.com/jamesmontemagno/MediaPlugin/issues/326)
  - This seems to occur when you don't add the entries to the manifest / file_paths.xml as specified in the readme.

## Bug Information

Version Number of Plugin: 2.6.2
Device Tested On: Samsung S8 (Android 7.0), iPhone 5s
Simulator Tested On: n.a.
Version of VS: Visual Studio 2017 15.3
Version of Xamarin: 2.3.4.267
Versions of other things you are using: Plugin.Permissions 1.2.1

### Steps to reproduce the Behavior

Everything should be setup as described in the readme:
- Target Android SDK is 25, so:
  - xml folder was created under Resources
  - file_paths.xml was created under that xml folder
  - the provider was added to the manifest, where the package name placeholder was replaced with my own package name.

Create a view and view model where the view model holds an ICommand to handle, e.g. a button click.
Call the TakePhotoAsync in the handler.

### Expected Behavior

The camera dialog will be opened and allows you to take a picture.

### Actual Behavior

An exception is thrown:
`Java.Lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Android/data/MY_PACKAGE_NAME/files/Pictures/IMG_20170823_130231.jpg`

The 'Pictures' folder was created, both on the internal and external storage. There's just no image.

### Code snippet

```
// Call this from the ICommand
private async Task TakePhoto()
{
   var options = new StoreCameraMediaOption();
   var media = await CrossMedia.Current.TakePhotoAsync(options);
}
```

**Comment by jamesmontemagno** [comment]
What is your package name? It must be set to something like "com.company.appname"

Rest assured this works fine just try the samples.

**Comment by Knots23** [comment]
The package name is correct and exactly in the form 'com.company.appname'.

The permissions should not be the issue. These are set (among others):
- Camera
- Write External Storage
- Read External Storage

Like I said, it did work with Android API 23, but after upgrading to 25 it stopped, even though I followed the readme and add all extra settings.

**Comment by jamesmontemagno** [comment]
If you can create a small sample that I can reproduce send it my way to test out.

**Comment by obartelt** [comment]
I had the same problem. You need to change the file_paths.xml. It must read:

<external-path name="my_images" path="Android/data/com.package.name/files/Pictures" />

instead of:

<external-files-path ...>

**Comment by mrTR24** [comment]
following +1

**Comment by jamesmontemagno** [comment]
Can't reproduce

**Comment by obartelt** [comment]
Have you read my comment? Sorry, it got corrupted somehow. It should've read:

I had the same problem. You need to change the file_paths.xml. It must read:

<external-path ...>

instead of:

<external-**files**-path ...>

At least that works for me...

**Comment by jamesmontemagno** [comment]
@obartelt  can you copy and paste your full file_paths.xml in here?

**Comment by obartelt** [comment]
@jamesmontemagno sure, here you go:

`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="my_images" path="Android/data/com.amtangee.android/files/Pictures" />
  <external-path name="my_movies" path="Android/data/com.amtangee.android/files/Movies" />
</paths>`

**Comment by jamesmontemagno** [comment]
Yeah, that one doesn't work anymore you need to update the scheme to the new way I have documented.

You don't need to specify the full path, that is probalby why it didn't work.

**Comment by obartelt** [comment]
Hmm, I think you got me wrong here. The way you documented doesn't work ("external-files-path" instead of "external-path"). I tried all different kinds of solutions (full path, no full path, different prefixes, etc.), but the one I posted is the only one that worked for me.

**Comment by jamesmontemagno** [comment]
could just depend on your settings, if you look at my sample works just fine. https://github.com/jamesmontemagno/MediaPlugin/blob/master/tests/MediaAndroidTest/Resources/xml/file_paths.xml

**Comment by jamesmontemagno** [comment]
As long as you have it working that is good :)

**Comment by obartelt** [comment]
Yeah, definitely ;-)  But your sample isn't working for me. Maybe device specific? I have a Honor 9...

**Comment by milena23** [comment]
I have the same problem on Huawei device
Looks like it's something about this issue https://stackoverflow.com/questions/39895579/fileprovider-error-onhuawei-devices

**Comment by PaulVrugt** [comment]
@jamesmontemagno 

why is this issue closed?

The issue seems to be specfic to some huawei devices that have an sd card. In my case, its a p8 lite 2017. We don't seem to have a fix for this, because i think this should be fixed in the plugin. If you take a look at the comment of @milena23 , it contains a link to a stackoverflow post about the issue.

Right now, i don't seem to have a way to fix the issue, as the fix suggested by @obartelt breaks the plugin for other devices

**Comment by PaulVrugt** [comment]
@obartelt see my updated comment. I've posted an example of the xml that seems to work for all devices

**Comment by obartelt** [comment]
@PaulVrugt thanks, but that seems to be exactly what I have, and what I posted here on Oct 3/5 2017?

**Comment by PaulVrugt** [comment]
@obartelt 

Right, now that i read it for the 3rd time I see you are correct. The discussion between you and jamesmontemagno seemed to go specifically about the external-files-path and external-path, and there was no more mentioning about the full path after jamesmontemagno stated you shouldn't use the full path. That's why I didn't understand that this was necessary.

Anyway, good for you that you're already using the method I (and apparently you too ;) ) posted, since this seems to work on all devices.

@jamesmontemagno , this confirms that this seems to be the only working way. Probably a good idea to update the documentation, or provide us with an alternative solution.
