### ISSUE TITLE
Taking a video on Nexus 5 always returns error message

### ISSUE THREAD

**Issue by rodrigommacedo** [jamesmontemagno/MediaPlugin#330]
Version Number of Plugin: 3.0.1
Device Tested On: Nexus 5

### Expected Behavior
Taking a video should return a MediaFile result.

### Actual Behavior
Always returns message error: Unable to locate media file at content://media/external/video/media/156934

### Code snippet
          StoreVideoOptions mediaOptions = new StoreVideoOptions()
			{
				Name = "test.mp4",
				CompressionQuality = 92,
				DesiredLength = TimeSpan.FromSeconds(10),
                                SaveToAlbum = true
			};

             var file = await CrossMedia.Current.TakeVideoAsync(mediaOptions);

**Comment by jamesmontemagno** [comment]
Did you setup your file provider? https://github.com/jamesmontemagno/MediaPlugin#android-n

Works fine on my devices that I have tested here.
