### ISSUE TITLE
Is it possible to save picture not camera taken to the gallery ?

### ISSUE THREAD

**Issue by Moret84** [jamesmontemagno/MediaPlugin#331]
Hi, and thanks for your plugin.
Suppose I have a byte stream representing an image in my code. Can I save it to the system gallery using your plugin ?
Cheers

**Comment by jamesmontemagno** [comment]
That is not possible with this plugin. You could probably grab my code that exposes images out to the galleries though and just use that.

**Comment by Moret84** [comment]
Thank you anyway.
