### ISSUE TITLE
Issue in playing video which is taken using low compression

### ISSUE THREAD

**Issue by hashimks** [jamesmontemagno/MediaPlugin#332]
Hello,

I have used the media plugin for recording a video from an android device (say Xiaomi Mi4). Here i set the VideoStoreOptions like below.

var file = await CrossMedia.Current.TakeVideoAsync(new Plugin.Media.Abstractions.StoreVideoOptions
                {
                    Directory = "TestMyApp",
                    Name = "testmyvideo.mp4",
                    DesiredLength = TimeSpan.FromMinutes(3),
                    Quality = Plugin.Media.Abstractions.VideoQuality.Medium,
                    CompressionQuality = 50
                });

When i record video, the video file is around 800MB which is taking a long time to upload and download. I wanted to view these videos in a iOS web view/safari. This will play in iOS web view if i set the uploaded Url path but is taking lot of time to load.

So what I did is I reduced Compression quality to 0 keeping quality as medium. The uploaded video is not playing in webview/safari. I did even try with the Quality to low as well and same issue. But only thing is uploaded file size is reduced but cannot play in webview. Is there any way we can reduce the video recorded size from android (3 minutes) to less than 15MB which will play in the iOS webview/safari?   

Can you please help me? I am really stuck here... :(

**Comment by hashimks** [comment]
Hello James,

Can u please help me on this? Medium compression with 50 quality video record is taking size of 800MB for 3 minutes video. If i reduce it below and record the video is not getting played in iOS.... i am really stuck here... can u pls advice?

**Comment by hashimks** [comment]
@jamesmontemagno Hello James... anything u found out?

**Comment by hashimks** [comment]
@jamesmontemagno This became a show stopper for me :(

**Comment by angelieri** [comment]
I think this is not a commercial component nor has a support with SLA.
This is a open source that you can dig in it and try to solve it by yourself.

**Comment by hashimks** [comment]
i know that. Also it is found that the compression details are below and could see the audio codec is AMR(narrow band). Please see the below image.

![mediainfo](https://user-images.githubusercontent.com/30616681/29824268-af62efbc-8cee-11e7-9dbc-f7a1f1367628.png)

Also an issue is posted here as well by some other guy

https://forums.xamarin.com/discussion/102022/xamarin-media-plugin

**Comment by jamesmontemagno** [comment]
Compression Quality doesn't apply to the actual videos at all. 

Quality however does, which is a VideoQuality.

How this works is that it sets the https://developer.android.com/reference/android/provider/MediaStore.html#EXTRA_VIDEO_QUALITY on the intent. 

* High/Medium are treated the same and set 1 for this
* Low sets it to 0, for low which has a dramatic difference in size

For instance 10 second video:
* High/Medium = 50MB on my Nexus 6
* Low = 240KB on my Nexus 6

The quality difference is very clear though between the two.

You would want to use your own video compression code on the device as this library does not do any post processing. Or you could use a media encoding service on your server.

Closing as working as expected and will add documentation during the re-write for the quality levels.

**Comment by hashimks** [comment]
@jamesmontemagno Hello James, thanks for your response. I did not ask for the video encoding. Video encoding is fine. However for low quality compression, the audio format is AMR narrow band which is not supported in iOS. So I may need to use the High/Medium compression. However as mentioned by you, for a 10 sec video it is taking 50MB, think of a video of around 3 minutes. It will go beyond 600MB. It will be really helpful if the low compression video can be set the audio quality to AAC rather than the AMR narrow band which will resolve this. This will definitely will be requested by lot of people who explore your plugin (which is really a cool one). Let me know your thoughts.

**Comment by jamesmontemagno** [comment]
Essentially this plugin just launches the built in camera apps, the plugin does not record any video and does not have control over how the video/audio is recorded and every device/app could be different, so if you want fine grain control I would probably implement your own Camera2 implementation on Android and record the video yourself. It is more work, but probably worth it in the end for your app if needs fine grain camera work.
