### ISSUE TITLE
iOS - Memory Issue after Opening/Closing Camera/Photo Library 100+ times

### ISSUE THREAD

**Issue by Robbie188** [jamesmontemagno/MediaPlugin#336]
The iOS version of my XForms app is crashing after 50+ images have been taken with the media plugin, as far as I can tell it is running out of memory.

There is quite a lot going on in my app so to find the root of the problem I have tried to test each part in isolation. I have found that using this plugin to just keep taking pictures but not do anything with the returned  image file eventually causes the app to crash.

On android it works fine.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPad Mini running iOS 11 Developer beta 8
Simulator Tested On: N/A
Version of VS: 2017 Enterprise 2017 15.3.1
Version of Xamarin: Xamarin Forms 2.4.0.269-pre2
Versions of other things you are using:

### Steps to reproduce the Behavior

In a blank XForms app add a button which calls TakePhotoAsync method then just does nothing with the file which gets returned.

Run on a physical iPad (I only have iPad mini to test on) Keep clicking the button and taking a picture over and over again (sorry this takes for ever and is really boring).

### Expected Behavior

Lets you keep taking photos for ever (or until battery runs out or you die)

#### Actual Behavior

After between 70 and 80 photos have been taken, pressing the "Use Image" button starts to take a lot longer to return from camera to app.  Then after between 80 and 100 photos are captured, the app crashes.

### Code snippet

```

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestImageApp"
             x:Class="TestImageApp.MainPage">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="70"/>
        </Grid.RowDefinitions>
        <Button Clicked="TakePhotoClicked" Grid.Row="1" Text="Take Photo"></Button>
    </Grid>
</ContentPage>

```

```
public async void TakePhotoClicked(object sender, EventArgs args)
{
    var filename = DateTime.Now.ToString("yyyyMMdd_hhmmssff") + ".png";
    var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
    {
        Directory = "TestImageApp",
        Name = filename,
        PhotoSize = Plugin.Media.Abstractions.PhotoSize.Large
    });
    file = null;
}

```

**Comment by LovinAndrei** [comment]
I'm having the same issue. What I've discovered is that you don't even have to take an image, just by opening the Camera or the Album picker it will increase the memory consumption by 100 mb on my iPad. I've stripped my code of everything else, so the issue must be caused by the Media Plugin.

**Comment by dhewitson** [comment]
I have tested this myself and have found that writing a native SWIFT iOS app with a basic controller with one button that only opens the camera and takes a photo and does nothing with them also causes this issue. It is not this plugin.

This is also an exception that was caught inside Xamarin when this issue occurred for me:

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: *** setObjectForKey: object cannot be nil (key: UIImagePickerControllerOriginalImage)
Native stack trace:
	0   CoreFoundation                      0x000000018a93eff8 <redacted> + 148
	1   libobjc.A.dylib                     0x00000001893a0538 objc_exception_throw + 56
	2   CoreFoundation                      0x000000018a822528 <redacted> + 0
	3   PhotoLibrary                        0x0000000197b18980 <redacted> + 756
	4   PhotoLibrary                        0x0000000197b1864c PLNotifyImagePickerOfImageAvailability + 28
	5   CameraUI                            0x00000001a08e990c <redacted> + 456
	6   CameraUI                            0x00000001a08e9218 <redacted> + 548
	7   UIKit                               0x0000000190aa5010 <redacted> + 96
	8   UIKit                               0x0000000190aa4f90 <redacted> + 80
	9   UIKit                               0x0000000190a8f504 <redacted> + 440
	10  UIKit                               0x0000000190aa4874 <redacted> + 576
	11  UIKit                               0x0000000190aa4390 <redacted> + 2480
	12  UIKit                               0x0000000190a9f728 <redacted> + 3192
	13  UIKit                               0x0000000190a7033c <redacted> + 340
	14  UIKit                               0x000000019126a014 <redacted> + 2400
	15  UIKit                               0x0000000191264770 <redacted> + 4268
	16  UIKit                               0x0000000191264b9c <redacted> + 148
	17  CoreFoundation                      0x000000018a8ed42c <redacted> + 24
	18  CoreFoundation                      0x000000018a8ecd9c <redacted> + 540
	19  CoreFoundation                      0x000000018a8ea9a8 <redacted> + 744
	20  CoreFoundation                      0x000000018a81ada4 CFRunLoopRunSpecific + 424
	21  GraphicsServices                    0x000000018c284074 GSEventRunModal + 100
	22  UIKit                               0x0000000190ad5058 UIApplicationMain + 208
	23  OSInspect_iOS_beta                  0x0000000100c47634 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 340
	24  OSInspect_iOS_beta                  0x000000010058859c UIKit_UIApplication_Main_string___intptr_intptr + 44
	25  OSInspect_iOS_beta                  0x000000010058845c UIKit_UIApplication_Main_string___string_string + 172
	26  OSInspect_iOS_beta                  0x00000001000f4164 OnsiteInspect_iOS_Application_Main_string__ + 212
	27  OSInspect_iOS_beta                  0x000000010126e9f4 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 244
	28  OSInspect_iOS_beta                  0x00000001039611dc mono_jit_runtime_invoke + 836
	29  OSInspect_iOS_beta                  0x00000001039cb844 do_runtime_invoke + 112
	30  OSInspect_iOS_beta                  0x00000001039ce46c do_exec_main_checked + 152
	31  OSInspect_iOS_beta                  0x000000010394abd4 mono_jit_exec + 268
	32  OSInspect_iOS_beta                  0x0000000103a7f100 xamarin_main + 2148
	33  OSInspect_iOS_beta                  0x0000000103922014 main + 96
	34  libdyld.dylib                       0x000000018982959c <redacted> + 4

Stack Trace:
	  at ObjCRuntime.Runtime.ThrowNSException (System.IntPtr ns_exception) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/ObjCRuntime/Runtime.cs:319 
  at ObjCRuntime.Runtime.throw_ns_exception (System.IntPtr exc) [0x00000] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/runtime/Delegates.generated.cs:126 
  at (wrapper native-to-managed) ObjCRuntime.Runtime:throw_ns_exception (intptr)
--- End of stack trace from previous location where exception was thrown ---
  at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/4691/d2270eec/source/xamarin-macios/src/UIKit/UIApplication.cs:79 
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in

**Comment by prashantvc** [comment]
@Robbie188 @dhewitson have you guys added the Camera access privacy text to info.plist?

**Comment by Robbie188** [comment]
Hey @prashantvc thanks for looking into it. Apologies, what exactly is it you mean by "Camera access privacy text"? I have keys for NSCameraUsageDescription and NSPhotoLibraryUsageDescription in my info.plist but I am assuming this is something different?

**Comment by prashantvc** [comment]
> I have keys for NSCameraUsageDescription and NSPhotoLibraryUsageDescription in my info.plist

This is exactly what I meant. Sorry for the confusion

**Comment by dhewitson** [comment]
@prashantvc yes

**Comment by akhare22sandeep** [comment]
Any update on this issue ? 
We are observing increase in memory gradually and once after 10 to 15 images have been take App Crashes. 

Do we need to dispose the file every time after using

**Comment by akhare22sandeep** [comment]
Thanks James for fixing it ! 
When it will be available to download from nuget  ?

**Comment by jamesmontemagno** [comment]
you can get CI builds by adding: https://ci.appveyor.com/nuget/mediaplugin to your nuget feeds

**Comment by akhare22sandeep** [comment]
Just verified the fixed. Photo pick from Library is still an issue . 10 Photo upload took 28.1 MB of memory
10 Photo taken from camera 2.5 MB of memory.

**Comment by jamesmontemagno** [comment]
Interesting, i will look into it.

**Comment by jamesmontemagno** [comment]
@akhare22sandeep are you on iphone or ipad?

**Comment by akhare22sandeep** [comment]
last test was on IPhone5s  OS 11.0.2 , Today planning to  test on IPhone6

**Comment by akhare22sandeep** [comment]
Today tested on Android Samsung Galaxy Tab A 2016 Tablet .. its worse than IOS 
10 **Camera captured** photo upload increased the app memory by **17.72 MB** 
10 **photo pick** from Library increased the app memory by  **10.54 MB**

**Comment by Robbie188** [comment]
Thanks for fixing this James, much appreciated!!
