### ISSUE TITLE
[Feature Request] Ability to take multiple pictures before exiting the camera app.

### ISSUE THREAD

**Issue by WillAutioItrax** [jamesmontemagno/MediaPlugin#34]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:
Device Tested On:
Simulator Tested On:

## Feature Request:
It would be useful to be able to take several pictures in a row before returning to the calling method. Rather than doing: Tap "Take a Photo" button; take a picture; accept it (tap the check mark - on android); Tap "Take a Photo" button; etc until done. It would be preferable to avoid the [Tap "Take a Photo" button; ] step for subsequent pictures. When done, we could tap the back button.
Thanks for considering this request

**Comment by jamesmontemagno** [comment]
No plan to ever implement sorry.
