### ISSUE TITLE
[Android] App get crashed after taking picture

### ISSUE THREAD

**Issue by tushark2099** [jamesmontemagno/MediaPlugin#340]
**Bug Information**

Version Number of Plugin:  3.0.1
Device Tested On: Any device of android
Simulator Tested On: 
Version of VS:  VS2017 (V 15.3.2)
Version of Xamarin:  4.6.0.299 
Versions of other things you are using:

**Steps to reproduce the Behavior :** 
Open the camera or photo gallery. Select a photo or click a photo. App gets crash.

after debugging. i have find out that only one line causing this crash. if i comment out that line there is no crash.  this is only happening on Android project not on IOS side. 

if i dont call "await Plugin.Media.CrossMedia.Current.TakePhotoAsync"  method. Crash never come.

 **Code snippet**
        string tempDirectory = "Kia";
                string tempFileName = "vehicleNumber.jpg";
                MediaFile mediaFile = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions()
                {
                    Directory = tempDirectory,
                    Name = tempFileName,
                    SaveToAlbum = true
                });
    if (mediaFile != null)
                {

// Other stuff
      
              }

**Crash log**

UNHANDLED EXCEPTION:
09-13 10:29:10.911 I/MonoDroid(14488): System.ObjectDisposedException: Cannot access a disposed object.
09-13 10:29:10.911 I/MonoDroid(14488): Object name: 'Xamarin.Forms.Platform.Android.ImageRenderer'.
09-13 10:29:10.911 I/MonoDroid(14488):   at Java.Interop.JniPeerMembers.AssertSelf (Java.Interop.IJavaPeerable self) [0x00029] in <6cd960837cc24c26bab2a0a29b597627>:0 
09-13 10:29:10.911 I/MonoDroid(14488):   at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualInt32Method (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00000] in <6cd960837cc24c26bab2a0a29b597627>:0 
09-13 10:29:10.911 I/MonoDroid(14488):   at Android.Views.View.get_Visibility () [0x0000a] in <d278c06ad5684d6882c743a94a93ebc2>:0 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.Platform.Android.VisualElementTracker.UpdateIsVisible () [0x0002e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:288 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.Platform.Android.VisualElementTracker.HandlePropertyChanged (System.Object sender, System.ComponentModel.PropertyChangedEventArgs e) [0x002dc] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\VisualElementTracker.cs:150 
09-13 10:29:10.911 I/MonoDroid(14488):   at (wrapper delegate-invoke) <Module>:invoke_void_object_PropertyChangedEventArgs (object,System.ComponentModel.PropertyChangedEventArgs)
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindableObject.OnPropertyChanged (System.String propertyName) [0x0000a] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:136 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.Element.OnPropertyChanged (System.String propertyName) [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\Element.cs:380 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindableObject.SetValueActual (Xamarin.Forms.BindableProperty property, Xamarin.Forms.BindableObject+BindablePropertyContext context, System.Object value, System.Boolean currentlyApplying, Xamarin.Forms.BindableObject+SetValueFlags attributes, System.Boolean silent) [0x000f4] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:589 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindableObject.SetValueCore (Xamarin.Forms.BindableProperty property, System.Object value, Xamarin.Forms.BindableObject+SetValueFlags attributes, Xamarin.Forms.BindableObject+SetValuePrivateFlags privateAttributes) [0x0015b] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindableObject.cs:386 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindingExpression.ApplyCore (System.Object sourceObject, Xamarin.Forms.BindableObject target, Xamarin.Forms.BindableProperty property, System.Boolean fromTarget) [0x001f9] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:173 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindingExpression.Apply (System.Boolean fromTarget) [0x0003e] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:55 
09-13 10:29:10.911 I/MonoDroid(14488):   at Xamarin.Forms.BindingExpression+BindingExpressionPart.<PropertyChanged>b__47_0 () [0x00000] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Core\BindingExpression.cs:539 
09-13 10:29:10.911 I/MonoDroid(14488):   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <d278c06ad5684d6882c743a94a93ebc2>:0 
09-13 10:29:10.911 I/MonoDroid(14488):   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <d278c06ad5684d6882c743a94a93ebc2>:0 
09-13 10:29:10.911 I/MonoDroid(14488):   at (wrapper dynamic-method) System.Object:dae0d283-e155-48a8-853b-788ee778bdbf (intptr,intptr)

**Comment by Whrothus** [comment]
I have the same problem

**Comment by jamesmontemagno** [comment]
You are trying to access a disposed object. Read through the documentation on how to display it.

**Comment by tushark2099** [comment]
Read through the documentation on how to display it. "... which particular document ?. I did the same why you guys shown in sample code. If possible could you please let me know what wrong with my code

**Comment by tushark2099** [comment]
even i am not accessing any disposed object.  
if i just run the following line of code which is calling the api call. i got error. regard less further using the media option.

Code : 

string tempDirectory = "Kia";
string tempFileName = "vehicleNumber.jpg";
MediaFile mediaFile = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions()
{
Directory = tempDirectory,
Name = tempFileName,
SaveToAlbum = true
});

**Comment by jamesmontemagno** [comment]
It is app in the readme: https://github.com/jamesmontemagno/MediaPlugin/blob/master/README.md

I also don't know what platform you are trying or what your error is. There is additional setup and samples in this repo.
