### ISSUE TITLE
[iOS] Camera screen doesn't hide after "Don't allow" button is pushed.

### ISSUE THREAD

**Issue by fabasoad** [jamesmontemagno/MediaPlugin#343]
## Bug Information

Version Number of Plugin: **3.0.1**
Device Tested On: **iPhoneSix+**
Simulator Tested On: **-**
Version of VS: **2017**
Version of Xamarin: **4.5.0.476 (1be4f0c)**
Versions of other things you are using: **Xamarin.iOS and Xamarin.Mac SDK - 10.10.0.35 (4cffddf)**

### Steps to reproduce the Behavior

1. Call the code to open the camera on iOS (see **Code snippet** section)
2. At the first time camera shows the message regarding camera permissions access and two buttons: **Don't allow** and **OK**. _(Screenshot 1)_
3. Press **Don't allow** button.

### Expected Behavior
_Functionally_: Camera screen should be hidden.
_Technically_: _TakePhotoAsync_ method should return _null_.

### Actual Behavior
_Functionally_: Camera screen still shown but with black screen. Anyway it allows user to tap the **PHOTO** button and get the black image. _(Screenshot 2)_ 
_Technically_: _TakePhotoAsync_ returns _non-null_ object (black image file).

### Code snippet
`var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions { Directory = "TestFolder", Name = "SomeName" });`

### Screenshots
![Screenshot 1](https://user-images.githubusercontent.com/2127723/30477967-c0d41b8c-9a17-11e7-9593-71a49a035ccc.png)
![Screenshot 2](https://user-images.githubusercontent.com/2127723/30477966-c0cdacac-9a17-11e7-91db-fabcbc06998c.png)

**Comment by jamesmontemagno** [comment]
What version of iOS? I would recommend using the permission plugin to handle proper permissions

**Comment by sergei-kobak** [comment]
We are using iOS 10.2.

The thing is: we are already using the permissions plugin, and everything goes fine for all the photos, except the very first one. At this point, permissions plugin returns CameraAccess.AccessNotSet, so we have to call CrossMedia.Current.TakePhotoAsync "blindly". 
Then iOS shows us "... Would Like to Access the Camera", and after choosing "Don't Allow" - we expect to just get back without the ability to take "empty" photo.

Thanks a lot.

**Comment by jamesmontemagno** [comment]
I think I can fix this up for sure. 

If it is not set as "Granted" then you should try to request it before taking the photo.

If they press "Don't Allow" it will then return "Denied"

This seems like an easy enough fix though on my end to request permissions.

**Comment by fabasoad** [comment]
Hi! Do you have an ETA of the release with this fix? Thanks in advance.

**Comment by prashantvc** [comment]
@fabasoad we do not have an ETA at the moment but you can download the fix here
https://ci.appveyor.com/project/JamesMontemagno/mediaplugin/build/3.0.2.128-beta/artifacts

And check out the complete changelog for the build (here)[https://github.com/jamesmontemagno/MediaPlugin/blob/master/CHANGELOG.md#302]

Please let us know if have any issues/feedback

**Comment by jamesmontemagno** [comment]
I'll deploy beta to nuget

**Comment by fabasoad** [comment]
Hi @jamesmontemagno! Just checked the behavior and it looks strange. Please find the _steps to reproduce_ below.
1. Run application very first time.
2. Run the same code snippet as in bug description.
3. Message _"My Application Would Like to Access the Camera. Don't Allow. OK."_ appears.
4. Click "OK".

_Expected behavior_:
I see the camera to be able to take a photo.

_Actual behavior_:
The same message appears again. And I see the camera only when I click "OK" again.

Media Plugin version: _3.0.2.129-beta_

**Comment by jamesmontemagno** [comment]
File a new bug

**Comment by fabasoad** [comment]
Hi @jamesmontemagno
The new bug has been created - [#383](https://github.com/jamesmontemagno/MediaPlugin/issues/383)
