### ISSUE TITLE
MediaPickerActivity is stopped during Camera is opened

### ISSUE THREAD

**Issue by salamoun** [jamesmontemagno/MediaPlugin#345]
I'm expecting strange behaviour when Camera is opened using MediaPlugin on Android.
Using Gallery photo pick, all happens as expected. Xamarin.Forms MainActivity is stoped and MediaPickerActivity is only paused, than gallery picker is running.
But with Camera Pick all activities are stopped (MainActivity and MediaPickerActivity) and I can't catch any new activity that is started (i'm using ActivityLifecycleCallbacks interface to detect activity lifecycles).
So, when Camera picker is running my apps thinks that is going to background, because no activities are started.
My target is too detect if app is on foreground or background, using this technique: https://stackoverflow.com/a/42679191/3855598.
It works fine, but MediaPickerActivity is not working due to strange activity lifecycle.
Any ideas? Thanks.

**With Camera:**
OnActivityPaused: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityCreated: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityStarted: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityResumed: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityPaused: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityStopped: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityStopped: md585056583c541273b4e233dd03f989739.MainActivity
-- Camara Is Opened --
OnActivityStarted: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityResumed: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityDestroyed: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity

**With Gallery Pick:**
OnActivityPaused: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityCreated: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityStarted: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityResumed: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityPaused: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityStopped: md585056583c541273b4e233dd03f989739.MainActivity
-- Gallery is Opened --
OnActivityStarted: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityResumed: md585056583c541273b4e233dd03f989739.MainActivity
OnActivityStopped: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity
OnActivityDestroyed: md5a3e164e78ade0c22cefea770ddd0bc49.MediaPickerActivity

**Comment by prashantvc** [comment]
Could you share following information? It will help us to troubleshoot this issue

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### A sample project demonstrating the issue 

### Screenshots

**Comment by prashantvc** [comment]
Because we have not received a reply to our request for more information, I am marking this issue as closed. If you are still encountering this issue on the latest version of the plugin, please don’t hesitate to reopen the ticket with the requested information. Thanks!
