### ISSUE TITLE
Plugin is not working on Android device.

### ISSUE THREAD

**Issue by ManojMali0807** [jamesmontemagno/MediaPlugin#348]
Hello @jamesmontemagno ,

Your plugin is too good.

I have used this plugin in my xamarin forms app.

After implementation, the capture & pick image functionality was working fine.
But now on Android device, capture & pick image is not working any more.
Android app is crashing.
On iPhone, its working fine.

Here is the output of android app crash:
`09-21 21:26:53.005 D/Mono    (15231): Assembly Loader probing location: '/storage/emulated/0/Android/data/guguus.guguus/files/.__override__/Plugin.Media.Abstractions.dll'.
09-21 21:26:53.006 D/Mono    (15231): AOT: image '/storage/emulated/0/Android/data/guguus.guguus/files/.__override__/Plugin.Media.Abstractions.dll.so' not found: dlopen failed: library "/data/app/guguus.guguus-1/lib/x86/libaot-Plugin.Media.Abstractions.dll.so" not found
09-21 21:26:53.006 D/Mono    (15231): AOT: image '/usr/local/lib/mono/aot-cache/x86/Plugin.Media.Abstractions.dll.so' not found: dlopen failed: library "/data/app/guguus.guguus-1/lib/x86/libaot-Plugin.Media.Abstractions.dll.so" not found
09-21 21:26:53.007 D/Mono    (15231): Assembly Ref addref guguus.Mobile.XamarinForm.Shared[0xaab44a60] -> Plugin.Media.Abstractions[0xaab43f80]: 2
`

Please help me to find out the reason of crash.
Thank you

**Comment by jamesmontemagno** [comment]
Looks like this is something with AOT or something else not with the plugin. Open a bugzilla report with xamarin please.

**Comment by ManojMali0807** [comment]
Thank you..

**Comment by ManojMali0807** [comment]
Hello @jamesmontemagno ,

My android app is still crashing on capture/pick image.
Do you know anything about this..

`09-26 19:28:45.726 D/Mono    (21873): Assembly Ref addref guguus.Mobile.XamarinForm.Shared[0xb7717e00] -> Plugin.Media[0xb77071e8]: 2
09-26 19:28:45.726 D/Mono    (21873): Assembly Ref addref Plugin.Media[0xb77071e8] -> Plugin.Media.Abstractions[0xb77062b8]: 3
09-26 19:28:45.726 D/Mono    (21873): Unloading image System.Threading.Tasks.dll [0xb8ef1de8].
09-26 19:28:45.726 D/Mono    (21873): Image addref System.Threading.Tasks[0xb8e45870] -> System.Threading.Tasks.dll[0xb7a7f6e0]: 8
09-26 19:28:45.726 D/Mono    (21873): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
09-26 19:28:45.726 D/Mono    (21873): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
09-26 19:28:45.726 D/Mono    (21873): Assembly Ref addref Plugin.Media.Abstractions[0xb77062b8] -> System.Threading.Tasks[0xb7a80250]: 6
09-26 19:28:45.766 D/Mono    (21873): Unloading image System.IO.dll [0xb8f043c0].
09-26 19:28:45.766 D/Mono    (21873): Image addref System.IO[0xb8e45930] -> System.IO.dll[0xb7ae4730]: 8
09-26 19:28:45.776 D/Mono    (21873): Config attempting to parse: 'System.IO.dll.config'.
09-26 19:28:45.776 D/Mono    (21873): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.IO/System.IO.config'.
09-26 19:28:45.776 D/Mono    (21873): Assembly Ref addref Plugin.Media.Abstractions[0xb77062b8] -> System.IO[0xb7ae66e8]: 6
09-26 19:28:45.776 D/Mono    (21873): Assembly Ref addref Plugin.Media[0xb77071e8] -> Plugin.Permissions.Abstractions[0xb77081c0]: 2
09-26 19:28:45.786 D/Mono    (21873): Assembly Ref addref Plugin.Media[0xb77071e8] -> Plugin.Permissions[0xb7709130]: 2
09-26 19:28:45.786 D/Mono    (21873): Assembly Ref addref Plugin.Permissions[0xb7709130] -> Plugin.Permissions.Abstractions[0xb77081c0]: 3
09-26 19:28:45.786 D/Mono    (21873): Unloading image System.Threading.Tasks.dll [0xb8f4cb30].
09-26 19:28:45.786 D/Mono    (21873): Image addref System.Threading.Tasks[0xb8f4d518] -> System.Threading.Tasks.dll[0xb7a7f6e0]: 9
09-26 19:28:45.786 D/Mono    (21873): Config attempting to parse: 'System.Threading.Tasks.dll.config'.
09-26 19:28:45.786 D/Mono    (21873): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Threading.Tasks/System.Threading.Tasks.config'.
09-26 19:28:45.786 D/Mono    (21873): Assembly Ref addref Plugin.Permissions.Abstractions[0xb77081c0] -> System.Threading.Tasks[0xb7a80250]: 7
09-26 19:28:45.786 D/Mono    (21873): Unloading image System.Collections.dll [0xb8f4dfb0].
09-26 19:28:45.786 D/Mono    (21873): Image addref System.Collections[0xb8f4def0] -> System.Collections.dll[0xb77c2be8]: 10
09-26 19:28:45.786 D/Mono    (21873): Config attempting to parse: 'System.Collections.dll.config'.
09-26 19:28:45.786 D/Mono    (21873): Config attempting to parse: '/usr/local/etc/mono/assemblies/System.Collections/System.Collections.config'.
09-26 19:28:45.786 D/Mono    (21873): Assembly Ref addref Plugin.Permissions.Abstractions[0xb77081c0] -> System.Collections[0xb77c3528]: 8
09-26 19:28:45.816 I/Timeline(21873): Timeline: Activity_launch_request time:93739519
09-26 19:28:45.846 I/art     (21873): System.exit called, status: 0`
