### ISSUE TITLE
[FEATURE REQUEST]Allow Picking All Sorts of Media Types ex. Audio

### ISSUE THREAD

**Issue by ahmedalejo** [jamesmontemagno/MediaPlugin#35]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug

Version Number of Plugin: 2.3.0
Device Tested On: N/A
Simulator Tested On: N/A

### Actual Behavior
Can only pick images and videos
### Steps to reproduce the Behavior
N/A

## Feature Request:
Should be able to Pick all sorts o media files, mp3, pdf e.t.c

**Comment by jamesmontemagno** [comment]
Out of scope for the plugin sorry. Only focusing on video and photos.

**Comment by ahmedalejo** [comment]
Cool! I was
