### ISSUE TITLE
[Feature Request]  - MediaFile

### ISSUE THREAD

**Issue by galadril** [jamesmontemagno/MediaPlugin#351]
Maybe it would be handy to extend the MediaFile model to add methods for getting media size.
And a possibility to resize or reduce quality afterwards.

Every mobile has a different camera, with different quality.. I can't just set the reduced quality or size on the action of taking a picture.. I need to see the size of the MediaFile to see if it exceeds my max size..

Should that be possible??

Thanks for the effort!

**Comment by groege** [comment]
I'm actually also resizing the images to a max width/height of 1280...
With % of original size I can't be sure what dimensions the pic will have...

**Comment by jamesmontemagno** [comment]
No new features.
