### ISSUE TITLE
TakeVideoAsync crash on iOS 11 with SaveToAlbum 

### ISSUE THREAD

**Issue by MarcorOnline** [jamesmontemagno/MediaPlugin#356]
Hello, 
a bug is appeared after iOS 11 upgrade.

## Bug Information
"TakeVideoAsync" crash on iOS 11 if "SaveToAlbum" is true

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 7 Plus

### Steps to reproduce the Behavior
Call "TakeVideoAsync" with SaveToAlbum = true on iOS 11

### Actual Behavior
Crash pressing "Use video" after video recording.

### Code snippet
```
file = await CrossMedia.Current.TakeVideoAsync(new StoreVideoOptions
{
	Directory = "MyAppName",
	Name = DateTime.Now.ToString("hh-mm-dd-MM-yyyy") + ".mp4",
	DefaultCamera = CameraDevice.Rear,
	SaveToAlbum = true,
	Quality = VideoQuality.Medium
});
```

Thanks for your support

**Comment by prashantvc** [comment]
I am not able to reproduce this issue with following permissions enabled

- Camera
- Mic
- Photos library

Make sure you have these permission enabled on your app.

Please share the complete crash log, and stacktrace if you continue to have an issue

**Comment by jamesmontemagno** [comment]
And are you compiling against iOS11?

**Comment by MarcorOnline** [comment]
@jamesmontemagno @prashantvc both compiling against iOS8 and iOS11

Here the full code that shows that **all permissions checks** are passed before the **TakeVideoAsync** invocation:
https://gist.github.com/MarcorOnline/5a569c922125768bbe1ed66b42252add

Info.plist contains the right keys, obviously:
```
<key>NSPhotoLibraryUsageDescription</key>
<string>Choose video to upload from gallery</string>
<key>NSCameraUsageDescription</key>
<string>Register videos for challenges</string>
<key>NSMicrophoneUsageDescription</key>
<string>Register audio for challenges</string>
```

I'm using the nuget packages. Next week I will try importing the GitHub files (now I can't do it beacuse I'm out of office). Tell me if you have any ideas.

Thanks for your support!

**Comment by jamesmontemagno** [comment]
So, i think they removed some APIs from iOS 11: http://sametdede.com/alassetslibrary-is-deprecated-now-what/

Will need to switch it over to PHPhotoLibrary

**Comment by JensSchadron** [comment]
iOS 11 Added a new permission to add pictures to the media library.

So it works when you add the following to the info.plist
```xml
<key>NSPhotoLibraryAddUsageDescription</key>
<string>This app needs access to the photo gallery.</string>
```

**Comment by MarcorOnline** [comment]
@jamesmontemagno the solution provided by @JensSchadron works well!

Thanks!

**Comment by jamesmontemagno** [comment]
Will add to docs!
