### ISSUE TITLE
[Feature] Add Support for Tizen

### ISSUE THREAD

**Issue by swift11** [jamesmontemagno/MediaPlugin#357]
Could you add support for Samsung TV please ?

https://developer.tizen.org/development/tizen-.net-preview/introduction

**Comment by rookiejava** [comment]
Hello. Thanks for your intrest on Tizen. I am responsible for xamarin.forms.platform.tizen. I'll promise that we contribute the tizeb backend for MediaPlugin soon.(within 1-2weeks)

**Comment by rookiejava** [comment]
As promised last week, we submitted PR to add Tizen backend. (#391) Could you review and merge this ?@jamesmontemagno.  After merging and publishing nuget package, we will also contribute both sample app and test app for Tizen. Of course we already test with Tizen device internally, and it worked well. :) 
Please feel free to contact me if you have any questions or suggestions.
