### ISSUE TITLE
the plug in not working for android without exception

### ISSUE THREAD

**Issue by merral** [jamesmontemagno/MediaPlugin#358]
i install the plug in and i did exactly as u mention in ur  description it work for ios and UWP but showing nothing for android no pickup no take photo i mean when hit this
``` csharp
 file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions { CompressionQuality = 20, PhotoSize = PhotoSize.Small });
                if (file == null)
                    return;

                var im = ImageSource.FromStream(() =>
                {
                    var stream = file.GetStream();
                    return stream;

                });

```
for ios and uwp showing the pickup dialog but nothing happen for android

**Comment by prashantvc** [comment]
Could you elaborate what is not working? I am not able to reproduce this issue in my test project using latest version of the plugin

**Comment by jamesmontemagno** [comment]
Assumption is you didn't add the file.xml in your resources.

**Comment by merral** [comment]
i solve this issue but forget to close thnx guys for your response
