### ISSUE TITLE
AllowCropping turns image sideways

### ISSUE THREAD

**Issue by jpmock** [jamesmontemagno/MediaPlugin#360]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:  3.0.1
Device Tested On:  iPhone 7+
Simulator Tested On:
Version of VS For Mac:  7.1.5 build 2
Version of Xamarin:  
Versions of other things you are using:

### Steps to reproduce the Behavior

Plugin works excellent and once a picture is taken, say in portrait mode, it renders properly, but if I add the setting:  AllowCropping=true, once the image is selected it renders sideways.

### Expected Behavior

Render the image in portrait mode as expected

### Actual Behavior

Image is flipped 90 degrees

**Comment by jamesmontemagno** [comment]
Dupicate
