### ISSUE TITLE
Bitmap too large to be uploaded into a texture error in some phones even after reducing size an quality in android #354

### ISSUE THREAD

**Issue by varun13487** [jamesmontemagno/MediaPlugin#363]
**This is in reference to closed issue** #354 

I tried resizing it even then it is not showing. And also how can I find out that when to resize and when not. I am picking images from gallery of different sizes, If I will pick an image of very small size on resizing it and applying to an image view of a particular size, it will be pixelated. I am very new to Xamarin.forms. Can you suggest something?

Can I get the size of image Media file that I will get using this plugin?

**Comment by jamesmontemagno** [comment]
You will need to re-size your image or simply set the "MaxWidthOrHeight" to a different size. Realize that each Android device has different limitations for Bitmaps

https://www.google.com/search?q=android+image+resize+xamarin&oq=android+image+resize+xamarin&aqs=chrome..69i57j0j69i64.3476j0j7&sourceid=chrome&ie=UTF-8

**Comment by varun13487** [comment]
Not Satisfied with the solution. Please stop closing the issues until they are really resolved.
