### ISSUE TITLE
Cropping is not working and on ios device can not take Portrait images

### ISSUE THREAD

**Issue by AshishAsodiya** [jamesmontemagno/MediaPlugin#364]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Moto G3, iPhone 6,iPhone 6s
Simulator Tested On:
Version of VS: 
Version of Xamarin: 6.3
Versions of other things you are using:

### Code snippet
```csharp
await CrossMedia.Current.Initialize();
try
{
	if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
	{
		throw new System.Exception(":( No camera available.");
	}
	var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
	{
		DefaultCamera = CameraDevice.Front,

		AllowCropping = true,
		Directory = "La_Marocaine",
		Name = "Face.jpg"
	});
	if (file == null)
	{
		return null;
	}
	var stream = file.GetStream();
	//byte[] cropedBytes = await CrossXMethod.Current.CropImageFromOriginalToBytes(file.Path);
	//return new MemoryStream(cropedBytes);
	return stream;
}
catch (Exception ex)
{
	throw ex;
}
```

**Comment by jamesmontemagno** [comment]
Not enough info

**Comment by AshishAsodiya** [comment]
Hello James,

Which information you need? Please tell me i will provide to you
