### ISSUE TITLE
TakePhotoAsync crashed when saving to album after iOS 11 update

### ISSUE THREAD

**Issue by EnriqueEgremy** [jamesmontemagno/MediaPlugin#368]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6
Simulator Tested On: (can't reproduce in emulator)
Version of VS: 7.2  (visual studio for mac)
Using the Plugin.Permissions v2.0.2

### Steps to reproduce the Behavior
Take a photo, and try to save to an album.

### Expected Behavior
The photo is saved.

### Actual Behavior
The app crash

### Code snippet

var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                    Directory = "ValidaIO",
                    Name = fileName,
                    CompressionQuality = 70,
                    RotateImage = true
                    SaveToAlbum = true
                });

### Screenshots

![captura de pantalla 2017-10-06 a la s 18 17 35](https://user-images.githubusercontent.com/29898855/31503847-54f3f048-af36-11e7-8aac-759acdb81b80.png)

If i comment the SaveToAlbum part, it stop crashing.

**Comment by jamesmontemagno** [comment]
You must add:
<key>NSPhotoLibraryAddUsageDescription</key>
<string>This app needs access to the photo gallery.</string>

**Comment by EnriqueEgremy** [comment]
i have the permission
<key>NSPhotoLibraryUsageDescription</key>
	<string>This app needs access to photos.</string>

did the name of the permission changed on iOS 11 to NSPhotoLibraryAddUsageDescription ?

**Comment by EnriqueEgremy** [comment]
OK, that fixed the problem.

Thank you very much.

**Comment by jamesmontemagno** [comment]
It is a new permission! :(

**Comment by EnriqueEgremy** [comment]
Is the second time (the firs one was with you plugin of geolocator) that iOS added a new permission and is nowhere to be found in their documentation :/

**Comment by jamesmontemagno** [comment]
Basically each iOS update there are new ones :( We are doing a big blog on them actually.

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html

and

https://developer.apple.com/documentation/corelocation/choosing_the_authorization_level_for_location_services/request_always_authorization
