### ISSUE TITLE
Xamarin Forms IOS app memory keeps increasing 

### ISSUE THREAD

**Issue by akhare22sandeep** [jamesmontemagno/MediaPlugin#369]
I am developing Xamarin Forms app for Android and IOS . Android testing is still not done but for IOS Iphone testing we found by using media library for photo pickup and camera attached is consuming lot of memory. The PhotoSize  is configured to be small. 
 For Example 10 photos pick up from library and 10 camera taken photos and uploading to sever memory is increased by 47 MB. 

## Bug Information

Version Number of Plugin:3.0.1
Device Tested On: 5s , 6 , 6s
Simulator Tested On: NA
Version of VS:  2015 
Version of Xamarin: 4.7
Versions of other things you are using: Xamarin Forms 2.4.0.282 , 

### Code snippet
``
  private async Task UploadReceipt()
        {
            var action = await DialogService.ShowActionSheetAsync("Select receipt from", "Cancel", null, new List<string> { "Camera", "From Library" });
            if (action == "Camera")
            {
                await TakePhoto();
            }
            else if (action == "From Library")
            {
                await PickPhoto();
            }
            else
            {
                // nothing 
            }
        }

        async Task TakePhoto()
        {

            try
            {
                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    await DialogService.ShowAlertAsync("No Camera", ":( No camera avaialble.", "OK");
                    return;
                }

                var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    PhotoSize = PhotoSize.Small,
                    CompressionQuality = 92,
                    SaveToAlbum = false,
                    DefaultCamera = CameraDevice.Rear

                });

                if (file == null)
                {
                    return;
                }

                await UploadPhoto(file);
            }
            catch (Exception ex)
            {
                await DialogService.ShowErrorImage(ex.ToString());
            }
        }

        async Task PickPhoto()
        {

            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                await DialogService.ShowAlertAsync("Photos Not Supported", ":( Permission not granted to photos.", "OK");
                return;
            }
            var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                PhotoSize = PhotoSize.Small,
                CompressionQuality = 92,

            });

            if (file == null)
            {
                return;
            }
            await UploadPhoto(file);

        }

      
        async Task UploadPhoto(MediaFile file)
        {
            DialogService.ShowProgress(Acr.UserDialogs.MaskType.Black, "Uploading Receipt");
            var receiptModel = mediaService.GetPhoto(Transaction.TransactionId, file);

            if (receiptModel == null)
            {
                await DialogService.ShowErrorImage("Failed to get image");
            }

            if (Transaction.Receipts == null)
            {
                Transaction.Receipts = new List<ReceiptsModel>();
            }

            Transaction.Receipts.Add(receiptModel);
            try
            {
                var result = await receiptService.AddReceipt(receiptModel);
                if (result != null)
                {
                    await DialogService.ShowSuccessImage("Receipt Uploaded !", Constants.SuccessShortDisplay);
                }
               
                ReceiptAttached = true;
                DisplayIcon = false;
                await RefreshReceipts(Transaction.TransactionId);
             
                RaisePropertyChanged(() => Comments);
            }
            catch (ApplicationUnAuthirizedException ex)
            {

                Debug.WriteLine("Authorization failed " + ex.ErrorMessage);
                await DialogService.ShowAlertAsync(ex.Message, "Authorization failed", "Ok");
                await NavigationService.NavigateToAsync<LoginViewModel>(2);
            }
            catch (ApplicationException ex2)
            {

                Debug.WriteLine("Failed to get Data  failed " + ex2.ErrorMessage);

                await DialogService.ShowAlertAsync(ex2.ErrorMessage, "Error", "Ok");
            }
            catch (Exception ex3)
            {
                Debug.WriteLine("Failed to remove the receipt " + ex3.ToString());

                await DialogService.ShowAlertAsync(ex3.Message, "Error", "Ok");
            }
            finally
            {
                DialogService.HideProgress();
            }

        }

**Comment by jamesmontemagno** [comment]
Duplicate #336
