### ISSUE TITLE
Frozen screen when taking picture from iPhone

### ISSUE THREAD

**Issue by fcogutierrez** [jamesmontemagno/MediaPlugin#37]
Hi.

After take a picture from my iPhone camera, the screen is frozen, and it does not return to the app.
However, if I pick a picture, it does not do anything when I select a picture.

I am using Xamarin 2.3.

What can be happening? **In Android and iPad works fine**.

**Comment by fcogutierrez** [comment]
In emulator works fine, but not in device... :-(

**Comment by jamesmontemagno** [comment]
Wasn't able to reproduce with 2.5.0-beta5 at all. Not sure how you were calling it though. I tested on iphone 6.
