### ISSUE TITLE
[Feature request] Aspect ratio for media options

### ISSUE THREAD

**Issue by Jesuqq** [jamesmontemagno/MediaPlugin#370]
Hi,
it would be cool to be able to provide wanted aspect ratio for the camera in media options. For example to take square photos with camera:
```
var mediaOptions = new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    AspectRatio = AspectRatio.Square
                };

MediaFile file = await CrossMedia.Current.TakePhotoAsync(mediaOptions);
```

**Comment by jamesmontemagno** [comment]
Unfortunately the api for the cameras don't work this way. You would need a custom image resizer control.
