### ISSUE TITLE
iOS, Photo's orientation gets changed from Portrait to Landscape

### ISSUE THREAD

**Issue by bprochniak** [jamesmontemagno/MediaPlugin#371]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6
Simulator Tested On:
Version of VS: 2017, 15.3.5
Version of Xamarin: 4.7.9.45 
Versions of other things you are using: Xamarin.Forms 2.4.0.282, Xamarin.iOS 11.0.0.0, XCode 9, iOS SDK 11

### Steps to reproduce the Behavior

1. Pick a portrait photo from the device gallery:
2. The orientation gets changed to landscape

### Expected Behavior

Image's orientation should stay Portrait

### Actual Behavior

The photo appears as landscape

### Code snippet

`MediaFile file = await CrossMedia.Current.PickPhotoAsync();`

`
<Image Source ="{ Binding PictureSelector.ImageSource }" HorizontalOptions="Center" VerticalOptions="Start" WidthRequest="96" HeightRequest="96" />`

### Comment

It was working fine with 2.6.2, XCode 8, iOS SDK 10 and Xamarin.iOS 10. Now it works only when I set RotateImage to False:

`MediaFile file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions() { RotateImage = false });`

but I works just for the first time. If I choose the same picture from the gallery again the photo appears as landscape.

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jamesmontemagno/MediaPlugin/issues/333
