### ISSUE TITLE
Could not install package 'Xamarin.Android.Support.Compat 25.3.1'

### ISSUE THREAD

**Issue by waletoye** [jamesmontemagno/MediaPlugin#372]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
3.0.1
Device Tested On:
Not installing
Simulator Tested On:
Not installing
Version of VS: 
Visual Studio 2017
Version of Xamarin:
4.6.0.299
Versions of other things you are using:

### Steps to reproduce the Behavior
I tried to install the lastest version 3.0.1
### Expected Behavior
Install without any problems
### Actual Behavior
Could not install package 'Xamarin.Android.Support.Compat 25.3.1'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.		
### Screenshots
No screenshots

**Comment by prashantvc** [comment]
The Xamarin.Android.Support.Compat 25.3.1 NuGet package contains assemblies for MonoAndroid v7.0. So you will need to change the target framework of your Android project to be 7.0. You should be able to change that in the Visual Studio project options 

You may need to update your Android SDKs if v7.0 is not available.

**Comment by waletoye** [comment]
Thanks, but still didn't work after trying these. 
I changed:

Compile using android version -> 7.1 Nougat
Minimum -> 6 Marshmallow
Target -> 7 Nougat

And could not install version 3.0.1
2.6.2 installed without problems.

Help please

**Comment by jamesmontemagno** [comment]
Close and reopen the solution so nuget can update. Works just fine

**Comment by jamesmontemagno** [comment]
https://blog.xamarin.com/mastering-android-support-libraries/

**Comment by waletoye** [comment]
Works now. Thanks. API 25

**_Additionally_**, I tried to install the latest Android Support 26. libraries
I get similar MonoAndroid v7.1 error. Even after installing API 26
