### ISSUE TITLE
take photo not working with xamarin iOS

### ISSUE THREAD

**Issue by sowmyasql** [jamesmontemagno/MediaPlugin#373]
Hi, I have an issue with Xam.media plugin where I cannot access camera with iOS simulator, 
Xam media plugin version: 2.6.2
Xamarin Forms: 2.3.4.270
How to resolve?

**Comment by jamesmontemagno** [comment]
you can't take photos in simulator, only pick photos. iOS simulators don't have cameras

**Comment by sowmyasql** [comment]
Ok. And I can't even pick photos, I am getting exception:
system.objectdisposedException in Main.cs xamarin IOS project.
