### ISSUE TITLE
Uploaded image using this plugin from Gallery or Picture taken

### ISSUE THREAD

**Issue by ravikanasagra1** [jamesmontemagno/MediaPlugin#376]
From primary reading about this plugin, I have observed that this plug in should have one feature - Image file size. 

In my case, I want to restrict user to some size like user could not select image more then 5 MB or any size.

Can we have this on this plugin or suggest code snippet to get size.

**Comment by jamesmontemagno** [comment]
Not planned and not really possible with available APIs
