### ISSUE TITLE
Documentation suggestion and Nuget package improvement

### ISSUE THREAD

**Issue by nikkilocke** [jamesmontemagno/MediaPlugin#378]
When I installed the NuGet package, it did not install Plugin.Permissions automatically. So, when I followed the instructions in the `readme.txt` file (which are less comprehensive than the ones in `README.md` on github), the android version would not compile with `The name 'PermissionsImplementation' does not exist in the current context` It would be good if the Permissions plugin was installed automatically. Failing that, the `readme.txt` file could be updated with more comprehensive instructions.

Also, all the code examples in the README.md file to do with permissions will not compile unless you add 

    using Plugin.Permissions;
    using Plugin.Permissions.Abstractions;

It would be good if the documentation made this explicit.

**Comment by jamesmontemagno** [comment]
Added
