### ISSUE TITLE
Including this plugin in a project causes it to fail to compile

### ISSUE THREAD

**Issue by nikkilocke** [jamesmontemagno/MediaPlugin#379]
## Bug Information

Version Number of Plugin: 3.0.1
Version of VS: Community 2017  15.2 (26430.13)
Version of Xamarin:4.5.0.486 (fec6f88)
Versions of other things you are using:
sqlite-net-pcl 1.4.118

### Steps to reproduce the Behavior
Create an empty Xamarin project, add sqlite-net-pcl and your plugin. Try to compile.

### Expected Behavior
Project compiles.

### Actual Behavior
Error messages:
1>------ Build started: Project: DefectReport.Android, Configuration: Debug Any CPU ------
2>------ Skipped Build: Project: DefectReport.iOS, Configuration: Debug iPhone ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: DefectReport.UWP, Configuration: Debug x86 ------
3>Project not selected to build for this solution configuration 
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>  DefectReport.Android -> E:\TEMP\Xamarin\DefectReport\DefectReport.Android\bin\Debug\DefectReport.Android.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.Content.Loader+IOnLoadCanceledListenerImplementor, Xamarin.Android.Support.Core.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.Content.Loader+IOnLoadCanceledListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.Content.Loader.IOnLoadCanceledListenerImplementor' will refer to 'Android.Support.V4.Content.Loader+IOnLoadCanceledListenerImplementor, Xamarin.Android.Support.Core.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.Content.Loader+IOnLoadCompleteListenerImplementor, Xamarin.Android.Support.Core.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.Content.Loader+IOnLoadCompleteListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.Content.Loader.IOnLoadCompleteListenerImplementor' will refer to 'Android.Support.V4.Content.Loader+IOnLoadCompleteListenerImplementor, Xamarin.Android.Support.Core.Utils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.OS.CancellationSignal+IOnCancelListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.OS.CancellationSignal+IOnCancelListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.OS.CancellationSignal.IOnCancelListenerImplementor' will refer to 'Android.Support.V4.OS.CancellationSignal+IOnCancelListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.ActionProvider+ISubUiVisibilityListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.ActionProvider+ISubUiVisibilityListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.ActionProvider.ISubUiVisibilityListenerImplementor' will refer to 'Android.Support.V4.View.ActionProvider+ISubUiVisibilityListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.ActionProvider+IVisibilityListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.ActionProvider+IVisibilityListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.ActionProvider.IVisibilityListenerImplementor' will refer to 'Android.Support.V4.View.ActionProvider+IVisibilityListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.IOnApplyWindowInsetsListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.IOnApplyWindowInsetsListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.IOnApplyWindowInsetsListenerImplementor' will refer to 'Android.Support.V4.View.IOnApplyWindowInsetsListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.IViewPropertyAnimatorListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.IViewPropertyAnimatorListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.IViewPropertyAnimatorListenerImplementor' will refer to 'Android.Support.V4.View.IViewPropertyAnimatorListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.IViewPropertyAnimatorUpdateListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.IViewPropertyAnimatorUpdateListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.IViewPropertyAnimatorUpdateListenerImplementor' will refer to 'Android.Support.V4.View.IViewPropertyAnimatorUpdateListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : Duplicate managed type found! Mappings between managed types and Java types must be unique. First Type: 'Android.Support.V4.View.MenuItemCompat+IOnActionExpandListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'; Second Type: 'Android.Support.V4.View.MenuItemCompat+IOnActionExpandListenerImplementor, Xamarin.Android.Support.v4, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1668,3): warning : References to the type 'Android.Support.V4.View.MenuItemCompat.IOnActionExpandListenerImplementor' will refer to 'Android.Support.V4.View.MenuItemCompat+IOnActionExpandListenerImplementor, Xamarin.Android.Support.Compat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>    Processing: obj\Debug\res\layout\tabbar.xml
1>    Processing: obj\Debug\res\layout\toolbar.xml
1>    Processing: obj\Debug\res\values\styles.xml
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorCompatHelper;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorListenerCompat;
1>  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/v4/animation/AnimatorProvider;
1>  
1>  UNEXPECTED TOP-LEVEL EXCEPTION:
1>  java.lang.RuntimeException: Translation has been interrupted
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:608)
1>  	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:311)
1>  	at com.android.dx.command.dexer.Main.run(Main.java:277)
1>  	at com.android.dx.command.dexer.Main.main(Main.java:245)
1>  	at com.android.dx.command.Main.main(Main.java:106)
1>  Caused by: java.lang.InterruptedException: Too many errors
1>  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:600)
1>  	... 4 more
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1965,3): error : java.lang.IllegalArgumentException: already added :  Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat;
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 2 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

**Comment by jamesmontemagno** [comment]
Did you update ALL of your Support Libraries on android? https://blog.xamarin.com/mastering-android-support-libraries/

That is what is causing this. They all must be the same version number.

**Comment by nikkilocke** [comment]
It is not possible to update the Android support libraries. Attempting to do so gives the error message:
Could not install package 'Xamarin.Android.Support.Animated.Vector.Drawable 26.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by nikkilocke** [comment]
P.S. All the Android packages are the same version - 23.3.0

**Comment by jamesmontemagno** [comment]
Change your compile target and read through the link i sent. You MUST use Version 25+ and compile against SDK 25 to use this library.

**Comment by nikkilocke** [comment]
Thanks for the helpful support. I think my problem was that clicking the update button tried to update to v26.0.2, which does not seem to be compatible with any of the choices on the Android build and target menus. I have now upgraded everything individually to 25.4.0.2, and I get some new error messages:
1>    Processing: C:\Dev\DefectReport\DefectReport\DefectReport.Android\obj\Debug\__library_projects__\Xamarin.Android.Support.Transition\library_project_imports\res\values\values.xml
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(2): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(3): error APT0000:  Error: No resource found that matches the given name: attr 'colorAccent'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'colorPrimary'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'windowActionBar'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(4): error APT0000:  Error: No resource found that matches the given name: attr 'windowActionModeOverlay'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(2): error APT0000:  Error: No resource found that matches the given name: attr 'windowNoTitle'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(4): error APT0000:  Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.Dialog'.
1>C:\Dev\DefectReport\DefectReport\DefectReport.Android\Resources\values\styles.xml(4): error APT0000:  Error: No resource found that matches the given name: attr 'colorAccent'.
3

**Comment by nikkilocke** [comment]
Which I have now solved by deleting the contents of %USER%\AppData\Local\Xamarin and doing rebuild all.

Thanks again for the help and unpaid support. Anything I can do for you, just ask (donations?).

**Comment by jamesmontemagno** [comment]
:)

I do have sample apps on Android/UWP you can leave tips in: https://github.com/jamesmontemagno/xamarin.plugins But not necessary at all.
