### ISSUE TITLE
How can I switch take photo or record video after launch camera.

### ISSUE THREAD

**Issue by Ying1986** [jamesmontemagno/MediaPlugin#38]
https://github.com/XLabs/Xamarin-Forms-Labs/issues/1208

I hope to implement above function.

When use this library, I have to make two menu for camera function, such as **Launch Camera** (photo, video).

**Comment by jamesmontemagno** [comment]
iOS only has either or, not both for the UIImagePickerController.

**Comment by Ying1986** [comment]
@jamesmontemagno 
don't close this issue.

In fact it is possible with UIImagePickerController, you can see if **MediaType** not specified.

Please reference **Camera** app on iPhone.

I implement on iOS with my own code, but I want to with library.
