### ISSUE TITLE
[Feature Request]  Set camera flash default

### ISSUE THREAD

**Issue by Philyorkshire** [jamesmontemagno/MediaPlugin#380]
I have already done this on a local version for a project I am working on, will just need to update my fork and create a PR if the feature is accepted...

It would be nice to have in the main library a way to set the flash mode;

FLASH_ON - camera opens with flash set on
FLASH_OFF - camera opens with flash set off
DEFAULT - determined by the device/platform from the last time they opened the camera usually

My current implementation looks like so when creating the camera;

`var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    DefaultCamera = CameraDevice.Rear,
                    FlashMode = CameraMode.FLASH_ON,
                    PhotoSize = PhotoSize.Large,
                    SaveToAlbum = false,
                    Directory = "Example",
                    Name = $"{DateTime.Now:yyyyMMddTHHmmss}-analysis.jpg"
                });
`

**Comment by jamesmontemagno** [comment]
Send a fork down and then link to this. 

II can adjust the enums, but they should be:
```
public enum CameraFlash
{
Default
On
Off
}
```

**Comment by Philyorkshire** [comment]
Yeah sounds good, assign to me and I will send a fork PR

**Comment by jamesmontemagno** [comment]
done :)

**Comment by Philyorkshire** [comment]
Thanks, I am working on this. Just taking a little longer as I am working on getting it working for UWP - which the docs seem a little scarce in how to set the flash.

**Comment by Krumelur** [comment]
@Philyorkshire Is this still being worked on? If not, can you maybe provide what you have done so far?

**Comment by Philyorkshire** [comment]
@Krumelur I couldn't find out for the life of me how to do it with UWP and got stuck... will create a branch on my fork soon and send a link

**Comment by VivianTio** [comment]
Hi, does this function able to put in to the code already?

**Comment by Osmosis311** [comment]
@Philyorkshire @jamesmontemagno any update on this one? would love to have it.  thanks for the efforts here!!!

**Comment by joben12** [comment]
@Philyorkshire @jamesmontemagno any update on this?, anyway we can help? would love to have this one.

**Comment by jamesmontemagno** [comment]
No new features.
