### ISSUE TITLE
[iOS] Popup message with "Don't allow. OK." text appears twice.

### ISSUE THREAD

**Issue by fabasoad** [jamesmontemagno/MediaPlugin#383]
## Bug Information

- Version Number of Plugin: **3.0.2.129-beta**
- Device Tested On: **iPhoneSix+**
- Version of VS: **Professinal 2017**
- Version of Xamarin: **4.5.0.476 (1be4f0c)**
- Versions of other things you are using:
  - Xamarin.iOS and Xamarin.Mac SDK: **10.10.0.35 (4cffddf)**
  - iOS version: **11.0.3**

### Steps to reproduce the Behavior

1. Run application very first time.
2. Run the code snippet.
3. Message _"My Application Would Like to Access the Camera. Don't Allow. OK."_ appears.
4. Click _"OK"_.

### Expected Behavior
I see the camera to be able to take a photo.

### Actual Behavior
The same message appears again. And I see the camera only when I click _"OK"_ again.

### Code snippet
`var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions { Directory = "TestFolder", Name = "SomeName" });`

**Comment by jamesmontemagno** [comment]
Can you past all of the permissions you have listed in the info.plist for me.

**Comment by prashantvc** [comment]
@fabasoad I am not able to reproduce this on iPhone SE running iOS 11
Could you share the details James asked in ^ comment?

**Comment by fabasoad** [comment]
@jamesmontemagno @prashantvc regarding camera only this:
`<key>NSCameraUsageDescription</key>
<string>My Application Would Like to Access Phone Camera</string>`

**Comment by jamesmontemagno** [comment]
do you have other ones in there that say the same things?

It is literally impossible for iOS to pop up the dialog twice. Perhaps the camera app had never had permissions requested?

**Comment by fabasoad** [comment]
I've downloaded the latest _3.0.2.175-beta_ build today and this bug isn't reproduces with it. So, I think this issue might be closed. Thanks!
