### ISSUE TITLE
My app is crashing while uploading image

### ISSUE THREAD

**Issue by ShahriatHossain** [jamesmontemagno/MediaPlugin#385]
I am trying to upload image file using my android version 6 samsung j7 and my app is crashing and getting such error:

11-02 09:49:39.291 E/libEGL  (24738): HWUI Context(-198675520) Damaged Report-Shader
11-02 09:49:39.291 E/libEGL  (24738): HWUI   Shaders(5):
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 0) Handle(7)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 1) Handle(9)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 2) DAMAGED Handle(11)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 3) Handle(17)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 4) Handle(19)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libGLESv2(24738): HWUI Protection: wrong calling from app context F:ES2-glDeleteShader, handle(11)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libEGL  (24738): HWUI Context(-198675520) Damaged Report-Shader
11-02 09:49:39.291 E/libEGL  (24738): HWUI   Shaders(5):
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 0) Handle(7)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 1) Handle(9)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 2) Handle(11)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 3) DAMAGED Handle(17)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 4) Handle(19)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libGLESv2(24738): HWUI Protection: wrong calling from app context F:ES2-glDeleteShader, handle(17)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libEGL  (24738): HWUI Context(-198675520) Damaged Report-Shader
11-02 09:49:39.291 E/libEGL  (24738): HWUI   Shaders(5):
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 0) DAMAGED Handle(7)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 1) Handle(9)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 2) Handle(11)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 3) Handle(17)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 4) Handle(19)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libGLESv2(24738): HWUI Protection: wrong calling from app context F:ES2-glDeleteShader, handle(7)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libEGL  (24738): HWUI Context(-198675520) Damaged Report-Shader
11-02 09:49:39.291 E/libEGL  (24738): HWUI   Shaders(5):
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 0) Handle(7)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 1) DAMAGED Handle(9)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 2) Handle(11)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 3) Handle(17)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 4) Handle(19)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libGLESv2(24738): HWUI Protection: wrong calling from app context F:ES2-glDeleteShader, handle(9)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libEGL  (24738): HWUI Context(-198675520) Damaged Report-Shader
11-02 09:49:39.291 E/libEGL  (24738): HWUI   Shaders(5):
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 0) Handle(7)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 1) Handle(9)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 2) Handle(11)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 3) Handle(17)
11-02 09:49:39.291 E/libEGL  (24738): HWUI     Unit 4) DAMAGED Handle(19)
11-02 09:49:39.291 E/libEGL  (24738): ------------------------------------------------
11-02 09:49:39.291 E/libGLESv2(24738): HWUI Protection: wrong calling from app context F:ES2-glDeleteShader, handle(19)
11-02 09:49:39.291 D/libEGL  (24738): eglTerminate EGLDisplay = 0xd9e5e834
11-02 09:49:39.591 D/Mono    (24738): Assembly Ref addref System.Xml[0xf3526d60] -> System[0xf3525ce0]: 13

Can any one please give any solution.

**Comment by prashantvc** [comment]
@ShahriatHossain Where are you uploading the image to? Could you share more information?
I don't think issue has anything to do with the Media plugin
