### ISSUE TITLE
Xamarin Forms UWP TakePhotoAsync "Saving a copy..." Camera Modal Doesn't Dismiss 

### ISSUE THREAD

**Issue by aherrick** [jamesmontemagno/MediaPlugin#386]
Have a simple UWP app where I'm taking a picture using the plugin.

I'm calling into a helper method to generate the photo and upload it. That is working fine and my photo gets posted to my backend.

However, the camera modal never disappears. It simply gets stuck at "Saving a copy..." 

Is there a certain way I need to dismiss the camera in UWP? I don't have this issue in iOS or Android.

Below is the basic code for context:

            var tbCamera = ToolBarHelper.GenerateToolbarButton("Camera", new Command(async () =>
            {
                var photo = await CameraHelper.GetPhoto();
                await App.AppService.UploadPicture(photo);
            }));
            ToolbarItems.Add(tbCamera);

![2017-11-02_9-37-57](https://user-images.githubusercontent.com/586671/32328958-f2d9308a-bfb1-11e7-9b2b-8e6c28b46a45.png)

**Comment by jamesmontemagno** [comment]
I am not able to reproduce this at all. UWP pops up the dialog and there is no further interaction from the app. Perhaps a windows bug.

**Comment by aherrick** [comment]
@jamesmontemagno thanks for the response. What version of Win10 are you on? I'm on Fast 17025.

I'm assuming you are just testing with the Sample application? I can give that a go.

**Comment by jamesmontemagno** [comment]
I use stable Windows. That is the only version I support when developing plugins. I would check with others as nothing has changed and only Windows has.

**Comment by aherrick** [comment]
Sounds good thank you!

**Comment by jamesmontemagno** [comment]
feel free to grab the code and debug it though, UWP code is pretty simple

**Comment by aherrick** [comment]
I'd love to but am running into another Windows/Forms issue with 17025 where UWP won't debug. :laughing:

Perhaps I should just go back to Win stable lol... Will keep this thread posted though. :smile:
