### ISSUE TITLE
Capture Camera- filpath OK .. but only 800bytes on disk

### ISSUE THREAD

**Issue by StanleyBroo** [jamesmontemagno/MediaPlugin#388]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: CAT s41 shared internal storage
Version of VS: 2017 enterprise
Version of Xamarin: forms 2.4.0 stable

### Steps to reproduce the 
Set returned image option to maxwidth 1024px
Compression 70%

Launch camera at 13M size
Zoom the photo
Take picture

### Expected 
file saved on disk
### Actual Behavior
Only 800 bytes saved on disk (no real image data)

If not zooming the picture the file is saved
If setting the returned image size to Max 640px ...only 800bytes is saved. So it looks like a image is saved ..but the image file is corrupted and not saved entirely

**Comment by StanleyBroo** [comment]
Normal behavior on all other devices is that the photo is saved in the app data picture folder. However on CAT s41 the full image is also saved in camera folder.
Also noticed out of memory crashes in these devices but not the normal consumer phones (lg, samsung all sorts just works)
Dont know What CAT s41 has it says 7.0 but looks like lollipop. This is a completly
new Phone from Bullit Group..which I assume gonna be a popular one amongst the ones who need a rugged Phone

**Comment by jamesmontemagno** [comment]
Have you tried without any compression?

**Comment by jamesmontemagno** [comment]
Closing as I can't fix specific issues with devices
