### ISSUE TITLE
Can "Take picture" be tested on emulator? It throws an error while I try to do so

### ISSUE THREAD

**Issue by tanvi2504** [jamesmontemagno/MediaPlugin#389]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
Android it depends on if you have it configured and iOS no
