### ISSUE TITLE
Photo taken from camera rotates to wrong direction

### ISSUE THREAD

**Issue by akamud** [jamesmontemagno/MediaPlugin#39]
## Bug 
Taking a photo from camera rotates the image to the wrong direction.

Version Number of Plugin: `2.4.0-beta2` and `2.4.0-beta3`
Device Tested On: Motorola XT890
Simulator Tested On: VS Emulator for Android - 5.7'' Marshmallow (Android 6.0) - Similar to Samsung Galaxy Note 4

### Expected Behavior
Image should be on the same orientation as shown while using the camera

### Actual Behavior
Image gets rotated 90º CCW

### Steps to reproduce the Behavior
Take a photo from camera and show it in an `Image` from Xamarin Forms

**Comment by jamesmontemagno** [comment]
VS Emulator has issues as it actually adds borders around the image. So the logic rotates it. On a device I haven't had any issues. Please download the tests and run through the code.

**Comment by jamesmontemagno** [comment]
Can you test out: 2.5.1-beta35, seeing great results here with new logic.
