### ISSUE TITLE
[iOS] PickVideoAsync returns media file rotated by 90°

### ISSUE THREAD

**Issue by fabasoad** [jamesmontemagno/MediaPlugin#392]
## Bug Information

- Version Number of Plugin: **3.0.2.175-beta**
- Device Tested On: **iPhone SE**
- Version of VS: **Professional 2017**
- Version of Xamarin: **4.5.0.476 (1be4f0c)**
- Versions of other things you are using:
  - iOS version: **11.0.3**
  - Xamarin.iOS and Xamarin.Mac SDK: **10.10.0.35 (4cffddf)**

#### Pre-conditions
Create a video using a camera in a portrait mode before starting the test

#### Steps to reproduce
1. Run the code snippet
2. Choose created video

### Expected Behavior
Video should be in a portrait mode

### Actual Behavior
Video in a landscape mode (rotated by 90°)

### Code snippet
`var video = await CrossMedia.Current.PickVideoAsync();`

**Comment by tylerhartwig** [comment]
We found similar issues today with PickPictureAsync().

Oddly enough, when giving permission to select photos, the picture is returned with the correct orientation. After this however, it is returned rotated. 

Plugin Version: 3.0.1
Device Tested: iPhone 7 (physical device)
iOS version: 11.0
Xamarin.iOS: 11.2.1.0

**Comment by benevbright** [comment]
I faced the same issue when I pick a photo from the library. (iOS)
It didn't happen before.

And I think the hint might be that the photo took a little bit time because it's in the iCloud Library.

The problem is that some photo is rotated incorrectly and some are not.
