### ISSUE TITLE
Application does not resume after calling CrossMedia.Current.TakePhotoAsync (Windows Phone)

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#4]
_From @pauldiston on June 9, 2016 15:6_

Please take a moment to fill out the following (change to preview to check or place x in []) and remove all unused areas

This is a 
- [x] Bug

Which plugin does this impact:
- [x] Media

## Bug

Version Number of Plugin: 2.3.0
Device Tested On: Microsoft Lumia 640

### Expected Behavior
Application should resume after calling CrossMedia.Current.TakePhotoAsync

### Actual Behavior
After calling CrossMedia.Current.TakePhotoAsync, and accepting the taken image, the Resuming... message appears on the phone however the next line after calling TakePhotoAsync is never called. In release mode, the application will crash.
### Steps to reproduce the Behavior
1. Call CrossMedia.Current.TakePhotoAsync
2. Accept taken photo
3.Notice that the application doesn't resume

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#326_

**Comment by pauldiston** [comment]
The underlying issue seems to be filled on Bugzilla :-
https://bugzilla.xamarin.com/show_bug.cgi?id=41076

I have tested this and can confirm that on XF version 2.3.1.111-pre2, the app will resume, as expected, after the TakePhotoAsync method is invoked and the photo is captured.

**Comment by jamesmontemagno** [comment]
^ Via this will close out.
