### ISSUE TITLE
TakePhotoAsync is not working in Media Plugin

### ISSUE THREAD

**Issue by SureshbabuLucky** [jamesmontemagno/MediaPlugin#400]
Hi All,

Xam.Plugin.Media Plugin is working fine up to yesterday but now I am facing the problem to take the photo from the camera is not working.

 MediaFile File= await CrossMedia.Current.TakePhotoAsync(
            new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "MediaPluginPhoto",
                Name = DateTime.Now + ".jpg",
                DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Front,

            });

Here I am getting Null value and unable to open camera in my app.
I am already given permissions for camera in androidmanifest.xml

Please help me get out of this issue
Thanks in Advance

**Comment by jamesmontemagno** [comment]
Ask yourself what changed between yesterday and today if it magically stopped working.

This is not enough info at all.
