### ISSUE TITLE
Way to ask for permission again from user for iOS device if denied once

### ISSUE THREAD

**Issue by ravikanasagra1** [jamesmontemagno/MediaPlugin#403]
This is an issue continuation to defect 383 [https://github.com/jamesmontemagno/MediaPlugin/issues/383]

Visual Studio 2015 Professional
IOS 10.2
Plugin version - 3.0.2.188-beta

On first time user would be asked to "Allow" or "Don't Allow". On first time user, selects "Don't Allow" by mistake. So, he would get error pop up from next time that permission denied. 

Could we have some way (like some plugin method) using which I could ask for permission again by pop up having allow and not allow with message explaining reason why permission needs to allowed in case of permission denied case.

**Comment by jamesmontemagno** [comment]
It is impossible on iOS you must do your own pop up and then direct them to settings
