### ISSUE TITLE
Front Camera always launches first

### ISSUE THREAD

**Issue by denmusic1992** [jamesmontemagno/MediaPlugin#405]
I'm trying to use the lib for adding some photos in my app.
I need to use rear camera of my device, but when i call "TakePhotoAsync", the front camera appears.
The code:
`var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "ISSO-S",
                    DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
                    MaxWidthHeight = 1280,
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.MaxWidthHeight,
                    Name = String.Format("IMG_{0}.jpg", DateTime.Now.ToString("yyyyMMdd_HHmmss")),
                });`
As you can see, I have a parameter "DefaultCamera", but it doesn't work.
My testing phone is Asus Zenfone3, Android 7.0..
So what is the issue? Can you help me?

**Comment by jamesmontemagno** [comment]
There is no guarantee on android and default to whatever the user used last on some devices.
