### ISSUE TITLE
Quality.Medium,CameraDevice.Front,Directory = "Videos"  are not working on Android while using TakeVideoAsync.

### ISSUE THREAD

**Issue by vivekshah-zymr** [jamesmontemagno/MediaPlugin#406]
Hello,

I am using media plugin for recording a video for iOS and Android. And I want to set `Quality = VideoQuality.Medium`, for that. But In case of android device Quality set to Medium gives the result the same as Quality set as High. Other than that `DefaultCamera = CameraDevice.Front` is not opening front camera by default on android(Working fine with iOS). And also video doesn't save on gallery.

## Bug Information

Version Number of Plugin: 3.0.3
Device Tested On: Moto G5 / Honor 6X (works fine on iPhone 6s)
Simulator Tested On: NA
Version of VS: 7.2.2

### Steps to reproduce the Behavior
In Android,  I am recording video using below code. But the quality of the video is same as High even if I used Medium, and the video is not even stored in Gallary.
```
var file = await CrossMedia.Current.TakeVideoAsync(new Plugin.Media.Abstractions.StoreVideoOptions
            {
                DefaultCamera = CameraDevice.Front,
                Directory = "Videos",
                SaveToAlbum = true,
                Name = filename,
                Quality = VideoQuality.Medium,
            });
```

### Expected Behavior
The video quality should be different then the High, and video should be stored in the gallery. The video should be saved in the gallery. And front camera should be open by default.

### Actual Behavior
The video is not saving in the gallery, rear camera open by default and quality of the video is High instead of Medium.

### Requirement
I want to record video of 3 min approx but size goes much higher than 300 MB, how can I record 3 min video with medium quality and around 100 MB.

**Comment by jamesmontemagno** [comment]
Yes, unfortunately these are not supported officially by all camera apps on Android. The info is sent in the intent, but not guaranteed
