### ISSUE TITLE
Orientation EXIF metadata never returned by MediaPlugin on Xamarin.iOS

### ISSUE THREAD

**Issue by aaronclausen** [jamesmontemagno/MediaPlugin#407]
## Bug Information

Version Number of Plugin:
3.0.1

Device Tested On:
iPhone 7 (via MacBook Pro build host)

Simulator Tested On:
None - real iPhone 7 only

Version of VS: 
VS 2017 (15.4.4)

Version of Xamarin:
4.7.10.38 and Xamarin.iOS SDK 11.3.0.47

### Steps to reproduce the Behavior
 - Select an existing image from the iPhone Gallery using MediaPlugin
 - Load the image either from the returned "GetStream()" contents or by loading from the physical "Path" location.
 - Use ExifLib to then read the EXIF Orientation value
 - Observe: value is always 0 and actual Orientation values in original source image are never returned
![img_7239](https://user-images.githubusercontent.com/3827163/33225718-5699336e-d1d1-11e7-8597-f158d677edd3.jpg)

### Expected Behavior
I should be able to read EXIF Orientation values from the resulting GetStream() contents as well as the resulting image that resides at the "Path" location. Latitude, Longitude, Altitude are successfully returned, I expect Orientation to also be returned.

### Actual Behavior
When reading the resulting GetStream() image or the loaded in image from "Path", the EXIF Orientation value is ALWAYS set to 0. I never receive other Orientation values, despite them definitely existing in the image that I selected. Therefore, I can't correctly rotate selected images for display in UIImageViews, because I have no Orientation value to use.

### Code snippet
I am selecting the image using this:

            if (CrossMedia.Current.IsPickPhotoSupported)
            {
                var mediaOptions = new Plugin.Media.Abstractions.PickMediaOptions
                {
                    RotateImage = false
                };

                resultingPhoto = await CrossMedia.Current.PickPhotoAsync(mediaOptions);
            }

Then I am trying to read the Orientation value using this:

                        ushort RawOrientation = 0;
                        reader.GetTagValue<ushort>(ExifTags.Orientation, out RawOrientation);
                        Orientation = Convert.ToInt32(RawOrientation);

### RotateImage = true
When I change the parameter to RotateImage = true, I would then expect the MediaPlugin to rotate the image for me correctly as well, even if it still returns Orientation=0 in EXIF metadata. However, the image is not rotated with this option enabled. Therefore it seems like the MediaPlugin has no visibility of the original Orientation value of my selected gallery image.

### Example Image Attached
Attached is an offending test image from my photo gallery that has a Orientation value of 3.
When selected by the MediaPlugin, I am getting Orientation=0 returned, the result is that the image is always displayed upside down as I don't know to rotate it according to Orientation=3.

**Comment by jamesmontemagno** [comment]
Did you try latest beta? I think it is fixed there already.

**Comment by aaronclausen** [comment]
I can confirm it's fixed in the beta! Thanks heaps James!!! I'm up and running now.. Yay!!!!!!

**Comment by hyprstereo** [comment]
(Xamarin, iOS) 
Hi, the orientation issue seems to appear when i set 'AllowCropping = true', it only works when it's set to false.

**Comment by jamesmontemagno** [comment]
Can you open a new bug @hyprstereo ?
