### ISSUE TITLE
When using PickPhotoAsync with PhotoSize option - photo is overwritten inside the gallery.

### ISSUE THREAD

**Issue by milena23** [jamesmontemagno/MediaPlugin#408]
## Bug Information

Version Number of Plugin: 3.0.2.188-beta, 3.0.1
Device Tested On: Xiaomi Redmi 4, Redmi 4 Pro
Simulator Tested On: -
Version of VS: Community 15.4.4
Version of Xamarin: 4.7.10.38 (Xamarin Forms 2.5.0.91635)

### Steps to reproduce the Behavior
Use PickPhotoAsync with PickMediaOptions PhotoSize.

### Expected Behavior
Returned image has reduced size, initial image in gallery is not changed.

### Actual Behavior
Initial image in gallery has reduced size.

### Code snippet
`await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                CompressionQuality = 50,
                PhotoSize = PhotoSize.Medium,
            });`

It seems to be a device specific thing, as Sumsung device works as expected.

**Comment by prashantvc** [comment]
@jamesmontemagno any thoughts on how this should work?

**Comment by jamesmontemagno** [comment]
it shouldn't override the existing, and pretty sure that is impossible as it has copied it locally by then.

**Comment by jamesmontemagno** [comment]
Since it is device specific there is really nothing that I can fix or do about it. So closing this. But feel free to investigate and send a pr
