### ISSUE TITLE
iOS 11 Photos Access Permission

### ISSUE THREAD

**Issue by mdcso** [jamesmontemagno/MediaPlugin#409]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 6s (iOS version 11.0 and above)
Simulator Tested On: NA
Version of VS: 7.2.2
Version of Xamarin: 
Versions of other things you are using:

1. iOS UiImagePickerController(11.0) does not need an implicit permission to access a single photo from photos. 
2. where as iOS UiImagePickerController(10.0)/ PHPhotoLilbrary still needs the same
3. Here in Crossmedia, we called implicitly called photolibrary. requestAuthorization which in turn called photos access permission after the user pick the photo already.
4. even if user chooses, dont allow is permission alert, the photos will still get displyed.

### Steps to reproduce the Behavior
1. CrossMedia.Current.PickPhotoAsync shows the permission popup, even in iOS 11 where it is not needed.
2. even in case permission is needed, user should not be able to select the image until the permission is given.

**Comment by prashantvc** [comment]
Yup, this is a bug. 

In iOS 11, UIImagePickerController runs as a separate process from the app. The app can't see the whole Photos library instead it gets read-only access for the selected image.

Thanks for reporting the bug :)

NOTE: We can reproduce this issue in the `samples/MediaSample.sln`

**Comment by jamesmontemagno** [comment]
I assume this is the same for vidoes....

**Comment by uwiedemann** [comment]
We are seeing this behaviour with the most recent version of MediaPlugin/MediaSample with **iOS 12**:

Version Number of Plugin: 4.0.1.5
Device Tested On: iPhone XR, iPhone X
Simulator Tested On: iPhone 8
Version of VS: 2019 for Mac (8.0.6 (build 4))
Version of Xamarin: 3.6.0.344457

![Simulator Screen Shot - iPhone 8 - 2019-05-20 at 20 16 59_framed](https://user-images.githubusercontent.com/30995269/58043483-8f5d7900-7b3d-11e9-985e-86f6be62c7ad.png)

Could anybody confirm this?

**Comment by uwiedemann** [comment]
@jamesmontemagno Seems like an old bug has come out again... Or am I doing something wrong?
