### ISSUE TITLE
Localisation support

### ISSUE THREAD

**Issue by rsseurope** [jamesmontemagno/MediaPlugin#41]
## Feature Request:
It would be nice if we could change the description of "Cancel", "Take photo", "Use photo" and "Retake" so it can match the app's language.

**Comment by jamesmontemagno** [comment]
These aren't hard coded in the app anywhere.

**Comment by JelleDamen** [comment]
For some reason the text is in english only (on iOS at least) if I take a picture on a dutch device, it still says: "Cancel". Where can I look to fix this ?

**Comment by jamesmontemagno** [comment]
See: https://stackoverflow.com/questions/8258391/how-do-i-localize-uiimagepickercontroller/8268438

**Comment by JelleDamen** [comment]
Thanks!
