### ISSUE TITLE
Cancel camera causing app to crash

### ISSUE THREAD

**Issue by JMumford123** [jamesmontemagno/MediaPlugin#411]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.0.1.0
Device Tested On: One+ five
Simulator Tested On: Android
Version of VS: 2017 Community
Version of Xamarin: forms 4.7
Versions of other things you are using: N/A

### Steps to reproduce the Behavior

Open Camera, calling TakePhotoAsync from OnAppearing and clicking cancel to exit.

### Expected Behavior

Returns to page

### Actual Behavior

App crashes gets put into breakMode "an unhandled exception occured"

### Code snippet

```
protected override void OnAppearing()
        {
            base.OnAppearing();
            await LoadCamera();
        }
        private async void LoadCamera()
        {
            await CrossMedia.Current.Initialize();
            if (!CrossMedia.Current.IsCameraAvailable
          || !CrossMedia.Current.IsTakePhotoSupported)
            {
                await DisplayAlert("No Camera", ":( No camera is available", "OK");
                return;
            }
            var file = await CrossMedia.Current.TakePhotoAsync(
                new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "uploads",
                    Name = "test.jpg"
                }
                );
            if (file == null)
                return;

            _img.Source = ImageSource.FromFile(file.Path);
            _btnSubmit.IsVisible = true;
            file.Dispose();
        }
    }

```

### Screenshots

N/A

**Comment by jamesmontemagno** [comment]
You should try/catch the call to take a photo and see what the exception is saying.

**Comment by excellapay** [comment]
I am seeing the same issue. Running on IOS 11.2.1

**Comment by jamesmontemagno** [comment]
I am in no way able to reproduce this on iOS or Android. Tested on my Galaxy 7 and iPhone 6.

I even added a test app in tests/PopUpMediaCamera

works great.

**Comment by tjheckler** [comment]
I was receiving the same error "object reference not set to an instance of an object" when canceling "take photo", I put it in a try catch block to get error, but, just changed the error to a custom message saying photo was canceled so it doesn't crash the app. using android 7.0 emulator, iPhone x max and iPhone 6, iOS 12.3xx

**Comment by tjheckler** [comment]
takePhoto.Clicked += async (sender, args) =>
            {
                try
                {
                    await CrossMedia.Current.Initialize();

                    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                    {
                        await DisplayAlert("No Camera", ":( No camera available.", "OK");
                        return;
                    }


                    var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                    {
                        SaveToAlbum = true,
                        PhotoSize = PhotoSize.Custom,
                        CustomPhotoSize = 50, //Resize to 50% of original
                        CompressionQuality = 92,
                        AllowCropping = true


                    });

                    //Get the public album path
                    var aPpath = file.AlbumPath;

                    //Get private path
                    var path = file.Path;


                    if (file == null)
                        return;

                    await DisplayAlert("File Location", file.Path, "OK");

                    image.Source = ImageSource.FromStream(() =>
                    {
                        var stream = file.GetStream();
                        return stream;
                    });
                    Image = file;
                    image.IsVisible = true;
                }
                catch(Exception ex)
                {
                    await DisplayAlert("Canceled", "Photo Canceled" , "OK");
                }
            };
