### ISSUE TITLE
Window background visible while choosing image in gallery in Android

### ISSUE THREAD

**Issue by georgethms10** [jamesmontemagno/MediaPlugin#412]
While choosing photos from gallery using the plugin, the the window background is shown for a second 

Version Number of Plugin: 3.0.1 
Device Tested On: Samsung gallery s8 , Samsung galaxy s6 edge
Version of VS:  7.2.2 build 11
Version of Xamarin: Xamarin forms: 2.3.4.270

### Reproduce steps
1. Try to choose a picture from gallery. 
2. If you have given window background in App theme in styles.xml then that screen is flashed before our page is shown with the selected image

### Expected Behavior
It should not show the window background while choosing picture from gallery in Android
### Actual Behavior
Its shows the window background while choosing image from gallery in Android

**Comment by prashantvc** [comment]
@georgethms10 Is this specific to Samsung Device? Could you share sample project to demonstrate the problem? It will help us to troubleshoot the issues

**Comment by jamesmontemagno** [comment]
This is a bit out of my control as I launch the activity which then prompts for it. Seems to be specific to Samsung as I see it on my S7, but not Nexus
