### ISSUE TITLE
iOS - Crash on PickPhotoAsync when user taps outside the popover

### ISSUE THREAD

**Issue by EdHubbell** [jamesmontemagno/MediaPlugin#413]
## Bug Information

Version Number of Plugin: 3.0.2.188-beta
Device Tested On: iPad Air iOS 11.1.2
Simulator Tested On: none
Version of VS: for Mac 7.2.2 (build 11)
Version of Xamarin: Xamarin Forms 2.50.91635
Versions of other things you are using:

### Steps to reproduce the Behavior
Execute code that launches CrossMedia.Current.PickPhotoAsync. Tap outside the popover area and have the popover disappear.

### Expected Behavior
Keep on truckin'. 

### Actual Behavior
App crashes with System.ObjectDisposedException - Cannot access a disposed object. Object name: 'MediaPickerController'

**Comment by duzenko** [comment]
Same here

**Comment by duzenko** [comment]
I still get them in debugger even though it does not cause app crashes.
