### ISSUE TITLE
Impossible to install the Nuget on Android 

### ISSUE THREAD

**Issue by CJACQUEL** [jamesmontemagno/MediaPlugin#414]
Hello,

I was using version 2.6.1 
But when I want to move to version 3.0.1 its impossible to install the nuget on Android.

Could you help ? 
Thank you,
cjacquel

**Comment by jamesmontemagno** [comment]
What error is nuget giving you? Did you set your compile against version to 6.0+?

**Comment by CJACQUEL** [comment]
Hello, 
The nuggets has been installed
But I have the message : Media does not contains definition for Abstraction and Crossmedia.
My customers have Android 8.
Thx,
cjacquel,

**Comment by jamesmontemagno** [comment]
Did you install the nuget into all of your projects. Also be sure to do a clean and rebuild.
