### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by attrib75** [jamesmontemagno/MediaPlugin#415]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On:  IPhone ai586
Simulator Tested On: n/a
Version of VS: 2017 community 15.5
Version of Xamarin: 4.8.0
Versions of other things you are using:
Plugin.Permissions 2.1.0
Plugin.Connectivity 3.0.3
Plugin.DeviceInfo 3.0.2
Plugin.Geolocator 4.1.3
Plugin.Settings 3.1.1

### Steps to reproduce the Behavior
Invoke CrossMedia.Current.TakePhotoAsync() several (3 or more) times

detailed here: https://stackoverflow.com/questions/47757015/xam-plugin-media-too-many-open-files

### Expected Behavior
get bytes from file, dispose file, be able to call again

### Actual Behavior
receive exception 'too many open files' 

error occurs here:
 using (System.IO.Stream stream = file.GetStream())
 
### Code snippet
https://stackoverflow.com/questions/47757015/xam-plugin-media-too-many-open-files

**Comment by jamesmontemagno** [comment]
Unable to reproduce with my sample app. 

Took about 25 photos with no issues. It must just be something with your logic of streams and maybe not cleaning something up.

**Comment by attrib75** [comment]
Turns out it was trying to name the file dynamically to include the date time.  If I just named the file the same name, it works fine

**Comment by jamesmontemagno** [comment]
Can you show me the code snippet you were trying to use for the dates? it probably had illegal characters in it.

**Comment by attrib75** [comment]
$"photo{DateTime.Now.ToString("yyyyMMddHHmmss")}.jpg"
