### ISSUE TITLE
plugin.mediamanager can not play video 

### ISSUE THREAD

**Issue by yangwulong1978** [jamesmontemagno/MediaPlugin#416]
currently we are doing a xamarin.form  apps.

we are Using  plugin.media to record video, get the path in the returned File(mp4 file), and then use plugin.mediamanager to play video.
everytime try to play video,and the program crashes and throws below exception.

do you have any idea what this error it is ?
### Screenshots
![errormessage](https://user-images.githubusercontent.com/4809957/33912148-cd250e02-dfe8-11e7-86bb-6d8c8e821d84.png)

**Comment by jamesmontemagno** [comment]
I think this is something else. Would recommend opening an issue on the mediamanager github project.
