### ISSUE TITLE
Take video not working in Android 4.4 KitKat version

### ISSUE THREAD

**Issue by mdcso** [jamesmontemagno/MediaPlugin#417]
When taking video on a kitkat android phone with Target Android version as 24 and above, the video is not getting created in the sample folder. While trying to open the file created in sample folder, it shows error as Cannot play video

**Comment by prashantvc** [comment]
Could you provide the following information? It will help us to troubleshoot the issue


## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### Code snippet

### Screenshots

**Comment by mdcso** [comment]
Tried taking video in the sample app with target android version as Android 7.0 or later (Api level 24). The recorded video is saved in the gallery of the device instead of saving in the app folder.
Version of Plugin : 3.0.1
Device: HTC One 
Version VS : 7.2.1 VS for Mac
Steps to reproduce the Behavior:
take a video  and save it from the sample app and then try to play the video going to the app folder using file explorer. 
Expected Behavior:
Video should be played.
Actual Behavior:
Only file with the name is getting created.

**Comment by jamesmontemagno** [comment]
I was not able to reproduce this with the sample on my S7.

I took a video. Went in to file explorer -> Android -> data -> com.plugin.mediatest -> files -> Movies -> DefaultVideos -> video.mp4 -> open in video player and played fine.

**Comment by mdcso** [comment]
Issue is reproducible only in Kitkat OS phones. We tested it in HTC one, running 4.4.4 Kitkat OS. In Samsung s7, its working fine.

**Comment by mdcso** [comment]
@jamesmontemagno : Is there any update on the above mentioned ticket.
