### ISSUE TITLE
Android Simulator: Failed to ensure (incorrect?) directory: /storage/sdcard/.../Pictures

### ISSUE THREAD

**Issue by Gantonator** [jamesmontemagno/MediaPlugin#418]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: No Real Devices
Simulator Tested On: Nexus 6 Android 5.0.1, Nexus 5 Android 4.4.2
Version of VS: 14.0.25431.01 Update 3
Version of Xamarin: 4.7.10.22 (fe36bec)
Versions of other things you are using:

### Steps to reproduce the Behavior
Attempt CrossMedia.Current.TakePhotoAsync on a pre Marshmallow android device.  (Possibly only on emulated devices).
I do definitely have the permissions in my androidmanifest.
![image](https://user-images.githubusercontent.com/18462104/34011625-90d00896-e108-11e7-9378-63926c28a41e.png)
I am also overriding OnRequestPermissionsResult in my MainActivity.
![image](https://user-images.githubusercontent.com/18462104/34011639-a429c148-e108-11e7-8e29-b28aac9d658c.png)

I'm also checking Permissions using your permissions plugin before taking a photo and finding storage permissions to be granted: 
![image](https://user-images.githubusercontent.com/18462104/34011851-771ce68e-e109-11e7-8265-a48fc515bf1a.png)

### Expected Behavior
An image file is stored in the local directory for the App.  In this case I would expect this to be in "/data/data/Coast.Android/files"

### Actual Behavior
The plugin attempts to store the image file in the directory "/storage/sdcard/Android/data/Coast.Android/files/Pictures" which does not exist on the device (at least on the emulated device).  The "/storage/sdcard/" directory does exist but is empty and so I see "Failed to ensure directory: /storage/sdcard/Android/data/Coast.Android/files/Pictures An unhandled exception occured."  I think this comes from MediaPlugin/src/Media.Plugin.Android/MediaPickerActivity.cs line 459 Environment.GetExternalStoragePublicDirectory(mediaType)?

When I use an emulated Nexus 6 Android with Android 6.0 I see that the image file is correctly saved in "/storage/emulated/0/Android/data/Coast.Android/files/Pictures/"

### Code snippet

Snippet: https://gist.github.com/Gantonator/25c735e9de0528ad0d004e12e830034e
Stack Trace: https://gist.github.com/Gantonator/515253d5c3616c9cf0cac87e567558ce

This error might be relegated to simulated devices?  I don't have any physical pre-Android 6.0 devices to test this on unfortunately.

Thanks

**Comment by jamesmontemagno** [comment]
This is most likely due to the file paths.xml not being setup correct or you are not manually setting your target version number.

**Comment by Gantonator** [comment]
I'm really sorry to do this.  I've been troubleshooting this for hours.

I have Target Android version and file_paths both exactly as you have recommended in the readme
![image](https://user-images.githubusercontent.com/18462104/34020421-0912523c-e12c-11e7-9617-a2e500501745.png)

![image](https://user-images.githubusercontent.com/18462104/34020445-290a7c9a-e12c-11e7-8921-705b2b997c41.png)

![image](https://user-images.githubusercontent.com/18462104/34020467-43df4168-e12c-11e7-959c-310810a98a3e.png)

Does anything stick out immediately?  Changing the content of file_paths.xml seems to have no effect on the error message so it probably is that but I can't see what I'm doing wrong.

Again, apologies.

**Comment by Gantonator** [comment]
I see the same error in your com.plugin.mediatest solution
https://gist.github.com/Gantonator/c97aca60630e04c0ef4c169d13619ffe

I have put it down to the emulators for now, though I do encounter it on all the combinations of Nexus 5,6,7 on Android 4.4.2 and 5.0 when using Google Apis

![image](https://user-images.githubusercontent.com/18462104/34021536-622eb026-e132-11e7-91dd-fb6144ccca83.png)

**Comment by jamesmontemagno** [comment]
What happens when you say SaveToAlbum = false?

**Comment by jamesmontemagno** [comment]
I ran you exact code in my mediaandroidtest test project from tests/Media.sln and it worked perfect on my Nexus 6 running 5.1.1 (physical device)

I also ran it on an emulator for 5.0.1:

![image](https://user-images.githubusercontent.com/1676321/34022506-835a7548-e0f4-11e7-8c75-e079c8d9e142.png)



Your exception is saying you don't have the permissions required even though your manifest is there, so not really sure.

**Comment by Gantonator** [comment]
**SOLUTION**

Sorry.  This was stupid.  For some reason AVD defaults to giving emulated devices 0mb of external storage.

![image](https://user-images.githubusercontent.com/18462104/34037743-da8013b8-e181-11e7-8437-a7e4cb27a11c.png)
