### ISSUE TITLE
Photo rotation in Android

### ISSUE THREAD

**Issue by wallacesantos** [jamesmontemagno/MediaPlugin#419]
When I take a photo on iPhone (a selfie, a.c.a) and I open this phone on Android device, this phote is displayed rotated to right 90º.

## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 7 (iOS 11.2.1) / Samsung Galaxy S5 Neo (Android 7.0)
Version of Xamarin: 7.3 (build 799)
Versions of other things you are using:
=== Visual Studio Enterprise 2017 for Mac ===

Version 7.3 (build 799)
Installation UUID: 4c9b86dd-2fe3-4bd4-92a5-dc41dcc0bae0
Runtime:
	Mono 5.4.1.7 (2017-06/e66d9abbb27) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504010007

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.0
	1.1.1
	1.0.4
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Versions:
	2.0.0
	1.0.3
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.0
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.2 (13772)
Build 9C40b

=== Xamarin.iOS ===

Version: 11.6.1.2 (Visual Studio Enterprise)
Hash: 6857dfcc
Branch: xcode9.2
Build date: 2017-12-04 21:20:41-0500

=== Xamarin.Android ===

Version: 8.1.0.24 (Visual Studio Enterprise)
Android SDK: /Users/wallacesantos/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		5.0 (API level 21)
		5.1 (API level 22)
		6.0 (API level 23)
		7.0 (API level 24)
		7.1 (API level 25)
		8.0 (API level 26)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 26.0.2
SDK Build Tools Version: 27.0.1

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.3.2
Hash: 461f09a
Branch: 1.3-release
Build date: Tue, 03 Oct 2017 18:26:57 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 4.0.0.214 (Visual Studio Enterprise)

=== Build Information ===

Release ID: 703000799
Git revision: df590420ea5bc681994baefff2eabdaad889fba9
Build date: 2017-12-05 09:23:45-05
Xamarin addins: 51068d6eaf3b6fb4fbc72b33cb869b0ebff04ec5
Build lane: monodevelop-lion-d15-5

=== Operating System ===

Mac OS X 10.13.2
Darwin 17.3.0 Darwin Kernel Version 17.3.0
    Thu Nov  9 18:09:22 PST 2017
    root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Internet of Things (IoT) development (Preview) 7.1

Xamarin.FFImageLoading 2.2.25
Xamarin.FFImageLoading.Forms 2.2.25

### Steps to reproduce the Behavior
1. Take a photo on IPhone
2. Upload to server
3. Download and open on FFImageLoading on Android

### Expected Behavior
The photo display in right position, not rotated.

### Actual Behavior
The photo is displayed on Android rotated 90º to right
Important: 
1. If I take a photo on Android, I don't see any problem, even making the opposite way
2. If I open the taken photo on iPhone, it opens normally (no rotate)

### Code snippet
This is the code used:
        /// <summary>
        /// Takes the photo.
        /// </summary>
		private async void TakePhoto()
        {
            await Camera.Current.Initialize();

            if (!Camera.Current.IsCameraAvailable || !Camera.Current.IsTakePhotoSupported)
            {
                await DisplayAlert("WiseShopper",
                                   AppResources.cameraNotAvailableMessage,
                                   "OK");
                return;
            }
            try
            {
                var file = await Camera.Current.TakePhotoAsync(new CamAbstractions.StoreCameraMediaOptions
                {
                    PhotoSize = CamAbstractions.PhotoSize.Small,
                    Directory = "WiseShopper",
                    DefaultCamera = CamAbstractions.CameraDevice.Front,
                    SaveToAlbum = true // This line crashes iPhone
                });

                if (file == null)
                    return;

                this._imageFile = file.Path;
                this.imageAvatar.Source = ImageSource.FromFile(file.Path);
            }
            catch (System.Exception ex)
            {
                ExceptionHelper exh = new ExceptionHelper(ExceptionType.None,
                                                          "Error while loading taking a photo on ProfileEditPage class.",
                                                          ex);
                exh.Source = "ProfileEditPage-TakePhoto";
                exh.LogException();
            }
        }
### Screenshots
![android](https://user-images.githubusercontent.com/27156947/34012365-dfcd4fb8-e0e9-11e7-8a0e-bb0bd5a1f25c.png)
![iphone](https://user-images.githubusercontent.com/27156947/34012461-39d219a8-e0ea-11e7-947d-08fa69198a3e.jpg)

**Comment by jamesmontemagno** [comment]
Fixed in beta

**Comment by dPritz** [comment]
Still having this issue in 3.1.2

**Comment by Padalingam** [comment]
Even i have this issue, when i capture the image in ipad and upload to the server later i viewed the same uploaded image in WPF project the image got rotated 180

**Comment by jamesmontemagno** [comment]
See https://github.com/jamesmontemagno/MediaPlugin/issues/438

**Comment by Padalingam** [comment]
Yes, It got fixed. I used iOS for stream. Thanks @jamesmontemagno. But i need to check from the server

**Comment by jamesmontemagno** [comment]
Realize that there is exif data that has how the image was stored by iOS itself, so you should be looking at that data.

**Comment by Padalingam** [comment]
Yes, I need to store the image locally, what i did for that, by using DI i stored it and send it to the server because i need to take consecutive images

**Comment by Padalingam** [comment]
@jamesmontemagno when i build the project i got the following error on Xamarin forms

/Users/*****/Projects/ProjectName/iOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.IO.Stream Plugin.Media.Abstractions.MediaFile::GetStreamWithImageRotatedForExternalStorage()', referenced from the method 'System.Void ProjectName.ClassName/<getureDetected>d__27::MoveNext()' in 'Plugin.Media.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (ProjectName.iOS)

Can you please help me around this

**Comment by jamesmontemagno** [comment]
You most likely are having a build issue on your machine
remove the nugets/re-added them.

You may have not updated all of them.

Also do a full clean/rebuild

**Comment by Padalingam** [comment]
I have created new branch. There, i rewrite the logic its works fine
