### ISSUE TITLE
Cannot access to media gallery but only to camera

### ISSUE THREAD

**Issue by sayed-seliman** [jamesmontemagno/MediaPlugin#421]
Hi,

how can I access to media gallery and not just to the camera?
I mean not to use the "TakePicture" but to show the "gallery" button inside the camera itself.

Thanks

**Comment by jamesmontemagno** [comment]
PickPhoto

**Comment by sayed-seliman** [comment]
Ok, but I want to open the camera and let the user able to access media gallery from there not with a specific call. How can I do this?

Do you have a code snippet?

**Comment by jamesmontemagno** [comment]
That would depend on the users' camera app they use. Plugin has no control over this.

**Comment by sayed-seliman** [comment]
But in every app I use I can access the gallery from the camera itself instead when using the plugin I cannot.

Il giorno 20 Dic 2017, 00:06, alle ore 00:06, James Montemagno <notifications@github.com> ha scritto:
