### ISSUE TITLE
[BUG]TakePhotoAsync Error with FileProvider naming

### ISSUE THREAD

**Issue by EnriqueEgremy** [jamesmontemagno/MediaPlugin#422]
## Bug Information

Version Number of Plugin: 3.1.1
Device Tested On: Motorola X Play
Version of VS for mac:  7.3.2

### Steps to reproduce the Behavior
Android package name to something, **"com.companyname.appname.13"**    <-- put a number at the end of the package name.
Put same name on the <provider> section inside the AndroidManifest.xml

### Expected Behavior

Open camera to take a photo.

### Actual Behavior

Crash with:  
Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference

### Code snippet

This is what i put inside my android manifest.

<provider android:name="android.support.v4.content.FileProvider" android:authorities=**"com.companyname.app_nameV2.13.fileprovider"** android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>

When i change the package name of my app to **"com.companyname.app_nameV2"** and change it inside the provider manifest to **"com.companyname.app_nameV2.fileprovider"** it works without problem.
I have a really dire issue with this, because my app its already on Google Play and i can't change the package name without erasing the old app and creating a new one.
I'm not sure if adding numbers at the end of the package name cause a parse problem at the moment of reading the photoUri in this line (162) of code in the MediaPickerActivity.cs.

var photoURI = FileProvider.GetUriForFile(this,																Application.Context.PackageName + ".fileprovider",new Java.IO.File(path.Path));

Thanks in advance.

**Comment by jamesmontemagno** [comment]
You can't have numbers in your package name:

https://stackoverflow.com/questions/34635067/numbers-in-package-name-android-studios
