### ISSUE TITLE
App crashes after tapping OK button, but not if first cancel and then OK again (observed only on Samsung Note 4 SM-N9100 with Android 6.0.1)

### ISSUE THREAD

**Issue by cbs-cbt** [jamesmontemagno/MediaPlugin#423]
## Bug Information

Version Number of Plugin: v3.1.1
Device Tested On: Samsung Note 4 SM-N9100 with Android 6.0.1
Simulator Tested On: works on other devices I tested on
Version of VS: Microsoft Visual Studio Professional 2017 Version 15.5.2
Version of Xamarin: Xamarin   4.8.0.753 (6575bd113)
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Start taking picture : tap on a button in my application that will run TakePictureAsync (see code below)
2. Tap the "camera" button (Android will show a preview of the picture with two button : OK / Cancel)
3. Tap the "OK" button
4. App crashes

### Expected Behavior
App doesn't crashes when tapping the "OK" button

### Actual Behavior
App crashes when tapping on "OK" button
The curious thing : if instead of "OK", user tap "cancel" and then retake the picture. Tapping then "OK" doesn't crashes the app and everything works fine
Works on other devices than Samsung Note 4 SM-N9100

### Code snippet
```csharp
public async Task<string> TakePictureAsync(int p_nInspectionID)
{
  string l_strFileName = await GetFreePictureFileNameAsync(p_nInspectionID);

  var l_scmoOptions = new Plugin.Media.Abstractions.StoreCameraMediaOptions
  {
    Directory = "TakenPictures",
    Name = l_strFileName
  };

  string l_strTakenPictureFilePath = null;

  string l_strResult = null;

  using (var l_fPictureFile = await CrossMedia.Current.TakePhotoAsync(l_scmoOptions))
  {
    if (l_fPictureFile != null) l_strTakenPictureFilePath = l_fPictureFile.Path;
  }
  
  if (l_strTakenPictureFilePath != null)
  {
    System.Diagnostics.Debug.WriteLine("Taken picture file path : [{0}]", l_strTakenPictureFilePath);
  
    IFolder l_fPictures = await GetPicturesFolderAsync();
  
    l_strResult = PortablePath.Combine(l_fPictures.Path, l_strFileName);
  
    IFile l_fSource = await FileSystem.Current.GetFileFromPathAsync(l_strTakenPictureFilePath);
  
    await l_fSource.MoveAsync(l_strResult);
  }

  return (l_strResult);
}
```

### Screenshots
![image](https://user-images.githubusercontent.com/15328452/34246873-aa56c980-e630-11e7-8b8e-cf6b4443e244.png)

**Comment by jamesmontemagno** [comment]
please post a stack trace into: http://gist.github.com

**Comment by cbs-cbt** [comment]
Hello James,
First of all thank you for you great job, and thank you taking time to help me solve this topic.

Unfortunately I don't have access to the machine (it is a user machine).

But the application is connected to App Center, here is what I have in the detail of the crash log.
[https://gist.github.com/cbs-cbt/a571c570dde45f74f320f2382fbce7e7](url)

**Comment by jamesmontemagno** [comment]
I have a S7 and don't have this issue at all, which is weird as it does the same thing. 

I assume you are doing a try/catch around taking the photo? that is best practice as Android could always throw for a number of reasons.

I have added a null check, but that mostly means the original image isn't there. Would need more logging to go farther, but you can try the new betas

**Comment by cbs-cbt** [comment]
Hello James,
Thank you, I will try the beta and keep you inform. The customer is actually in holiday.
To answer your question: yes I do a try/catch around the photo taking.
