### ISSUE TITLE
Java.Lang.ClassNotFoundException when linking was None

### ISSUE THREAD

**Issue by Maxima078** [jamesmontemagno/MediaPlugin#424]
Hi,
I was facing this error with 3.1.1 on Android 7.1.1 when linking was "None":
Java.Lang.ClassNotFoundException: md53a863c3de0ddfd328a1a6f9b5c6656b4.MediaPickerActivity

Then I turned it to "Sdk Assemblies Only" and it fixed the problem. So I turned it again to "None" and... it also works !

I'm using .NET Standard 1.6 and Xamarin.Forms 2.4.
Note I already have both the provider and the file_paths.xml in my Android project (needed by another package) thus I just added:

    <external-files-path name="my_images" path="Pictures" />
    <external-files-path name="my_movies" path="Movies" />

Do you have any idea about this?
Also, after installing the package I had to remove "MainApplication.cs" that was automatically generated, do you know why this file was generated after installation?

Thanks.

**Comment by jamesmontemagno** [comment]
This file is required or you must merge it with your current [Application] class as it lets the plugin have access to the current activity.
https://github.com/jamesmontemagno/CurrentActivityPlugin

You probably just need to clean/rebuild fully

**Comment by Maxima078** [comment]
Thank you for your answer. There is no need for this kind of settings in iOS and UWP?

**Comment by jamesmontemagno** [comment]
Correct
