### ISSUE TITLE
Camera photo async method crashes with SIGABRT code error

### ISSUE THREAD

**Issue by gokuldasc** [jamesmontemagno/MediaPlugin#426]
This works fine on Android but crashes on iPhone.
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:3.1.1
Device Tested On:iPhone 6s
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:2.5.0.121934
Versions of other things you are using:
Added necessary permissions for iOs version 11 the key name has changed.
Privacy - Photo Library Usage Description: NSPhotoLibraryAddUsageDescription (Previously key was NSPhotoLibraryUsageDescription). Before changing this I was getting unauthorized 
 exception.
### Steps to reproduce the Behavior
Simple photo capture using below code

### Code snippet
  var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                    {
                        SaveToAlbum = true,
                        Name = "newphoto.jpg"

                    });
### Screenshots

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

**Comment by jamesmontemagno** [comment]
Did you add permissions?

**Comment by gokuldasc** [comment]
Yes. I have added permissions. I have to downgrade the version back to 3.0.1  The version 3.1.1 crashes

**Comment by jamesmontemagno** [comment]
Can you post a full stack trace: https://gist.github.com/

**Comment by gokuldasc** [comment]
HI James,I have added all permissions and also the . full stack trace.
Regards,Gokul 

    On Wednesday, December 27, 2017 10:07 PM, James Montemagno <notifications@github.com> wrote:
 

 Did you add permissions?—

**Comment by gokuldasc** [comment]
Hi James, I have added full stack trace at the link you provided. Today it is crashing also on version 3.0.1 It was working fine on this version till yesterday.
I had to delete app due to space constraints and redeployed the app and problem started.
Any ideas?

Regards,
Gokul

**Comment by jamesmontemagno** [comment]
are you out of space on your device? That could be an issues. Once you paste it to gist.github.com you need to give me the link.

**Comment by gokuldasc** [comment]
Hi James,The problem started once I deleted the app and redeployed. There is enough space on device.Stack trace linkTake photo crashes with SIGABRT code.

  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
Take photo crashes with SIGABRT code.
 Take photo crashes with SIGABRT code.  |   |

  |

  |

 Regards,Gokul 

    On Tuesday, January 2, 2018 1:49 AM, James Montemagno <notifications@github.com> wrote:
 

 are you out of space on your device? That could be an issues. Once you paste it to gist.github.com you need to give me the link.—

**Comment by jamesmontemagno** [comment]
You can try 3.1.2, which i haven't been able to reproduce your issue
