### ISSUE TITLE
[Feature Request] Audio

### ISSUE THREAD

**Issue by sjreed** [jamesmontemagno/MediaPlugin#427]
James,

Your PlugIn is great!  Works well in my app pretty straight out of the box.

However, I was surprised it did not contain Audio.  I wasn't able to find a plugin out there so I guess I will build my own.  

Are you aware of one?

Thanks...Steve

**Comment by jamesmontemagno** [comment]
Check: https://github.com/xamarin/XamarinComponents#community-provided-open-source-plugins

**Comment by sjreed** [comment]
James,

 

Thanks for the link.  I see a couple of items there worth looking into further.

 

In today’s development world it is difficult to find a single product that is complete.  Yours does a good job of dealing with ‘visual’ media, but is lacking the ‘audio’ media.  Others allow for media ‘playing’ without the ‘capture’.  Too bad there is not a single one that combines all.

 

Thanks again…Steve
