### ISSUE TITLE
Camera wont open

### ISSUE THREAD

**Issue by xamarinuser** [jamesmontemagno/MediaPlugin#428]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:3.1.1
Device Tested On:11.2.1
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
when clicked on the take picture button on few ios devices the camera doesn't open. Few clients reported. When we tested on our devices which has ios 11 it is working fine.

**Comment by prashantvc** [comment]
> when clicked on the take picture button on few ios devices the camera doesn't open

Could you be more specific? What are these devices? 
Do you get any error messages/exceptions?

**Comment by xamarinuser** [comment]
var options = new StoreCameraMediaOptions()
                    {
                        Directory = FOLDERNAME,
                        SaveToAlbum = true,
                        CompressionQuality = 75,
                        CustomPhotoSize = 50,
                        PhotoSize = PhotoSize.MaxWidthHeight,
                        MaxWidthHeight = 2000
                    }; with these settings the camera wont open on ios devices for taking picture

**Comment by prashantvc** [comment]
I am not able reproduce this on iPhone SE running iOS v11.2.1, is it possible to share a sample project (delete bin, obj, and packages folders before sending) demonstrating this issue? It will help us to troubleshoot the issue

**Comment by jamesmontemagno** [comment]
You can try 3.1.2, which i haven't been able to reproduce your issue

**Comment by xamarinuser** [comment]
Yes I was not able to reproduce that issue in 3.1.2 when I tested in beta as it is released today we will use for the next release but for now we used 3.0.1

Thanks,
Hema
