### ISSUE TITLE
Camera doesn't open on iOS 11

### ISSUE THREAD

**Issue by dBiazioli** [jamesmontemagno/MediaPlugin#429]
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: iPhone 7 - iOS 11.2.1
Simulator Tested On: Xamarin Live Player 1.3.117, from beta channel
Version of VS: VS 2017 Community -15.4.5
Version of Xamarin: 2.4.0.282
Versions of other things you are using:

### Steps to reproduce the Behavior
Just run the Sample and touch on 'Take Photo' or 'Take Video'

### Expected Behavior
Opening the camera

### Actual Behavior
"Take Photo" throws an "Unknown enum type / InvalidOperationException"
"Take Video" throws an "Value cannot be null. Parameter name: value / ArgumentNullException"
"Pick Photo" and "Pick Video" works fine

### Code snippet
This plugin Sample project.

### Screenshots
Take Photo:
![image](https://user-images.githubusercontent.com/4949608/34519810-1015c640-f06d-11e7-87a9-c511db28b53e.png)

Take Video:
![image](https://user-images.githubusercontent.com/4949608/34519792-00872390-f06d-11e7-8ab4-f36d5d82fab5.png)

**Comment by jamesmontemagno** [comment]
This is with the Live Player as it is not supported for taking a photo.
