### ISSUE TITLE
[Feature Request] Ability to select multiple image files from the picker

### ISSUE THREAD

**Issue by ItchyMcTenders** [jamesmontemagno/MediaPlugin#43]
## Feature Request:
It would be awesome to select more than one file at a time from the galley before returning the result.
(PS thanks for the awesome package!)

**Comment by HLemmer** [comment]
This is exactly what we've been looking for as well. (+1)

**Comment by jamesmontemagno** [comment]
I have no current plans on implementing this. I have closed it in the past, but will leave it here for now.

**Comment by jamesmontemagno** [comment]
Removing clutter as will not implement.
