### ISSUE TITLE
Getting Width and Height of Image

### ISSUE THREAD

**Issue by higher-faster-better** [jamesmontemagno/MediaPlugin#431]
I have a question.
How can I get width and height of image that I get from TakePhotoAsync or PickPhotoAsync?
Thanks.

**Comment by prashantvc** [comment]
We do not have APIs to get the Picture metadata in this plugin. You may to use platforms' APIs to do it

**Comment by bastianbecker21** [comment]
@prashantvc `TakePhotoAsync` or `PickPhotoAsync` have `SaveMetaData` property. It means that I can get metadata? Please give me your opinion. Thanks!
