### ISSUE TITLE
Black or half black image when choosing photo

### ISSUE THREAD

**Issue by hvaughan3** [jamesmontemagno/MediaPlugin#437]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.2, 3.1.1, 3.0.1
Device Tested On: None
Simulator Tested On: iPhone 4s, iOS 8.4 Simulator
Version of VS: VS 2017 Professional - 15.5.3
Version of Xamarin: VS Xamarin - 4.8.0.757, XF Plugin Version - 2.3.4.270
Versions of other things you are using:

### Steps to reproduce the Behavior
0. Installing any stable Media plugin version above 2.6.2
1. Pick a default photo from the photo library on the device

### Expected Behavior
The full image is displayed on the device

### Actual Behavior
Only for certain images, the resulting image given to the app is either completely black or about half of the image is black and the other half displays part of the chosen image

### Code snippet

    await Instance.Initialize(); //Instance is a public static property of type IMedia

    MediaFile file = await Instance.PickPhotoAsync(new PickMediaOptions {
        CompressionQuality = 85,
        PhotoSize          = PhotoSize.Large
    });

    string filePath  = FileHelper.CopyFile(file.Path, FileHelper.ExternalDocumentStoragePathToFile("blah.jpg"));

    MyImage.Source = ImageSource.FromFile(filePath);

### Screenshots
**Screenshot showing image in photo album before picking it:**
![simulator screen shot - iphone 4s - photo album image before picking it](https://user-images.githubusercontent.com/6466876/35012409-4a5e35a0-facf-11e7-947b-6de583e4f217.png)

**Screenshot showing image picked from photo album after saving locally and displaying local copy:**
![simulator screen shot - iphone 4s - photo album image after saving locally and displaying](https://user-images.githubusercontent.com/6466876/35012408-4a478ca6-facf-11e7-9a09-24e1bf2b484f.png)

Everything works perfectly when I install 2.6.2 and it consistently messes up the same images when trying any of the stable versions above that (3.0.1, 3.1.1, 3.1.2). I have not tried any pre-release versions.

**Comment by prashantvc** [comment]
I don't have a device running iOS 8.4 right now, could you confirm if you see this issue in iOS 11

**Comment by jamesmontemagno** [comment]
Unable to reproduce on iOS 8, 9, 10, or 11:
https://www.screencast.com/t/Rv2JnLGLY2qc

It must be how you are displaying them.

**Comment by hvaughan3** [comment]
@jamesmontemagno Actually I saved the photo back to the device's photo album and it saved with the black part.

**Comment by jamesmontemagno** [comment]
Is that code part of the plugin? Or is it something you wrote? I don't see it at all here in the issue.
