### ISSUE TITLE
3.0.1 Raw Data iOS & Android Differences (iOS Landscape Swap Possibility)

### ISSUE THREAD

**Issue by ryanherman** [jamesmontemagno/MediaPlugin#438]
## Bug Information

Version Number of Plugin: 3.1.2
Device Tested On: 
Simulator Tested On: 7.1 Android & iPhone X 11.2
Version of VS: 15.5.4
Version of Xamarin: 4.8.757
Versions of other things you are using:

### Steps to reproduce the Behavior
Upload same photo on iOS & Android using 3.1.2

### Expected Behavior
File should not be stored as landscape on iOS.  Android works fine
### Actual Behavior
The files are the exact same image size but when you launch photoshop and view the file info (Raw Data), they contain very different exif info and I think it is the cause of images showing up as landscape on iOS.  Most notably the PixelXDimension are swapped with Y for some reason.

Please see this File Difference comparison:
https://www.diffchecker.com/X0b078Qo

[Android File]
https://s3.amazonaws.com/media.1iota/member/fbf28b24-fd3c-40ee-9523-fcff752ffaff/droid.jpg

[iOS File]
https://s3.amazonaws.com/media.1iota/member/fbf28b24-fd3c-40ee-9523-fcff752ffaff/ios.jpg

### Code snippet
```C#
 var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                PhotoSize = PhotoSize.Medium
            });
```
### Screenshots

![sample](https://user-images.githubusercontent.com/2665592/35018701-bdb66cc2-fad7-11e7-80e0-4f3fc353d911.jpg)

As you can see, the iOS images I uploaded to s3 are rotated to landscape but the Android are as they should be in portrait.

**Comment by jamesmontemagno** [comment]
Yes, iOS stores images in landscape so you have to look at exif or use this helper method:

https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Abstractions/MediaFile.cs#L77

**Comment by ryanherman** [comment]
ah thank you, can I use this for Android and iOS or do something like this?

```C#
            System.IO.Stream fileStream;

            if (Device.RuntimePlatform == Device.iOS)
                fileStream = file.GetStreamWithImageRotatedForExternalStorage();
            else
                fileStream = file.GetStream();
```

**Comment by jamesmontemagno** [comment]
I am pretty sure on Android it does the same thing actually.
