### ISSUE TITLE
Size of image selected

### ISSUE THREAD

**Issue by AmperayaniMadan** [jamesmontemagno/MediaPlugin#44]
Feature Request:
Hi, Is there any way I can get the size of the images I select. I know that it is planned for future versions (I am guessing the image metadata provides that information )but in the interim, if there is any way which I can obtain the size of the image selected, may be from the stream or something like that.

Thanks,
Madan

**Comment by jamesmontemagno** [comment]
Not currently in the plugin. You would have to use the exif libraries.

**Comment by n1schal** [comment]
@jamesmontemagno  Hi there. Thanks for this great library! 

Anyways, sorry for commenting on a closed issue but what's the proper way to get the file size? I tried file.GetStream().Length but that isn't giving me the correct size of the file.

**Comment by jamesmontemagno** [comment]
that would be the length of the stream not the file, you would need to read the info from disk.
