### ISSUE TITLE
iOS app on iPad shows low quality stream when taking a picture

### ISSUE THREAD

**Issue by StijnProceedix** [jamesmontemagno/MediaPlugin#443]
## Bug Information

Version Number of Plugin: 3.1.2
Device Tested On: iPad 4
Version of VS: 2017 (15.5.3)
Version of Xamarin: Xamarin.Forms 2.5

### Steps to reproduce the Behavior

Run a simple app to take a picture.
I'm using the default StoreCameraMediaOptions
var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
{
      Directory = "Sample",
      Name = "test.jpg"
});

### Expected Behavior

I expect to have the same video streaming quality between my own app and the iOS Camera app.

### Actual Behavior

The quality/resolution in my own app is not as good as the iOS Camera app.
Even when tapping the screen to focus.
Only when I zoom in on a solid surface, the camera's autofocus kicks in and the quality improves.

### Screenshots

XamarinForms app
![img_0125](https://user-images.githubusercontent.com/23027639/35159162-9ab2dd0a-fd39-11e7-9a60-135cf3265e34.PNG)

Default camera app
![img_0126](https://user-images.githubusercontent.com/23027639/35159188-a9cf3d92-fd39-11e7-8ef5-dba9701e6894.jpg)

**Comment by jamesmontemagno** [comment]
The library uses the standard UIImagePickerController. The result is what Apple shows and has full power over.

Most likely the actual camera itself uses an AVCapture session and they do a bunch of other intense stuff. There is literally no toggles for photo quality. So what you are seeing is what Apple decided. You can file a radar with them.
