### ISSUE TITLE
[UWP] MaxWidthHeight image resizing is not implemented/working on PickPhotoAsync and TakePhotoAsync

### ISSUE THREAD

**Issue by jBijsterboschNL** [jamesmontemagno/MediaPlugin#448]
## Bug Information
With TakePhotoAsync and PickPhotoAsync the images are not being resized on UWP when using MaxWidthHeight and PhotoSize = PhotoSize.MaxWidthHeight.

Version Number of Plugin: 3.1.3
Device Tested On: Windows 10 Local Machine
Simulator Tested On: 
Version of VS: 2017 version 15.5.2
Version of Xamarin: Xamarin.Forms.2.5.0.91635
Versions of other things you are using:

### Steps to reproduce the Behavior
Execute either PickPhotoAsync or TakePhotoAsync with options MaxWidthHeight = 1024 and PhotoSize = PhotoSize.MaxWidthHeight. Take of pick a photo and check the local storage folder with the saved images. These are the original and non-resized images.

### Expected Behavior
Image gets resized using the MaxWidthHeight setting and stored to the local storage folder.

### Actual Behavior
Original (non resized) image gets stored in local storage folder.

### Code snippet

```csharp
var options = new PickMediaOptions
{
    MaxWidthHeight = 1024,
    PhotoSize = PhotoSize.MaxWidthHeight
};
var file = await _mediaService.PickPhotoAsync(options);

OR:

var options = new StoreCameraMediaOptions
{
    DefaultCamera = CameraDevice.Rear,
    MaxWidthHeight = 1024,
    PhotoSize = PhotoSize.MaxWidthHeight,
    Directory = folderPath,
    Name = fileName
};
var file = await _mediaService.TakePhotoAsync(options);
```

**Comment by jamesmontemagno** [comment]
Correct, this is not implemented and only on iOS/Android

**Comment by jBijsterboschNL** [comment]
Hi @jamesmontemagno, thanks for your quick response. Will this be implemented in the near future? What's the reason that this isn't implemented yet? Is this difficult to add on UWP?

**Comment by jamesmontemagno** [comment]
I have no plans currently. But you can send a PR.
