### ISSUE TITLE
UWP -  PickPhotoAsync when run in Release mode results in an error from onecore

### ISSUE THREAD

**Issue by WillAutioItrax** [jamesmontemagno/MediaPlugin#449]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: Local Machine
Simulator Tested On: none
Version of VS: 2017 15.5.4
Version of Xamarin: 4.8.0.757
Versions of other things you are using:
Xamarin Forms 2.4.0.280
lots of other plugins.

### Steps to reproduce the Behavior
execute code to Pic a Photo in UWP for Release

### Expected Behavior
code runs with no errors

### Actual Behavior
Get an error message:
onecore\com\combase\inc\comcataloghelpers.hpp(64)\combase.dll!75BA8550: (caller: 75BA82E0) ReturnHr(5) tid(95c) 80040154 Class not registered

### Code snippet

```csharp
// I have a Debug.WriteLine before and after the PickPhotoAsync to show where I get the error.
Debug.WriteLine("->mediaFile = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions");
mediaFile = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
{
       PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small
});
Debug.WriteLine("->mediaFile path:" + mediaFile.Path);
```

### Debug Output

`mediaFile = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions`

onecore\com\combase\inc\comcataloghelpers.hpp(64)\combase.dll!75BA8550: (caller: 75BA82E0) ReturnHr(5) tid(95c) 80040154 Class not registered

->mediaFile path:C:\Users\<User>\AppData\Local\Packages <MyApp>_2gr1j9mzh5y0e\LocalState\3009image - Copy.jpg

### Additional notes
When I run this in Debug mode, the onecore error does not happen anywhere.

When I run it in Release mode I get additional onecore and onecoreuap error messages when I try to do stuff with the MediaFile object.

**Comment by jamesmontemagno** [comment]
Could be something with .NET Native perhaps linking something out... Will have to investigate

**Comment by prashantvc** [comment]
@WillAutioItrax I am not able to reproduce this issue on Windows 10 machine (Surface Pro 4)
Could you share the sample project demonstrating the problem? It will help us to troubleshoot the issue

**Comment by WillAutioItrax** [comment]
@prashantvc Thanks for taking a look at this. I have been working on other parts of the app for a few days. When I re-ran it for UWP, the issue was gone. Sorry. I do not know what changed to fix it. To fix a different Android issue, I had done a Clean and delete of the bin and obj directories. Maybe that cleared it up. If it comes back, I'll try to make a project where it is reproducible.

**Comment by leonmeijer** [comment]
I have similar errors:

Unhandled exception at 0x76D99931 (combase.dll) in MyApp.Clients.UWP.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x1224B560, 0x00000001).


Unhandled exception at 0xC329C2C8 in MyApp.Clients.UWP.exe: 0xC0000005: Access violation executing location 0x00000000.
