### ISSUE TITLE
TakePhotoAsync hangs in iPad on second time, then crashes

### ISSUE THREAD

**Issue by attrib75** [jamesmontemagno/MediaPlugin#450]
## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: iPad 6,12
Simulator Tested On:
Version of VS: 2017 15.5
Version of Xamarin:  4.8.0.752
Versions of other things you are using: iOS 10.3.3
### Steps to reproduce the Behavior

Click an image button, the click handler invokes the Media helper.  Can take a picture.  Click the image button again to take a new picture

### Expected Behavior

able to take another picture

### Actual Behavior

app hangs then crashes, the following log output:

[https://gist.github.com/attrib75/c6103e72bab0f3fa977d4bb76a8f3fbf](url)

this does NOT happen in iPhone.  I saw a thread about stylizing the slider, but this app does not contain anything of the sort to my knowledge. 

### Code snippet

`      

        private async void OnCameraTapped(object sender, EventArgs args)
        {

            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                throw new Exception("No camera available");
            }
           
            using (MediaFile file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                //Name = $"photo{DateTime.Now.ToString("yyyyMMddHHmmss")}.jpg",
                Name = "Photo1.jpg",
                PhotoSize = PhotoSize.Medium,
                CompressionQuality = 80,
                AllowCropping = true,
                Directory = "AppDir"
            }))

            {
                if (file == null)
                {
                    ImgBytes = null;
                }
                else
                {
                    using (System.IO.Stream stream = file.GetStream())
                    {
                        ImgBytes = new byte[stream.Length];
                        await stream.ReadAsync(ImgBytes, 0, Convert.ToInt32(stream.Length));
                        file.Dispose();
                        
                    }
                    Device.BeginInvokeOnMainThread(async () =>
                    {
                        PhotoImage.Source = ImageSource.FromStream(() =>
                        {
                            return new MemoryStream(ImgBytes);
                        });
                    });
                }
                
            }
           
        }`

**Comment by jamesmontemagno** [comment]
Remove your using statement. You are disposing of the file and then trying to use it.

**Comment by attrib75** [comment]
Yes but this same code works on iPhone.  I can even navigate to another page then back and it still happens.   I even had the camera functionality in another class I instantiated on button click every time which created new instance of file

**Comment by jamesmontemagno** [comment]
Interesting, can you create a small repro project for me?

Looks like something with the status bar, but would need your project to validate things

https://stackoverflow.com/questions/31872650/how-can-i-set-cg-context-show-backtrace-environmental-variable

**Comment by attrib75** [comment]
Thanks for reopening.  I have a sample project.  What is the best delivery mechanism for you?

**Comment by jamesmontemagno** [comment]
If you can put it up on github that would be the best.

**Comment by attrib75** [comment]
Thanks, just added you to a repo

**Comment by jamesmontemagno** [comment]
Looks like it is a blank repo right now.

**Comment by attrib75** [comment]
Right.  There's another branch.  First timer here uploading to git from vs.  Used to vsts.
Thanks

**Comment by attrib75** [comment]
The other branch is in the same repo

**Comment by jamesmontemagno** [comment]
I was unable to reproduce this on my iPad with your source code that I pulled into the sample `test` app in this repo.

I am unable to run your sample because it has private nuget feeds.

**Comment by attrib75** [comment]
This is bizarre. Tried it on a brand new ipad

**Comment by attrib75** [comment]
Maybe it has something to do with the UI library I'm using? This is where the private nuget feed comes in.  I'm not understanding how you ran it.

**Comment by attrib75** [comment]
Any chance I can send you something you can run?  I'm trying to avoid having to implement another library. Bummer

**Comment by jamesmontemagno** [comment]
Yeah, you can try. Or another option is to fork of this code and debug through issue.

**Comment by attrib75** [comment]
I added the dlls you need and removed the nuget references to them.  This should allow you to run the sample.  I appreciate you spending the time.  Thank you

**Comment by attrib75** [comment]
This issue can be closed.  It was determined that the UI framework used was styling the slider bar that appears on iPad when the camera is invoked.  Removing the styling worked

http://www.openradar.me/30396879

**Comment by jamesmontemagno** [comment]
ahhh good one, yup that is a huge problem :( I think I documented it somewhere, else I will.
