### ISSUE TITLE
Camera can not start up after turning on/off flash with CrossLamp

### ISSUE THREAD

**Issue by drmashu** [jamesmontemagno/MediaPlugin#451]
If you call CrossLamp.Current.TurnOn / TurnOff and call CrossMedia.Current.TakePhotoAsync, the message "The camera is in use by another application" is displayed and the camera does not start up.

## Bug Information

Version Number of Plugin: 3.1.2
Device Tested On: Xperia XZ
Simulator Tested On:
Version of VS: Pro 2017
Version of Xamarin: 2.5.0.122203
Versions of other things you are using:
kphillpotts.Lamp.Plugin 1.0.0.1

### Steps to reproduce the Behavior

CrossLamp.Current.TurnOn();

CrossLamp.Current.TurnOff();

await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions { });

### Screenshots

[https://imgur.com/nj5YJfA](url)

**Comment by jamesmontemagno** [comment]
This would be an issue with cross lamp as it isn't releasing the camera.
