### ISSUE TITLE
Camera crashes if target is above Android 6

### ISSUE THREAD

**Issue by BillyMartin1964** [jamesmontemagno/MediaPlugin#455]
You mention having to add permissions, but I have your permission plugin and it still crashes. I also use your permission plugin for the flashlight (Camera) and that works fine.

//My Request for Permission

  await Permissions.CheckPermissions(Permission.Camera);
                await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    DisplayAlert("No Camera", ":( No camera available.", "OK");
                    return;
                }

//My Permission plugin code

public static class Permissions
    {
        //Used to check if the app has been given Location and Camera Permissions
        public static async Task<bool> CheckPermissions(Permission permission)
        {
            var permissionStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);
            bool request = false;
            if (permissionStatus == PermissionStatus.Denied) //If they've already refused permission
            {
                if (Device.RuntimePlatform == Device.iOS)
                {
                    string question;

                    if (permission == Permission.Camera)
                        question = $"To use the flashlight the {permission} permission is required. Please go into Settings and turn on {permission} for the app.";
                    else
                        question = $"To use this plugin the {permission} permission is required. Please go into Settings and turn on {permission} for the app.";

                    var title = $"{permission} Permission";
                    var positive = "Settings";
                    var negative = "Maybe Later";
                    var task = Application.Current?.MainPage?.DisplayAlert(title, question, positive, negative);
                    if (task == null)
                        return false;

                    var result = await task;
                    if (result)
                    {
                        CrossPermissions.Current.OpenAppSettings();
                    }

                    return false;
                }

                request = true;

            }

            if (request || permissionStatus != PermissionStatus.Granted)
            {
                var newStatus = await CrossPermissions.Current.RequestPermissionsAsync(permission);
                if (newStatus.ContainsKey(permission) && newStatus[permission] != PermissionStatus.Granted)
                {
                    string question;

                    if (permission == Permission.Camera)
                        question = $"To use the flashlight the {permission} permission is required.";
                    else
                        question = $"To use the plugin the {permission} permission is required.";

                    var title = $"{permission} Permission";
                    var positive = "Settings";
                    var negative = "Maybe Later";
                    var task = Application.Current?.MainPage?.DisplayAlert(title, question, positive, negative);
                    if (task == null)
                        return false;

                    var result = await task;
                    if (result)
                    {
                        CrossPermissions.Current.OpenAppSettings();
                    }
                    return false;
                }
            }

            return true;
        }

        public static async Task<bool> GetPermissions()
        {

            bool permissionsGranted = false;
            try
            {
                var permissionsList = new List<Permission>()
                {                    
                    Permission.Camera,
                    Permission.Location
                };

                foreach (var permission in permissionsList)
                {
                    var status = await CrossPermissions.Current.CheckPermissionStatusAsync(permission);

                    if (status != PermissionStatus.Granted)
                    {
                        if (await CrossPermissions.Current.ShouldShowRequestPermissionRationaleAsync(permission))
                        {
                            await App.Current.MainPage.DisplayAlert("Need a permission", $"Required: {permission.ToString()}", "OK");
                        }

                        var results = await CrossPermissions.Current.RequestPermissionsAsync(permission);
                        //Best practice to always check that the key exists
                        if (results.ContainsKey(permission))
                            status = results[permission];
                        if (status == PermissionStatus.Granted || status == PermissionStatus.Unknown)
                        {
                            permissionsGranted = true;
                        }
                        else
                        {
                            await App.Current.MainPage.DisplayAlert("Permission Denied", "Can not continue, try again.", "OK");
                            permissionsGranted = false;
                            break;
                        }
                    }
                }

            }
            catch (System.Exception)
            {
                return permissionsGranted = false;// await App.Current.MainPage.DisplayAlert("Error", "Error: " + ex.Message, "Ok");
            }
            return permissionsGranted;
        }

**Comment by jamesmontemagno** [comment]
Did you follow the full setup: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

Also what is the stack trace?

**Comment by BillyMartin1964** [comment]
Got it, thanks to you, James! I didn't have:

using Plugin.Permissions.Abstractions;
or 
<provider android:name="android.support.v4.content.FileProvider" 
				android:authorities="YOUR_APP_PACKAGE_NAME.fileprovider" 
				android:exported="false" 
				android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" 
				android:resource="@xml/file_paths"></meta-data>
</provider>

Thank you so much!

**Comment by BillyMartin1964** [comment]
There is a Settings Gear icon and a four-colored Square icon on the camera. Does anyone know why they are disabled when I access the camera via the media plugin? The Flash icon and the Reverse camera view icons are both enabled, though.

**Comment by jamesmontemagno** [comment]
it is based on the camera app, we just ask it to take a photo. The default camera app is in control after that.

**Comment by BillyMartin1964** [comment]
K Thanks, James. Guess this issue is closed.
