### ISSUE TITLE
Navigate to home view after taking/uploading image

### ISSUE THREAD

**Issue by qaliwebguru** [jamesmontemagno/MediaPlugin#456]
## Bug Information

I have created very simple view for uploading profile photo to server via API Call. 

As soon as i select the image the current page disappears and app is redirected to home view which is Master detail view. Image is uploaded successfully though. 

Version Number of Plugin: 3.1.3
Device Tested On: IPhone 6
Simulator Tested On: N/A
Version of VS: 15.5.1
Version of Xamarin: 4.8.0753
Versions of other things you are using:

### Steps to reproduce the Behavior
1- Install Media Plugin and create a view with UploadPhoto in Master Detail Navigation
2- The code for selecting image and displaying image.
3- The last part is to use "CrossFileUploader" to post to API to upload to server. 

Note: The behaviour is same with or without step 3 above. 

### Expected Behavior
This is how it is working properly on Android device. 

1- Select image is clicked and image is selected.
2- The image should is displayed in image area above the button. 
3- After displaying, it uploads the image to server. 

### Actual Behavior

This is how it is not working on IOS device. 

1- Select image is clicked and image is selected.
2- The current page disappears and home view is loaded. 
3- It uploads the image to server during all that refresh and redirects. 

### Code snippet

        <StackLayout>       
     
            <Image x:Name="imageDisplay" />
            <Button
                x:Name="SelectPhoto"
                Clicked="SelectPhoto_Clicked"               
                Text="Select "
                VerticalOptions="Center" />
        </StackLayout>

```csharp
private async void SelectPhoto_Clicked(object sender, EventArgs e) {
            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                DisplayAlert("Photos Not Supported", ":( Permission not granted to photos.", "OK");
                return;
            }
            var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium


            });
            if (file == null)
                return;

            imageDisplay.Source = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                //file.Dispose();
                return stream;
            });


            string token = await Settings.GetAccessToken();


            await  CrossFileUploader.Current.UploadFileAsync("http://mainapi.example.com/api/v1/users/uploadprofilephoto", new FilePathItem("ProfilePhoto", file.Path), new Dictionary<string, string>()
                {
                   {"Authorization" , "Bearer " + token}
                }
    );
}
```

### Screenshots
![ios-screenshot](https://user-images.githubusercontent.com/31895946/35574454-c96d36b8-05d1-11e8-8466-91de7b8062c7.png)

Following is the screenshot of Android screen. This is how it should work. 
![android-screenshot](https://user-images.githubusercontent.com/31895946/35574519-e61b11cc-05d1-11e8-96b8-965b67d9adcf.png)

**Comment by prashantvc** [comment]
I am not able to reproduce this on my devices, is it possible to share the sample project demonstrating the problem.

Additionally, you can debug the code downloading/cloning the code from this repo

**Comment by qaliwebguru** [comment]
Thanks for your reply. I will try to get demonstrating project up as soon as possible for you.

**Comment by faulinger** [comment]
I was facing the same issue. I tried using an older Xam.Plugin.Media Version. Using 3.0.1 works now fine for me.

**Comment by thomasflad** [comment]
Same issue here. Downgrading to 3.0.1 fixes the problem for me also.

**Comment by chuckgiddens** [comment]
I have having the same problem with 4.0.1.5 but I cannot roll all the way back to 3.0.1.
Will this ever be fixed?

**Comment by marthinch** [comment]
I have similar issue, i use 4.0.1.1 anyone fix this ?

**Comment by nicktiberi** [comment]
I think I found a fix. If you set `ModalPresentationStyle = MediaPickerModalPresentationStyle.OverFullScreen`, it won't navigate away from the page once you're done using the camera.

Example:

```
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
 {
    Directory = "Sample",
    Name = "test.jpg",
    ModalPresentationStyle = MediaPickerModalPresentationStyle.OverFullScreen
});
```
