### ISSUE TITLE
how to convert image view to MediaFile.

### ISSUE THREAD

**Issue by bezblue** [jamesmontemagno/MediaPlugin#457]
i need to get stream in image but i can't convert imageView to stream.

**Comment by prashantvc** [comment]
Could you elaborate what are you trying to do? 
I think this issue is out of scope of this project

**Comment by bezblue** [comment]
i need to use getStream method. but i have path file without use pick image.
i need auto background pick.
i'am sorry, understand?

**Comment by jamesmontemagno** [comment]
If you have the file path just use System.IO to open it https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/files/
