### ISSUE TITLE
[UWP] Unable to preview the video on Windows phone

### ISSUE THREAD

**Issue by NikolaNel** [jamesmontemagno/MediaPlugin#462]
When we record a video with a windows phone, sometimes we cannot preview the video. There is a black screen with the record again and select video buttons only. This only happens on the windows phone.
On the desktop UWP app we can preview the video.

## Bug Information
Version Number of Plugin: 3.1.3
Device Tested On: Microsoft Lumia 640 LTE
Version of VS: 15.5.6

### Steps to reproduce the Behavior
Use the plugin to take a video in UWP. After the video is taken, there are buttons to:
select the video or to record again.

### Expected Behavior
Along with the buttons we should be able to play the video before selecting it or recording again.

### Actual Behavior
A black screen with the two buttons is displayed and no options to play the video.

### Screenshots
https://goo.gl/rTKzPZ

**Comment by jamesmontemagno** [comment]
This is the windows UI I have no control over it.

**Comment by NikolaNel** [comment]
But the strange thing is that sometimes (albeit rarely) there is a video preview
