### ISSUE TITLE
How to Select Multiple Images?

### ISSUE THREAD

**Issue by Srusti-Thakkar** [jamesmontemagno/MediaPlugin#463]
I am using this plugin and it works fine for single image.

But, I want to use this plugin for multiple images. For example I want add selection for multiple images from gallery. Also If I am using capturing method then I am able to capture multiple photo and select from them. How to implement this functionality using this plugin?

**Comment by prashantpimpale93** [comment]
@Srusti-Thakkar Have you solve this issue?

**Comment by WagnerMattei** [comment]
@Srusti-Thakkar  Solved??
