### ISSUE TITLE
Get List<Image> from Gallery. Xamarin Forms

### ISSUE THREAD

**Issue by idimkk** [jamesmontemagno/MediaPlugin#465]
**Thanks for the great plugin, I have one question.**
How can I get a list of all images (for example, a list of paths) from a gallery or all albums?
I do not need to open the gallery to select a photo, I want to upload them, for example, as in the Instagram when trying to publish.

**Comment by jamesmontemagno** [comment]
This library does not support this capability. We launch the default album to pick an image from.

**Comment by idimkk** [comment]
Thanks for the answer!
You could suggest how you can solve this problem, if possible?
