### ISSUE TITLE
Error when app start

### ISSUE THREAD

**Issue by manonaga2188** [jamesmontemagno/MediaPlugin#467]
[ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference
  at (wrapper dynamic-method) System.Object:a510dffd-64d3-4452-9492-7a3ba8518cd7 (intptr,intptr,intptr)
 End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference

**Comment by manonaga2188** [comment]
https://github.com/jamesmontemagno/MediaPlugin/issues/226

Fixed my issue.

Thanks

**Comment by alexeystrakh** [comment]
> #226
> 
> Fixed my issue.
> 
> Thanks

@manonaga2188 what was the issue and how did you fix that?

**Comment by ondrejsv** [comment]
> > #226
> > Fixed my issue.
> > Thanks
> 
> @manonaga2188 what was the issue and how did you fix that?

"delete bin and obj folders on Android project and rebuild it"

https://github.com/jamesmontemagno/MediaPlugin/issues/226#issuecomment-298005958

**Comment by marcinbogiel** [comment]
> 
> 
> > > #226
> > > Fixed my issue.
> > > Thanks
> > 
> > 
> > @manonaga2188 what was the issue and how did you fix that?
> 
> "delete bin and obj folders on Android project and rebuild it"
> 
> [#226 (comment)](https://github.com/jamesmontemagno/MediaPlugin/issues/226#issuecomment-298005958)



> 
> 
> > > #226
> > > Fixed my issue.
> > > Thanks
> > 
> > 
> > @manonaga2188 what was the issue and how did you fix that?
> 
> "delete bin and obj folders on Android project and rebuild it"
> 
> [#226 (comment)](https://github.com/jamesmontemagno/MediaPlugin/issues/226#issuecomment-298005958)

App works again, thank you! :)

**Comment by bssol** [comment]
[#226](https://github.com/jamesmontemagno/MediaPlugin/issues/226)
fixed issue;

I moved file_paths to LayOut folder; and issue fixed
