### ISSUE TITLE
RequestCameraPermissions method contains storage permission

### ISSUE THREAD

**Issue by coolhunter33** [jamesmontemagno/MediaPlugin#469]
Hello.

In iOS version of MediaImplementation class we have next code for TakePhotoAsync method:
`var permissionsToCheck = new List<Permission> { Permission.Camera };`   
`await CheckPermissions(permissionsToCheck.ToArray());`

**_So when we're tapping "Take a photo" - we're seeing only 1 popup with Camera permission request._**

On Android the same functionality contains next code for RequestCameraPermissions method (which is called inside the TakePhotoAsync() ):
`if (hasCameraPermission != Permissions.Abstractions.PermissionStatus.Granted)`
`permissions.Add(Permissions.Abstractions.Permission.Camera);`

`if(hasStoragePermission != Permissions.Abstractions.PermissionStatus.Granted)`
`permissions.Add(Permissions.Abstractions.Permission.Storage);`

_**The same functionality like on iOS but it requires 2 popup permissions.**_

Is there any way to avoid showing the permission popup for accessing storage in scenario when I want to take a photo?
Or it is not possible to use camera on Android without having both permissions?

Thanks in advance.

**Comment by jamesmontemagno** [comment]
On android you ONLY need storage, but if you added the Camera permission in your android manifest then it is required:

bool checkCamera = HasPermissionInManifest(Android.Manifest.Permission.Camera);

So don't add that if you don't need to. Else you need both permissions.
