### ISSUE TITLE
Ability to build on osx

### ISSUE THREAD

**Issue by Murf** [jamesmontemagno/MediaPlugin#47]
Hi James,
Is it possible to build on mac osx please?

**Comment by jamesmontemagno** [comment]
Do you mean a Xamarin.Mac version? You should be able to open the project in Xamarin Studio.

Can you let me know what the actual issue is?

**Comment by Murf** [comment]
Hi James,
I have forked this repo, and want to build it so I can stick it in a local nuget repo.
Either that or build it as an iOS and Android component/package that I can drag and drop into other projects.
My setup is:
Mac OSX Mavericks,
Xamarin Studio

**Comment by jamesmontemagno** [comment]
@Murf so what exact issues are you facing? Does the NuGet not build or are you having an issue building the actual project in src?

What version of Xamarin Studio are you on? You will need 6.0 or newer for the C# 6 stuff.

See the requirements here: https://developer.xamarin.com/guides/cross-platform/getting_started/requirements/#Mac_OS_X_Requirements

**Comment by Murf** [comment]
Hi James,
I want to be able to customise it hence my own fork
I have Xamarin Studio 6.0.2
What do I have to do to build the packaged target? I just end up with a directory full of dll?

**Comment by jamesmontemagno** [comment]
The easiest way to auto generate the nuget is just to put it in appveyor. 

Else, you will have to download NuGet.exe and run it via command line to package the files once they have all been built in release mode. https://dist.nuget.org/index.html

Documentation for NuGet is here: https://docs.nuget.org/create/creating-and-publishing-a-package

**Comment by Murf** [comment]
So no way to do it in MAC osx?
It doesn't HAVE to be a nuget package, I just need a way to get it into my other projects.
If I just copy the dll's, I have no references?

**Comment by Murf** [comment]
It's ok James, I will use appveyor... Thanks anyway!

**Comment by jamesmontemagno** [comment]
You could just include the projects into your project. 

It is completely doable on the Mac, I sent all the docs needed. It is just a command line to create the actual NuGet if you wanted to do that, else just include the files into your app that are needed.
