### ISSUE TITLE
This plugin doesn't work on Xamarin Live Player

### ISSUE THREAD

**Issue by moximo13** [jamesmontemagno/MediaPlugin#476]
I did follow the instructions to set up this media plugin.

It's working fine on both simulator and devices, but when I tried on Xamarin Live Player, 'Take a photo' and 'Pick a photo' doesn't work: No camera or my picture storage appear.

I don't know whether this is a bug or I miss something. I really want my app working on Xamarin Live Player because I can share other testers to test my app via QR code rather than download it from stores.

I must apologize if I do miss something from the instructions.

**Comment by jamesmontemagno** [comment]
Already open bugs in bugzilla for it. As documented the live player is for rapid prototying and getting started and not compatible with all libraries.

**Comment by FizzBuzz791** [comment]
Might be handy to mention this fact somewhere prominent... I've spent a fair amount of time trying to figure out what was wrong before coming here to find out it is just XLP.
