### ISSUE TITLE
How to make the flash light open while the camera was activate?

### ISSUE THREAD

**Issue by VivianTio** [jamesmontemagno/MediaPlugin#478]
How to make the flash light open while the camera was activate?

I add  CrossLamp.Current.TurnOn(); but this only can activate flash light but the camera was fail to activate.

    CrossMedia.Current.Initialize();
            if (!CrossMedia.Current.IsTakePhotoSupported && !CrossMedia.Current.IsTakeVideoSupported)
            {
                DisplayAlert("Message", "Photo Capture and Pick Not supported", "ok");
                return;
            }
            else
            {

                CrossLamp.Current.TurnOn();

                var file = CrossMedia.Current.TakePhotoAsync(new 
                Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    //DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Front,
                    CompressionQuality = 92,
                    SaveToAlbum = true,
                    Directory = "Image",
                    Name = DateTime.Now + "_test.jpg"
                });

**Comment by jamesmontemagno** [comment]
Seems like a limitation of iOS.
