### ISSUE TITLE
(await ...PickPhotoAsync()).GetStream().Length is 3x bigger on iOS

### ISSUE THREAD

**Issue by iforlife** [jamesmontemagno/MediaPlugin#48]
## Bug 

Version Number of Plugin:2.3.0
Device Tested On: HTC One - Android 5.0, iPhone 6 

### Expected Behavior
MediaFile.GetStream().Length should be almost the same as the actual image size in bytes

### Actual Behavior
MediaFile.GetStream().Length is 2-3 times bigger than the actual image size in bytes. That's only on iOS. On Android - it's OK.
For image size of 60-70KB the MediaFile.GetStream().Length is almost 200KB.

### Steps to reproduce the Behavior
I'm using it in PCL:
var photo = await CrossMedia.Current.PickPhotoAsync()

**Comment by jamesmontemagno** [comment]
Have you tried the latest beta packages out? Let me know if you still see the same results there so I can debug.

**Comment by iforlife** [comment]
Hey James.
Yeap. Just did. Same result :( This is not critical problem, we can live with it, but definitely not nice one since every byte counts on mobile.

I just saw the new improvements you introduced since the last stable version - great work. Love the new features! Do you think we'll have new stable version any time soon?

**Comment by iforlife** [comment]
Any ETA on this one?

**Comment by jamesmontemagno** [comment]
I have not investigated it just yet sorry, but is on radar. I am looking for help on bug fixes.

**Comment by jamesmontemagno** [comment]
I am not sure as literally all we do is:  () => File.OpenRead(path)

So there isn't anything I can do about it. I can only assume there is some overhead to the stream itself. Will close for now as nothing else I can do here.
