### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Azmarel** [jamesmontemagno/MediaPlugin#481]
I can't see the option to translate buttons. Can we translate the take photo buttons or retake photo to other languages??
Cheers

**Comment by prashantvc** [comment]
What platforms is this? Could you share more details?

**Comment by Azmarel** [comment]
IOS. My system language is Polish and the buttons are in english

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/MediaPlugin/issues/468
