### ISSUE TITLE
FR: Screenshot API

### ISSUE THREAD

**Issue by aherrick** [jamesmontemagno/MediaPlugin#486]
Not sure if this belongs/is wanted... but might be nice to have an exposed API to capture a screenshot. 

Would return a byte array image of the current view.

I'm doing this currently in an app for iOS/Android/UWP via DependencyService.

**Comment by prashantvc** [comment]
I too am not sure if screenshot belongs in this plugin, any thoughts @jamesmontemagno ?
However, you are welcome to send a PR :)

**Comment by aherrick** [comment]
If not, perhaps the Share plugin? I feel it could find a home somewhere though.

**Comment by aherrick** [comment]
PR: https://github.com/jamesmontemagno/MediaPlugin/pull/489

**Comment by jamesmontemagno** [comment]
Not adding any new functionality to this plugin. Already too complex.
