### ISSUE TITLE
Images are always saved to Album

### ISSUE THREAD

**Issue by Vandersteen** [jamesmontemagno/MediaPlugin#488]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: Moto G3
Simulator Tested On:
Version of VS: Android 6.0
Version of Xamarin: 2.5.0
Versions of other things you are using:

### Steps to reproduce the Behavior
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        Directory = "Images",
                        SaveToAlbum = false,
                        Name = String.Format("img-{0}.jpg", DateTime.Now.Ticks),
                        PhotoSize = Plugin.Media.Abstractions.PhotoSize.Full,
                        RotateImage = false
                    });
### Expected Behavior

Image should not get saved in Gallery, but it still is

### Actual Behavior

The image is saved in the gallery, if i delete the file (from our app), the file is still in the gallery

**Comment by Vandersteen** [comment]
After some investigation, it appears it is not a issue with the plugin, but rather with the implementation of the camera app. There are some workarounds, but all very hackish.

In our case this is not intended and we will need to make a custom camera implementation.

**Comment by prashantvc** [comment]
Yes, you're right, it's not actually a bug with plugin. There are few other devices exhibit this behaviour.

**Comment by tylerseawell4** [comment]
@Vandersteen @prashantvc I have the SaveToAlbum = false, and mine is still saving to camera roll? What did you have to do to get around this?

**Comment by Vandersteen** [comment]
You cannot get around it without using some hacking solutions (which do not work 100% of the time) while you use the CameraIntent (which this plugin does).

The CameraIntent uses the available default camera app someone else wrote (google / samsung / ...), and that camera app does whatever it wants. If you do not want this you will have to write a custom camera implementation.
