### ISSUE TITLE
[Feature Request] Overwrite file

### ISSUE THREAD

**Issue by softclickbr** [jamesmontemagno/MediaPlugin#49]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
## Feature Request:

Plugin.Media.Abstractions.StoreCameraOptions would have a bool overwrite option, to overwite the file in the current directory if found, instead to rename _2 _3 etc.

**Comment by jamesmontemagno** [comment]
No new features.
