### ISSUE TITLE
NullExceptionError in iOS

### ISSUE THREAD

**Issue by jdausten97** [jamesmontemagno/MediaPlugin#490]
I have your plug-in working just fine for Android and now I'm trying to implement it for iOS. I'm developing in Visual Studio for Mac. Here is my ICommand code that calls the camera. As I said, it works fine for Android but gets a NullExceptionError when  trying to call AcquirePicture because cameraProvider is null. I've followed your readme instructions, added the two bits of info to my info.plist.

try
                    {
                        ICameraProvider cameraProvider = DependencyService.Get<ICameraProvider>();
                        ResumeImage = await cameraProvider.AcquirePicture();

                        if (ResumeImage != null)
                        {
                            var stream = await Common.GetStreamFromImageSourceAsync((StreamImageSource)ResumeImage);
                            PictureImages.Add(Convert.ToBase64String(stream.ReadAllBytes()));
                            OnPropertyChanged(nameof(ResumeImage));
                            IsRestartEnabled = true;
                            IsDoneEnabled = true;
                            pageCount += 1;
                            ScanPageText = "Scan Page " + pageCount;
                        }
                    }
                    catch (NullReferenceException)
                    {
                        MessagingCenter.Send(this, "PageError", "The image was not captured. Please try again.");
                    }
                    catch (Exception ex)
                    {
                        MessagingCenter.Send(this, "PageError", ex.Message);
                    }

**Comment by jamesmontemagno** [comment]
Not sure what an ICameraProfider is. See samples and docs.
