### ISSUE TITLE
Error testing the plugin (System.NullReferenceException: Object reference not set to an instance of an object.) FOR App

### ISSUE THREAD

**Issue by DanCaro** [jamesmontemagno/MediaPlugin#491]
I do all for use the pluging media to take photos, my frist issues it when y install  the  CurrentActivity don't create the class main application, but i read and create the file, then when  i trie to test mi aplication the LoadApplication(new App()); on mi file MainActivity show that error.

I don´t know why 

Version Number of Plugin: 3.1.3
Device Tested On: Android 4.4 Samsung
Version of VS: 2017

![image](https://user-images.githubusercontent.com/37224892/37226013-347f1298-239e-11e8-883b-3b6347f195c6.png)

**Comment by epracsupply** [comment]
I have the same problem.

**Comment by msjjd** [comment]
same problem :(

**Comment by jamesmontemagno** [comment]
Did you install the nuget into all projects. You can run the samples and see how to set it up.

**Comment by ali-h2010** [comment]
Did anyone manage to fix this issue?
It occurs on Android only
