### ISSUE TITLE
Troubles with Xam.Plugin.Media

### ISSUE THREAD

**Issue by epracsupply** [jamesmontemagno/MediaPlugin#493]
hello

I've been facing a trouble with my app using xam.plugin.media. I think it's a great plugin and I need to put it into my software.

I think I followed all steps describe by the documentation, but is not working yet.

Even, I downloaded the examples from github, and copy code portions to my app.

The error is:

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

The error is shown in the droid MainActivity, method OnCreate.

![image](https://user-images.githubusercontent.com/25669811/37243047-ccb6afea-2438-11e8-80c2-7b22a0ad6ddc.png)

This is my AndroidManifest

![image](https://user-images.githubusercontent.com/25669811/37243467-3b39931e-243f-11e8-8901-5de682257c98.png)

The xml directory and file_paths.xml file already exist.  All permissions have been configured.

Please excuse my English, 

Thank you for your help. I really appreciate it!

Version Number of Plugin:
Xam.Plugin.Media 3.1.3
Device Tested On:
Samsung Galaxy J5 Prime Android 7.0
Simulator Tested On:
Version of VS: 
2017 v 15.5.6
Version of Xamarin:
4.8.0.760

**Comment by jamesmontemagno** [comment]
Ensure all nugets are installed and up to date and that you follow the readme and try samples.
