### ISSUE TITLE
Image taken from iPhone shows rotated on Android device 

### ISSUE THREAD

**Issue by ravikanasagra1** [jamesmontemagno/MediaPlugin#495]
## Bug Information

Version Number of Plugin: 3.1.3 (Stable)
Device Tested On: IPhone 6, Motorola G5S+
Simulator Tested On: NA
Version of VS: VS 2015, VS Mac
Version of Xamarin: 4.8.0.756
Versions of other things you are using: NA

### Steps to reproduce the Behavior
Take Photo from IPhone camera and save binary in DB
If you open same binary in Image View on Iphone, it shows correct image
But If you open same image binary in Android device, it shows left side rotated image

### Expected Behavior
Image should show without rotation.

### Actual Behavior
Image shows rotated on android device

### Code snippet
```
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        SaveToAlbum = false,
                        CompressionQuality = 90,
                        PhotoSize = PhotoSize.Medium,
                        RotateImage = false,
                    });
```

### Screenshots
Image on Iphone (Taken on Iphone) ->
![correctimage](https://user-images.githubusercontent.com/19424672/37270792-2d9d1038-25f6-11e8-9dfb-7ad1a787dc79.jpg)

Image on Android (taken on Iphone) ->
![rotatedimage](https://user-images.githubusercontent.com/19424672/37270795-2fde2c88-25f6-11e8-9b1a-1ad57825f14d.jpg)

If I try to read EXIF, it gives TopRight. It should be TopLeft
```
using (var stream = file.GetStream())
                    {
                        var photoinfo = ExifLib.ExifReader.ReadJpeg(stream);
                        ExifLib.ExifOrientation orientation = photoinfo.Orientation;
                    }
```
Is there a way I can update, EXIF for this image file.

**Comment by jamesmontemagno** [comment]
Use: GetStreamWithImageRotatedForExternalStorage
