### ISSUE TITLE
[Feature Request] allow user to limit type of image being picked during PickPhotoasync

### ISSUE THREAD

**Issue by sam9116** [jamesmontemagno/MediaPlugin#497]
I am writing a xamarin app that relies on PickPhotoasync to pick photo to upload an image onto cloud storage. 

Due to file size restrictions I needed to resize image down to a smaller size. 

My resize function only supports png and jpg as inputs, it would be nice if I can specify phototype restrictions during pickphotoasync.

**Comment by jamesmontemagno** [comment]
No new features.
