### ISSUE TITLE
auto capture in xamarin.android

### ISSUE THREAD

**Issue by sagarmp02** [jamesmontemagno/MediaPlugin#499]
I need to implement auto capture image without user interaction after some seconds. help me
![lrfit](https://user-images.githubusercontent.com/37401688/37518807-c9f26570-293c-11e8-89dd-348783163f58.png)

**Comment by owenmodral** [comment]
Similarly, auto capture (without any user interaction) for a timelapse project would be fantastic. Is this possible?

**Comment by owenmodral** [comment]
Similarly, auto capture (without any user interaction) for a timelapse project would be fantastic. Is this possible?

**Comment by om297** [comment]
Similarly, auto capture (without any user interaction) for a timelapse project would be fantastic. Is this possible?

**Comment by jamesmontemagno** [comment]
Not possible with this library, you need platform specific implementations.
