### ISSUE TITLE
OutOfMemoryError android

### ISSUE THREAD

**Issue by rudacs** [jamesmontemagno/MediaPlugin#502]
## Bug Information

```
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Forcing collection of SoftReferences for 60MB allocation
[art] Starting a blocking GC Alloc
[art] Throwing OutOfMemoryError "Failed to allocate a 63489036 byte allocation with 8388608 free bytes and 49MB until OOM"
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Starting a blocking GC Alloc
[art] Forcing collection of SoftReferences for 60MB allocation
[art] Starting a blocking GC Alloc
[art] Throwing OutOfMemoryError "Failed to allocate a 63489036 byte allocation with 8388608 free bytes and 49MB until OOM"
```

Version Number of Plugin: 3.1.3
Device Tested On: Android Galaxy S5
Simulator Tested On: No
Version of VS: 7.4 for Mac
Version of Xamarin: Android 8.2.0.15
Versions of other things you are using:

### Steps to reproduce the Behavior

Select or Take Photo

### Expected Behavior

No crash

### Actual Behavior

Crash after select or take photo.

### Code snippet

```
var options = new PickMediaOptions
{
     CompressionQuality = 72
};
var file = await CrossMedia.Current.PickPhotoAsync(options);
```

**Comment by rudacs** [comment]
I have tested on other devices such as the Samsung A3 Duos. Everyone had the same problem.
Device power is not being taken into account.

**Comment by rudacs** [comment]
After setting the quality to 30, the error did not occur. But I can not use that quality.
Is there a way to solve this problem?

**Comment by jamesmontemagno** [comment]
Set android:largeHeap="true" in your android manifest "Application" node.
