### ISSUE TITLE
Localization for Andriod and UWP

### ISSUE THREAD

**Issue by mmarshad** [jamesmontemagno/MediaPlugin#504]
Hi, I need to show the localized text and custom buttons (if possible) like "Retry" and "OK" on confirmation screen. my question is how can I customize that screen (If I can) and also pass the localize strings for the button labels. Please note that I'm using .NETStandard project and .resx files for resources.
My other question is that when we take photo it shows the confirmation screen, before proceeding further, Is it possible to skip that view?

**Comment by jamesmontemagno** [comment]
Android and UWP use the system UIs so they get translated by the parent app.

**Comment by mmarshad** [comment]
Thanks for the response. Could you please explain how do I translate or add resources for these in my parent app as I'm new to this and this is my first project.
Thanks in advance
