### ISSUE TITLE
Hiding the video button while capturing photo

### ISSUE THREAD

**Issue by mmarshad** [jamesmontemagno/MediaPlugin#505]
How can I disable or hide the "Video" button (Red Circle) while taking photo using TakePhotoAsync () method or customize the view (e.g hiding zoom feature, image gallary option, settings button from top etc)

**Comment by prashantvc** [comment]
Could you give us more information please? What device is this? iOS/Android version

**Comment by mmarshad** [comment]
Well my app would be targeting for all three platforms (iOS/Andriod/UWP) however in first instance I'm concentrating on Android only.

**Comment by jamesmontemagno** [comment]
This is the device UI, we have no control.
