### ISSUE TITLE
Plugin.Media.Abstractions.MediaPermissionException

### ISSUE THREAD

**Issue by h4rdc0d3** [jamesmontemagno/MediaPlugin#509]
When I debug my app in Android API 19 it works but when I debug in Android API 24 the exception "Plugin.Media.Abstractions.MediaPermissionException: Camera permission (s) is required" is displayed when I want to access the camera and this exception comes out when I want to select a photo from the gallery "Plugin.Media.Abstractions.MediaPermissionException: Storage permission (s) are required".

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: Samsung Galaxy S7 (API 24), Samsung Galaxy Tab E (API 19)
Simulator Tested On: N/A
Version of VS: 15.6.4
Version of Xamarin: 4.9.0.752
Versions of other things you are using: Xam.Plugin.Connectivity 3.1.1, Xam.Plugins.Settings 3.1.1

#### C#
````csharp
private ImageSource imageSource;
private MediaFile file;

private async void prueba(object sender, EventArgs args)
        {
            await CrossMedia.Current.Initialize();

            if (CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakePhotoSupported)
            {
                var source = await DisplayActionSheet("¿Donde tomar la imagen?", "Cancelar", null, "Galeria", "Camara");

                switch (source)
                {
                    case "Cancelar":
                        file = null;
                        break;
                    case "Galeria":
                        file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                        {
                            PhotoSize = PhotoSize.Small
                        });
                        break;
                    case "Camara":
                        file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                        {
                            Name = "prueba.jpeg",
                            PhotoSize = PhotoSize.Small,
                            SaveToAlbum = true
                        });
                        break;
                    default:
                        break;
                }
            }
            else
            {
                file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                {
                    PhotoSize = PhotoSize.Small
                });
            }

            if (file != null)
            {
                imageSource = ImageSource.FromStream(() =>
                {
                    var stream = file.GetStream();
                    file.Dispose();
                    return stream;
                });

                imageProduct.Source = imageSource;
            }
        }
````

#### AndroidManifest
````xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.Shopm" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="15" android:targetSdkVersion="27" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.FLASHLIGHT" />
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<application android:label="Shopm">
    <provider android:name="android.support.v4.content.FileProvider"
          android:authorities="${applicationId}.fileprovider"
          android:exported="false"
          android:grantUriPermissions="true">

      <meta-data android:name="android.support.FILE_PROVIDER_PATHS"
                       android:resource="@xml/file_paths"></meta-data>
    </provider>
  </application>
</manifest>
````

**Comment by jamesmontemagno** [comment]
You don't need to add the permissions in there...
I automatically add Camera/Write External and handle it from there.

**Comment by h4rdc0d3** [comment]
The permissions do not add them to me automatically, I have to add them manually in Android to make it work. Is it necessary to install PermissionsPlugin to show me the Android window that the application needs Camera/Write External permissions?

**Comment by jamesmontemagno** [comment]
We compile them in at run time, which means you don't need to add them at all.

Else the permission plugin which is installed in this will pop up the dialog boxes for you automatically.

**Comment by h4rdc0d3** [comment]
I have done what you said, I compiled a released version for Android and installed it on my smarthphone with Android API 24, when I click on the button to take a picture or take a picture of the Android gallery it should show a dialog box but does not show me the dialog box for Camera / External Write permissions. I have to assign the permissions manually from settings / applications / myapp

**Comment by lombardac** [comment]
I have the same issue after targeting Android 8.1 API 27

**Comment by robedyvean** [comment]
getting Plugin.Media.Abstractions.MediaPermissionException: Camera permission(s) are required when running in Oreo ...

**Comment by robedyvean** [comment]
Actually it was my bad. When you install the plugin in Visual Studio it comes up with a comprehensive readme file within VS - once I had faithfully applied all the relevant advice it worked. I think the answer for me was CrossCurrentActivity.Current.Init(this, bundle);

**Comment by crystallove** [comment]
> Actually it was my bad. When you install the plugin in Visual Studio it comes up with a comprehensive readme file within VS - once I had faithfully applied all the relevant advice it worked. I think the answer for me was CrossCurrentActivity.Current.Init(this, bundle);

Really? Is this working with you? Im still facing to below error after take picture from camera. 
"System.ArgumentException: Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project."
Could you please help to resolve this?

**Comment by rcunniffe** [comment]
"Actually it was my bad. When you install the plugin in Visual Studio it comes up with a comprehensive readme file within VS - once I had faithfully applied all the relevant advice it worked. I think the answer for me was CrossCurrentActivity.Current.Init(this, bundle);"

I've done the same but specifically for using the camera it fails with "Plugin.Media.Abstractions.MediaPermissionException: Contacts permission(s) are required." `CrossCurrentActivity.Current.Init(this, bundle);` is working as for other permissions like viewing gallery it's fine.

I've asked for permission in the code, accepted on the screen. Also updated the manifest with, camera, storage, contacts and a few others i already use. 

Any ideas?

**Comment by AbdulrahmanHO** [comment]
Hi,
After adding the required Permissions in Android for CAMERA, Read/Write External Storage, either in AndroidManifest.xml or at Android Project>>Properties>>Android Manifest>>Required Permissions; then make sure to enable the permission from your Device/Emulator itself:
go to your Device or Emulator then Sittings>>search for Permission>> App Permissions>> Camera>>then Enable your deployed App to use Camera.
Appreciated...

**Comment by greektreat** [comment]
I'm really stuck on this. I have gone throught the steps over and over and I'm still getting the same error. Not sure what to do next,
"Plugin.Media.Abstractions.MediaPermissionException: Camera permission(s) are required."
My Device is running Android 7.1 I looked at each file in the sample and it is implemented the same way.

**Comment by H4rdC0d3** [comment]
It's been a while since I solved the problem but I do not remember how I solved it. I remember that I installed a plugin called [Permissions Plugin for Xamarin](https://github.com/jamesmontemagno/PermissionsPlugin) and followed the steps indicated by James. In the file MainActivity.cs of the Android project modify the following line:
```csharp
Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity.Init(this, bundle);
```
for this:
```csharp
Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
```
Because I produced compilation errors by other James plugins. Finally I was uploading the minimum API version to 19 (I recommend programming from API 21).

**Comment by chamunzira** [comment]
> It's been a while since I solved the problem but I do not remember how I solved it. I remember that I installed a plugin called [Permissions Plugin for Xamarin](https://github.com/jamesmontemagno/PermissionsPlugin) and followed the steps indicated by James. In the file MainActivity.cs of the Android project modify the following line:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity.Init(this, bundle);
> ```
> 
> for this:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
> ```
> 
> Because I produced compilation errors by other James plugins. Finally I was uploading the minimum API version to 19 (I recommend programming from API 21).

This worked for me

**Comment by greektreat** [comment]
> It's been a while since I solved the problem but I do not remember how I solved it. I remember that I installed a plugin called [Permissions Plugin for Xamarin](https://github.com/jamesmontemagno/PermissionsPlugin) and followed the steps indicated by James. In the file MainActivity.cs of the Android project modify the following line:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity.Init(this, bundle);
> ```
> 
> for this:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
> ```
> 
> Because I produced compilation errors by other James plugins. Finally I was uploading the minimum API version to 19 (I recommend programming from API 21).

Thanks for this, It started working all of a sudden. I did move the whole solution to another location and added it to git. Maybe there was something weird with the files

**Comment by DeveloperAntonKuznietsov** [comment]
> It's been a while since I solved the problem but I do not remember how I solved it. I remember that I installed a plugin called [Permissions Plugin for Xamarin](https://github.com/jamesmontemagno/PermissionsPlugin) and followed the steps indicated by James. In the file MainActivity.cs of the Android project modify the following line:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity.Init(this, bundle);
> ```
> 
> for this:
> 
> ```cs
> Plugin.CurrentActivity.CrossCurrentActivity.Current.Activity = this;
> ```
> 
> Because I produced compilation errors by other James plugins. Finally I was uploading the minimum API version to 19 (I recommend programming from API 21).
> 
> Another factor that is possible is that when compiling in Debug mode, you should put in Release mode when compiling, because in my case when compiling in Debug mode it did not show the window to accept permissions. (Check)

Good Job

**Comment by janeirojoaopedro** [comment]
CrossCurrentActivity.Current.Init(this, bundle)
Work for my! Thanks @robedyvean

**Comment by jmontana10** [comment]
this plugin generates errors on all sides
