### ISSUE TITLE
Broken camera image rotation on WP8.1 for Lumia 930

### ISSUE THREAD

**Issue by jimutt** [jamesmontemagno/MediaPlugin#51]
## Bug 

Version Number of Plugin: 2.5.1.0 (have experienced the same issue on 2.3 as well)
Device Tested On: Nokia Lumia 930 (Windows Phone 8.10.14234.375)
Simulator Tested On: N/A

### Expected Behavior
The camera image should be properly rotated no matter the device orientation when using TakePhotoAsync. 

### Actual Behavior
On the specific device the WinPhoneRT version of the media plugins rotates the image 90 degrees counter clockwise when in portrait mode. If tilting the device 90 degrees to the left, placing it in landscape mode the camera image rotation is correct. But if tilting it to the right the image is upside down. In other words: the camera image does not readjust according to the device orientation. 

Please refer to these images:
[Portrait](https://1drv.ms/i/s!ArvY_GnQCZJ_hKYkk7f9wC4Qrrgl6A)
[Normal landscape](https://1drv.ms/i/s!ArvY_GnQCZJ_hKYgIzLazWIpu6ON_A)
[Flipped landscape](https://1drv.ms/i/s!ArvY_GnQCZJ_hKYfuQcr4g7w3Hfraw)

### Steps to reproduce the Behavior
Build and run a basic Windows Phone 8.1 RT app running the default code example from the plugin home page (the code below "Usage"). Or download this example project: https://1drv.ms/u/s!ArvY_GnQCZJ_hKYoSmuvJUfsxIy8Fg

I've only been able to test the application using the Lumia 930. So I don't know if it's working on other WP8.1 devices. On Android I've never experienced this issue though.

**Comment by jimutt** [comment]
Update: Had the possibility to test this on a Lumia 925 as well (running WP 8.1.14225.359) and got the exact same behaviour.

**Comment by jluisestrada** [comment]
I tested this on a Lumia 535 and Im able to reproduce this bug (WP 8.10.14234.375)

**Comment by jimutt** [comment]
Any update/comment on this one? :) I consider it a quite big issue since the behaviour is really not expected from a user's standpoint.

**Comment by jluisestrada** [comment]
I copied the branch and made the change myself? Do you want it? Or maybe I could make a pull request

**Comment by jimutt** [comment]
@jluisestrada  Yes, sure! Would be great if you could share it with me. Though maybea pull request would be nice as well.

**Comment by jamesmontemagno** [comment]
@jluisestrada  Please send down a PR if there is a fix out there for it so I can review.

**Comment by marcojak** [comment]
Same problem here.

Do you have a solution?

**Comment by jamesmontemagno** [comment]
Will merge in #75 soon after a few tweaks and get a new beta build up.
