### ISSUE TITLE
Take photo and store to memory

### ISSUE THREAD

**Issue by raV720** [jamesmontemagno/MediaPlugin#510]
Saving photo to storage takes some time but it is not needed in some cases. It would be better performance to allow to save photo directly to memory instead of file (byte array or memory stream or sth).

**Comment by vbisbest** [comment]
Same issue here.  I just need the bytes.

**Comment by davidpsaylor** [comment]
I'd like the bytes without a file as well, but for a different reason.  I'd like the photo to not be stored on the device directly because there could be patient health information in the picture.  We protect it in our app, but can't do anything outside of it.

**Comment by jamesmontemagno** [comment]
No new features.
