### ISSUE TITLE
[FeatureRequest] Add a way to indicate an image has been selected or taken

### ISSUE THREAD

**Issue by professeurburp** [jamesmontemagno/MediaPlugin#511]
We are currently using MediaPlugin to let the use take a photo or pick one from its gallery and update an image through a REST webservice.

Due to bandwidth limitations and later display size, we are limiting image sizes to either 256 or 1024px, using _PhotoSize.MaxWidthHeight_ options.

The trouble is, in that case, post-processing is made during the awaitable _PickPhotoAsync()_ and _TakePhotoAsync() tasks, without any possibility outside these tasks to know when the image has actually been selected and post-processing is now happening.

This creates a delay that can be several seconds long when the original image is quite large, as the gallery is still displayed throughout the image post processing, and can be misleading for the user, as there is no possibility for him to be sure an image has actually been selected.

Unluckily, I have no clue on how this could be done effectively and properly, maybe stopping camera or gallery display as soon as an image has been selected, providing an event and/or a callback so that the caller gets a way to react, such as displaying an activity indicator in the meantime, for instance, but this is totally open to discussion.

**Comment by jamesmontemagno** [comment]
No new features.
