### ISSUE TITLE
Crash app on Huawei - Take Photo

### ISSUE THREAD

**Issue by sinappsys** [jamesmontemagno/MediaPlugin#512]
With the Xam.Plugin.Media 3.1.3 library on Huawei the app crashes when trying to take a picture.
It's a big problem! Many Huawei devices that are in production crashing.
I hope you find a solution as soon as possible

Thank you

## Bug Information

Version Number of Plugin: Xam.Plugin.Media 3.1.3 
Device Tested On: HUAWEI MODEL: ALE L21, VNS-L31, MYA-L11, CAM-L21, WAS-LX1, WAS-LX1A,RNE-L21, FRD-L09, SCL-L21, PRA-TL10.
Version of VS: Visual Studio 2017
Version of Xamarin:  2.5.0.122203
ANDROID >= 5.0

### Code snippet
                       await CrossMedia.Current.Initialize();
                        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                        {
                            await DisplayAlert("Attenzione", "La fotocamera non è disponibile", "OK");
                            return;
                        }
                        var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                        {
                            PhotoSize = Plugin.Media.Abstractions.PhotoSize.MaxWidthHeight,
                            MaxWidthHeight = 1024,
                            DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
                            CompressionQuality = 92,
                            AllowCropping = false,
                            Directory = "TempSelfie",
                            Name = "selfiephoto.jpg"
                        });

### Output Crash
Xamarin caused by: android.runtime.JavaProxyThrowable: System.ArgumentException: Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project. ---> Java.Lang.IllegalArgumentException: Failed to find configured root that contains /storage/0000-0000/Android/data/com.sinappsys.prizeme/files/Pictures/TempSelfie/selfiephoto_2.jpg
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()<a938d5e7ad4e464d84b51834aa647f9e>:0
Java.Interop.JniEnvironment.StaticMethods.CallStaticObjectMethod(JniObjectReference type, JniMethodInfo method, JniArgumentValue* args)<c54c96d1b94441d894da3d0aa5ba3546>:0
Android.Runtime.JNIEnv.CallStaticObjectMethod(IntPtr jclass, IntPtr jmethod, JValue* parms)<f3b831d1fb2e42f68fdd2f345c3c06d3>:0
Android.Support.V4.Content.FileProvider.GetUriForFile(Context context, string authority, File file)<dc495abdac154ae3bea326f4da3a4ec0>:0
Plugin.Media.MediaPickerActivity.OnCreate(Bundle savedInstanceState)<53eb7f81ed534faeabc15483d2bbce6a>:0
--- End of inner exception stack trace ---
Plugin.Media.MediaPickerActivity.OnCreate(Bundle savedInstanceState)<53eb7f81ed534faeabc15483d2bbce6a>:0
Plugin.Media.MediaImplementation.<TakePhotoAsync>d__17.MoveNext()<53eb7f81ed534faeabc15483d2bbce6a>:0
UXDivers.Artina.Grial.FotoPage.<>c__DisplayClass7_0.<<ScattaFoto>b__0>d.MoveNext()<dc9eb174bb484268b168a651d44c99bf>:0
Android.App.SyncContext.<>c__DisplayClass2_0.<Post>b__0()<f3b831d1fb2e42f68fdd2f345c3c06d3>:0
Java.Lang.Thread.RunnableImplementor.Run()<f3b831d1fb2e42f68fdd2f345c3c06d3>:0
Java.Lang.IRunnableInvoker.n_Run(IntPtr jnienv, IntPtr native__this)<f3b831d1fb2e42f68fdd2f345c3c06d3>:0
at (wrapper dynamic-method) System.Object:1fb178b9-43d9-405c-ba44-515b62a06e9e (intptr,intptr)
mono.java.lang.RunnableImplementor.n_run(Native Method)
mono.java.lang.RunnableImplementor.run()RunnableImplementor.java:30
android.os.Handler.handleCallback()Handler.java:761
android.os.Handler.dispatchMessage()Handler.java:98
android.os.Looper.loop()Looper.java:156
android.app.ActivityThread.main()ActivityThread.java:6523
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run()ZygoteInit.java:942
com.android.internal.os.ZygoteInit.main()ZygoteInit.java:832

**Comment by jamesmontemagno** [comment]
Duplicate #496
