### ISSUE TITLE
Camera Settings

### ISSUE THREAD

**Issue by acaliaro** [jamesmontemagno/MediaPlugin#515]
Hi guys.
I have a question.

When the camera is open, I can modify "camera settings" (for example, on a Zebra TC70 device, I long press the display and a lot of icons appears so I can change settings). Is it possible not to visualize these settings? I would like only to take photo and videos without change settings...

Thanks

**Comment by jamesmontemagno** [comment]
The library just launches the default camera app and doesn't know anything about it.
