### ISSUE TITLE
After checking storage permission, In iOS PickPhotoAsync opening permission popup

### ISSUE THREAD

**Issue by shrutigoyal123** [jamesmontemagno/MediaPlugin#517]
@jamesmontemagno Please help.
## Bug Information

Version Number of Plugin:3.1.3
Device Tested On: iPhone 6s+, iOS 10

### Steps to reproduce the Behavior
I am using Plugin.Permission for checking storage and camera permission. It is working in android properly but in iOS If I check storage permission then it is giving 'Granted' which is expected.But PickPhotoAsync function redirecting to gallery along with a storage permission popup.

### Expected Behavior
If Storage permission is granted then PickPhotoAsync function should not open the popup. Or is popup is opening It should not redirect to gallery for picking any photo.

### Actual Behavior
PickPhotoAsync function redirecting to gallery along with a storage permission popup.

### Code snippet
storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                        if (storageStatus != PermissionStatus.Granted)
                        {
                            storageStatus = await Utils.CheckPermissions(Permission.Storage);
                        }
                        if (storageStatus == PermissionStatus.Granted)
                        {
                            photo = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
                            {
                                PhotoSize = PhotoSize.Small,
                                CompressionQuality = 92,

                            });
                            if (photo == null)
                                return;
                            galleryFilePath = photo.Path;
                            using (var memoryStream = new MemoryStream())
                            {
                                photo.GetStream().CopyTo(memoryStream);
                                photo.Dispose();
                                picData = memoryStream.ToArray();
                            }
                        }

**Comment by jamesmontemagno** [comment]
iOS needs photos permissions.

**Comment by shrutigoyal123** [comment]
@jamesmontemagno 

If PickPhotoAsync opening permission popup Then Plugin.Permission should give denied and Utils.CheckPermissions function should open the popup but at this time popup is not opening .Instead on PickPhotoAsync function gallery and popup both are opening at the same time.

Lets assume I don't have photo permission then it should not open gallery with out allow photo permission.

It's behaviour is quite strange. Please help.
