### ISSUE TITLE
Need to record video in the background

### ISSUE THREAD

**Issue by federicoparra** [jamesmontemagno/MediaPlugin#518]
Hi, I'm building an app in which images are shown and the camera records the facial expressions the person does as a reaction to those pictures. Since the stimuli (the pictures) should occupy the full screen of the device, there is no place for any controls (i.e. record button and the like). So video recording shall start, then images are shown, then video stops recording. 

I managed to do that in a UWP project with UWP apis and I am trying now to do it in Xamarin Forms to make it work on Android and iOS. 

Is there a way to do that with your plugin out of the box?

Otherwise, do you think it is worth modifying this plugin, or what I am trying to do is so different I would do better starting all over again coding my own plugin?

Thank you so much,

Federico

**Comment by jamesmontemagno** [comment]
Not possible with this plugin

**Comment by federicoparra** [comment]
Thank you! 

Any other plugin you'll recommend for this? Otherwise any other clue for me to pursue?
