### ISSUE TITLE
Photos being saved in gallery

### ISSUE THREAD

**Issue by matheusgigliotti** [jamesmontemagno/MediaPlugin#523]
All pictures taken by this device are showing on google photos app (motorola use google photos app as gallery).

This is only happening on this model of device.

I recorded a video of the actual behavior.

https://streamable.com/j46ep

Bug Information
Version Number of Plugin: 3.1.1
Device Tested On: Moto C Plus XT1726
Simulator Tested On: None
Version of VS: Visual Studio Enterprise 2017, Version 15.5.6
Version of Xamarin: 4.8.0.760
Versions of Xamarin.Android.SDK 8.1.5.0

Expected Behavior
Picture taken should not be saved in gallery.

Actual Behavior
Photos are being saved in gallery.

Code snippet

https://github.com/matheusgigliotti/PhotoApp/tree/master/PhotoApp

        private async void BtnSaveToAlbum_Clicked(object sender, EventArgs e)
        {
            await TakePicture(true);
        }

        private async void BtnDontSaveToAlbum_Clicked(object sender, EventArgs e)
        {
            await TakePicture(false);
        }

        private async Task TakePicture(bool saveToAlbum)
        {
            var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
            var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);

            if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
                cameraStatus = results[Permission.Camera];
                storageStatus = results[Permission.Storage];
            }

            if (cameraStatus == PermissionStatus.Granted && storageStatus == PermissionStatus.Granted)
            {
                await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    await DisplayAlert("No Camera", ":( No camera available.", "OK");
                    return;
                }

                var name = string.Format("PhotoApp_{0}", DateTime.Now.ToString("yyMMddhhmmss"));

                var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
                    SaveToAlbum = saveToAlbum,
                    Name = name,

                });

                if (file == null)
                    return;

                //await DisplayAlert("File Location", file.Path, "OK");

                image.Source = ImageSource.FromStream(() =>
                {
                    var stream = file.GetStream();
                    return stream;
                });
            }
            else
            {
                await DisplayAlert("Permissions Denied", "Unable to take photos.", "OK");
                //On iOS you may want to send your user to the settings screen.
                //CrossPermissions.Current.OpenAppSettings();
            }
        }

Screenshots

https://streamable.com/j46ep

**Comment by jamesmontemagno** [comment]
Duplicate: https://github.com/jamesmontemagno/MediaPlugin/issues/89
