### ISSUE TITLE
Access image from local storage manually

### ISSUE THREAD

**Issue by btidoug** [jamesmontemagno/MediaPlugin#526]
I have my Xamarin.Forms app working perfectly with the plugin for taking and picking photos.  The app will handle the image and upload to a website just fine. My problem is that my app also runs in offline mode.  I will store various data in a table locally along with the path and filename of any image taken or picked.  Then, when the device is back on line, my app will upload the local records and image to the web site.

When the app comes back online, I don't know how to load the file from the stored path into a MediaFile object so I can just re-use my current code for uploading the image.  Any ideas?

**Comment by omon77** [comment]
`new MediaFile(file.Path, () => file.OpenStreamForReadAsync().Result, albumPath: null);`
Doesn't that work?

**Comment by btidoug** [comment]
I will definitely try that out!

**Comment by omon77** [comment]
First parameter - file.Path is the string property, containing the path to the image on the local device.

**Comment by btidoug** [comment]
Ok - and the what object is file?  system.io file or something different?

**Comment by omon77** [comment]
In the code I posted, it's Storage file.
You can just pass the string with the path, though.

**Comment by btidoug** [comment]
@omon77  sorry for being so dense.  I'm just not getting it.  My app is in Xamarin.Forms and I am just focusing on the Android part for now.  The below snippet of code is in the viewmodel of the pcl project where I read the data from the local sqlite db and try to go and grab the actual file from local storage and prepare to upload to web api.  What am I missing?

```
AccountingDTO receiptDTO = new AccountingDTO
{
     Email = AppSettings.Email,
     Token = AppSettings.Token,
     AccountCategoryId = receipt.AccountCategoryId,
     Amount = receipt.Amount,
     Date = receipt.Date,
     Description = receipt.Description,
     Note = receipt.Note,
     Filename = receipt.Filename, <------ this is just a string to the local file
     Mileage = false
};

var file = new MediaFile(receipt.Filename, () => System.IO.File.OpenStreamForReadAsync().Result, albumPath: null);

```
... and then I call my rest client to do the upload to my web api.

**Comment by omon77** [comment]
@btidoug Isn't it working? What exactly isn't working?

**Comment by btidoug** [comment]
@omon77 the "system.io.file ... " part of the var file = line is not compiling.  What should that line look like?

![error](https://user-images.githubusercontent.com/6748163/39192329-f30c648c-47a6-11e8-9935-98810d818cbd.png)

**Comment by omon77** [comment]
@btidoug try replacing second parameter
`() => System.IO.File.OpenStreamForReadAsync().Result`
with something like this
`() => { using (var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read))
{
	return new StreamReader(fileStream).ReadToEnd();
}}`

**Comment by btidoug** [comment]
![error](https://user-images.githubusercontent.com/6748163/39199508-a27c0444-47b7-11e8-9c9d-bfc64b1a9630.png)

**Comment by jamesmontemagno** [comment]
File.OpenRead(path) should work jsut fine.

**Comment by jamesmontemagno** [comment]
You shouldn't be creating a new Media File... that is for the API.

You have the path... do `File.OpenRead(path)` and go from there to convert it into byte[] to upload.
