### ISSUE TITLE
Image is flipped horizontally when using front facing camera

### ISSUE THREAD

**Issue by sqlboy2000** [jamesmontemagno/MediaPlugin#53]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: iPhone 6s Plus, Moto E
Simulator Tested On: x86 Android

### Expected Behavior

I'm using the sample application - when I click "take photo" then switch to the front facing camera and click the camera button, the image returned should look identical to the preview.

### Actual Behavior

I'm using the sample application - when I click "take photo" then switch to the front facing camera and click the camera button, the image returned is flipped on it's horizontal axis.

### Steps to reproduce the Behavior

Launch the sample application, switch to the front facing (selfie) camera, and take a photo. The returned image will be incorrectly flipped horizontally.

**Comment by jamesmontemagno** [comment]
Have you tried updating to the latest beta release of the NuGet? the fix is in there based on the device you are on.

**Comment by sqlboy2000** [comment]
I have not. Are your betas stable enough for production use or should I wait for next version?

**Comment by jamesmontemagno** [comment]
The current version is extremely close to being released as stable. I think maybe even  more stable then stable currently.

**Comment by jamesmontemagno** [comment]
You can always revert back if you need to easily.

**Comment by sqlboy2000** [comment]
Ok, I'll try and let you know.

**Comment by sqlboy2000** [comment]
Same problem. Still only happens when I swap to the front facing camera. Main camera works fine.

**Comment by jamesmontemagno** [comment]
Was this on Android or iOS or both that you have tested the latest beta on?

**Comment by sqlboy2000** [comment]
Both. I have a Moto E running Android 22 and my iPhone 6s Plus running iOS 9.3.4.

**Comment by jamesmontemagno** [comment]
Interesting.... will give it a test here tomorrow.

I was using and demoing 2.3.0 and 2.5.1 on my nexus 6 (Android API 21 (5.1.1)) with no issues, will test on 6p too.

**Comment by appdog** [comment]
Can confirm that rotation is less of an issue in most scenarios on Android, but unfortunately I have seen issues with Sony Z2 (D6503, OS version 6.0.1) when using 2.5.1-beta38. I understand that the beta38 is the beta release fixing the rotation issue?

**Comment by sqlboy2000** [comment]
I tried the Beta and it did not fix the issue.

**Comment by appdog** [comment]
Here are my results using version 2.5.1-beta38:

- Sony D6503 (Android 6.0.1) - incorrect orientation
- Samsung S5 Neo (Android 5.1.1) - correct orientation
- iPhone 5 (iOS 10) - correct orientation

**Comment by jamesmontemagno** [comment]
Here is where I am rotating and re-sizing: https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.Android/MediaImplementation.cs#L386

My recommendation is to step through the code for your Sony and see if it is returning the correct information.

**Comment by jamesmontemagno** [comment]
Closing for now as I can't attempt to rotate if the Exif data doesn't exist, sorry.

**Comment by tomeastmanjr** [comment]
I see where all of the confusion is here, as I was just experiencing the same issue.

I took a selfie and held up a finger pointing left. The preview showed this as pointing left. When it saved, it was pointing right. This did not seem like the desired result to me.

I then held up a sticky note with writing on it. The screen showed the text backwards in the preview. When it saved, the text was showing properly.

I am guessing that your issue @sqlboy2000 is the same as mine, a different perspective and expected outcome. The preview is the one flipping the picture to make it easier on our brains (I had never actually paid attention to this). The camera is taking the picture and saving it properly.
