### ISSUE TITLE
I get an "Unhandled Exception:  System.ArgumentException: Unable to get file location." when running on galaxy s5 android

### ISSUE THREAD

**Issue by TheMo** [jamesmontemagno/MediaPlugin#530]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: 28th april 2018
Simulator Tested On: 28th april 2018
Version of VS: 2017 15.6.6
Version of Xamarin: 
Versions of other things you are using:

### Steps to reproduce the Behavior
download the the sample project from mediaPlugin

### Expected Behavior
It should take pictures and it should take videos

### Actual Behavior
Getting the follwing error:
Unhandled Exception:

System.ArgumentException: Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project. occurred

### Code snippet
Android.manifest
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="App1.Android" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="27" />
	<application android:label="App1.Android" android:icon="@drawable/icon"></application>
	<provider android:name="android.support.v4.content.FileProvider" 
            android:authorities="App1.Android.fileprovider" 
            android:exported="false" 
            android:grantUriPermissions="true">
		<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
	</provider>
</manifest>`

---------------------------------------------------------------------------------
filepath xml:

`<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-files-path name="my_images" path="Pictures" />
  <external-files-path name="my_movies" path="Movies" />
</paths>`

**Comment by jamesmontemagno** [comment]
change the package and authority to something like:


com.test.app and com.test.app.fileprovider

**Comment by TheMo** [comment]
Hi,
No that did not help. 

![package name](https://user-images.githubusercontent.com/999020/39403776-1499daae-4b84-11e8-83be-dac57c2b5006.JPG)
![android manifest](https://user-images.githubusercontent.com/999020/39403777-14b5c14c-4b84-11e8-81db-b9e894b7b147.JPG)

**Comment by TheMo** [comment]
I got fixed.
If you look at the image I uploaded the provider section was not in between the application tags. After doing that I still got the same error. Than I followed the solution on this page [https://forums.xamarin.com/discussion/119942/mediaplugin-argument-exception-unable-to-get-file-location](url) and it worked. I hope you can change the documentation.

**Comment by satyansh-sagar** [comment]
@TheMo The page you tagged is not there.

**Comment by satyansh-sagar** [comment]
@TheMo Cool, it worked, But the linked you gave doesn't exist.

I have attached the solution.
![image](https://user-images.githubusercontent.com/30821164/39810467-b5832170-53a2-11e8-995d-ca67fdbbfcb3.png)


basically , we have to keep the provider tag inside the application tag.
