### ISSUE TITLE
Camera not working in Release Mode

### ISSUE THREAD

**Issue by foxkarthick** [jamesmontemagno/MediaPlugin#531]
My Coding is working In Debug Mode, Camera is not responding after Release and installed in other devices. 
Bellow is the error message.

"Unable to get file location, this most likely means that the file provider information is not set in your android manifest file. please check documentation on how to set this up in your project."

eve after added manifest file also facing the same issue. 

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: 30-Apr-2018
Simulator Tested On: 30-Apr-2018
Version of VS: 2017
Version of Xamarin: 2.4.0.280
Versions of other things you are using:

**Comment by maherzaidoune** [comment]
same  problem here 
xamarin forms 3.0.0.482
media plugin 4.0.0.9

**Comment by jamesmontemagno** [comment]
did you setup the file provider? did you change your package name? Working for me.

**Comment by roymjohn** [comment]
Assemblies for these plugins are not loaded in release mode...Load it via Forms.Init method.
https://forums.xamarin.com/discussion/95851/correct-way-of-calling-xamarin-forms-init-on-uwp
