### ISSUE TITLE
Playing video in Android Preview is not possible?

### ISSUE THREAD

**Issue by TheMo** [jamesmontemagno/MediaPlugin#534]
## Bug Information

Version Number of Plugin:3.2.1
Device Tested On: samsung galaxy s5
Simulator Tested On:
Version of VS:  2017.15.6.7
Version of Xamarin:
Versions of other things you are using: xamarin forms 2.5

### Steps to reproduce the Behavior
Record a video and push play in preview
### Expected Behavior
Should play video
### Actual Behavior
Getting message box with following message:
Unable to play video, Sorry, this video cannot be played.

**Comment by dtelaroli** [comment]
Same problem with:
Moto G2 XT1069
Android 6.0

**Comment by jamesmontemagno** [comment]
This would be a problem with the phone as it is in the camera app at that point.
