### ISSUE TITLE
select from gallery.

### ISSUE THREAD

**Issue by szaid07** [jamesmontemagno/MediaPlugin#535]
How to access the gallery of a device to select the image from the gallery.

**Comment by Axemasta** [comment]
You can find the sample code for this [in the sample provided in this repo.](https://github.com/jamesmontemagno/MediaPlugin/blob/master/samples/MediaSample/MediaSample/MediaPage.xaml.cs)

Forgetting permissions (which you must check for) you can simply call:

```
var image = await CrossMedia.Current.PickPhotoAsync();

if (image == null)
{
    return;
}

//do something
```
Hope this helps!
