### ISSUE TITLE
Last version + Plugin.Permissions 3.0.0.8 Build error: could not load assembly 'Plugin.Permissions.Abstractions, Version=2.2.1.0

### ISSUE THREAD

**Issue by SyaoranChang** [jamesmontemagno/MediaPlugin#537]
I install Xam.Plugin.Media 3.2.1 + Plugin.Permissions 3.0.0.8
I build I get this error:
error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Plugin.Permissions.Abstractions, Version=2.2.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
error : File name: 'Plugin.Permissions.Abstractions.dll

## Bug Information

Version Number of Plugin: 3.2.1
Device Tested On:
Simulator Tested On:
Version of VS: 15.7.1
Version of Xamarin: 4.10.0.442
Versions of other things you are using:

**Comment by jamesmontemagno** [comment]
I have rolled back this updated for now.
