### ISSUE TITLE
How to choose video codec when taking video on iOS

### ISSUE THREAD

**Issue by alihaluk** [jamesmontemagno/MediaPlugin#538]
I use CrossMedia on my Xamarin.Forms project. Our customers has various models of devices. Apple started took videos on HEVC format with iPhone 8 and iOS 11 as default. We encountered a quite interesting problem recently.

The video taken on iPhone X has HEVC (h.265) video codec.

The video taken on older than iPhone 8 such as 6s, has h.264 video codec.

The new codec, HEVC, has issues about running properly on HTML. Only voice, no picture.

So I wonder about that Is there any chance to set video codec in StoreVideoOptions or anywhere else ?

P.S: I am aware about that this is not a bug of the plugin but may be it considered as an enhancement or I can get some help.

**Comment by frooti7** [comment]
@jamesmontemagno  please provide update on this issue?

**Comment by jamesmontemagno** [comment]
This is not possible as we pop up the standard camera control. I don't believe you can specify any of that.
