### ISSUE TITLE
Camera not showing

### ISSUE THREAD

**Issue by biermeister69** [jamesmontemagno/MediaPlugin#539]
Camera is not showing when I execute this code:
`var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
            var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
            
            if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
                cameraStatus = results[Permission.Camera];
                storageStatus = results[Permission.Storage];
            }

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                App.Current.MainPage.DisplayAlert("Error de Cámara", "No hay cámara disponible.", "OK");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "Test",
                SaveToAlbum = true,
                CompressionQuality = 75,
                CustomPhotoSize = 50,
                PhotoSize = PhotoSize.MaxWidthHeight,
                MaxWidthHeight = 2000,
                DefaultCamera = CameraDevice.Front
            });

            if (file == null)
                return;`

The values of permission variables are OK:
cameraStatus: PermissionStatus.Granted 
storageStatus: PermissionStatus.Granted
IsCameraAvailable: true
IsTakePhotoSupported: true

Despite this, nothing happens after executing TakePhotoAsync

## Bug Information

Version Number of Plugin: 3.1.3
Device Tested On: Samsung Galaxy J3
Simulator Tested On: --
Version of VS: Community 2017 v.15.3.5
Version of Xamarin: 2.5.1.527436
Versions of other things you are using:
  Plugin.Permissions: 2.2.1

**Comment by biermeister69** [comment]
Could anyone please help me? I don't find a solution.

**Comment by NGumby** [comment]
I had the same issue, it was because my code was in a Task.Run.  I changed it to be in an async method and it started working.

`private async void OnTakePicture()`

**Comment by wish666master** [comment]
Please help! 
Can someone please let me know how you guys resolved this issue? 
Camera and gallery both not accessible, I have added all files and permissions as James Suggested.
much appreciate if anyone can help me.

Plugin.Media.Abstraction.media
Error: "Camera permission(s) are required."
Code below:

`using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using FitnessGuru.Model;
using Plugin.Media;
using Plugin.Media.Abstractions;
using Xamarin.Forms;

namespace FitnessGuru
{
    public partial class Progress : ContentPage


    {
        ObservableCollection<MediaModel> Photos = new ObservableCollection<MediaModel>();


        public Progress()
        {
            InitializeComponent();

        }

        private async void photoBtn_Pressed(object sender, EventArgs e)

        {


            var isInitialized = await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported || !CrossMedia.IsSupported || !isInitialized)
            {
                await DisplayAlert("Error!", "Camera not Found", "ok");
                return;
            }

            var newPhotoId = Guid.NewGuid();

            using (var photo = await CrossMedia.Current.TakePhotoAsync(new StoreVideoOptions()
            {
                Name = newPhotoId.ToString(),
                SaveToAlbum = true,
                DefaultCamera = CameraDevice.Rear,
                Directory = "Fitness Gallery",
                CustomPhotoSize = 50

            }))
            {
                if (string.IsNullOrWhiteSpace(photo?.Path))
                {
                    return;
                }

                var newPhotoMedia = new MediaModel()
                {
                    MediaID = newPhotoId,
                    Path = photo.Path,
                    LocalDateTime = DateTime.Now
                };

                Photos.Add(newPhotoMedia);
                photo.Dispose();

            }

            listPhotos.ItemsSource = Photos;

        }

    }
}
`

**Comment by jamesmontemagno** [comment]
Unable to reproduce, looks fine.
