### ISSUE TITLE
Xamarin.Forms - Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll

### ISSUE THREAD

**Issue by miglrodri** [jamesmontemagno/MediaPlugin#54]
Please fill out either the bug or feature request section and remove whatever section you are not using.
## Bug

Version Number of Plugin: 2.5.1-beta38
Device Tested On: Visual Studio Emulator
Simulator Tested On: Mobile Emulator 10.0.10586.0 WVGA 4 inch 512MB
### Expected Behavior
1. await CrossMedia.Current.TakePhotoAsync(...) should show camera stream feed
2. await CrossMedia.Current.PickPhotoAsync() should show image library
### Actual Behavior
1. Black screen on the camera app? Got the button at the bottom to take a picture. any action raise an exception
2. Nothing happens, no page is launched.

For both scenarios the output comes with:
**Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.ni.dll**
This does not happen on: Emulator 8.1 WVGA 4 inch 512MB (all good after updating the plugin version)
### Steps to reproduce the Behavior

I have a page that launch both scenarios:
1. await CrossMedia.Current.TakePhotoAsync(...)
2. await CrossMedia.Current.PickPhotoAsync()
## Feature Request:

Some clarification if possible

**Comment by jamesmontemagno** [comment]
Did you specify all the permissions you need in the app manifest. I am not really sure what device you are saying is having an issue here as you reference Windows 8.1 and Windows 10. What type of app is it?

**Comment by miglrodri** [comment]
Hello,

The VS project name i'm trying to run is named "App.Mobile.WinPhone (Windows Phone 8.1)".

This projects were auto-generated when i created a PCL portable solution.

So i was trying to run on Emulator 8.1 and all good, but when i run in Emulator 10 it gave me the error.

In the properties of the project i clicked on "Package Manifest", then it opens "Package.appxmanifest".

In that file i go to the tab Capabilities and i have checked Internet and Webcam. http://i.imgur.com/8ZfVf3y.png

Best regards, Miguel

**Comment by jamesmontemagno** [comment]
Unable to reproduce on my side.
