### ISSUE TITLE
Problem installing in Android project

### ISSUE THREAD

**Issue by JBNZ** [jamesmontemagno/MediaPlugin#540]
Hi, I have added via Nuget Xam.Plugin.Media v 3.1.3 to my App solution, selecting all projects. However for the Android project I get the following error - "Package restore failed. Rolling back package changes for '<Android Project Name'."

I am running VS 2017 Community 15.6.7

Any help greatly appreciated.

Cheers John

**Comment by jamesmontemagno** [comment]
what is the rest of your error?

**Comment by JBNZ** [comment]
This message appears in the Error List window when I install the plugin. If I then run the App it still runs but the Plugin has not been installed against the Android project. So the problem is that I cannot write the required code in the readme section Android Current Activity Setup.

**Comment by jamesmontemagno** [comment]
you will need to give me full logs from output.

**Comment by JBNZ** [comment]
So sorry James, looks like another plugin may be causing a problem with Android project - will sort that out and try your plugin again - apologies John
