### ISSUE TITLE
Camera Rotation doesn't work when using a ActionSheetPicker to choose the TakePicture option

### ISSUE THREAD

**Issue by dinisvieira-xo** [jamesmontemagno/MediaPlugin#543]
Camera Rotation in Landscape doesn't work when using a ActionSheetPicker to choose the TakePicture option.
This seems to be an issue with all plugin versions I tested except for version 2.6.2

## Bug Information

Version Number of Plugin: 3.1.3 (also happen with other versions **EXCEPT 2.6.2**)
Device Tested On: iPhone 5s and iPhone SE
Simulator Tested On: None
Version of VS: 15.7.1
Version of Xamarin: 4.10.0.442
Versions of other things you are using: Xamarin.Forms 3.0.0.446417 (Also happens with several 2.5.x versions)

### Steps to reproduce the Behavior

1. Use a "DisplayActionSheet" to show an option to "TakePhoto"
2. Rotate the device to landscape (might have to do it 2/3 times if the bug doesn't happen in the first time)

### Expected Behavior

Camera should rotate properly according with device orientation

### Actual Behavior

Camera doesn't rotate and the whole interface is "cropped"

### Code snippet

I created a sample based on the Xamarin.Forms Blank app, I added the MediaPlugin v3.1.3
Then I only changed the MainPage with the code below. (Also added the Info.plist permissions)

```
    public partial class MainPage : ContentPage
    {
        public MainPage()
        {
            InitializeComponent();
        }

        public async Task TakePhotoWithPicker()
        {
            var action = await this.DisplayActionSheet(null,
                "Cancel",
                null,
                "Take Picture");

            await TakePhoto();
        }

        public async Task TakePhoto()
        {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                DisplayAlert("No Camera", ":( No camera available.", "OK");
                Debug.WriteLine("No camera");
            }

            var options = new StoreCameraMediaOptions
            {
                DefaultCamera = CameraDevice.Rear,
                PhotoSize = Device.RuntimePlatform == Device.iOS ? PhotoSize.Full : PhotoSize.Large
            };

            var file = await CrossMedia.Current.TakePhotoAsync(options);
            file.Dispose();
        }
    }
```

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:CameraApp"
             x:Class="CameraApp.MainPage">

    <Grid VerticalOptions="Center">

        <Button Grid.Row="0"  x:Name="PhotoButton" Text="Take Photo" Clicked="TakePhoto"/>
        <Button Grid.Row="1" x:Name="PhotoButtonWithPicker" Text="Take Photo w/ Picker" Clicked="TakePhotoWithPicker"/>

    </Grid>

</ContentPage>
```

### Screenshots
  
  
**Use picker before Taking Photo:**

![img_0011](https://user-images.githubusercontent.com/32739076/40010552-07c6acce-579d-11e8-9adb-71f08a1d551e.PNG)
  
  
**Camera displays ok in Portrait when opened:**

![img_0014](https://user-images.githubusercontent.com/32739076/40010562-0b2a92a4-579d-11e8-8270-50ecb94646f8.PNG)
  
  
**After rotating to Landscape UI is cropped:**

![img_0013](https://user-images.githubusercontent.com/32739076/40010565-0df377ee-579d-11e8-8947-d8e67c59e745.PNG)

**Comment by quinndgodfrey** [comment]
I am having the same issue, very happy you could pinpoint it to calling it from an action sheet.

Have you found a work around by chance?

I've tried running waiting for the action sheet to close, and kicking the take photo action off on another thread but neither of these seemed to work

**Comment by dinisvieira-xo** [comment]
@quinndgodfrey I was unable to find any workaround except using the older version "2.6.2" of the plugin. That version seems to work well.

**Comment by quinndgodfrey** [comment]
@dinisvieira-xo Good to know, thank you very much

**Comment by dinisvieira-xo** [comment]
I can no longer reproduce this issue in the new 4.0.1.5 version.
I'm going to assume it's fixed and close 👍
