### ISSUE TITLE
Unable to install the plugin after Xamarin.Android.Support.Compat 27.0.2 update

### ISSUE THREAD

**Issue by dlpopescumtk** [jamesmontemagno/MediaPlugin#544]
## Bug Information

**Version Number of Plugin**: 3.1.3

**Other version info below:**

Microsoft Visual Studio Professional 2017 
Version 15.7.1
VisualStudio.15.Release/15.7.1+27703.2000
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

C# Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Merq   1.1.17-rc (cba4571)
Command Bus, Event Stream and Async Manager for Visual Studio extensions.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Mono Debugging for Visual Studio   4.10.5-pre (ab58725)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.8.0-beta6-62830-08. Commit Hash: e595ee276d14e14bfb3eb323fb57f2aa668bddea
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.1 for F# 4.1   15.7.0.0.  Commit Hash: 16ecf5a30ad868d183c58e4a71a71c23d4ed3ba9.
Microsoft Visual F# Tools 10.1 for F# 4.1

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

Xamaridea.VisualStudioPlugin   1.0
VS + Xamarin + IDEA = Love

Xamarin   4.10.0.442 (396b18cef)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.12.264 (fc37cd02e)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   8.3.0.19 (HEAD/342b2ce96)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.10.1.177 (7e782c1)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

### Steps to reproduce the Behavior

Install MvvmCross 6.0.1 or update the Xamarin.Android.Support.Compat packages to 27.0.2
Try to install the Media plugin which still uses Xamarin.Android.Support.Compat 25.4.0.2

### Expected Behavior

The plugin should install just fine

### Actual Behavior

Install fails with  _Error NU1107	Version conflict detected for Xamarin.Android.Support.Compat. Reference the package directly from the project to resolve this issue. 
 ConnectDrive.Droid -> MvvmCross.Droid.Support.V7.RecyclerView 6.0.1 -> Xamarin.Android.Support.v7.RecyclerView 27.0.2 -> Xamarin.Android.Support.Compat (= 27.0.2) 
 ConnectDrive.Droid -> ConnectDrive.Common -> Xam.Plugin.Media 3.1.3 -> Xamarin.Android.Support.Core.Utils 25.4.0.2 -> Xamarin.Android.Support.Compat (= 25.4.0.2)._				

### Screenshots

![media_plugin_error](https://user-images.githubusercontent.com/21035866/40135272-d29951ae-593c-11e8-9ad2-faec558cdab8.jpg)

**Comment by jamesmontemagno** [comment]
So, you should manually install Support.COmpat and Core.Utils 27.0.2 manually

**Comment by jamesmontemagno** [comment]
NuGet isn't very smart so you have to do things manually if there is twisted and tangled version numbers and dependencies
