### ISSUE TITLE
StoreCameraMediaOptions Compile Error

### ISSUE THREAD

**Issue by GaryBeasley** [jamesmontemagno/MediaPlugin#549]
I'm receiving a compile error stating the following:

Error	CS0433	The type 'StoreCameraMediaOptions' exists in both 'Plugin.Media.Abstractions, Version=3.2.1.0 and 'Plugin.Media, Version=1.0.0.0

Version Number of Plugin:  4.0.0.9
Device Tested On: Compile error
Simulator Tested On:
Version of VS: 2015 15.7.2
Version of Xamarin: 3.0.0.482510

Thanks in advance for any resolution!

**Comment by jamesmontemagno** [comment]
Make sure all of your projects have 4.0.0.9 and that you have removed Plugin.Media.Abstractions.

Looks like you have something lingering in there.
