### ISSUE TITLE
CompressionQuality on iOS is avoided when PickPhotoAsync

### ISSUE THREAD

**Issue by Glabenwitt** [jamesmontemagno/MediaPlugin#55]
CompressionQuality option is lost when calling PickPhotoAsync.
PickPhotoAsync method create StoreCameraMediaOptions from PickMediaOptions without keeping CompressionQuality parameter.

Version Number of Plugin: 2.5.1-beta38
Device Tested On: -
Simulator Tested On: iPad 2 iOS 9.3

**Comment by jamesmontemagno** [comment]
Can you show me the code you are using to call PickPhotoAsync please.

**Comment by jamesmontemagno** [comment]
Ah, nm I see it now.
