### ISSUE TITLE
Image is not being saved on the right path on Android.

### ISSUE THREAD

**Issue by LeonanFragaLeonardo** [jamesmontemagno/MediaPlugin#555]
Hi!
I'm trying to get the image saved manually from using TakePhotoAsync() method. 
I want to do this: take a photo, store its name in SQLite and then retrieve it with some query, for example, take a photo called by newphoto.jpg, which is located in the Pictures directory of the specific platforms, and with some SQL query get the filename and retrieve this image file from the full path using Environment.GetFolder() method. On iOS it works, but on Android, the problem is in the file path.

I'm getting this path with Environment.GetFolder(Environment.SpecialFolder.MyPictures): "/storage/emulated/0/Android/data/user/0/com.companyname.PhotoTest/files/Pictures/Sample/test_20.jpg". 
However, the plugin stores the image on in another path:
"/storage/emulated/0/Android/data/com.companyname.PhotoTest/files/Pictures/Sample/test_20.jpg"

The difference between this two-path it is in "/user/0". I could use something like this, filepath.Replace("/user/0/", /), but it does not seem like a right way to solve this, because the "user/0" can be changed.
Here is my file_paths.xml
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="my_images" path="Android/data/com.companyname.PhotoTest/files/Pictures" />
</paths>
```
All the configuration steps are already done.
## Bug Information

Version Number of Plugin: 4.0.0.9
Device Tested On: Android - Xiaomi Redmi Note 4X (Android 6.0 - API 23)
Version of VS: 2017 CE
Version of Xamarin: 3.0.0.446417

### Steps to reproduce the Behavior
- Create a new Standard Project;
- Use the code available [here](https://github.com/jamesmontemagno/MediaPlugin/blob/master/README.md) (Usage section);
- Get the Image path from Filename using the following code;
```
var imageName = "test_20.jpg";
//var documentsPath = Path.Combine("/storage/emulated/0/Android"+System.Environment.GetFolderPath(Environment.SpecialFolder.MyPictures).Replace("/user/0/","/"), "Sample");
var documentsPath = Path.Combine(System.Environment.GetFolderPath(Environment.SpecialFolder.MyPictures), "Sample");
var path = Path.Combine(documentsPath, imageName);
```

### Expected Behavior
Save an image in this path: /storage/emulated/0/Android/data/user/0/com.companyname.PhotoTest/files/Pictures/Sample/test_20.jpg
### Actual Behavior
Image is being saved in this folder:
/storage/emulated/0/Android/data/com.companyname.PhotoTest/files/Pictures/Sample/test.jpg

I'll appreciate if someone helps me with this problem.

**Comment by jamesmontemagno** [comment]
You can get the path from the file that is returned, which is where it is saved.

**Comment by LeonanFragaLeonardo** [comment]
First of all, I really appreciate your work Mr. Montemagno, I want one day to overcome your knowledge of Xamarin.

Regarding your suggestion, it works perfectly when retrieving an image after capturing the image.
However, my logic was to store only the image name and with the plugin retrieve the Image by name with the path, but I believe that because Android updates allow more than 1 user on the device, the stored directory contains a "/user/0 "and this makes it necessary to do a workaround, in my case I had to do a DependencyService to work with the paths of the files.

**Comment by kkarakk** [comment]
for future reference no android the way to get the path is 

`this.GetExternalFilesDir(Android.OS.Environment.DirectoryPictures).AbsolutePath+"file_name"`
