### ISSUE TITLE
Plugin.Media.Abstractions.MediaPermissionException: Storage/camera permission(s) are required.

### ISSUE THREAD

**Issue by sanasz91mdev** [jamesmontemagno/MediaPlugin#556]
i have completely followed all the instructions at setup to get start using media plugin, when ever i am trying to pick photo from storage / take photo from camera i am having permission denied error.

I guess The WRITE_EXTERNAL_STORAGE & READ_EXTERNAL_STORAGE permissions are required, and library have not automatically added these. 

following code returns permission Denied:
```
                var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);

                if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
                {
                    var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
                    cameraStatus = results[Permission.Camera];
                    storageStatus = results[Permission.Storage];
                }
```

my androidmanifest.xml contains: 
```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.DocApp">
	<uses-sdk android:minSdkVersion="19" android:targetSdkVersion="25" />
	<application android:label="DocApp.Android">
    <provider android:name="android.support.v4.content.FileProvider" 
				android:authorities="com.companyname.DocApp.fileprovider" 
				android:exported="false" 
				android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" 
				android:resource="@xml/file_paths"></meta-data>
</provider>

  </application>
</manifest>

```

file_paths.xml includes

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-files-path name="my_images" path="Pictures" />
  <external-files-path name="my_movies" path="Movies" />
</paths>
```

Added following to MainActivity.cs

```
  public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

```

## Bug Information

Version Number of Plugin: 4.0.0.9 (latest)
Device Tested On:
Simulator Tested On: May 27, 2018
Version of VS: 2017
Version of Xamarin: 3.0.0.48

**Comment by cvenkat38** [comment]
use <external-path > instead of  <external-files-path> in you file_paths.xml.  That should solve your problem. Let me Know on the same.

**Comment by mareklevy** [comment]
I had the same problem when I started running Live Player. The solution was to set the Xamarin Live Player permission on your phone.
However, this example did not succeed in running the Live Player, it is better to use build directly on a mobile device or emulator.

**Comment by jamesmontemagno** [comment]
It adds them yes, but it still needs to actually prompt the user for permissions:

**Comment by jamesmontemagno** [comment]
This is probably because you didn't setup the CurrentActivity Plugin. You must call Init.

https://github.com/jamesmontemagno/MediaPlugin#android-current-activity-setup
