### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by hkidd88** [jamesmontemagno/MediaPlugin#558]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

After following all the set-up directions and implementing the following code block to check camera permissions, I am still getting the DisplayAlert that permissions are denied for the camera.

`// verifies that the user has permission to access the camera
            var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
            if (cameraStatus != PermissionStatus.Granted)
            {
                var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera });
                cameraStatus = results[Permission.Camera];
                if (cameraStatus != PermissionStatus.Granted)
                {
                    await DisplayAlert("Permissions Denied", "Unable to take photos.", "OK");
                    CameraButton.IsEnabled = false;
                    return;
                }
            }`

I am developing a cross-platform application in Xamarin, using .NET 2.0 Standard. I have the permissions and media plugins installed, but cannot figure out where I am going wrong. I am testing on an "Android_Accelerated_x86_Oreo (Android 8.1 - API 27)" with the hardware for camera set to true in the ADM.

The repository I am working in is https://github.build.ge.com/212703631/CameraPOC and is a simple application that only needs to open the camera using the button created, take a picture, and display it.

Do you have any ideas of why I am unable to gain permission to the camera and how I could overwrite that?

**Comment by jamesmontemagno** [comment]
you don't need the camera permission on android. I have samples in this repo that you can walk through. I don't add the camera permission to the android manifest. Also ensure that you setup the current activity plugin: https://github.com/jamesmontemagno/MediaPlugin#android-current-activity-setup
