### ISSUE TITLE
Xam.Plugin.Media throwing error This functionality is not implemented in the portable version of this assembly

### ISSUE THREAD

**Issue by IveVasilj** [jamesmontemagno/MediaPlugin#559]
I've already made a post on stackoverflow, so to make it easier for me and you I will just  post a link and there will be my problem and everything explained about it.

https://stackoverflow.com/questions/50706824/xamarin-forms-xam-plugin-media-throwing-error-this-functionality-is-not-implem

**Comment by jamesmontemagno** [comment]
Ensure that you have your Android project set to compile against 7.1+ and then re-add the nuget
