### ISSUE TITLE
iOS - Unable to detect if the camera permission has been disabled

### ISSUE THREAD

**Issue by CliffCawley** [jamesmontemagno/MediaPlugin#56]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.5.1-beta38

### Expected Behavior
IsCameraAvailable to return false if Camera permission has been disabled in the per app settings

### Actual Behavior
IsCameraAvailable returns true as it doesn't check permission

### Steps to reproduce the Behavior
Disable the Camera in the app settings and observe that IsCameraAvailable returns true

(Incoming PR with fix for this)

**Comment by jamesmontemagno** [comment]
For the time being use the Permission Plugin as that is the best way to handle permissions in general on iOS/Android. I will re-visit this in a future release as it should be handled in all Operating Systems.
