### ISSUE TITLE
 When selecting with double click in the gallery, closes the previous modal window

### ISSUE THREAD

**Issue by francodelsancio** [jamesmontemagno/MediaPlugin#563]
## Bug Information

Version Number of Plugin: 4.0.0.9
Device Tested On: IOS Simulator
Simulator Tested On: Iphone 6s IOS 11.4
Version of VS:  VS for MAC OS High Sierra
Version of Xamarin: Xamarin.Forms 3.0
Versions of other things you are using: Xamarin.Forms - Target Framework: .NET Standard 2.0

### Steps to reproduce the Behavior
Have a modal window before the gallery, go to the gallery and double click on the photo
### Expected Behavior
That only close the gallery and not the previous view
### Actual Behavior
When I'm going to select the photo in the gallery, and double click on it. closes not only the gallery but also the previous view
### Code snippet
It is not necessary
### Screenshots
not possible

(Apparently the popView is not controlled in the double click)

**Comment by Omarkth** [comment]
This only happens on iOS 11 and above, tested on iOS 10 and it's all good, tested on the latest iOS 12 beta 5 and the bug is there

**Comment by Omarkth** [comment]
I found the problem, the picker controller was being disposed twice, and one of the two calls is actually before the picker is really dismissed.

The first call is in the "MediaPickerDelegate.cs" line 166:
```
	picker.DismissViewController(true, onDismiss); <<<< this is where you dismiss the picker
	try
	{
		picker.Dispose(); <<<<< this is where you dispose it, it's not dismissed yet
	}
	catch
	{

	}
```
To fix it, I moved the dispose call to inside the dismiss  completion handler:
```
	picker.DismissViewController(true, () =>
	{
		onDismiss();
		try
		{
			picker.Dispose();
		}
		catch
		{

		}
	});
```
Then I found the second call, which was in the "MediaImplementation.cs" line 310:
```
	try
	{
		picker?.Dispose();
	}
	catch
	{

	}
```
So, one of these must go, and since the second call was guranteed to be after actually dismissing the picker since it's in the Task.ContinueWith and the task is completed in the dismiss completion handler, I finally decided to remove the first call from the "MediaPickerDelegate.cs" and leave it as 
```
	picker.DismissViewController(true, onDismiss);
```

@jamesmontemagno: should I submit a PR?

**Comment by jamesmontemagno** [comment]
I think this was added for: https://github.com/jamesmontemagno/MediaPlugin/issues/413

**Comment by Omarkth** [comment]
in #413 you just added some try/catch blocks, the dispose statement was there already.

**Comment by Brosten** [comment]
Seems like this is still a problem (Xam.Plugin.Media = 4.0.1.5  iOS = 12)

I would very much appriciate a fix for this

**Comment by iupchris10** [comment]
I'm seeing that https://github.com/jamesmontemagno/MediaPlugin/pull/606 has been merged. Can we get a beta build for this anytime soon to verify the fix?

**Comment by Brosten** [comment]
@jamesmontemagno Could you please answer the question above? This is a pretty serious problem for our iOS app and from what I can see the MediaPlugin is not replaced by functionality in Xamarin.Essentials. Should we start looking for Another photo implementation?

**Comment by jamesmontemagno** [comment]
Pushed out a new preview

**Comment by Brosten** [comment]
How should I act around usage of MediaPlugin AND PermissionPlugin? 
Last stable version of MediaPlugin was from 2018-08. And to update to latest beta I also need to update PermissionPlugin. Should I consider it MORE safe to use the latest beta versions when using the latest stable? 

The reason I more or less MUST update is to get rid of the bug described in this issue...
