### ISSUE TITLE
DefaultCamera not honored on UWP

### ISSUE THREAD

**Issue by hauteur** [jamesmontemagno/MediaPlugin#565]
Setting the DefaultCamera property in a Xamarin Forms project for UWP is not honored.  Setting it to default to the rear camera still starts the camera using the front camera.

## Bug Information

Version Number of Plugin:  **4.0.0.9**
Device Tested On:  **Surface Pro 3 - Fall Creators Build**
Simulator Tested On: **Windows 10 Fall Creators Build**
Version of VS: **Visual Studio 15.7**
Version of Xamarin: **3.0.0.550146**
Versions of other things you are using:

### Steps to reproduce the Behavior
Use the camera on UWP from a Xamarin Forms project.  Set DefaultCamera to Plugin.Media.Abstractions.CameraDevice.Rear.

### Expected Behavior
The rear camera should be selected.  This does work on iOS and Android.

### Actual Behavior
The front camera is selected.  Changing to the rear camera is a manual step.

**Comment by jamesmontemagno** [comment]
No plans on implementing any fixes for UWP at this point.
