### ISSUE TITLE
Camera doesn't start in full screen mode on UWP

### ISSUE THREAD

**Issue by hauteur** [jamesmontemagno/MediaPlugin#566]
Showing the camera on UWP is not full screen.  The modal presentation style only applies to iOS.  There should be a property that defaults the camera to full screen mode if it does not do it by default.

## Bug Information

Version Number of Plugin:  **4.0.0.9**
Device Tested On:  **Surface Pro 3 - Fall Creators Build**
Simulator Tested On: **Windows 10 Fall Creators Build**
Version of VS: **Visual Studio 15.7**
Version of Xamarin: **3.0.0.550146**
Versions of other things you are using:

### Steps to reproduce the Behavior
Use the camera on UWP from a Xamarin Forms app
### Expected Behavior
The camera app should open in full screen mode or have an option to do so.  According to the tooltip the modal presentation style only applies to iOS.
### Actual Behavior
The camera app is not in full screen mode.

**Comment by jamesmontemagno** [comment]
This is as designed as I call to UWP itself.
