### ISSUE TITLE
Get error on TakePhotoAsync after updating package from 3.0.1 to 4.0.0.9  on andriod

### ISSUE THREAD

**Issue by Afshin1980** [jamesmontemagno/MediaPlugin#571]
ExceptionDispatchInfo.Throw ()
JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args)
JniPeerMembers+JniStaticMethods.InvokeObjectMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters)
FileProvider.GetUriForFile (Android.Content.Context context, System.String authority, Java.IO.File file)
MediaPickerActivity.OnCreate (Android.OS.Bundle savedInstanceState)
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:591)
android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:565)
android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:403)
md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.n_onCreate(Native Method)
md54cd65ac53ae710bff80022afc423e0f3.MediaPickerActivity.onCreate(MediaPickerActivity.java:42)
android.app.Activity.performCreate(Activity.java:7174)
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
android.app.ActivityThread.-wrap11(Unknown Source:0)
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
android.os.Handler.dispatchMessage(Handler.java:105)
android.os.Looper.loop(Looper.java:164)
android.app.ActivityThread.main(ActivityThread.java:6938)
java.lang.reflect.Method.invoke(Native Method)
com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by jamesmontemagno** [comment]
Ensure that you set everything correct in your xml config for file_paths and also for the new current activity init.

**Comment by jamesmontemagno** [comment]
Unable to reproduce. Try the new sample projects.
