### ISSUE TITLE
Missing Exif GPS data - TakePhotoAsync

### ISSUE THREAD

**Issue by ClausElmann** [jamesmontemagno/MediaPlugin#573]
Hi James

Sorry for not using standard template.

I seems that when using TakePhotoAsync, the MediaFile lacks GPS EXIF data.

Taking a foto first and then use PickPhotoAsync works fine, here is GPS EXIF data.

Reproduce : Simply download your sample app

Thanks :-)

**Comment by jamesmontemagno** [comment]
For iOS you need to pass in the information to set it on the Exif as iOS doesn't give this information to apps

**Comment by ClausElmann** [comment]
Thanks, James

You learn every day :-)

**Comment by jamesmontemagno** [comment]
My fault as not clearly documented to be honest.
