### ISSUE TITLE
System.NotImplementedException

### ISSUE THREAD

**Issue by Genfood** [jamesmontemagno/MediaPlugin#577]
Hey,

i forked your repo and packed it myself to get a NuGet package. I implemented a simple test app but always if I try to call `CrossMedia.Current` I get the following error:

> System.NotImplementedException: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.

This is strange because if I install the original NuGet package 
(from nuget.org package source) it works fine.

I added the sample project: [src.zip](https://github.com/jamesmontemagno/MediaPlugin/files/2149306/src.zip)
Any ideas?

**Comment by jamesmontemagno** [comment]
Install the nuget into all projects.
