### ISSUE TITLE
Issue with GetStreamWithImageRotatedForExternalStorage

### ISSUE THREAD

**Issue by edamreed** [jamesmontemagno/MediaPlugin#579]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.1.1
Device Tested On: iPad Mini 4
Simulator Tested On: None
Version of VS: 15.7.1
Version of Xamarin: Forms 3.0.0.482510
Versions of other things you are using:

### Steps to reproduce the Behavior
Call TakePhotoAsync with RotateImage = true
Call GetStreamWithImageRotatedForExternalStorage

### Expected Behavior
Image should be displayed (either correctly rotated or not)

### Actual Behavior
Stream seems to return null or empty

### Code snippet
```
            await CrossMedia.Current.Initialize();

            if (CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakePhotoSupported)
            {
                var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    AllowCropping = true,
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                    SaveToAlbum = false,
                    RotateImage = true                    
                });

                if (file == null)
                    return;

                Image.Source = ImageSource.FromStream(() =>
                {
                    //GetStream works but image is incorrectly rotated
                    var stream = file.GetStreamWithImageRotatedForExternalStorage();
                    return stream;
                });              
            }
```

### Screenshots
None

**Comment by edamreed** [comment]
Ok, I can't debug this on iOS as I dont have a Mac with the correct OS so I added some alerts:-

```
                    var stream = file.GetStreamWithImageRotatedForExternalStorage();

                    if (stream == null)
                        DisplayAlert("TakePicture", "stream is null", "Ok");
                    else if(stream.Length == 0)
                        DisplayAlert("TakePicture", "stream is 0 length", "Ok");
```

I don't see either so might not be a null / empty stream.

**Comment by edamreed** [comment]
Ok, added some Alerts and the stream has data but does not seem to work when using ImageSource.FromStream.

**Comment by edamreed** [comment]
Changed SaveToAlbum = true and when I open the gallery, the image is rotated 90 deg.
Have RotateImage = true which could cause the issue? I'll try setting it to false.
I still can't set the image source to the byte array of the image using GetStreamWithImageRotatedForExternalStorage.


```
using (var ms = new MemoryStream())
{                    
     file.GetStreamWithImageRotatedForExternalStorage().CopyTo(ms);
     details.LabelImage = ms.ToArray();
}
```
using the byte array for an image
`
return ImageSource.FromStream(() => new MemoryStream(this.LabelImage));
`
This does not work for me, GetStream works ok.

**Comment by edamreed** [comment]
Ok so, RotateImage = false + GetStreamWithImageRotatedForExternalStorage allows me to display the image but its still incorrectly rotated in my app and the gallery.

**Comment by edamreed** [comment]
If SaveMetaData is false, the photo rotation issue goes away, at least with photos taken AND displayed on the same device.
GetStreamWithImageRotatedForExternalStorage still does not seem to work for me.

**Comment by t3slaughter** [comment]
GetStreamWithImageRotatedForExternalStorage worked for me for months but with the latest 4.1.0.1 version and Xamarin.Forms 3.0.0.446417 iOS shows the correct byte array length but it is filled with 0s.

**Comment by edamreed** [comment]
Funny, didn't check the content (as I can't debug my code), only looked at the length.

**Comment by t3slaughter** [comment]
Yes. 4.0.1.1. Thanks.
