### ISSUE TITLE
UWP app missing X with a circle or check mark with a circle on TakePhotoAsync method

### ISSUE THREAD

**Issue by faceoffers28** [jamesmontemagno/MediaPlugin#58]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Xamarin.Forms v2.2.0.31
PCL targeting profile 259
Device Tested On: ACER Liquid M330 running Windows 10
Simulator Tested On:

### Expected Behavior
When I take a picture using the CrossMedia.Current.TakePhotoAsync method, I should be presented with a option to either cancel the photo or accept the photo. In a Windows 10 device, you get either an X with a circle around it or a check mark with a circle around it. The CrossMedia.Current.PickPhotoAsync method works just fine.

### Actual Behavior
I don't see the X with a circle or the check mark with a circle. Please see attached photo.

### Steps to reproduce the Behavior

 ```
var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Front,
                        //PhotoSize = Plugin.Media.Abstractions.PhotoSize.Small,
                        //CompressionQuality = Plugin.Media.Abstractions.,
                        SaveToAlbum = true,
                        Directory = "somedirectoryname",
                        Name = string.Format("somedirectoryname_{0}", DateTime.Now.ToString("yyMMddhhmmss")),

                    });

```
## Feature Request:
Please fill in what you would like

Screen shot showing that the options are missing,
![image1](https://cloud.githubusercontent.com/assets/10619627/17875733/3bbd0d3c-689a-11e6-9d91-ed7742fd6769.JPG)

**Comment by jamesmontemagno** [comment]
I am calling the core APIs: https://msdn.microsoft.com/en-us/windows/uwp/audio-video-camera/capture-photos-and-video-with-cameracaptureui

https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin.WindowsStore/MediaImplementation.cs#L105

I can only assume a firmware bug.

**Comment by faceoffers28** [comment]
@jamesmontemagno Thanks for the quick response! My OS build is 10.0.14393.67. The firmware is 1078.37.2000.0023. Do you know how I can file a bug with Microsoft? Thanks in advance!

**Comment by jamesmontemagno** [comment]
I would test out their sample apps to see what they are doing with these apis and report a bug there if it exists. They usually have a repo on github of all the samples.

**Comment by faceoffers28** [comment]
@jamesmontemagno It looks like this could be the issue. It's the same line of code that you indicated in the GitHub link you posted. I assume this reference needs to be added, so the method will resolve.

You must add a reference to assembly Windows.Foundation.FoundationContract, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime

![cameracaptureui issue_windows2](https://cloud.githubusercontent.com/assets/10619627/17895471/cfac229e-6912-11e6-8183-14058dbbf001.png)

I've only been developing for about a year and working with Xamarin for even less, so this is a little over my head. Any idea on how I can fix this? Any help is much appreciated. Thanks!

**Comment by faceoffers28** [comment]
@jamesmontemagno The issue has been fixed. I am 99.9% sure that adding a width to get my ActivityIndicator to work in Windows 10 did the trick. Does this make sense? The spot where the ActivitiyIndicator goes contains the indicator and a status message. Now, the status message doesn't show in Windows 10 (works in iOS and Android), but the accept and reject photo selection displays. Here is the code.

```
<ActivityIndicator x:Name="activityIndicatorCamera" Style="{StaticResource ActivityIndicatorStyle}"
            		   IsVisible="{Binding IsBusy}"
                       IsRunning="{Binding IsBusy}"
                       HorizontalOptions="EndAndExpand" >
            <ActivityIndicator.WidthRequest>
              <OnPlatform x:TypeArguments="x:Double" iOS="50" Android="50" WinPhone="400" />
            </ActivityIndicator.WidthRequest>
</ActivityIndicator>
```
