### ISSUE TITLE
Android.Content.Res.Resources+NotFoundException: Resource ID #0x7f030000

### ISSUE THREAD

**Issue by ravisinghunnao** [jamesmontemagno/MediaPlugin#581]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:4.0.1.1
Device Tested On:Samsung Galaxy on 8
Simulator Tested On: none
Version of VS:  VS2017
Version of Xamarin:
Versions of other things you are using: Xamarin forms 3.1.0.583944

### Steps to reproduce the Behavior
Coded as per instructions shown in read me file.
### Expected Behavior
Camera should take a picture and set as source of image control.
### Actual Behavior
After capturing and confirming image, application crashes with exception given in title.
### Code snippet
        private async void imgCapture_Tapped(object sender, EventArgs e)
        {
            try
            {
                if (await CrossMedia.Current.Initialize())
                {

                    var cameraStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
                    var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);

                    if (cameraStatus != PermissionStatus.Granted || storageStatus != PermissionStatus.Granted)
                    {
                        var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Camera, Permission.Storage });
                        cameraStatus = results[Permission.Camera];
                        storageStatus = results[Permission.Storage];
                    }

                    if (cameraStatus == PermissionStatus.Granted && storageStatus == PermissionStatus.Granted)
                    {

                        var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                        {
                           
                        });
                  
/*never reached to below lines*/

                        Image image = sender as Image;
                        image.Source = ImageSource.FromStream(() => { return file.GetStream(); });
                    }
                    else
                    {
                        await DisplayAlert("Permissions Denied", "Unable to take photos.", "OK");

                    }
                }
            }
            catch (Exception ex)
            {

                Classes.Global.SaveError(Models.User.UID, ex.Message, ex.ToString());
            }
        }

**Comment by jamesmontemagno** [comment]
Unable to reproduce on my end here with my samples.

**Comment by yasiralijaved** [comment]
This crash is happening on Samsung Galaxy S7.

**Comment by aphex3k** [comment]
+1 for LG G5 on Android 7 and emulator running Android 6 (API 23)

**Comment by aphex3k** [comment]
Actually, this is not an issue with the media plugin. I was able to resolve this issue by adding an icon resource suitable for Android 6 & 7 to my project...
