### ISSUE TITLE
Plugin.Media.Abstractions.MediaFileNotFoundException

### ISSUE THREAD

**Issue by ruchiverma6** [jamesmontemagno/MediaPlugin#582]
We are getting this crash while picking photo from Gallery:

**Crash Logs:**
MediaImplementation+<PickPhotoAsync>d__16.MoveNext ()
Plugin.Media.Abstractions.MediaFileNotFoundException: Unable to locate media file at content://com.sec.android.gallery3d.provider/union/image/item/1645
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter`1[TResult].GetResult ()
MediaImplementation+<PickPhotoAsync>d__16.MoveNext ()
ExceptionDispatchInfo.Throw ()
TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task)
TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task)
TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task)
TaskAwaiter`1[TResult].GetResult ()
UserProfileViewModel+<ChoosePhoto_Clicked>d__56.MoveNext ()
ExceptionDispatchInfo.Throw ()
AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state)
SyncContext+<>c__DisplayClass2_0.<Post>b__0 ()
Thread+RunnableImplementor.Run ()
IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this)
(wrapper dynamic-method) System.Object:227f5848-65bf-4bb6-a770-644e74e8a738 (intptr,intptr)

## Bug Information

Version Number of Plugin:
Device Tested On: Galaxy On Nxt
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 4.10.10.2
Versions of other things you are using: Xam.Plugin.Media: 3.1.3

**Comment by jamesmontemagno** [comment]
Unable to reproduce you can check the new sample projects.
