### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by Kulu-M** [jamesmontemagno/MediaPlugin#583]
When trying to build the example:

![image](https://user-images.githubusercontent.com/9268124/42620672-e2fddc80-85bb-11e8-9e56-b7669fc5320e.png)

When trying to update the NuGetpackages:

![image](https://user-images.githubusercontent.com/9268124/42620742-18cd9a58-85bc-11e8-8efb-bc7bd6033ebb.png)

Don't know how to use this package.

**Comment by jamesmontemagno** [comment]
Fixed up! They are now all updated to latest and greatest.

**Comment by Kulu-M** [comment]
Thanks for updating!
