### ISSUE TITLE
Plugin crashes app when second picture is accepted.

### ISSUE THREAD

**Issue by OrangeGoblin1973** [jamesmontemagno/MediaPlugin#584]
Version Number of Plugin: 4.0.1.1
Device Tested Samsung S6 phone after google play deployment API 24.
Simulator Tested On: On: Geny motion S8 API 26
Version of VS: 2017 Community 15.7.4
Version of Xamarin: 3.1.0.637273
Versions of other things you are using:

### Steps to reproduce the Behavior
Take one picture and accept the image. Take the second image, when accepting the image app crashes.

### Expected Behavior
Images should be taken and accepted using the camera one after the other

### Actual Behavior
App crashes after the second image is accepted. There is no stack trace that is the same. It is different each time.
[Output Trace.txt](https://github.com/jamesmontemagno/MediaPlugin/files/2190439/Output.Trace.txt)

### Code snippet
    private async void TakePicture()
        {
            int imagecount = DailyImageCount;
          
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "FoodSnap",
                Name = GetTimestamp(DateTime.Now),
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Custom,
                CustomPhotoSize = 50
            });

            if (file == null)
                return;

            FilePath = file.Path;       
        }

### Screenshots
No screenshots available as the app bails out on accepting the image. I have tried keeping a trace and debugging, but the output from VS is different each time.

**Comment by jamesmontemagno** [comment]
Do you have kill activity on in your developer options?

**Comment by OrangeGoblin1973** [comment]
I'm sorry James, embarrassingly I don't know what you mean in relation to this, being a little green behind the gills for Xamarin...

Are we talking about 

callingActivityA2() {
    Intent i = new Intent(this, activityA2.class);
    startActivity(i);
    finish();
 }

in relation to https://stackoverflow.com/questions/51312074/xamarin-media-plugin-crashes-when-second-photo-is-taken...

**Comment by jamesmontemagno** [comment]
It is just an android thing that you can tell the phone to kill your activity when you leave it.

Pull down my examples as I just validated that it works fine on my phone and google emulators.
