### ISSUE TITLE
Camera Not Opening in Android

### ISSUE THREAD

**Issue by Malith1994124** [jamesmontemagno/MediaPlugin#590]
public static async Task<String> getCamera()
        {
            try
            {
                var media = CrossMedia.Current;
                MediaFile file = null;
                await media.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    PhotoSize = PhotoSize.Medium,
                    DefaultCamera = CameraDevice.Front,
                    CompressionQuality = 50
                }).ContinueWith(t =>
                {
                    if (!t.IsCanceled)
                        file = t.Result;
                });

                String base64 = null;
                if (file != null)
                    base64 = await toBase64(file);

                return base64;
            }
            catch (Exception ex)
            {
            }
            return null;
        }

I using above code but when it run it ask permission but camera is not opening. Please help um stuck in here more than week.
Full code can find here - https://github.com/Malith1994124/Kiosk
## Bug Information

Version Number of Plugin: 3.0.1
Device Tested On: Samsung J5
Simulator Tested On: android_accelerated_x86_oreo
Version of VS: 2017 15.7.5
Version of Xamarin: 3.0.0.561731
Versions of other things you are using: NET 4.7.0.3

**Comment by jamesmontemagno** [comment]
Did you follow all of: https://github.com/jamesmontemagno/MediaPlugin#android-current-activity-setup

Also did you try the sample in the repo?

**Comment by Malith1994124** [comment]
yes, and it ask camera permission also but camera not openning

**Comment by Zilounay** [comment]
Why is this closed?

I'm experiencing the same issue on Android 9 and Android One, followed the steps linked above.

Permission is asked, then a white activity appears to be pushed, but nothing is in it.
