### ISSUE TITLE
Type exists error in both Plugin.Media.Abstractions version 1.0.0.0 Plugin.Media 

### ISSUE THREAD

**Issue by einsfacts** [jamesmontemagno/MediaPlugin#592]
## Bug Information

Type exists in both Plugin.Media.Abstractions version 1.0.0.0 Plugin.Media 

Version Number of Plugin:
Device Tested On:  Lenovo 6.0 API 23
Version of VS: 2017

### Steps to reproduce the Behavior
Updated nuget package to the latest stable version
Plugin.Permissions 3.0.0.12
Xam.Plugin.Media 4.0.1.1

### Expected Behavior
To be worked as expected

### Actual Behavior
Getting The type 'StoreCameraMediaOptions' exists in both 'Plugin.Media.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' and 'Plugin.Media, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

### Code snippet
 var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                });

### Screenshots

![untitled](https://user-images.githubusercontent.com/24378635/43406666-cbce8444-942d-11e8-8d8d-fc51a8d73676.png)

**Comment by jamesmontemagno** [comment]
When upgrading the DLL is removed, ensure it isn't in your project anymore.

**Comment by einsfacts** [comment]
Removed the abstractions files from the project reference.  It is working fine now.

Thanks
