### ISSUE TITLE
PickPhotoAsync returns null when first using an ActionSheet

### ISSUE THREAD

**Issue by TravyDale** [jamesmontemagno/MediaPlugin#593]
## Bug Information

Version Number of Plugin: 4.0.1.1
Device Tested On: Galaxy S6
Version of VS: 15.7.5
Version of Xamarin: 3.1.0.637273
Versions of other things you are using:
Acr.UserDialogs: 7.0.1
### Steps to reproduce the Behavior
Before opening the option to pick a photo, open an ActionSheet. If the user selected the option labeled 'Photos', then let the user select a photo with the MediaPlugin.
Use `CrossMedia.Current.PickPhotoAsync()` to select a photo and then go to use the file returned from the plugin.
### Expected Behavior
The object returned from `CrossMedia.Current.PickPhotoAsync()` be a reference to an object containing the details of the photo selected.
### Actual Behavior
Object returned from `CrossMedia.Current.PickPhotoAsync()` is always null.
### Code snippet
```
var answer = await UserDialogs.Instance.ActionSheetAsync("Choose how to obtain image", "Cancel", null, null, "Camera", "Photos");

if (string.IsNullOrWhiteSpace(answer))
	return;

await CrossMedia.Current.Initialize();

if (answer.Equals("Camera"))
{
	if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
		return;

	var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
	{
		Directory = "Sample",
		Name = "test.jpg"
	});

	if (file == null)
		return;
}
else if (answer.Equals("Photos"))
{
	if (!CrossMedia.Current.IsPickPhotoSupported)
		return;

	var file = await CrossMedia.Current.PickPhotoAsync();

	if (file == null)
		return;
}
```
### Comments
When I do not initially prompt with an ActionSheet and just call `CrossMedia.Current.PickPhotoAsync()` right away, it appears to be working as expected. It seems to only be acting this way when I initially bring up an ActionSheet and then let the user select an image. I do not visually notice a difference between both situations. Just that the ActionSheet way always returns null for the file object.

**Comment by jamesmontemagno** [comment]
Can you try setting:  ModalPresentationStyle = MediaPickerModalPresentationStyle.OverFullScreen

**Comment by TravyDale** [comment]
Ok, I take back my bug report but have to show you something goofy! I guess I was trusting the debugger that it was null but really wasn't?? I was just putting a breakpoint at the null check line and if I saw (null), I assumed it didn't work and quit the app. I guess I've never seen this before. Debugger is saying it is null but if I let it run, it acts like it isn't null. [shrug]

![image](https://user-images.githubusercontent.com/5438512/43496711-7b17a04e-9504-11e8-99c0-594c0d63d315.png)
