### ISSUE TITLE
After updating iOS app, the photos taken by MediaPlugin dissapear

### ISSUE THREAD

**Issue by juancho559** [jamesmontemagno/MediaPlugin#595]
Hi,

Maybe, this could be very simple, I don't know if I'm missing something because i have searched a lot this issue and I haven't found anything related. My scenario is the following one:

When I update the iOS app, seems that the private folder is deleted and my photos disappear.  Below, all the information required:

## Bug Information

Version Number of Plugin: 4.0.0.9
Device Tested On: IPhone SE
Simulator Tested On: iPhone X iOS 11.4
Version of VS: Visual Studio Form Mac - Version 7.5.3 (build 7)
Version of Xamarin: Xamarin.Forms (3.1.0.583944)
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Just install a new version of the App in iOS, and the photos taken in the version before get disappear.
2. Even, when you debug the application, every time that you run it, the photos get disappear.

### Expected Behavior
The photos must be kept between different updates. Android works perfect.

### Actual Behavior
The photos are not kept after an update of an app in iOS.

### Code snippet
            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {

                Directory = Constants.RootFolder,
                CompressionQuality = Constants.CompressionPhotoQuality,
                Name = Guid.NewGuid().ToString()
            });

NOTE: I don't know if it's possible to change the default location where photos are stored.

Thanks!!

**Comment by jamesmontemagno** [comment]
What directory are you attempting to save them in?

**Comment by jamesmontemagno** [comment]
The debug is probably not a real use case as it may clear out your files each time on deploy too.

**Comment by juancho559** [comment]
Hi James,

I'm just setting the Directory name and that's it. I don't know where I can change the default location of the images folder. I suppose that I'm saving all the image in the default location that the component uses.

Hope to be clear, regards!!

**Comment by jamesmontemagno** [comment]
Gotcha, we save it in the Personal Folder... I will double check this stuff next week, but I think it should be okay....

**Comment by juancho559** [comment]
Hi James,

Take a look of this post: 
https://forums.xamarin.com/discussion/73940/environment-specialfolder-personal-is-a-good-place-to-store-photos-in-my-app

Seems that storing photos in "Personal" folder is not enough to keep photos between updates. A good place could be the "Library" folder.

Regards,

**Comment by BillyMartin1964** [comment]
I'm having the same issue, @jamesmontemagno ! It keeps them on startup and shutdown, but not on update or debug... ONLY IN iOS... Android works fine.

**Comment by BillyMartin1964** [comment]
I have spent days on this, @jamesmontemagno and I don't know what to do. I desperately need to update my app  but I can't because if I do, all of my users will lose their images in their photo logs. I have tried everything I can think of. I copied the photo using a dependency service to:

` string documentsPath = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.Personal), "..", "Library");`

and then saved the path, but that didn't work, so I just saved the file name and added the above path on during the binding when I'm displaying the photos in a listview, but that didn't work either.

The debugging doesn't make the photos disappear if I don't change anything in the code, but if I change ANYTHING, then the photos don't show up. PLEASE HELP!

**Comment by juancho559** [comment]
Hi Billy, 

I did that, moving images to the Library folder, but seems that each time that the app is updated, the App Id changes, so the path is different and the component is not able to find the images. The weird of that situation is that the sqlite db3 file is kept between updates. I'm wondering whether on production, the appid changes each time that you are going to update your app. In the meantime, i'm going to save photos in the photo library and referencing images from there. 

Regards,

**Comment by BillyMartin1964** [comment]
@juancho559 , I ended up saving my images to Sqlite. My users will have a problem on the first upgrade, since their images are no longer showing up for them, but after that, they will be fine.

With Sqlite, I'm dealing with byte arrays, which is sort of a pain. I was able to let my users share photos to social media in Xamarin Forms iOS, but can't find any code for Android.

Would you happen to know how to share photos from a byte array in Xamarin forms Android? This is what I have so far, but bitmap is null after **bitmap.Compress**:

 ```
 public class ShareClass : Activity, IShare
    {
        public async void Share(byte[] imageData)
        {

            try
            {
                Bitmap bitmap;
                using (var stream = new MemoryStream(imageData))
                {
                    var imageSource = ImageSource.FromStream(() => stream);
                    bitmap = await GetBitmap(imageSource); 
                }
                using (var writeStream = new MemoryStream())
                {
                     bitmap.Compress(Bitmap.CompressFormat.Png, 100, writeStream);
                }

                var intent = new Intent(Intent.ActionSend);
                intent.SetType("image/png");
                intent.PutExtra(Intent.ExtraStream, bitmap);
                var intentChooser = Intent.CreateChooser(intent, "Share via");
                StartActivityForResult(intentChooser, 1);

            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
       
        Task<Bitmap> GetBitmap(ImageSource image)
        {
            return GetImageFromImageSource(image, Forms.Context);
        }

        private async Task<Bitmap> GetImageFromImageSource(ImageSource imageSource, Context context)
        {
            IImageSourceHandler handler;

            if (imageSource is FileImageSource)
            {
                handler = new FileImageSourceHandler();
            }
            else if (imageSource is StreamImageSource)
            {
                handler = new StreamImagesourceHandler(); // sic
            }
            else if (imageSource is UriImageSource)
            {
                handler = new ImageLoaderSourceHandler(); // sic
            }
            else
            {
                throw new NotImplementedException();
            }
            return await handler.LoadImageAsync(imageSource, context);
        }
    }



```

**Comment by juancho559** [comment]
@BillyMartin1964 I haven't done that before. I will be worried about the size of the database. 

Finally I found a solution, I'm going to try to explain it. 

@jamesmontemagno The default location that the MediaPlugin component use to save the photos is not persistent between updates. As I told you in a post before, seems that storing photos in "Personal" folder is not enough to keep photos between updates. A good place could be the "Library" folder, so it would be great to fix that. For that reason, the first step that I'm doing when I take or pick a picture, is moving images from the Media Plugin default location to the "Library" folder .

Second, iOS doesn't keep the same paths between redeploys (A new GUID is generated each time that an installation happens). @BillyMartin1964 For that reason, when you save in the database the path even with the "Library" folder included, the component is not able to find the photo when a new installation will be sent. But seems that iOS copies the "Library" folder to a Cache folder and then restored with the new GUID of the installation according to this post. https://forums.xamarin.com/discussion/comment/217282/#Comment_217282

Now, make sense that the db3 database is kept between updates if you reference the file like this:

       public static OrganizaDatabase Database
        {
            get
            {
                if (_database == null)
                {
                    _database = new OrganizaDatabase(DependencyService.Get<IFileHelper>().GetLocalFilePath(Constants.DatabaseFileName));
                }

                return _database;
            }
        }

        public string GetLocalFilePath(string fileName)
        {
            string docFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            string libFolder = Path.Combine(docFolder, "..", "Library", "Databases");

            if (!Directory.Exists(libFolder))
            {
                Directory.CreateDirectory(libFolder);
            }

            return Path.Combine(libFolder, fileName);
        }

So the idea is not saving the fullpath of the image in the sqlite database. A better way is saving the name of the image and create a computed property that gets the current path of the application and combine it with the name of the file.

        [Ignore]
        public string FotoPath
        {
            get
            {
                if (Device.RuntimePlatform == Device.Android)
                {
                    return this.Foto;
                }else
                {
                    if (string.IsNullOrEmpty(this.Foto))
                        return string.Empty;

                    return Path.Combine(DependencyService.Get<IFileHelper>().GetImagesFolder(Constants.RootFolder), this.Foto);
                }
            }
        }

This is the GetImageFolder method:

        public string GetImagesFolder(string folderName)
        {
            if (string.IsNullOrEmpty(folderName))
            {
                throw new ArgumentNullException(nameof(folderName));
            }

            string docFolder = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            string imagesFolder = Path.Combine(docFolder, "..", "Library", folderName);

            if (!Directory.Exists(imagesFolder))
            {
                Directory.CreateDirectory(imagesFolder);
            }

            return imagesFolder;
        }

Now, you just have to make the binding with the new computed property in all the forms that you want to show the photo.

Hope to be clear, regards!!

**Comment by BillyMartin1964** [comment]
**@juancho559 , I'm not quite sure I understand. I have never had a problem with iOS finding my database.**

**I have this in MainActivity:**
```

 var fileName = "HunterTracker.db3";
            var fileLocation = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            var fullPath = Path.Combine(fileLocation, fileName);
```

**And this as my Xamarin Forms Application Constructor:**

```
 public App(string DB_Path)
        {
            DbPath = DB_Path; // Database Path

```

**And it seems to work fine, except I can't use Xamarin Forms Previewer because I'm not allowed to have an argument in the constructor if I want to use it.**

**As for images, I was saving the ImageSource string into my database, but then switched to saving the byte[]. However, your comment has got me wondering if this would make my database too large.**

**Also, I would love to have my database stored on the sdCard when the phone has one.**

**At this point, I am totally lost and could really use your help. Thanks.**

**Comment by BillyMartin1964** [comment]
@juancho559 , what would the **Constants.RootFolder** be? I am using a custom folder when a user takes a picture with media plugin, but when he just chooses one of his photos from the gallery, I don't resave it, so I have no idea what the folder would be.

**Comment by BillyMartin1964** [comment]
@jamesmontemagno , I'm confused about what directory to find the pictures that are CHOSEN in the media plugin as opposed to the ones that are TAKEN. Taken photos are easy since they are saved to a folder of my choosing, but how do I find the folder that @juancho559 uses in his code above?

**His Code:**
                `return Path.Combine(DependencyService.Get<IFileHelper>().GetImagesFolder(Constants.RootFolder), this.Foto);`

**Comment by juancho559** [comment]
Hi @BillyMartin1964,
According to the explanation that I gave in my last post, I had to copy all the images (taken and picked) to an specific folder inside the “Library” folder in order to keep the files between updates. As I said before, I’m saving just a part of the path in my local database and then rebuilding the path with the new Guid that is generated each time that an installation in iOS is done. Feel free to send me an email with your contact info and we can talk about it if you want.

Regards,

**Comment by BillyMartin1964** [comment]
Thanks. I'm particularly interested on how to save the files that are chosen in the media plugin. The taken photos have an option for choosing the directory, but not the chosen photos.

Your email doesn't seem to be public. Please email me:

billy@sitesculptors.com

**Comment by BillyMartin1964** [comment]
@juancho559 , haven't heard from you. Code you please post the code that you use to save the chosen photos?

As you said, I NEED to have all of my fishing log photos saved to the same folder so that I can find them after an iPhone update.

This is what I have for both the taken and chosen photos... mostly from @jamesmontemagno 's examples:
```

 async void TakePhotoClicked(object sender, EventArgs e)
        {
            await Permissions.CheckPermissions(Permission.Camera);
            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                DisplayAlert("No Camera", ":( No camera available.", "OK");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
            {
                Directory = "FishingFanatic",
                Name = $"{DateTime.Now}.jpg",
                DefaultCamera = CameraDevice.Front,
                SaveToAlbum = true,
                CompressionQuality = 75,
                CustomPhotoSize = 50,
                PhotoSize = PhotoSize.MaxWidthHeight,
                MaxWidthHeight = 2000
            });

            if (file == null)
                return;


            PhotoLocation = file.Path;

            //DisplayAlert("File Location", file.Path, "OK");

            image.Source = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                file.Dispose();
                return stream;
            });
        }



        async void PickPhotoClicked(object sender, EventArgs e)
        {
            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                await DisplayAlert("Photos Not Supported", ":( Permission not granted to photos.", "OK");
                return;
            }
            var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
            {
                PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
            });

            if (file == null)
                return;



            PhotoLocation = file.Path;

            image.Source = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                file.Dispose();
                return stream;
            });
        }
```

**Comment by juancho559** [comment]
Hi @BillyMartin1964, according to your code, you need to do a copy of the file taken from the Media Plugin component in a specific folder that can be kept between updates. I'm going to mail you with my contact info.

regards,
