### ISSUE TITLE
TakeVideoAsync , CompressionQuality Not Working On API 22

### ISSUE THREAD

**Issue by AbanoubSedrak7** [jamesmontemagno/MediaPlugin#596]
## Bug Information

Version Number of Plugin:4.0.1.1
Device Tested On:Android 5.1. API 22
Simulator Tested On:
Version of VS: 2017
Version of Xamarin:3.0
Versions of other things you are using:

### Steps to reproduce the Behavior
When I Assign The Compression Quality Should Effect on The Resolution and Video Size but at my Phone (API 22) Not Working as i Excprected

### Expected Behavior
Compression Quality Should Work and Make the Resolution lower 
### Actual Behavior
The Video Recorded as it is not effected By Plugin

**Comment by jamesmontemagno** [comment]
This is based on the app's camera app. We pass the value and it is up to the camera after that.

**Comment by AbanoubSedrakDev** [comment]
Execuse me , but what If the camera not make compression how I can solve this problem please ?
