### ISSUE TITLE
TakePhoto/VideoAsync problem on simulator

### ISSUE THREAD

**Issue by Karvan** [jamesmontemagno/MediaPlugin#60]
## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Ipad , Iphone (IOS 9.3)
Simulator Tested On: iPhone 6s IOS 9.3

In Simulator CrossMedia.Current.IsCameraAvailable and CrossMedia.Current.IsTakePhotoSupported are true by default ,  and the result of var result = await CrossMedia.Current.TakePhotoAsync(options); is

System.NotSupportedException: Specified method is not supported.
at Plugin.Media.MediaImplementation.TakePhotoAsync (Plugin.Media.Abstractions.StoreCameraMediaOptions options)

and on Device (ios 9.3), the Plugin does not request for camera permission and only show a black screen. and if you add permission in AppManager in IOS, it will work fine.

**Comment by jamesmontemagno** [comment]
The simulator does not allow taking a photo.

The plugin will check against permissions the first time, but you should use the permission plugin or check yourself if you have the camera permission:
https://github.com/jamesmontemagno/PermissionsPlugin

In the future this will be integrated into the API
