### ISSUE TITLE
Permission required error even after set it in xamarin.forms 3.1 project

### ISSUE THREAD

**Issue by anirudhagupta** [jamesmontemagno/MediaPlugin#600]
## Bug Information

Version Number of Plugin: latest
Device Tested On: huawei 9 lite 
Simulator Tested On:
Version of VS:  VS latest and latest preview
Version of Xamarin: latest.
Versions of other things you are using:

### Expected Behavior

Camera permission required error even I set it in settings.

![image](https://user-images.githubusercontent.com/2105258/43922180-9b3bd50a-9c3b-11e8-80b2-e5cb80391799.png)
![image](https://user-images.githubusercontent.com/2105258/43922223-b720fc82-9c3b-11e8-8788-d6eefa6d814c.png)

**Comment by anirudhagupta** [comment]
for reproduce the issue, please check https://github.com/anirudhagupta/xamarin.forms-camera-testing

**Comment by jamesmontemagno** [comment]
You don't need this permissions. You just need to init the current activity: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information
