### ISSUE TITLE
Plugin.Media.Abstractions - Error can't deploy

### ISSUE THREAD

**Issue by Firice** [jamesmontemagno/MediaPlugin#602]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
Error MT2002: Failed to resolve "Plugin.Media.Abstractions.MediaFile" reference from "Plugin.Media, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" (MT2002)

Version Number of Plugin: 4.0.1.5
Device Tested On: 
Simulator Tested On:
Version of VS: 7.5.4 (Build 3)
Version of Xamarin: 3.1.0.583944
Versions of other things you are using:

### Code snippet

            await CrossMedia.Current.Initialize();

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                Console.WriteLine("No Camera: No camera available");
                return;
            }

            var file = await CrossMedia.Current.TakePhotoAsync(null);

            if (file == null) return;

            Console.WriteLine("File Location {0}", file.Path);

            ImageSource = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                return stream;
            });

**Comment by jamesmontemagno** [comment]
Uninstall the plugin from all of your libraries/apps and re-install them via NuGet

**Comment by Valliammai-Subramanian** [comment]
Tried re-installing them via NuGet. Still problem not resolved. Showing the error as "Failed to resolve "Plugin.Media.Abstractions.MediaFile" reference from "Plugin.Media, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null". 

Any other ideas??
