### ISSUE TITLE
Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file

### ISSUE THREAD

**Issue by LeonidasMx** [jamesmontemagno/MediaPlugin#603]
Version Number of Plugin: 4.01.5
Device Tested On: Samsun Glaxy S5
Simulator Tested On:
Version of VS:  2017 Versión 15.8.0
Version of Xamarin:

I have followed follow up all steps of the tutorial for make a simple application, for select one photo of the some directory or Take one Photo, the metod for select the photo works fine but the metod for Take a photo send the error :

Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project.

I noticed  that the the code 

 var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                });

returns the path 
"/storage/emulated/0/Android/data/com.companyname.AIAnalizeImage/files/Pictures/temp/images_5.jpeg" 

and the code
                var file = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium
                });

returs the path 
/storage/extSdCard/Android/data/com.companyname.AIAnalizeImage/files/Pictures

I don't know why the second code returns the route of the external storage "extSdCard" in stead off "emulated".
Some one have some Idea about it, thaks in advance.

Regards.

**Comment by apaini** [comment]
I have the same issue, this code works fine before. just leave this here for solutions

**Comment by apaini** [comment]
lol, it's our fault. just in case if someone have the same issue check AndroidManifest.xml file android:authorities="${applicationId}.fileprovider"  and chage to android:authorities="YOUR_APP_PACKAGE_NAME.fileprovider"

**Comment by Neelampclarion** [comment]
@apaini  my silly mistake.thanks for guiding me

**Comment by natilivni** [comment]
tried the above fix and I am still getting the issue.  Any other ideas?

**Comment by KthProg** [comment]
I'm also getting this issue after the fix above

**Comment by ArthurAttout** [comment]
After adding the provider in the manifest, another exception pops up : 
`
Java.Lang.RuntimeException: Unable to get provider com.companyname.Biomasse.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.companyname.Biomasse.FileProvider" on path: DexPathList[[zip file "/data/app/com.companyname.Biomasse-1/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname.Biomasse-1/lib/x86, /data/app/com.companyname.Biomasse-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]`

This is the manifest : 
```

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.Biomasse" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="27" />
	<uses-permission android:name="android.permission.CAMERA" />
	<application android:label="Biomasse.Android">
    <provider
      android:name="FileProvider"
      android:authorities="com.companyname.Biomasse.Android.fileprovider">

    </provider>
	</application>
</manifest>
```

I tried with 
android:authorities="com.companyname.fileprovider">
android:authorities="com.companyname.Biomasse.fileprovider">
android:authorities="com.companyname.Biomasse.Android.fileprovider">

with no luck

**Comment by ArthurAttout** [comment]
My bad, this was because I had to add the `<meta-data>` tag in provider.  I used [this](https://forums.xamarin.com/discussion/141732/why-file-is-not-opening-fileprovider-with-dependency-injection) as a template

**Comment by Ciip1996** [comment]
can you post the fixed xml @ArthurAttout  please?

**Comment by ArthurAttout** [comment]
I threw it away, Xamarin was giving me headaches. I think it was something like
```

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.AppQ4evo" android:installLocation="preferExternal">
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="27" />
    <uses-permission android:name="android.permission.INSTALL_LOCATION_PROVIDER" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <application android:label="AppQ4evo.Android" android:icon="@drawable/baseline_account_circle_black_18dp">
        <provider android:name="android.support.v4.content.FileProvider" android:authorities="com.companyname.AppQ4evo.fileprovider" android:grantUriPermissions="true" android:exported="false">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
    </application>
</manifest>
```

**Comment by haxxanshah** [comment]
I am still stucked with **Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project.**

Kindly review my Manifest.xml

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="Camera.Capture.Camera.Capture" android:versionCode="1" android:versionName="1.0" android:installLocation="auto">
	<uses-sdk android:minSdkVersion="19" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <provider android:name="android.support.v4.content.FileProvider"
      android:authorities="${applicationId}.fileprovider"
      android:exported="false"
      android:grantUriPermissions="true">
    <meta-data android:name="android.support.FILE_PROVIDER_PATHS"
      android:resource="@xml/file_paths"></meta-data>
  </provider>
  </manifest>`

**Comment by softsan** [comment]
I am still having that issue:(Media plugin version: 4.3.1-beta)
`ERROR:Unable to get file location. This most likely means that the file provider information is not set in your Android Manifest file. Please check documentation on how to set this up in your project.`


```
<application android:icon="@drawable/icon" android:label="Merck">
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="myproject.mypackage.fileprovider" android:exported="false" android:grantUriPermissions="true">
			<meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
		</provider>

```

**Comment by HK-AERIAL-VTOL** [comment]
softsan - did you get this figured out?

**Comment by softsan** [comment]
Yeh in my case the package name is was different (case sensitivity issue)

**Comment by llsspratt** [comment]
i still can not get it to work. I have looked this up and followed everyone of the direction with the same results. Can someone please help me ... this is awful.

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.xamarinfirebasestorage">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />	
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />	
	<application android:label="XamarinFirebaseStorage.Android" android:theme="@style/MainTheme">		
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.companyname.xamarinfirebasestorage.fileprovider" android:grantUriPermissions="true" android:exported="false">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
	</application>				
</manifest>

**Comment by llsspratt** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1" android:versionName="1.0" package="com.companyname.xamarinfirebasestorage">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="30" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.CAMERA" />	
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />	
	<application android:label="XamarinFirebaseStorage.Android" android:theme="@style/MainTheme">		
		<provider android:name="android.support.v4.content.FileProvider" android:authorities="com.companyname.xamarinfirebasestorage.fileprovider" android:grantUriPermissions="true" android:exported="false">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths" />
        </provider>
	</application>				
</manifest>
`

**Comment by llsspratt** [comment]
![error](https://user-images.githubusercontent.com/72828397/103049909-056b6280-4561-11eb-8635-8cd1d07ec058.png)

**Comment by DiegoVenancioVieira** [comment]
> i still can not get it to work. I have looked this up and followed everyone of the direction with the same results. Can someone please help me ... this is awful.

Do you found solution?

**Comment by RavindraJijotia** [comment]
I had same issue, i downgraded Xam.Plugin.Media version to 4.0.1.5

![image](https://user-images.githubusercontent.com/7958887/123524955-d2e82100-d6cd-11eb-9f7c-3a7cbfde2310.png)

**Comment by devatrivanus18** [comment]
right click the file_paths.xml then build action choose AndroidResource

**Comment by abhidotnet** [comment]
I was facing a similar issue and this is my android manifest file, in case it helps someone.

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
		  android:versionCode="1" 
		  android:versionName="1.0" 
		  package="SingleTon.Android"
		  android:installLocation="auto">
    <uses-sdk android:minSdkVersion="21" android:targetSdkVersion="31" />
    <application android:label="SingleTon.Android" android:theme="@style/MainTheme">
			<provider android:name="androidx.core.content.FileProvider"
		  android:authorities="SingleTon.Android.fileprovider"
		android:exported="false" android:grantUriPermissions="true">
				<meta-data android:name="android.support.FILE_PROVIDER_PATHS"
						   android:resource="@xml/file_paths"></meta-data>
			</provider>
	</application>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.CAPTURE_AUDIO_OUTPUT" />
	<uses-permission android:name="android.permission.CAPTURE_SECURE_VIDEO_OUTPUT" />
	<uses-permission android:name="android.permission.CAPTURE_VIDEO_OUTPUT" />
</manifest>
```
