### ISSUE TITLE
Android 8.0 | LG G6 - Both Camera and Pick picture functionalities crash: ResourcesImpl.loadDrawableForCookie

### ISSUE THREAD

**Issue by aymeric-apcurium** [jamesmontemagno/MediaPlugin#609]
Issue - camera crashing and causing app to return to root page on LG G6.

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: LG G6
Simulator Tested On:
Version of VS: 15.8.1
Version of Xamarin: 4.11.0.732
Versions of other things you are using:

### Steps to reproduce the Behavior
On a Android Oreo device (LG G6):
Start the camera TakePhotoPicker().
Take photo.
 ... crashes.

### Expected Behavior

Should not crash but simply return to page that invoked the camera

### Actual Behavior

Crashes and goes back to root page

### Code snippet

`await CrossMedia.Current.Initialize();

                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    await UserDialogs.Instance.AlertAsync(Master.upload_doc_no_camera);
                    return null;
                }
                var picture = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    Directory = DefaultDirectoryName,
                    Name = DefaultFileName
                });`

### Screenshots

Hockey App Crash report:
https://gist.github.com/aymeric-apcurium/d51e16880079b2dbe260ef49ba7bb641

**Comment by jamesmontemagno** [comment]
It says it is trying to load: res/mipmap-anydpi-v26/icon.xml 

I am not sure if that is this plugin at all.

**Comment by aymeric-apcurium** [comment]
Agreed, and yet it only happens on my LG G6. Other Android phones we've been testing are working fine.
 
I'll try to post in the next day the device manager logs where we've seen some errors tied to the samsung camera while trying to take a picture.

**Comment by aymeric-apcurium** [comment]
This is the error we saw while attempting to take a picture:
`08-30 15:12:54.357: E/AndroidRuntime(27633): FATAL EXCEPTION: main
08-30 15:12:54.357: E/AndroidRuntime(27633): Process: com.lge.camera, PID: 27633
08-30 15:12:54.357: E/AndroidRuntime(27633): java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
08-30 15:12:54.357: E/AndroidRuntime(27633):    at com.lge.camera.managers.TimerManager.displayInitCounter(TimerManager.java:411)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at com.lge.camera.managers.TimerManager$1.handleMessage(TimerManager.java:146)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at android.os.Handler.dispatchMessage(Handler.java:105)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at android.os.Looper.loop(Looper.java:164)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at android.app.ActivityThread.main(ActivityThread.java:6710)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at java.lang.reflect.Method.invoke(Native Method)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
08-30 15:12:54.357: E/AndroidRuntime(27633):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

**Comment by ornolisvt** [comment]
Same error on LG G6:
09-05 12:23:42.190 22791-22791/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lge.camera, PID: 22791
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at com.lge.camera.managers.TimerManager.displayInitCounter(TimerManager.java:411)
        at com.lge.camera.managers.TimerManager$1.handleMessage(TimerManager.java:146)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

**Comment by lepijulien** [comment]
Same issue for LG G6 on android 8.0

**Comment by nichojo89** [comment]
Also experiencing this on LG G6

**Comment by jamesmontemagno** [comment]
Looks like an issue in the LG G6 camera app, nothing I can do about this.

**Comment by mateuszSawa** [comment]
@jamesmontemagno How to fix this issue : 
1. Download source
2. Comment setting UseBackCamera line or check if it's not LG G6 (https://github.com/jamesmontemagno/MediaPlugin/blob/0150a2236b6c420a0dfd23f325a4c5a5bddaba03/src/Media.Plugin/Android/MediaPickerActivity.cs#L148)

**Comment by nichojo89** [comment]
Not the most readable but i've added a work around here --> https://github.com/jamesmontemagno/MediaPlugin/issues/586#issuecomment-417427136

**Comment by sroyvs** [comment]
Also running into this but, it's weird because if I turn off (not reboot, but simply press the power button to lock the screen) the phone and unlock it, everything now works.

**Comment by cansub1974** [comment]
> Also running into this but, it's weird because if I turn off (not reboot, but simply press the power button to lock the screen) the phone and unlock it, everything now works.

That works for me as well.  Very frustrating!  I lock and then unlock the phone while the camera is open and it works just fine.

**Comment by cansub1974** [comment]
> > Also running into this but, it's weird because if I turn off (not reboot, but simply press the power button to lock the screen) the phone and unlock it, everything now works.
> 
> That works for me as well. Very frustrating! I lock and then unlock the phone while the camera is open and it works just fine.

If you switch between front and back camera while the camera is open it will work.

**Comment by gsemenov** [comment]
I have the same problem on the LG stylo 4 device :-(

**Comment by gsemenov** [comment]
I found one solution, you can check it here https://github.com/jamesmontemagno/MediaPlugin/issues/586#issuecomment-473931382
