### ISSUE TITLE
Xamarin all OS: take a photo with CrossMedia.Current.TakePhotoAsync

### ISSUE THREAD

**Issue by erportico** [jamesmontemagno/MediaPlugin#61]
## Bug 
I'm creating a project where I have to take a lot of pictures. In my previous project for iOS all are working fine. I'm using the same code for a new project for all platforms (iOS, Android and UWP).

When I take a photo on Android the stream is empty. In UWP when I try to open the page where I can take a photo, the application is blocked: after 3-5 minutes it's unblocked and I can take a photo.

Version Number of Plugin: 2.3.0
Device Tested On: 
- Nokia Lumia 735 (Windows 10)
- Cubot Rainbow Sim Free Smartphone Dual Sim 3G Unlocked 5 Inch HD Android 6.0 Quad Core 1.3 GHz 1 GB Ram 16GB Rom Smart Phone 13MP Camera GPS WIFI Hots 
- iPhone 6s

Simulator Tested On:
- Android 6.0 as Nexus 6P API 23 x86
- my desktop with Windows 10

### Expected Behavior
I can take take a photo to save it on disk

### Steps to reproduce the Behavior

```
        /// <summary>
        /// Gets the camera command.
        /// </summary>
        /// <value>The camera command.</value>
        public ICommand CameraCommand
        {
            get { return _cameraCommand ?? new Command(async () => await ExecuteCameraCommand(), () => CanExecuteCameraCommand()); }
        }

        /// <summary>
        /// Determines whether this instance can execute camera command.
        /// </summary>
        /// <returns><c>true</c> if this instance can execute camera command; otherwise, <c>false</c>.</returns>
        public bool CanExecuteCameraCommand() {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported) {
                return false;
            }
            return true;
        }

        /// <summary>
        /// Executes the camera command.
        /// </summary>
        /// <returns>The camera command.</returns>
        public async Task ExecuteCameraCommand() {
            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions());
            
            if (file == null)
                return;

            byte[] imageAsBytes = null;
            using (var memoryStream = new MemoryStream()) {
                file.GetStream().CopyTo(memoryStream);
                file.Dispose();
                imageAsBytes = memoryStream.ToArray();
            }

            if (imageAsBytes.Length > 0) {
                var resizer = DependencyService.Get<IImageResize>();
                imageAsBytes = resizer.ResizeImage(imageAsBytes, 1080, 1080);

                var imageSource = ImageSource.FromStream(() => new MemoryStream(imageAsBytes));
                _images.Add(new GalleryImage { Source = imageSource, OrgImage = imageAsBytes });
            }
        }

```
Thank you for your job!

**Comment by jamesmontemagno** [comment]
Did you call:   await CrossMedia.Current.Initialize(); like the readme says?

**Comment by erportico** [comment]
Yes. I inserted this in a function like 

`        /// <summary>
        /// Initializes the media.
        /// </summary>
        private async void InitMedia() {
            await CrossMedia.Current.Initialize();
        }`

and I'm calling it in the ViewModel constructor. I tried to insert it in the function _ExecuteCameraCommand_ before calling _TakePhotoAsync_ but the result is the same.

**Comment by erportico** [comment]
For UWP I added on _MainPage.xaml.cs_ the _InitMedia_ and now it's working fine.
I tried to add it in the Android project but the problem is still there.

**Comment by MSiccDev** [comment]
I can confirm, having the same issue here on 2.3.0 and 2.5.1 beta40 (from Nuget) on Android N.

**Comment by jamesmontemagno** [comment]
@erportico 

You should call the Initialize() before you call the take photo:

```
 public async Task ExecuteCameraCommand()
        {

            await CrossMedia.Current.Initialize();
            var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions());

```

of do it in the pages on appearing:

```
 bool initialized;
        protected override async void OnAppearing()
        {
            base.OnAppearing();
            await CrossMedia.Current.Initialize();
            initialized = true;
            ((Command)CameraCommand).ChangeCanExecute();
        }
```

For UWP you must call initialize before calling anything else, so update your CanExecute to:

```
public bool CanExecuteCameraCommand()
        {
            if (!initialized)
                return false;

            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
            {
                return false;
            }
            return true;
        }
```

Also, make sure in your MainActivity you copied this code in for Android:

```
public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Permission[] grantResults)
        {
            PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }
```

I assume you also set your target to 23:
![image](https://cloud.githubusercontent.com/assets/1676321/18105749/749617cc-6eb5-11e6-86b0-3e1016584af2.png)



I tested the code out that you posed with my modifications on my Nexus 6P running 7.0 stock and it worked perfect. I got a file and got the stream from it.

For UWP I set the Webcam capability in the appxmanifest. In this instance your Command will have an issue because 
Small optimization: 
Finally, you should make sure you actually are creating a new command in your getter for the command:

```
public ICommand CameraCommand
        {
            get { return _cameraCommand ?? (_cameraCommand = new Command(async () => await ExecuteCameraCommand(), () => CanExecuteCameraCommand())); }
        }
```

Else it will just create a new one every time.


Closing as I tested this on all platforms with production level, and here is a test app that I used:

[App36.zip](https://github.com/jamesmontemagno/MediaPlugin/files/445906/App36.zip)

**Comment by erportico** [comment]
HI James,
I applied everything you said me but sometimes I have the same problem.

The problem is "sometimes" because if I tried for 10 times maybe is working but after that one time is wrong as in the following picture.

I take a phone, I have a path in the variable...
![filewithpath](https://cloud.githubusercontent.com/assets/19671573/18387462/b479fd2c-7694-11e6-8fea-8d1798d25458.PNG)

but when I convert the file in a `MemoryStream`, I don't receive in `imageAsBytes` anything.
![filewithpathbutzerobytes](https://cloud.githubusercontent.com/assets/19671573/18387463/b492f840-7694-11e6-9dcc-d0816c4f9fbe.PNG)

**Comment by erportico** [comment]
My fix at this problem is 

```
            byte[] imageAsBytes = null;
            using (var memoryStream = new MemoryStream()) {
                file.GetStream().CopyTo(memoryStream);
                imageAsBytes = memoryStream.ToArray();

                if (imageAsBytes.Length == 0) {
                    imageAsBytes = await FileHelper.GetImageAsByte(file.Path);
                }
                file.Dispose();
            }
```
