### ISSUE TITLE
Can't crop image

### ISSUE THREAD

**Issue by busidex-vinbrown** [jamesmontemagno/MediaPlugin#611]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: IPhone 5s
Simulator Tested On: N/A
Version of VS:  VS2017  v15.8.2
Version of Xamarin: 4.11.0.756
Versions of other things you are using:

### Steps to reproduce the Behavior
using the following code, I can take the picture, and cropping appears to be started, but I cannot actually change the image size.

var file = await CrossMedia.Current.TakePhotoAsync (new StoreCameraMediaOptions{
					AllowCropping = true,
					PhotoSize = PhotoSize.Small,
					CompressionQuality = 50
				});
### Expected Behavior
I can crop the image.
### Actual Behavior
I cannot crop the image.
### Code snippet

var file = await CrossMedia.Current.TakePhotoAsync (new StoreCameraMediaOptions{
					AllowCropping = true,
					PhotoSize = PhotoSize.Small,
					CompressionQuality = 50
				});

**Comment by jamesmontemagno** [comment]
It uses the build in cropping from iOS, we have no additional control over this.
