### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented. Facing the same issue even after copying the libraries

### ISSUE THREAD

**Issue by DivyaG014** [jamesmontemagno/MediaPlugin#615]
I included media plugin in all my projects but still i am getting the same error.
"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented."

when i am trying to access camera with TakePhotoAsync() method.
Please let me know if i am missing any other libraries.

**Comment by jamesmontemagno** [comment]
unable to reproduce. try to uninstall and re-install the nugets
