### ISSUE TITLE
Increase size of images (or use PhotoSize information) when AllowCropping is true (iOS)

### ISSUE THREAD

**Issue by smallcandles** [jamesmontemagno/MediaPlugin#616]
When taking a photo with AllowCropping set to true on iOS, the image returned from TakePhotoAsync is significantly smaller than expected.  

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Iphone 5s
Simulator Tested On: N/A (no camera in simulator)
Version of VS: 15.7.5
Version of Xamarin: 3.1.0.697729
Versions of other things you are using:

### Steps to reproduce the Behavior

Set AllowCropping to true and call TakePhotoAsync.  Set PhotoSize to Full if you choose, but I didn't see any difference regardless of Full or MaxWidthHeight with larger numbers (say 1500)

### Expected Behavior

Photos taken with my camera are 3024 x 4032.  I expected cropped images to be a smaller size directly related to the total area/portion of the image that is left intact during the crop.  If I don't zoom in at all, I would expect the resulting image to be rather large as well -- 2000x2000 or larger.

### Actual Behavior

All cropped images are returned as 640x640 in size or smaller depending on how much I zoom in.  The photo saved to the album is also this small.

### Code snippet

var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        PhotoSize = Plugin.Media.Abstractions.PhotoSize.Full,
                        DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
                        Directory = "MyProject",
                        SaveToAlbum = true,
                        AllowCropping = true,   // this will only work on iOS
                    });

**Comment by jamesmontemagno** [comment]
iOS does the cropping, i have no control
