### ISSUE TITLE
GetStream returns full stream size.

### ISSUE THREAD

**Issue by DualOpAmp** [jamesmontemagno/MediaPlugin#617]
After calling TakPhotAsync to return a compressed photo:
`var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                    {
                        CompressionQuality = 30,
                        CustomPhotoSize = 30,
                        MaxWidthHeight = 1000,
                        Directory = "CENSORED"
                        Name = photoName + ".jpg"
                    });`
I then call `file.GetStream()` to return a compressed version of the stream, which I then store in an array of bytes. Unfortunately, this is giving me the full-size, uncompressed stream of the photo. How do I get the stream from the photo that was taken, but resized to a more manageable size for the byte array. The bytes are going to eventually be sent over the wire to a POST URL as JSON.

**Comment by Moltroon** [comment]
Hello,
Unless I'm mistaken, if you want to use MaxWidthHeight parameter you need to add the PhotoSize parameter.
PhotoSize = PhotoSize.MaxWidthHeight

**Comment by Brosten** [comment]
Setting the PhotoSize has no effect on the compression. I also experience the same problem. Compression quality seems not to work.

**Comment by albilaga** [comment]
@DualOpAmp if you want to set CustomPhotoSize you need to set PhotoSize=PhotoSize.Custom like this
```
 var cameraOptions = new StoreCameraMediaOptions
                {
                   
                    PhotoSize = PhotoSize.Custom,
                    CustomPhotoSize = 30,
                };
```
