### ISSUE TITLE
Taking photo without previews.

### ISSUE THREAD

**Issue by ncmj-1998** [jamesmontemagno/MediaPlugin#622]
Is there a way to take photo repeatedly without having preview of it?

The use case for this scenario is that I have my phone mounted at a tripod and i am using a bluetooth clicker to take photo continuously and do not want any interaction with the phone.

**Comment by simonemarra** [comment]
I'm following the question. I need this feature too. On my old Nexus 5X I could confirm the preview using the volume up button (the same used to shoot a pic using a common selfie stick), but on other android devices it was not accepted.

**Comment by jamesmontemagno** [comment]
This is not possible as I call out to the native camera app that controls it.
