### ISSUE TITLE
Hololens support

### ISSUE THREAD

**Issue by jimbobbennett** [jamesmontemagno/MediaPlugin#625]
The media plugin doesn't work on HoloLens. The API to check if the camera is present works, but when the camera is accessed you get redirected to the store to download a camera app that is not supported on HoloLens.

First fix - mark HoloLens as not supported by checking the device family: https://elbruno.com/2016/08/24/hololens-some-apis-will-work-other-no-and-there-is-no-easy-way-to-find-it-s/

Later fix - implement support using the APIs shown here: https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/CameraStarterKit/cs/MainPage.xaml.cs

**Comment by jamesmontemagno** [comment]
No plans to support hololens from this package at this point. Only calling out to native api camera applications. Thanks for the suggestion though.
