### ISSUE TITLE
Only one operation can be active at at time | at Plugin.Media.MediaImplementation.GetMediaAsync

### ISSUE THREAD

**Issue by rasel-tr** [jamesmontemagno/MediaPlugin#626]
## Bug Information

After updating to latest plugin and xamarin forms, my project's old media pick code doesn't work on iOS anymore giving the error on the subject. Android part works as excepted.  If I delete the permissions of the app. It works once after the permissions are given but not after that. 

Version Number of Plugin: 4.0.1.5
Device Tested On: Iphone6
Simulator Tested On: -
Version of VS: 15.8.5
Version of Xamarin: 4.11.0.776
Versions of Xamarin iOS: 12.0.0.15

### Steps to reproduce the Behavior

try to use CrossMedia.Current.PickPhotoAsync()

### Expected Behavior

Opens the media picker page

### Actual Behavior

gives exception

### Code snippet

`if (Settings.Gallery)
{
    media = await CrossMedia.Current.PickPhotoAsync();
}`

**Comment by Simba-Mupfunya** [comment]
Same error when calling 'await TakePhotoAsync'

**Comment by rasel-tr** [comment]
@Simba-Mupfunya yes, the first call doesn't open the cam or gallery page and later calls throw this error. This plugin doesn't work anymore for iOS with Xamarin.Forms latest versions including 3.3.0.912540. And as far as I see, the maintenance of the code isn't active, I'll look for another solution for iOS or write my own code.

**Comment by Simba-Mupfunya** [comment]
@rasel-tr thanks for the confirmation on what i was noticing, i guess we have to write a dependency for iOS

**Comment by jburditt** [comment]
I also get this error on second call to "await PickPhotoAsync". If I make the click event sync instead of async, it does not crash.

**Comment by rasel-tr** [comment]
I wrote my own code to do the task but same happens. After debugging, I solved the problem with using Device.BeginInvokeOnMainThread. Something changed in Xamarin.Forms that broke my old code. Not the plugin problem.
