### ISSUE TITLE
Err: Unfortunatly, Camera has stopped (android 8.1 (API 27))

### ISSUE THREAD

**Issue by gsemenov** [jamesmontemagno/MediaPlugin#631]
I had problem with android 8.1 with my app. And then I tried to run your demo sample https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples . And got the same err on the two different real devices with android 8.1(API 27) . It strange, but it worked on emulator with API 27. And it strange, but some times it works on the android 8.1, and I don't know why. I tried to build, rebuild, reboot, run on different PC with different VS, and got this error too.

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Android 8.1(API 27). LG Q6 Plus and xiaomi mi a1
Simulator Tested On: 
Version of VS: 15.8.9
Version of Xamarin: 3.1.0.637273 (and also tried with 3.3.0.967583)
Versions of other things you are using: 

### Steps to reproduce the Behavior
I just run your sample on the real device with android 8.1. Them click "Take photo" button, then click button to take the photo on the native camera -> got err "Unfortunatly, Camera has stopped" 
### Code snippet
https://github.com/jamesmontemagno/MediaPlugin/tree/master/samples

### Screenshots
![ezgif-5-a2a39cdab0f7](https://user-images.githubusercontent.com/5072093/48412913-124ce380-e757-11e8-9897-4cc5572684f4.gif)

**Comment by georgemaksimenko** [comment]
+1

**Comment by jamesmontemagno** [comment]
Do you have kill activities on in your developer settings?

**Comment by gsemenov** [comment]
Which settings do you mean?  (I can provide screenshots of settings screens from the phone or VS)
For example these settings on the Android Options tab:
![2018-12-02_0-10-49](https://user-images.githubusercontent.com/5072093/49332913-d1fabb80-f5c6-11e8-9aca-8c29e66f57e4.png)

**Comment by sroyvs** [comment]
We have the same problem, it works fine on some older android devices, and on the API 27 emulator, but on my LG G6 (Android 8.0.0 - API 26) I get that constant camera app crashing

**Comment by gsemenov** [comment]
just for information: if I open camera and switch from back to front camera, then switch to back again and make photo it works. So some strange bug

**Comment by sroyvs** [comment]
Another way around the bug is to turn off (not reboot, but simply press the power button to lock the screen) the phone and unlock it, this will allow to take a picture and you wont get the "Camera has stopped" error

**Comment by khoduley** [comment]
why was this issue closed?
I have the same problem even in 4.1.1-beta.

**Comment by gsemenov** [comment]
Did somebody resolve this issue? Because it is still actual issue for my app.

**Comment by gsemenov** [comment]
I found one solution, you can check it here:
https://github.com/jamesmontemagno/MediaPlugin/issues/586#issuecomment-473931382
