### ISSUE TITLE
AlbumPath is null after TakePhotoAsync

### ISSUE THREAD

**Issue by georgikoemdzhiev** [jamesmontemagno/MediaPlugin#633]
## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Full Windows 10 tablet (v**10.0.17134**; Build **17134**)
Simulator Tested On: N/A
Version of VS: **15.9.2**
Version of Xamarin: **3.3.0.967583**
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
1. Follow all of the setup steps for UWP platform
2. Make sure that _StoreCameraMediaOptions_'s _SaveToAlbum_ is set to True
3. Execute _TakePhotoAsync_
4. Inspect the value of _AlbumPath_
### Expected Behavior
The AlbumPath's property should not be null but contain photo location data
### Actual Behavior
AlbumPath is null
### Code snippet
```
private async void TakePictureButtonOnClicked(object sender, EventArgs e)
{
    if (!await CheckPermissions())
    {
        await DisplayAlert("Permissions Denied", "Unable to take photos.", "OK");
    }

    var options = new StoreCameraMediaOptions();
    options.SaveToAlbum = true;
    options.DefaultCamera = CameraDevice.Rear;
    options.AllowCropping = CropEnabledSwitch.IsToggled;
    options.Directory = "InspectExPhotos";
    options.CompressionQuality = (int) CompressionSlider.Value;
    PhotoSize selectedSize = (PhotoSize) PhotoSizeQualityPicker.SelectedItem;
    options.PhotoSize = selectedSize;

    var photo = await CrossMedia.Current.TakePhotoAsync(options);
    if (photo == null) return;

    //Get the public album path
    var aPpath = photo.AlbumPath;

    //Get private path
    var path = photo.Path;

    AddPhoto(photo);
}
```
### Screenshots
![image](https://user-images.githubusercontent.com/11027608/48769852-99004400-ecb4-11e8-8765-e489a699f497.png)

Test Project:
[PhotosTest.zip](https://github.com/jamesmontemagno/MediaPlugin/files/2599412/PhotosTest.zip)

**Comment by jamesmontemagno** [comment]
It is not supported on Windows 10
