### ISSUE TITLE
The app is getting crash while calling the TakePhotoAsync method as it throwing the null reference Exception 

### ISSUE THREAD

**Issue by IshaDawar** [jamesmontemagno/MediaPlugin#634]
## Bug Information

Version Number of Plugin:2.6.2
Device Tested On:HTC Nexus 5 
Simulator Tested On:N/A
Version of VS: 7.4.3
Version of Xamarin: 2.4.0.38779
Versions of other things you are using: N/A

### Steps to reproduce the Behavior
1.Follow all of the setup steps for Android platform
2.Execute TakePhotoAsync Method
3. After Clicking Picture From Camera It Produce Null Reference Error.It shows the following exception-
System.NullReferenceException:Object reference not set to an instance of an object.
### Expected Behavior
App should not crash

### Actual Behavior
Path is null

### Code snippet
        async void Take_Photo_Tapped(object sender, EventArgs e)
        {
                 try
                    {
                        scannerViewModel.IsLoading = true;
                        await CrossMedia.Current.Initialize();
                        if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                        {
                            await App.Instance.Alert("alert, "No camera available.", "ok);
                             return;
                        }
                        ImageSource IOSImageSource = null;
                        var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                        {
                            CompressionQuality = 99,
                            PhotoSize = PhotoSize.Full,
                            SaveToAlbum = true
                        });

                        if (file == null)
                        {
                              return;
                        }
                        else
                        {
                            App.ImageStream = file.GetStream();
                        }
                     
                    }
                    catch (Exception e1)
                    {
                        await App.Instance.Alert("Alert", e1.Message,"ok);
                          return;
                    }                             
        }

### Android Manifest
       <provider android:name="android.support.v4.content.FileProvider" android:authorities="packagename.fileprovider" android:exported="false" android:grantUriPermissions="true">
            <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
      </provider>

### file Paths
      <?xml version="1.0" encoding="utf-8"?>
     <paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-files-path name="my_images" path="Pictures" />
    </paths>

**Comment by jamesmontemagno** [comment]
Would need a stack trace. Works fine in the sample

**Comment by IshaDawar** [comment]
Unfortunaly it crash without any stack trace..only shows the null reference error...as Object reference not set to an instance of an object.

**Comment by sedders123** [comment]
We are also having TakePhotoAsync return null for us, despite opening the intent and saving the image to the directory specified in the xml_paths file.

Is there anything we can do to help diagnose and debug this?

**Comment by sedders123** [comment]
Everything now seems to be working as expected. Unfortunately, I'm not 100% sure on the exact fix, though I believe that it was something to do with the configuration of the AndroidManifest.xml and the file provider paths. 

In case they are useful for anyone else, here are my working files

**AndroidMainfest.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.REDACTED.REDACTED"
          android:installLocation="auto" android:versionCode="19" android:versionName="1.0.18">
  <uses-sdk android:minSdkVersion="15" android:targetSdkVersion="27" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <application android:largeHeap="True" android:label="REDACTED" android:icon="@drawable/Icon">
    <provider android:name="android.support.v4.content.FileProvider"
              android:authorities="${applicationId}.fileprovider" android:exported="false"
              android:grantUriPermissions="true">
      <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/file_paths"></meta-data>
    </provider>
  </application>
</manifest>
```

**xml/file_paths.xml**
```xml
<?xml version="1.0" encoding="utf-8"?>

<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="my_images" path="Android/data/com.REDACTED.REDACTED/files/Pictures" />
  <external-path name="my_movies" path="Android/data/com.REDACTED.REDACTED/files/Movies" />
</paths>
```
