### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by MariSelviK** [jamesmontemagno/MediaPlugin#635]
Hi,
 I am implementing imagecapture in xamarin.forms. But app is crashed when it opens an android.

Java.NullPointerException
Attempt to invoke virtual method 'void android.support.v7.widget.ContentFrameLayout.setId(int)' on a null object reference

**Comment by TKNos** [comment]
@MariSelviK This issue was already [mentioned before](https://github.com/jamesmontemagno/MediaPlugin/issues/226). [This](https://github.com/jamesmontemagno/MediaPlugin/issues/226#issuecomment-298005958) should fix your problem.
