### ISSUE TITLE
I can call the camera on ios 9 and click on the latest ios system and it will crash

### ISSUE THREAD

**Issue by hsyxxwyq** [jamesmontemagno/MediaPlugin#636]
I can call the camera for my photo on ios 9, but on the latest ios system, clicking directly crashes

**Comment by hsyxxwyq** [comment]
I can call the camera for my photo on ios 9, but on the latest ios system, clicking directly crashes

**Comment by jamesmontemagno** [comment]
Are you running on device or simulator? What is the crash?

**Comment by jamesmontemagno** [comment]
Did you add permissions?
