### ISSUE TITLE
App crashing with: NullReferenceException in MediaPickerActivity.GetMediaFileAsync

### ISSUE THREAD

**Issue by PenguinPero** [jamesmontemagno/MediaPlugin#639]
I've got the crash report from hockeyapp with the following stacktrace:

`Xamarin caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object`

`Plugin.Media.MediaPickerActivity.<>c__DisplayClass30_0.<GetMediaFileAsync>b__0(Task<TResult> t)<5939e997f291496f805023da28f3a447>:0`

`System.Threading.Tasks.ContinuationResultTaskFromResultTask<TAntecedentResult, TResult>.InnerInvoke()<314bdcfad5c64d9d8f1b76a833634101>:0`

`System.Threading.Tasks.Task.Execute()<314bdcfad5c64d9d8f1b76a833634101>:0`

`Plugin.Media.MediaPickerActivity.<OnActivityResult>d__32.MoveNext()<5939e997f291496f805023da28f3a447>:0`

By looking at the code of the plugin and analyzing the crash I would say that this might be the issue:

https://github.com/jamesmontemagno/MediaPlugin/blob/caef079c36bb5f7497b73820a09b3098ba326c4b/src/Media.Plugin/Android/MediaPickerActivity.cs#L305

https://github.com/jamesmontemagno/MediaPlugin/blob/caef079c36bb5f7497b73820a09b3098ba326c4b/src/Media.Plugin/Android/MediaPickerActivity.cs#L310

at line 305 result for the task is set to null and then at line 310 Result.Item1 is accesed

## Bug Information
Version Number of Plugin: Latest

### Steps to reproduce the Behavior
N/A

### Expected Behavior
Not crashing

**Comment by georgethms10** [comment]
Is this fix available in 4.0.1.5 update in xamarin, if not when will this fix be available in Nuget!
