### ISSUE TITLE
In Android, the preview of the captured image is rotated 90 degrees anticlockwise while taking in portrait mode.

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#64]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
The preview of the captured image is not proper while taking in portrait mode.
Version Number of Plugin: 2.3.0
Device Tested On: Samsung Galaxy Tab 4, OS version: Android 4.4.2  
Simulator Tested On: NA

### Expected Behavior
The preview of the captured image should be proper as captured.
### Actual Behavior
The preview of the captured image is rotated anti-clockwise while taking in portrait mode.
### Steps to reproduce the Behavior
1. Load the application.
2. Tap on CameraCapture Button.
3. Capture an image -> Image should be captured with option to cancel or accept the image.
4. Accept the captured image -> Show the captured image in Image preview

The image is rotated anticlockwise

## Feature Request:
1. When I check the same in latest 2.5.1 beta40 build, this issue is fixed.
It would be helpful for my project if you can share the expected release date of stable build version.
2. What is the process to contact you If I have any questions like expected release dates and any further functionality clarifications.

**Comment by jamesmontemagno** [comment]
This is fixed in the beta so I will close it for now as that will be when it is available next.

**Comment by pradeeparutla** [comment]
Hi James,

It would be helpful for my project if you can share the expected release date(approximate is okay) of next stable build version.

Regards,
Pradeep Arutla
