### ISSUE TITLE
Ability to pop image/video picker without an animation

### ISSUE THREAD

**Issue by adrianknight89** [jamesmontemagno/MediaPlugin#646]
On Android, when an image is selected, I see two pop animations (one for the image page and one for the album  that contains it). Sometimes I see three pops with the first one being an unexpected empty page and a page title being the application name printed in large text.

I'd like to see this library support non-animated pops on both Android and iOS if possible so that the user has a better UI experience with the picker.

**Comment by jamesmontemagno** [comment]
Not sure what you mean.... On each platform we just call out to the native picker, so it is up to them what they do to be honest.

**Comment by adrianknight89** [comment]
When you're launching the native picker, you could configure certain things. For example, on iOS, you could present the new [view controller](https://github.com/jamesmontemagno/MediaPlugin/blob/9c19e16d656399072c37a5b37e3731fcbe588c87/src/Media.Plugin/iOS/MediaImplementation.cs#L292) without an animation. See the second parameter. I think there is one for dismissal as well.

On Android, you could create a `bundle` and pass it in when starting a new activity. I slightly modified `MediaImplementation` locally and was able to launch the picker without an animation:

```
var bundle = ActivityOptionsCompat.MakeCustomAnimation(context, 0, 0).ToBundle();
context.StartActivity(CreateMediaIntent(id, type, action, options), bundle);
```

Do you have any instructions for creating a Nuget locally? I didn't see that in the wiki.

**Comment by jamesmontemagno** [comment]
Just open in Visual Studio 2017/2019, build and then right lick and Pack :)

**Comment by jamesmontemagno** [comment]
You could send in a PR... basically on Options have an enum that has "Default" or "None" probably.

**Comment by adrianknight89** [comment]
Thanks. I'll see what I can do. Since I don't usually look at UWP or Tizen, what's your expectation for feature parity? Is it okay to leave out the other platform implementations for now?

**Comment by jamesmontemagno** [comment]
no need for feature parity really... just iOS/Android
