### ISSUE TITLE
TakePhotoAsync always return null 

### ISSUE THREAD

**Issue by Earu** [jamesmontemagno/MediaPlugin#647]
On Android, when using the TakePhotoAsync the result of the associated Task is always null. Our application has granted accesses to external write and read. The setup of the package does not seem to be the issue since the default camera app is showing up.

Version Number of Plugin:
4.0.1.5

Device Tested On:
Honor 8X & Wiko (U feel lite)

Version of VS: 
Visual Studio for Mac (7.7.2 build 21)

### Expected Behavior
Opens the camera app, returns a MediaFile object, and writes the picture to memory at Directory and with Name specified in the StoreCameraMediaOptions object.

### Actual Behavior
Opens the camera app, returns null, creates the Directory specified in the StoreCameraMediaOptions object but not the actual file.

### Code snippet
```
                var _media = CrossMedia.Current;
                var name = "something";
                var options = new StoreCameraMediaOptions
                {
                    Directory = "tmp",
                    Name = $"{name}.jpg",
                    PhotoSize = PhotoSize.Large,
                    AllowCropping = true,
                    DefaultCamera = CameraDevice.Rear,
                };

                var media = await _media.TakePhotoAsync(options);
```

**Comment by Eltee-Taiwo** [comment]
Try installing 4.3.1-beta and see if that works.

**Comment by xander96** [comment]
Same issue Happens to me for the following Android Devices:
Oneplus 6T, Samsung J3 2017

4.3.1-beta does not fix the issue.

Using Latest Visual Studio 2019 for Windows (16.1.6) and Latest Xamarin Forms (4.1.0.581479).

I think it is a Xamarin Forms issue.
