### ISSUE TITLE
Image is rotated clockwise in ios

### ISSUE THREAD

**Issue by henrikweimenhog** [jamesmontemagno/MediaPlugin#65]
## Bug 

Version Number of Plugin: 2.5.1 beta 40
Device Tested On: iPhone 5s
Simulator Tested On: iPhone 6s

### Expected Behavior
Images are not rotated

### Actual Behavior
Images are rotated clockwise

### Steps to reproduce the Behavior
Take a photo, either hold the phone upright or horizontal.
Show the image in the app. 

It would probably be best if we could have the Orientation information (EXIF) available as a property on MediaFile. This way everyone could decide for themselves if they wish to rotate the image or not.

**Comment by sqlboy2000** [comment]
"It would probably be best if we could have the Orientation information (EXIF) available as a property on MediaFile. This way everyone could decide for themselves if they wish to rotate the image or not."

- That's a great idea. Then we could all stop complaining and just fix our own rotation / flipping issues.

**Comment by pradeeparutla** [comment]
Any update on this?. I am facing similar issues with different Android and iOS devices

**Comment by henrikweimenhog** [comment]
Works in newest beta! Yay!
