### ISSUE TITLE
[UWP] 4.1.1 Beta not working/crashes on UWP 

### ISSUE THREAD

**Issue by Brosten** [jamesmontemagno/MediaPlugin#653]
## Bug Information

Version Number of Plugin: 4.1.1 Beta
Device Tested On: Windows 10 Pro 1809
Version of VS: 15.9.6
Version of Xamarin: 3.4.0.1029999
Versions of other things you are using: -

### Steps to reproduce the Behavior
1 Add a button to the main page
2 Add this to the code behind
```
      public async void Button_Clicked(object sender, EventArgs e)
      {
         var x = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
         {
            Directory = "MyDir",
            Name = "MyPic.jpg",
            SaveToAlbum = false,
            DefaultCamera = CameraDevice.Rear,
            AllowCropping = false // Setting TRUE seems to mess boundaries up in Windows 10
         });
      }

```

### Expected Behavior
Camera brought up when clicking the button

### Actual Behavior
App crashes with "System.TypeLoadException: Failure has occurred while loading a type"
Message = "Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

### Code snippet
See above

### Screenshots
-

Same thing happens when trying to pick from album.
I have set the WebCam permission, but still crashes.
When downgrading to latest stable (4.0.1.5) it works as expected.

**Comment by jamesmontemagno** [comment]
Fixing in 4.1.2! Thanks :)

**Comment by SteveFarmerJr** [comment]
Is this plugin still supposed to work with shared projects?  I am getting this same error on Android.  Have downgraded to 4.0.1.5 as well. Still no joy.
