### ISSUE TITLE
Cancel button has a small click range when selecting a video

### ISSUE THREAD

**Issue by JoesWeek** [jamesmontemagno/MediaPlugin#663]
When you select a video, click the Cancel button, Only red range is valid.

Version Number of Plugin: 4.2.0.1-beta

![tim 20190226162629](https://user-images.githubusercontent.com/28339829/53398389-7339b800-39e4-11e9-8ff7-cce844a85aec.png)

**Comment by jamesmontemagno** [comment]
This is the iOS control, the library has no control over what is displayed.
