### ISSUE TITLE
Permissions should work

### ISSUE THREAD

**Issue by sangitahirani1** [jamesmontemagno/MediaPlugin#668]
Without granting permissions , picking photo is working. if permissions not allowed for picking photo, photo can be picked up from gallery .

**Comment by KaranRami** [comment]
i am facing same thing.

Nugets i am using:
Plugin.Connectivity v2.1.0.4
Plugin.Media v4.0.1.5

```
var storageStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);
                if (storageStatus != PermissionStatus.Granted)
                {
                    var results = await CrossPermissions.Current.RequestPermissionsAsync(new[] { Permission.Storage });
                    storageStatus = results[Permission.Storage];
                }
```
In above code storageStatus is Denied, But still if condition return false.

**Comment by jamesmontemagno** [comment]
permissions work as expected
