### ISSUE TITLE
Optimize photos cannot be selected in select multiple photos mode

### ISSUE THREAD

**Issue by SoledadIce** [jamesmontemagno/MediaPlugin#669]
In iOS, I am using iCloud photo library, with the option "Optimize iPhone Storage: True". All the optimized photos cannot be selected, when using multi-select for photos.

**Comment by MatthewKapteyn** [comment]
Might be awhile before somebody writes this feature for MediaPlugin. In the meantime, i'm looking at 
[https://github.com/roycornelissen/GMImagePicker.Xamarin](https://github.com/roycornelissen/GMImagePicker.Xamarin)
