### ISSUE TITLE
Please Share the expected release date(approximate is okay) of next stable build version.

### ISSUE THREAD

**Issue by pradeeparutla** [jamesmontemagno/MediaPlugin#67]
Please fill out either the bug or feature request section and remove whatever section you are not using.

It would be helpful for my project if you can share the expected release date(approximate is okay) of next stable build version.

**Comment by pradeeparutla** [comment]
Hi James any update on this?

**Comment by jamesmontemagno** [comment]
beta51 will be the final beta before stable release unless anything pops up
