### ISSUE TITLE
Once image selected from picker, screens return to root Navigation view

### ISSUE THREAD

**Issue by Milner99** [jamesmontemagno/MediaPlugin#673]
## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Xamarin Visual Studio Mac
Simulator Tested On: iPhone 8 simulator 12.1 / Android API 26
Version of VS: 2017
Version of Xamarin: 3.6.0.220655
Versions of other things you are using: 

### Steps to reproduce the Behavior
- Implement plugins (Media, Permissions and CurrentActivity as per readmes)
- Copy sample code from this gubhub page
- change camera shoot code from example to photo picker
- run simulator (either Android API 26 or iOS 12.1 iPhone 8)
- My app sets up a navigation stack,
- pushed one master/detail to the stack (main list)
- change the detail view a view with photo picker button on
- photo picker appears (native ui)
- select a photo (tapping on photo)
- returns to view with image and displays on the <Image.../> placeholder
- then instantly moves to main view / root detail view away from photo picker xaml.

### Expected Behavior
selected image from the photopicker should return the stream as it does but NOT move directly to the main list. 

### Actual Behavior
stream is returned to the view, then the view moves to the main list, back to the main master/detail navigation view.

### Code snippet
`            await CrossMedia.Current.Initialize();
            if (!CrossMedia.Current.IsPickPhotoSupported)
            {
                DisplayAlert("No Camera", ":( No camera available.", "OK");
                return;
            }

            var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
            {
                PhotoSize = PhotoSize.Full
            });

            if (file == null)
                return;

            DisplayAlert("File Location", file.Path, "OK");

            imgPreview.Source = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                return stream;
            });
`
Directly after this return stream and image source setting the screen for some reason changes to ListPage.xaml. This code is running on CongratulateNewPost.xaml. Both with seperate xaml.cs obviously...

**Comment by Milner99** [comment]
To add to this, the unwanted functionality replicates Navigation.PopAsync() - it's like that's being fired straight after "return stream;" and the UI has updated to show the image selected from the gallery.

**Comment by adarshdev** [comment]
Facing the issue on galaxy s7 in both PickPhotoAsync() and TakePhotoAsync() while returning from the plugin it navigates to homepage

**Comment by Milner99** [comment]
I had code running in an overridden onAppearing() {...}  in the root NavigationPage. For some strange reason (and I'd love to know why!) this view's onAppearing method was being called after returning from the photo picker - as a result that method was instantiating a new page (for me, ListPage()) and that was overriding screen and destroying the alreay in place Navigation stack. I moved the new ListPage() from onAppearing to a new async'd method called from the constructor and now the plugin works fine. I presume onAppearing is still being called but of course i"m not overriding it anymore so the plugin is working as expected.

This can be closed now.

@adarshdev I wonder if you're overriding the onAppearing protected method on your root view - if so, try moving the calls in there is an async'd method called from the constructor of that root view/class.

Hope this makes sense.
