### ISSUE TITLE
UWP TakePhotoAsync results in "circle" preview

### ISSUE THREAD

**Issue by WillAutioItrax** [jamesmontemagno/MediaPlugin#676]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Win 10 PC - Local machine
Simulator Tested On: n/a
Version of VS: Win 10 V 1809   OS build 17763.379
Version of Xamarin: 4.12.3.80
Versions of other things you are using:

### Steps to reproduce the Behavior
I took the MediaSample app and added UWP to it.
### Expected Behavior
Take a picture and get a rectangular Preview.
### Actual Behavior
Take a picture and get a circular Preview with small circles at the top, bottom, left and right.
### Screenshots
![Media Curiosity 2019-03-17 145434](https://user-images.githubusercontent.com/15933820/54498771-5ea45d80-48c8-11e9-809e-1f0dc8ad9479.jpg)

Note: This happened first to a user of our app in UWP. Then I created a repo based on MediaSample and it does the same.

Thanks for looking at it.
Will

**Comment by Xo3-ToBapbl** [comment]
Have you tried set property AllowCropping to false in StoreCameraMediaOptions? It should resolve your issue: https://github.com/jamesmontemagno/MediaPlugin#allow-cropping

**Comment by WillAutioItrax** [comment]
@Xo3-ToBapbl Thanks for your reply. I just tried setting AllowCropping = False with no change.

**Comment by davidpsaylor** [comment]
I was able to see a difference on UWP after setting  AllowCropping = False.

**Comment by jamesmontemagno** [comment]
I don't do anything special besides make the request to UWP, it is out of my control at this point. Perhaps you changed the settings in the camera app?
