### ISSUE TITLE
Feature Request - Add option for taking a photo without the confirmation page.

### ISSUE THREAD

**Issue by Nerves82** [jamesmontemagno/MediaPlugin#679]
When taking a photo with TakePhotoAsync the library displays the capture view where the user can select the camera to use and other options, then capture the image. Once captured the library then shows the confirmation view where the captured image is shown with a Ok/Retry overlay for the user to confirm or try again. 

An option to skip this confirmation would be very handy as I would like my app to handle that itself. 

Add a flag in the StoreCameraMediaOptions (a.la SkipConfirmationScreen) which allows the library to immediately return the captured image.

**Comment by simader** [comment]
Or does anybody know, if it is possible to customize the confirmation page? For example add a button, or a textfield for a description.

**Comment by jamesmontemagno** [comment]
This library does not handle the UI for the camera so this is not possible. You need to write your own camera control if you want full control.
