### ISSUE TITLE
"Save to Album" attribute saving original image on album instead of compressed/resized one

### ISSUE THREAD

**Issue by viananicolas** [jamesmontemagno/MediaPlugin#68]
## Bug 

Version Number of Plugin: 2.5.1-beta 40
Device Tested On: Moto X Play - Marshmallow 6.0.1

### Expected Behavior
Android album should display the compressed or resized picture.
### Actual Behavior
When taking a picture with the "Save to Album" attribute enabled with the compression and/or size attribute set to a value, the original unmodified picture is sent to the album while the modified one is saved in the temporary folder.
### Steps to reproduce the Behavior
Enable the "Save to Album" attribute and set the quality and/or resize attributes to any level other than the default one and take a picture. When opening the album, the original unmodified picture will show up instead of the modified image. Write/read permissions are enabled.

**Comment by jamesmontemagno** [comment]
This is the expected behavior and how I programmed it.
