### ISSUE TITLE
"Permission recommendations" instructions doesn't work on Android

### ISSUE THREAD

**Issue by cmeeren** [jamesmontemagno/MediaPlugin#682]
The instructions written in the readme section on [Permission recommendations](https://github.com/jamesmontemagno/MediaPlugin#permission-recommendations) doesn't work on Android, at least not 9.0 (haven't tested others). The reason is that the instructions require both Camera and Storage permissions, but AFAIK Android will only give Storage since Camera isn't needed and thus isn't added to the manifest.

I am unsure which Android versions this applies to. I simply let `TakePhotoAsync` and `PickPhotoAsync` handle the permissions, which seems to work fine.

Let me know if you need more info about my environment/versions or other stuff (haven't included since I don't think it's relevant here).

**Comment by MosCD3** [comment]
same here

**Comment by jamesmontemagno** [comment]
You don't need to add anything I already do it for you.
