### ISSUE TITLE
Feature Request? - Grab location information at time of photo taken

### ISSUE THREAD

**Issue by apolloLegends** [jamesmontemagno/MediaPlugin#691]
I would like to be able to grab the location of the device at the time of the photo being taken. Currently, the MediaPlugin this has to be specified before hand (at which point the user could move which they typically do in our usage scenario).

This would probably add a dependency upon another plugin  - perhaps this is why this should be part of the Xamarin.Essentials (opened issues there too) but as the camera API has yet to be added to that project, i thought i'd at least make the request to get some feedback.  Perhaps there is a way to do this already and i'm overlooking it as it seems no one has previously asked for this functionality.

**Comment by jamesmontemagno** [comment]
You can pass in the location in and it will set it on the exif data.

**Comment by apolloLegends** [comment]
Hi James (@jamesmontemagno )

Perhaps you misunderstood the problem

1) GPS is running in the background with decent accuracy + 1 second resolution
2) The user wants to take a photo
3) I pass the location to as an input to function, it brings up the take photo interface
4) My user decides that this is not a good angle to take the photo after all and spends 30 seconds moving to a different location before taking and accepting the photo

Current - the location is as defined in Step 3
Expected - the location is as the user location as in Step 4

Worse,
1) GPS is cold, has really poor accuracy
2) User is ok that its not good accuracy and accepts warning when entering photo taking mode
3) User takes and accepts the photo after 10 seconds

Current - the location is as defined in Step 2
Expected - the location is as the user location as in Step 3. the GPS location can be significantly in this time whilst its getting a fix.

**Comment by jamesmontemagno** [comment]
After the photo is taken you could re-apply exif to the file if you have one. 

The issue you describe is a general problem. We could change the functionality so you provide the GPS right before the file is written, but at that point you might as well just re-write the exif data so you are in complete control.
