### ISSUE TITLE
TakePhotoAsync merges subdirectories

### ISSUE THREAD

**Issue by lvenchi** [jamesmontemagno/MediaPlugin#692]
## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: Samsung Note 9

### Steps to reproduce the Behavior
var photo = await Plugin.Media.CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
            {
                Directory = "Test/Subdirectory",
                SaveToAlbum = false, 
                CompressionQuality = 75,
                CustomPhotoSize = 50,
                PhotoSize = PhotoSize.Medium,
                MaxWidthHeight = 2000,
                DefaultCamera = CameraDevice.Front,
                Name = DateTime.Now.ToString() + ".jpg"
            });

### Expected Behavior
save the image in /storage/emulated/0/Android/data/com.companyname.myApp/files/Pictures/Test/Subdirectory
### Actual Behavior
saves the image in /storage/emulated/0/Android/data/com.companyname.myApp/files/Pictures/TestSubdirectory

**Comment by lvenchi** [comment]
I have solved this by moving the file manually but i think you should fix this, especially for dynamically-created folders so i wont close it.

**Comment by jamesmontemagno** [comment]
It doesn't support sub directories
