### ISSUE TITLE
[Feature Request] Implement event on the "take photo" button.

### ISSUE THREAD

**Issue by JoseluDAM2000** [jamesmontemagno/MediaPlugin#694]
I need to execute code in the same moment than i take the photo, by now i only can acept the preview and go back to my code, that can take a few seconds which would falsify the data collection of the accelerometer and the gyroscope.

**Comment by dansiegel** [comment]
why not just pass in a Command or a callback action?

**Comment by jamesmontemagno** [comment]
No way to handle this as the preview is via the platform and we have no control.
