### ISSUE TITLE
Android: MultiSelection on Samsung Gallery (v4.3.0.1)

### ISSUE THREAD

**Issue by Fredeinfo** [jamesmontemagno/MediaPlugin#697]
Version Number of Plugin: v4.3.0.1
Device Tested On: LG, Motorola, Samsung(7, 8, 9)
Version of Xamarin: 3.6

MultiSelection (PickPhotosAsync) do not work on Samsung Photo Gallery. It works fine on LG and Motorola devices.

**Comment by jamesmontemagno** [comment]
Could be that it doesn't support multi-select on that gallery. Does it allow you to select a single image?

**Comment by Fredeinfo** [comment]
> Could be that it doesn't support multi-select on that gallery. Does it allow you to select a single image?

Yes, It does allow to select a single image.
Thxs for reply.

**Comment by cloelke** [comment]
The picker shows the Samsung Gallery, (Does not support multi). On 4.0.15 it pop's up with an open from option that has the images that I can select or from with in it I can pick Gallery, Dropbox Onedrive etc. But on 4.3.01 it just goes direct to Gallery with no option to pick something else.

**Comment by IvicaSkrobo** [comment]
@cloelke 
 Have you found a way to have multi pick supported in the samsung gallery?
