### ISSUE TITLE
[Feature Request] Support Media stored in iCloud

### ISSUE THREAD

**Issue by MatthewKapteyn** [jamesmontemagno/MediaPlugin#703]
Photos that have been automatically moved by iOS into iCloud to 'optimize storage' are not available to select in MediaPlugin. It would be pretty nice to have this feature built in.

Closest thing I can find that supports this kind of feature is this project

[https://github.com/roycornelissen/GMImagePicker.Xamarin](https://github.com/roycornelissen/GMImagePicker.Xamarin)

There is one issue related to this feature request

[https://github.com/jamesmontemagno/MediaPlugin/issues/669](https://github.com/jamesmontemagno/MediaPlugin/issues/669)

**Comment by MatthewKapteyn** [comment]
Tested latest code commit from this weekend and am happy to say that iCloud images that were somehow populating in the gallery list don't crash the app anymore. Really looking forward to seeing official integration with GMImagePicker so that all iCloud images can be available :)

[https://github.com/roycornelissen/GMImagePicker.Xamarin/issues/63](https://github.com/roycornelissen/GMImagePicker.Xamarin/issues/63)

**Comment by jamesmontemagno** [comment]
Now implemented in latest beta :)
