### ISSUE TITLE
Unnecessary permission request when picking a photo on iOS

### ISSUE THREAD

**Issue by uwiedemann** [jamesmontemagno/MediaPlugin#704]
## Bug Information

On iOS the user is asked for Photos permission if you pick a photo, even though it is not needed. The photo is displayed, even if the permission is denied.

Version Number of Plugin: 4.0.1.5, master a6de2cb0cd5d94d1e155daa6696c1ed5e96d17c0
Device Tested On: iPhone X, iPhone XR (both 12.3.1)
Simulator Tested On: iPhone XR Simulator (12.2)
Version of VS: 16.1.3
Version of Xamarin: 4.0.0.425677
Versions of other things you are using:

### Steps to reproduce the Behavior

- Start the [Media.Plugin.Sample.iOS app](https://github.com/jamesmontemagno/MediaPlugin/tree/master/src/Media.Plugin.Sample/Media.Plugin.Sample.iOS), e.g. on an iOS simulator
- Select the action "Pick Photo".
- Select an arbitrary photo from the library

### Expected Behavior

The selected photo is displayed without being asked for permissions.

### Actual Behavior

The app asks for Photos permissions. It displays the selected photo even if the permissions are not granted.

Please note that you will be asked for the permission only once. If necessary, the sample app must be uninstalled first so that the permission is requested again.

### Code snippet

The culprit seems to be the call to PHAsset.[FetchAssets](https://developer.apple.com/documentation/photokit/phasset/1624782-fetchassets)() in [PhotoLibraryAccess.cs](https://github.com/jamesmontemagno/MediaPlugin/blob/master/src/Media.Plugin/iOS/PhotoLibraryAccess.cs). The call is according to Apple deprecated since iOS 8. Eventually using another API may avoid the permission request.

### Screenshots

Please see https://github.com/jamesmontemagno/MediaPlugin/issues/409#issuecomment-494101795

**Comment by uwiedemann** [comment]
As a workaround, you may set SaveMetaData to false in the PickMediaOptions of the call to PickPhotoAsync() - if you don't need the meta data.

```
var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
{
  SaveMetaData = false,
});
```

**Comment by jamesmontemagno** [comment]
This is by design if you need the metadata, so working as expected.
