### ISSUE TITLE
Error Navigation after picking photo from gallery

### ISSUE THREAD

**Issue by hugoranito** [jamesmontemagno/MediaPlugin#71]
Hello all,
I'm using Xam.Plugin.Media to pick a photo from gallery or camera. In iOS it works all fine but testing in android, after picking the photo from the gallery the app crashs when tries no navigate to another page.

**Error: Java.Lang.IlegalStateExecution: Can not perform this action after onSaveInstanceState**

Here's my code:

private async void SelectPicture(PostModel p)
		{

			if (!CrossMedia.Current.IsPickPhotoSupported)
			{
				await DisplayAlert("Photos Not Supported", "Permission not granted to photos.", "OK");
				return;
			}
			var file = await CrossMedia.Current.PickPhotoAsync();

			if (file == null)
				return;

			selfieImg.Source = ImageSource.FromStream(() =>
			{
				var stream = file.GetStream();
				file.Dispose();
				return stream;
			});

			
			await Navigation.PushAsync(new testePage());

		}

Thanks in advance.

**Comment by jamesmontemagno** [comment]
This mostly likely has to do with how Xamarin.Forms works and not the plugin actually. You are trying to navigate before your app has been fully hydrated. 

try to put an 

```
await Task.Delay(3000); 
```
before you navigate.

**Comment by hugoranito** [comment]
Thank you James, i had been able to solve it that way.
