### ISSUE TITLE
PickPhothoAsync always returns file with jpg extension.

### ISSUE THREAD

**Issue by rafaleonbb** [jamesmontemagno/MediaPlugin#72]
## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Bq Edison 3G
Simulator Tested On:

### Expected Behavior
Pick a png file and return a file with png extension

### Actual Behavior
Always returns the file with jpg extension

### Steps to reproduce the Behavior
Use PickPhotoAsync, select PNG file and display file.path
<code>var file = await CrossMedia.Current.PickPhotoAsync ();</code>
<code>System.Diagnostics.Debug.WriteLine(file.path);</code>

**Comment by jamesmontemagno** [comment]
The image looks alright though? 

I think it is hardcoded to .mp4 and .jpg though. Should be easy to work around and check to see if the file name is png get png or whatever it is. Will put in backlog.

**Comment by rafaleonbb** [comment]
The image looks alright inside the app but If I use it in PDF with a bitmap object, for example, the image doesn't print in PDF.
I thought validate the image format and only support JPG and BMP after PickPhotoAsync.
Thanks!

**Comment by muhaym** [comment]
@jamesmontemagno is this bug fixed yet? Where can I get correct file extension

**Comment by jamesmontemagno** [comment]
If it is still open then it hasn't been fixed.

I re-compress everything as a .jpg so it makes sense. It isn't a file picker, this is supposed to be used to be used for photo picking.

I will investigate, but it is pretty low priority.

**Comment by muhaym** [comment]
@jamesmontemagno  Is the re-compression done by default? becaues I faced error while sending the image to a REST Api service because I am sending a png file with jpg extension. 

Is using image as byte array and sending to service with jpg extension a solution?

**Comment by jamesmontemagno** [comment]
Check out: 2.6.0.16-beta

I now use the file name + extension instead of a name based on time.

**Comment by muhaym** [comment]
@jamesmontemagno  Thanks for your support :)

**Comment by jamesmontemagno** [comment]
Please test out with your use case and report back.

**Comment by muhaym** [comment]
@jamesmontemagno  Checked my use case in 3 devices and emulator, its working fine now. Thanks for your time and support!

**Comment by ysfyong** [comment]
Hi @jamesmontemagno 

I currently using ver 2.6.2. The file always return .jpg extension when I tried to attach .png file. Is there any method to get the file extension only using this media plugin?

**Expected Behavior**

Pick a png file and return a file with png extension

**Actual Behavior**

Always returns the file with jpg extension

**Steps to reproduce the Behavior**

Use PickPhotoAsync, select PNG file and display file.path
var file = await CrossMedia.Current.PickPhotoAsync ();
System.Diagnostics.Debug.WriteLine(file.path);
