### ISSUE TITLE
Device library fails to load images on Ipad

### ISSUE THREAD

**Issue by apuser455** [jamesmontemagno/MediaPlugin#722]
## Bug Information

Version Number of Plugin:3.1.3
Device Tested On: Ipad mini 12.1.4
Simulator Tested On:
Version of VS: VS 2019 Version 16.00
Version of Xamarin:3.1.0.697729
Versions of other things you are using:

### Steps to reproduce the Behavior
This doesnt occur all the time so it is hard to produce steps. Randomly I get an empty device library on Ipad. If I close the device library and open again it loads the images correctly. This is occurring randomly once a day.

### Expected Behavior
Device library images are loaded

### Actual Behavior
Device library images are not loaded

### Code snippet
`var file = 
				await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
				{
					CompressionQuality = 75,
					CustomPhotoSize = 25,
					PhotoSize = PhotoSize.Custom,
					MaxWidthHeight = 400
				});`
### Screenshots

![image](https://user-images.githubusercontent.com/53055858/61477091-8251e000-a95c-11e9-9589-f8c464eedd26.png)

**Comment by jamesmontemagno** [comment]
Try latest beta package
