### ISSUE TITLE
Video saved from ios cannot be viewed in web

### ISSUE THREAD

**Issue by binshidha** [jamesmontemagno/MediaPlugin#725]
## Bug Information
Video taken from ios(TakeVideoAsync)  cannot be viewed in web, it shows video has codec issue. PickVideoAsync is working fine.
Version Number of Plugin: 4.0.1.5
Device Tested On: iphone xs
Simulator Tested On: Used real device
Version of VS:  VS(2019) -16.1.1
Version of Xamarin: 4.1.0.581479

### Steps to reproduce the Behavior
Take video using TakeVideoAsync in ios. The video is capturing as .mp4. Byte array of the video is saved in server. then try to view the video saved in the server using movies&tv video player.

### Expected Behavior
Video should be played in the videoplayer.

### Actual Behavior
Video takenfrom ios is not playing in movies&TV .
Shows 'This item was encoded in a format that's not supported.0xc00d5212'.
Working fine in android.

### Code snippet
 var file = await CrossMedia.Current.TakeVideoAsync(
                new StoreVideoOptions
                {
                    Directory = Settings.VideoDirectory,
                    Name = Settings.VideoDirectory + Settings.VideoExtension,
                    Quality = VideoQuality.High,
                    DesiredSize = MaximumVideoSize * 1000000,
                    DefaultCamera = CameraDevice.Rear
                });
byte[] videoByteArray = System.IO.File.ReadAllBytes(file.Path); 
storing this byte array to server.

### Screenshots
![Screenshot (19)](https://user-images.githubusercontent.com/45423989/62023097-fa39c900-b1ec-11e9-85e2-5ef25a16ac87.png)

**Comment by jamesmontemagno** [comment]
do you have the correct codec? Maybe try VLC

**Comment by binshidha** [comment]
If the uploaded video is downloaded and open with vlc, then it plays. But all other media players throws error. The requirement was to preview video in web which doesn't right now due to this issue

**Comment by jamesmontemagno** [comment]
You would probably need to transcode it.
