### ISSUE TITLE
IOS: How to get original Media File Path/File Name instead of Temp file path with IsPickPhotoSupported

### ISSUE THREAD

**Issue by muffadal53** [jamesmontemagno/MediaPlugin#729]
When I use "CrossMedia.Current.IsPickPhotoSupported" method of plugin the file path which is returned is from TempPath and not the original FilePath. And, Each time, When I select the same file the  FileName returned as part of "MediaFile" is different every time. So, Can you tell me how to I get the original FilePath or the FileName of the selected photo stored on IOS? I need this information to check whether the File already exists on my Backend server. But, with different name for same file, I cannot achieve this. Any help is appreciated. Thanks.

Version Number of Plugin: 4.0.1.5
Device Tested On: IOS
Version of VS: VS 2017
Version of Xamarin: 3.6.0.344457

**Comment by maxiking01** [comment]
I have nearly the same problem. I would like to get file from gallery with original file size and name. However, after calling PickPhotoAsync the file has changed name and size. For example i tried to import 25 MB png file, but it was recompressed to 1MB. I used PhotoSize.Full , CompressionQuality =100 when fetching image

Version Number of Plugin: 4.0.1.5
Device Tested On: IOS
Version of VS: VS 2019 for Mac.
Version of Xamarin: 4.2.0.815419

**Comment by garie** [comment]
I'd also like the original file name, but for different reason - I want to parse the file name to get any additional data from that. This is particularly useful for images that weren't taken on the current device.

[This plugin for iOS](https://github.com/roycornelissen/GMImagePicker.Xamarin) allows you to get the original file name.
