### ISSUE TITLE
Storage permission Denied.

### ISSUE THREAD

**Issue by timbrand** [jamesmontemagno/MediaPlugin#73]
I'm getting the following error in the log on an Android 4.0.4 (API 15) device (Galaxy Nexus) when picking an image.
`Does not have storage permission granted, requesting.
Storage permission Denied.` 
It did not show any dialog at all. Just doesn't do anything.

The app has the rights to access the storage, as other actions are using the storage without any problems.
On an OnePlus with Android6.0 it just works fine;

Code:
`var crossMediaInit = await CrossMedia.Current.Initialize();
var mediaFile = await CrossMedia.Current.PickPhotoAsync();`

Version Number of Plugin: 2.5.1-beta40
Device Tested On: Galaxy Nexus (Android 4.0.4)

**Comment by timbrand** [comment]
I checked the persmission by using 
`var status = await Plugin.Permissions.CrossPermissions.Current.CheckPermissionStatusAsync(Plugin.Permissions.Abstractions.Permission.Storage);`
The status will return "Denied" here. So it's probably an error in the Permissions plugin?

**Comment by Spierki** [comment]
+1

**Comment by jamesmontemagno** [comment]
Have you set the correct build states:

https://github.com/jamesmontemagno/PermissionsPlugin#android-specific-in-your-baseactivity-or-mainactivity-for-xamarinforms-add-this-code

This works for me.

**Comment by Spierki** [comment]
I set them normally, the popup is still not displaying

**Comment by jamesmontemagno** [comment]
There is no pop up on anything under 6.0. 

I have tested this on 4 different emulators/devices and all working flawless.

**Comment by TarasMartynyuk** [comment]
+1 - both on emulator and on device with Android 8.0
