### ISSUE TITLE
Picking photo from gallery in android emulator without photo gallery app crashes

### ISSUE THREAD

**Issue by casas333** [jamesmontemagno/MediaPlugin#737]
## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: 
Simulator Tested On: Android 8.1
Version of VS: 8.2.5 (build 5)
Version of Xamarin: Xamarin.Mac - Version: 5.14.0.114 | Xamarin.Android - Version: 9.4.1.0 
Versions of other things you are using:

### Steps to reproduce the Behavior

1. Create/open an Android emulator
2. Disable Google Photos app and any other image gallery on the emulator
3. Try to pick a picture

### Expected Behavior
If theres no gallery available, the IsPickPhotoSupported should tell me it's not supported to take a picture

### Actual Behavior
IsPickPhotoSupported it's true even when there's no gallery available, resulting in a crash when I try to pick a picture using CrossMedia.Current.PickPhotoAsync();

### Code snippet
    private async void ClickedLoadPhotoCommand()
    {
                if (!CrossMedia.Current.IsPickPhotoSupported)
                {
                    Log.Error("Pick photo is not supported");
                    return;
                }

            var file = await CrossMedia.Current.PickPhotoAsync();
            if (file == null)
            {
                return;
            }
       ...
       }

### Screenshots

![Exception_Caught_and_Android_Device_Manager_and_Source_Not_Available_–_Visual_Studio_Community_2019_for_Mac](https://user-images.githubusercontent.com/35951952/64616781-8854c200-d3dd-11e9-955a-e44c46ce718c.png)

**Comment by jamesmontemagno** [comment]
You should try/catch it.

**Comment by casas333** [comment]
Ok, I agree, I should try/catch it. Beyond that, what about the IsPickPhotoSupported property? It's true when it's not really true that we can pick a picture because there's no gallery. Or am I understanding wrong the purpose of this property and it's flagging some other meaning?
