### ISSUE TITLE
Pick Photo works without permission on iOS

### ISSUE THREAD

**Issue by JasonixDev** [jamesmontemagno/MediaPlugin#738]
Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

When you disable the permission to pick a photo from your gallery and you call the method PickPhotoAsync you can open your gallery.

Version Number of Plugin: 4.0.1.5
Device Tested On: iPhone 6s and iPhone 8 on iOS 12.4
Simulator Tested On:
Version of VS: 16.2.5
Version of Xamarin: 4.2.0.709249
Versions of other things you are using:

### Steps to reproduce the Behavior
Disable the permission to pick photos from gallery

### Expected Behavior
You can´t open the gallery

### Actual Behavior
You can open the gallery

**Comment by jamesmontemagno** [comment]
That is correct. you need to give it permission and on iOS it will only ever pop up once. You can use the permissions plugin to query it.
