### ISSUE TITLE
PickPhotosAsync Crashes after selecting photos and pressing Done in iOS

### ISSUE THREAD

**Issue by Tonykidv2** [jamesmontemagno/MediaPlugin#743]
Hello, I just recently updated Xamarin and now this part of my code is crashing after I press Done after selecting my photos

`var _mediaFiles = await CrossMedia.Current.PickPhotosAsync(new Plugin.Media.Abstractions.PickMediaOptions
                    {
                        PhotoSize = PhotoSize.Medium
                        //,RotateImage = false
                    }, new MultiPickerOptions
                    {
                        MaximumImagesCount = 5
                    });`

Its break at the AppDelegates file with an exception message saying "Value cannot be null. Parameter name: cgiImage".

**Comment by Tonykidv2** [comment]
Seems to be an issue with iOS 13 on the simulator. I have a co-worker that has a iPhone 7 plus running iOS 13 but not on his simulator.

**Comment by oceanofinfinity** [comment]
Issue with iOS 13 (Unable to uplaod photos)

**Comment by jamesmontemagno** [comment]
This has been fixed up in latest beta
