### ISSUE TITLE
Android asks for permission but doesnt load camera, works in iOS

### ISSUE THREAD

**Issue by ColdstarJoey** [jamesmontemagno/MediaPlugin#744]
does any body have a fix for why my android camera does not display. i click the button it asks for access to camera and storage and then nothing. on iOS it works fine and the code i am using is:

`private async void SelectProfileImage_Clicked(object sender, EventArgs e)
        {

            await CrossMedia.Current.Initialize();
            try
            {
                profilePicture = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,
                    CompressionQuality = 92
                });
                if (profilePicture == null)
                    return;
                ProfileUpload.Source = ImageSource.FromStream(() =>
                {
                    var imageStram = profilePicture.GetStream();
                    ProfileFrame.BorderColor = Color.Green;
                    return imageStram;
                });
                ProfileFrame.IsVisible = true;
                ProfileButton.IsVisible = false;
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }
        }`

**Comment by jamesmontemagno** [comment]
you didn't finish the setup code - https://github.com/jamesmontemagno/MediaPlugin#android
