### ISSUE TITLE
Camera crash on CrossMedia.Current.TakePhotoAsync LG G7 

### ISSUE THREAD

**Issue by amalu2020** [jamesmontemagno/MediaPlugin#753]
Issue - camera crashing and causing app to return to root page on LG G6.

Bug Information:-

Version Number of Plugin: 4.0.1.5
Device Tested On: LG G7
Simulator Tested On: LG G7
Version of VS: 8.2.4 (build 17)
Versions of other things you are using:

Steps to reproduce the Behavior
Try to start camera using CrossMedia.Current.TakePhotoAsync in LG G7,
try to take photo,
camera crashes.

Expected Behavior
Camera should not crash, photo should be captured

Actual Behavior
Camera Crashes and ask to close it.

 Code snippet

 await CrossMedia.Current.Initialize();
  
var cameraPermissionStatus = await
CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Camera);
  var storagePermissionStatus = await CrossPermissions.Current.CheckPermissionStatusAsync(Permission.Storage);

     if (CrossMedia.Current.IsCameraAvailable && cameraPermissionStatus == PermissionStatus.Granted && storagePermissionStatus == PermissionStatus.Granted)
            {
                var options = new StoreCameraMediaOptions()
                {
                    PhotoSize = PhotoSize.Medium,
                    Directory = "xxxxx",
                    Name = $"xxxxxxx.jpg",
                    CompressionQuality = 80
                };
            MediaFile  images = await CrossMedia.Current.TakePhotoAsync(options);

**Comment by jamesmontemagno** [comment]
Please try latest beta version as I am pretty sure this is already fixed

**Comment by amalu2020** [comment]
@jamesmontemagno Thank you.. degrading to beta.. it works
