### ISSUE TITLE
[BUG] Closing PickPhotoAsync locks current view so the user can't navigate away if no photo is selected.

### ISSUE THREAD

**Issue by ludas96** [jamesmontemagno/MediaPlugin#757]
~~After calling PickPhotoAsync, then closing the gallery (by pressing back or tapping the navigationbar back-button), the user cannot navigate away from the page who called the method.
The view registers taps/events, but it simply cannot move push/pop the NavigationStack.~~
**EDIT** After playing around, I've just noticed the same issue occurs even when selecting a photo in the gallery, or actually just taking a photo with the camera.
Something is wrong with the plugin when it comes to returning to the original view.

Version Number of Plugin:  4.0.1.5 (also tested 4.4.3 BETA)
Device Tested On: Samsung Galaxy S10+ (One UI 1.1, Android Pie (APK 28)
Simulator Tested On: Android Emulator (APK 28, Pie) 28.0.25-5395263
Version of VS:  2019 Enterprise 16.4.0 Preview 1.0 & 16.3.3 Base
Version of Xamarin: Xamarin Forms 4.2.0.848062
Versions of other things you are using:

- ExpandableView 1.0.9
- Microsoft.CSharp 4.6.0
- Newtonsoft.Json 12.0.2
- Rg.Plugins.Popup 1.1.5.188
- Xam.Plugin.Connectivity 3.2.0
- Xam.Plugins.Messaging 5.2.0
- Xam.Plugins.Settings 3.1.1
- Xamarin.Essentials 1.3.1
- Xamarin.Forms.InputKit 3.0.12

### Steps to reproduce the Behavior

1. Call PickPhotoAsync
2. Abort the Gallery-page by navigating back (hardware button or navigationbar)
3. Try navigate away from the current page

### Expected Behavior
New page gets pushed to the NavigationStack and the view changes to the new View
### Actual Behavior
Nothing happens. The page gets pushed to the stack, but the view is not changing.
### Code snippet
```csharp
if(!CrossMedia.Current.IsPickPhotoSupported)
{
            return null;
}

var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
{
            PhotoSize = PhotoSize.Medium,
 });

return file;
```

**Comment by ludas96** [comment]
Might be same as #472 ?

**Comment by jamesmontemagno** [comment]
have you tried the latest beta package? 4.4.3?

**Comment by ludas96** [comment]
@jamesmontemagno Just tried the latest beta (4.4.3) with no difference at all.
I can still start the camera/open the photo gallery as normal, but any navigation is just stuck.
So the view itself hasn't been hung up.. it's just that I can't navigate away from it.

**Comment by jamesmontemagno** [comment]
Can you put together a small repro? I can't reproduce this at all I even update my sample project to have some navigation

**Comment by ludas96** [comment]
@jamesmontemagno  Sorry for the late reply!
Can't really provide much - due to company restrictions. However, I decided to remove everything that wasn't neccessary for the camera to work - as in, remove every single view other than login, mainmenu and photo preview (+ a test-view to test navigation).
After doing this, the navigation worked again.

So my first thought is that some plugin/nuget in the list above is the culprit. And I am, as of now, adding all the nugets one by one into my dummy project again to see where it fails.

**Comment by ludas96** [comment]
Issue has been fixed. Found some rather interesting (old) block of code that completely broke the app if it got resumed.
Anyway, issue was never related to this plugin after all.
