### ISSUE TITLE
App crashes when using multiple picker and selecting photos from iCloud

### ISSUE THREAD

**Issue by IngweLand** [jamesmontemagno/MediaPlugin#759]
## Bug Information

Version Number of Plugin: 4.4.4-beta (from NuGet)
Device Tested On: iPhone SE
Simulator Tested On: none
Version of VS: 16.3.5
Version of Xamarin: 4.2.0
Versions of other things you are using:

### Steps to reproduce the Behavior
1) Make sure you use iCloud photos by enabling this feature on iPhone. If you have just enabled it, give it some time so photos will sync to iCloud
2) use CrossMedia.Current.PickPhotosAsync
3) Select one or many photos, click Done
4) App crashes

To verify that this is related to iCloud photos:
1) Take few photos with regular app
2) Go to your app and immediately select those photos
3) Everything works

My be related to https://github.com/jamesmontemagno/MediaPlugin/issues/743 https://github.com/jamesmontemagno/MediaPlugin/issues/703 https://github.com/jamesmontemagno/MediaPlugin/issues/669

### Expected Behavior
Should work
### Actual Behavior
Does not work
### Screenshots

Failed to set thumbnail System.ArgumentNullException: Value cannot be null.
Parameter name: cgImage
at UIKit.UIImage..ctor (CoreGraphics.CGImage cgImage) [0x00042] in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.4.0.2/src/Xamarin.iOS/UIImage.g.cs:137
at Plugin.Media.ELCImagePickerViewController+ELCAlbumPickerController.GetCell (UIKit.UITableView tableView, Foundation.NSIndexPath indexPath) [0x00061] in D:\a\1\s\src\Media.Plugin\iOS\ECLImagePickerViewController.cs:348

**Comment by jamesmontemagno** [comment]
What about just "pickphoto" and not multiple photos?

**Comment by IngweLand** [comment]
last time I tried it was few months ago. But as I remember, PickPhoto worked with iCloud photos worked (and PickPhotos already did not work). I think this might be related to those other issues. The possible change with iOS 13 or one of last update is that before (e.g. 2-3 month ago) you could not see iCloud photo thumbs in the picker at all (so, basically this is why you could not select them before). Right now, all photos are visible, but crashes. Again, I am not completely sure when exactly this icloud photos thumbs visibility changed.

**Comment by IngweLand** [comment]
Confirmed with 4.4.5-beta:
1) Multipicker still does not work
2) Single pick works

**Comment by jamesmontemagno** [comment]
Thanks for validating

**Comment by jamesmontemagno** [comment]
Soooo i think 4.4.6-beta will fix this up... we will see how it is as it isn't super optimized currently. However.... better than crashing perhaps? we shall see and if i can improve it in the future.
