### ISSUE TITLE
iPad Air (and Air 2) displays empty thumbnails when running PickImageAsync

### ISSUE THREAD

**Issue by LSMadsen** [jamesmontemagno/MediaPlugin#76]
## Bug 
When running `PickPhotoAsync` on iPad Air and Air 2, thumbnails are displayed as gray block, so you can not see if it is the correct photo, you are choosing.

I used the default `PickPhotoAsync()` method

Version Number of Plugin: I have both tried with 2.5.1-beta40 or 2.3.0
Device Tested On: iPad Air and Air 2

### Expected Behavior
Thumbnails should be shown, so you can see, if it is the correct photo.

### Actual Behavior
Thumbnails are displayed as empty gray blocks, so you can not see, if you pick the right photo.

### Steps to reproduce the Behavior
Install the plugin together with XLabs.Forms.

**Comment by jamesmontemagno** [comment]
See: https://github.com/jamesmontemagno/MediaPlugin/issues/12
