### ISSUE TITLE
Error: redefinition of 'UIImageOrientation'

### ISSUE THREAD

**Issue by kgomezlogiudice** [jamesmontemagno/MediaPlugin#763]
## Bug Information

Version Number of Plugin: 4.0.1.5
Version of VS: 16.3.5
Version of Xamarin: 16.3.0.277

### Steps to reproduce the Behavior
1. Create a new Mobile Project.
2. Add Xam.Plugin.Media package
3. Add to const in App.xaml.cs code: MediaFile _file;
3. Build to Debug|iPhone or Release|iPhone

### Expected Behavior
Build succeeded
### Actual Behavior
error GF203180B: redefinition of 'UIImageOrientation'

**Comment by atrodriguez88** [comment]
https://github.com/xamarin/xamarin-macios/issues/7199
