### ISSUE TITLE
TakePhotoAsync

### ISSUE THREAD

**Issue by HK-AERIAL-VTOL** [jamesmontemagno/MediaPlugin#764]
Yes... I know others posted this... they were given no answer. My issue is that my app (using TakePhotoAsync) doesn't ever return.

My emulator and tablet both prompt me to allow photos\videos to be taken and to store\read them, and I allow them, but neither ever proceeds past the section.

var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Images",
                    Name = ticket_no + "test.jpg"
                });

I have manually added permissions, built the path xml file, adjusted my AndroidManifest.xml properly, and tried this is a standard (async) button event (not real good... I know) and changed it to a delegate in the page constructor. It does the same thing regardless of the situation. Can anyone tell me whey this routine hangs?

**Comment by jamesmontemagno** [comment]
You need to finish the permission code: https://github.com/jamesmontemagno/MediaPlugin#android
