### ISSUE TITLE
How can i edit the recording screen UI.

### ISSUE THREAD

**Issue by 1993gaurang** [jamesmontemagno/MediaPlugin#765]
Hi @jamesmontemagno Thanks for the great plugin.
I wanted to know is there a way I can Customize the camera screen UI where video recording happens.
![Screen Shot 2019-10-23 at 3 47 34 PM](https://user-images.githubusercontent.com/21169397/67383240-77869700-f5ac-11e9-8031-b0d4f86bd1a7.png).
talking about the above screen.

I would like to change the Icons and text for my app.

**Comment by jamesmontemagno** [comment]
There is no way to change it, we use the built in controls
