### ISSUE TITLE
Folder accessed shows no images or folders

### ISSUE THREAD

**Issue by Swannyj** [jamesmontemagno/MediaPlugin#766]
## Bug Information

Version Number of Plugin: 4.0.1.5
Device Tested On: HP Probook
Simulator Tested On: Nexus 5X
Version of VS:  2019
Version of Xamarin: Xamarin.Forms 4.0

### Steps to reproduce the Behavior
- Click button to upload an image.

### Expected Behavior
- I expected to be shown image folders and movie folders as specified in the `file_paths.xml`. 
- When I drag and drop an image onto the emulator, I expected to see it when I clicked the 'upload image' button.

### Actual Behavior
- I am shown a blank screen with 'Device folders' show

### Code snippet

            await CrossMedia.Current.Initialize();

            if(!CrossMedia.Current.IsPickPhotoSupported)
            {
                await DisplayAlert("Error!", "Not supported.", "Ok");
            }

            _mediaFile = await CrossMedia.Current.PickPhotoAsync();

### Screenshots

![Screenshot_1571997416](https://user-images.githubusercontent.com/23315847/67562230-37432800-f716-11e9-99b5-575e4b242ead.png)

**Comment by auratuk** [comment]
I have the same issue and testing on: 
 
- device: android emulator (Android 8.1 - API 27)
- plugin version: 4.4.6-beta
- xamarin.forms version: 4.0.0.497661
- version of VS: 2019

**Comment by auratuk** [comment]
Damn, my issue was that on the emulator images disappeared so that is the reason why this screen showed nothing

**Comment by jamesmontemagno** [comment]
yes, try a real device or download images
