### ISSUE TITLE
Crash on iOS13 when calling PickVideoAsync() due to access permissions

### ISSUE THREAD

**Issue by Chris-Marassovich** [jamesmontemagno/MediaPlugin#768]
## Bug Information
When I call PickVideoAsync() I get a crash related to path access.
Only occurs on iOS13 and not on earlier versions such as iOS12.
It does not crash on a iOS13 simulator but I expect that has quite different storage permissions.

Version Number of Plugin: 4.0.1.5
Device Tested On: iPhone 6s Plus iOS13.2
Simulator Tested On: iPhone 11 iOS13.1
Version of VS: 16.3.7
Version of Xamarin: 16.3.0.277 (d16-3@c0fcab7)

### Steps to reproduce the Behavior
1. Follow the setup for MediaPlugin.
2. have the following code:
`var file = await CrossMedia.Current.PickVideoAsync();`
When you hit the line that calls PickVideoAsync() and after in the UI you find and choose a video file and click Choose you get a crash.

### Expected Behavior
No crash and MediaFile object is returned.
### Actual Behavior
App crash with the following output
`**System.UnauthorizedAccessException:** 'Access to the path '/private/var/mobile/Containers/Data/PluginKitPlugin/CD7B74C5-26F3-4544-9E61-F6002E90DD31/tmp/trim.845FF578-5695-49F5-91FC-27A8E3961922.MOV' is denied.'`
### Code snippet
`var file = await CrossMedia.Current.PickVideoAsync();`

As I said this only occurs on iOS13 versions.  At the moment I have iOS13.2 and we also saw this on iOS13.1.

**Comment by tsjmattick** [comment]
were you able to find a resolution for this problem?

**Comment by jamesmontemagno** [comment]
You will want to use the latest preview.

**Comment by tsjmattick** [comment]
What build is that exactly?  When trying to use the 4.4.6 beta, I get an assembly reference error when building the project.

**Comment by Chris-Marassovich** [comment]
@tsjmattick sorry for the delay .. I just got back to this issue.  iOS13 has really been a rough update.  :-)
I have just taken 4.4.6-beta and it is working for me on a device.
I will note that inside VS2019 (windows) it shows all my references to the package as invalid … via those red squiggle lines BUT it (my projects) does build fine.

I assume that is a Roslyn/nuget package thing and being this is beta I am ok with that.

Cheers
Chris ...
