### ISSUE TITLE
Image is rotated counterclockwise 90° on Galaxy Tab S2

### ISSUE THREAD

**Issue by maxsieben** [jamesmontemagno/MediaPlugin#77]
## Bug 

Version Number of Plugin: 2.5.1-beta40
Device Tested On: Galaxy Tab S2 (SM-T815) with Android 6.0.1

### Expected Behavior
Images are not rotated.

### Actual Behavior
Image is rotated counterclockwise 90°.

### Steps to reproduce the Behavior
When picking an image with PickPhotoAsync (TakePhotoAsync is working) and showing it in a CircleImageView. This just happens on the Galaxy Tablet, on another test device (Motorola X Style, Android 6.0.1) everything is fine.

**Comment by jamesmontemagno** [comment]
Assumption here is that the device is returning the incorrect exif data. If you can run the test project then you can debug through where the image is rotated.

**Comment by maxsieben** [comment]
Hi thanks for your answer. I am having problems to run the test project. What I did:

1) Downloaded zip from https://github.com/jamesmontemagno/MediaPlugin
2) Opened /tests/Media.sln with Xamarin Studio
3) Set Media > TestsApps > Media Test >MediaAndroidTest as Startup Project
4) When trying to deploy to my device I get the error: The type or namespace name Permissions does not exist in the namespace Plugin. Are you missing an assembly reference? (CS0234) (Media.Plugin.Android)
This error comes from the file Media > Media.Plugin.Android > MediaImplementation.cs. In this file I get the error for this line: using Plugin.Permissions;

There is perhaps a very simple solution to my problem, however I can't find it out, hope you can help me.

**Comment by jamesmontemagno** [comment]
Did you restore the nuget packages?

**Comment by maxsieben** [comment]
My Xamarin Studio settings are to restore nuget packages when opening a solution. So right clicking on Media and selecting >Updating Nuget Packages< didn't work. 

What worked was to delete and add the Permissions Plugin again in Media > Media.Plugin.Android.

**Comment by fabionuno** [comment]
Hi @maxsieben. First open the `src/Media.sln` solution and restore the nuget packages then open the `tests/Media.sln`.

This problem occurs because all nuget packages are restored in a `packages` folder at the same level of `test/Media.sln` file, but this solution is referencing projects at the `src` folder.
When Xamarin build one of the projects at the `src` folder, it search to a `packages` folder inside the `src` folder and this folder doesn't exist

**Comment by maxsieben** [comment]
Hi @fabionuno. Thanks for the explanation, will try it out, when I find the time.
