### ISSUE TITLE
Pause while recording video?

### ISSUE THREAD

**Issue by alexthekid07** [jamesmontemagno/MediaPlugin#771]
When I record video on an Android device, I have the ability to pause mid-recording and then continue at my discretion.

In iOS, this pause feature isn't available. Is this something this plugin is responsible for controlling or is it just an iOS limitation? Is there any way to have parity with that feature between the two?

**Comment by jamesmontemagno** [comment]
We use the default controls, so whatever iOS provides is what the plugin provides.
