### ISSUE TITLE
How can I skip the "Is this pic OK" type of question?

### ISSUE THREAD

**Issue by WillAutioItrax** [jamesmontemagno/MediaPlugin#773]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

I am stepping through the Sample here on an Android. The camera app on the phone lets me go snap, snap, snap to take a set of pictures. The MediaPlugin has a different rhythm: snap, OK, snap, OK, snap, OK.
Where is the confirmation screen coming from and how can I skip over it?
Thanks!

**Comment by jamesmontemagno** [comment]
Nope, we just launch the native photo control which has that in it.

**Comment by WillAutioItrax** [comment]
Very interesting.
After some more digging, I landed on this statement:
`var media = await TakeMediaAsync("image/*", MediaStore.ActionImageCapture, options, token);`
MediaStore has a bunch of options available, one of which is IntentActionStillImageCamera. 
When I use ActionImageCapture I get the confirmation screen. 
When I use IntentActionStillImageCamera, there is no confirmation screen - but the resulting MediaFile is null.
