### ISSUE TITLE
Take photo android 4.4.4 don't work

### ISSUE THREAD

**Issue by mattiaberretti** [jamesmontemagno/MediaPlugin#78]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Vodafone 890N android 4.4.4
Simulator Tested On: ARM API 19 
I tried to take a photo from the camera but only appears a white view

### Actual Behavior
I tried to take a photo from the camera but only appears a white view

### Steps to reproduce the Behavior

 
if(CrossMedia.Current.IsCameraAvailable && CrossMedia.Current.IsTakePhotoSupported)
            {
                GC.Collect();
                var mediaOptions = new Plugin.Media.Abstractions.StoreCameraMediaOptions
                {
                    Directory = "Uizzi",
                    DefaultCamera = Plugin.Media.Abstractions.CameraDevice.Rear,
                    Name = $"{DateTime.UtcNow}.jpg",
                };
                
                var file = await CrossMedia.Current.TakePhotoAsync(mediaOptions);
                
                if (file == null) return true;
                this.ImageProfile.Source = ImageSource.FromFile(file.Path);

                using (var let = new System.IO.BinaryReader(file.GetStream()))
                {
                    var dati = let.ReadBytes((int)let.BaseStream.Length);
                    var res = DependencyService.Get<IResize>();
                    if (res != null)
                    {
                        var tmp = res.resizeImage(dati, 300, 300, file.Path);
                        this.datiNuovaFoto = tmp.dati;
                    }
                    else
                    {
                        var tmp = await DependencyService.Get<IResize_WP>().resizeImage(dati, 300, 300);
                        this.datiNuovaFoto = tmp.dati;
                    }
                }
                //var stream = file.GetStream();
                //using (var let = new System.IO.BinaryReader(stream))
                //{
                //    this.datiNuovaFoto = let.ReadBytes((int)stream.Length);
                //}
                this.ImageProfile.Source = ImageSource.FromStream(() =>
                {
                    return new System.IO.MemoryStream(this.datiNuovaFoto);
                });
                return true;
            }
            return false;

## Feature Request:
Please fill in what you would like

I tried to take a photo from the camera but only appears a white view

**Comment by robecon** [comment]
Same happens to me on Nexus 5X with Android 7.0, I only get a white view when using TakePhotoAsync.
Plugin version tested: 2.3.0 and 2.5.1 beta 56

**Comment by jamesmontemagno** [comment]
This has to do with the file path you are specifying: Name = $"{DateTime.UtcNow}.jpg",

It has illegal characters in it. In the next beta it will fix this for you, but for now remove illegal characters such as / \ and :

**Comment by jamesmontemagno** [comment]
Fixed in latest betas.
