### ISSUE TITLE
Just a qestion regarding focus

### ISSUE THREAD

**Issue by BlackLine-maker** [jamesmontemagno/MediaPlugin#782]
When using iPad or iPhone, users can tap the screen and the camera will attempt to focus.  We have some users saying their cameras aren't focusing well in our app which uses this plugin, but outside the app, the camera focuses good.  Is there a way to show a focus slider or something that we're not aware of?

**Comment by jamesmontemagno** [comment]
This library just pops up the native Camera itself, so it is out of our hands at that point and the OS takes full control. :(
