### ISSUE TITLE
TakeVideoAsync is deleting other photos and videos on S7 running android 6.0.1

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#8]
_From @garybettman on May 13, 2016 14:45_

Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug
- [ ] Feature Request

Which plugin does this impact:
- [ ] Battery
- [ ] Connectivity
- [ ] Contacts
- [ ] DeviceInfo
- [ ] ExternalMaps
- [ ] Geolocator
- [x] Media
- [ ] Permissions
- [ ] Settings
- [ ] Text To Speech
- [ ] Vibrate
- Other:

Version Number of Plugin: 2.3.0
Device Tested On: S7 running android 6.0.1
Simulator Tested On:

### Expected Behavior

When using TakeVideoAsync it should be creating a new video file

### Actual Behavior

It is not creating a new file and is actually deleting existing images and videos inside my camera directory. It is not deleting images in folders such as downloads.  This is working fine on iOS and other android devices running older versions.  I don't know if it is the S7 or android 6.0.1

### Steps to reproduce the Behavior
Make sure you have multiple images and videos in the Camera's folder.  If there is just one it seems to work.
Create a new xamarin forms app.
Create a button that when clicked fires off TakeVideoAsync .
Take a video.
Click ok to accept video.
You will notice that an image or video has been removed from the Gallery.

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#305_

**Comment by jamesmontemagno** [comment]
I can not solve device specific issues sorry.

**Comment by gaffkins** [comment]
The same issue. Samsung S7 Android 6.0.1.when I take video plugin return not recored video but other video from phone and delete this video.
