### ISSUE TITLE
PickPhotoAsync crash with iOS 10

### ISSUE THREAD

**Issue by whitedevils** [jamesmontemagno/MediaPlugin#80]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin:  2.3.0 and 2.5.x beta
Device Tested On: Iphone 6, iphone 5 both iOS 10
Simulator Tested On:

### Expected Behavior
When i take photo from gallery app allow to choose a photo

### Actual Behavior
When i call PickPhotoAsync app crash immediately

### Steps to reproduce the Behavior
iOS 10 installed and visual studio sample solution

**Comment by whitedevils** [comment]
I've found the problem, in this link there is solution https://pareshrvaghela.wordpress.com/2016/07/08/ios-10-and-privacy-settings/

**Comment by jamesmontemagno** [comment]
This is already in the readme. In the next beta it will check for this automatically.
