### ISSUE TITLE
Release stable version

### ISSUE THREAD

**Issue by Mikilll94** [jamesmontemagno/MediaPlugin#811]
The latest stable version of this plugin was released more than one year ago. Now only beta versions are released. Why is that? When will be the next stable version?

![image](https://user-images.githubusercontent.com/17653648/75062880-f7355b80-54e3-11ea-9eeb-581a3965dfa0.png)

**Comment by smillershout** [comment]
Hi there,

I'm also wondering when the next stable version will be released. Our suite of apps relies on this library and our users are experiencing issues related to the metadata which was fixed for version 4.4.8-beta.

Thanks,
Sam.

**Comment by jamesmontemagno** [comment]
5.0 i snow in beta and if goes well will release to stable :)

**Comment by smillershout** [comment]
Thanks for the response James. :)

🤞

**Comment by smillershout** [comment]
Hi @jamesmontemagno . I was wondering if there were any updates on this?

**Comment by jamesmontemagno** [comment]
Yes, I am waiting for us to release Xamarin.Essentials 1.5.2 which should be soon here.

**Comment by Mikilll94** [comment]
@jamesmontemagno 
Hi. Any update on this?

**Comment by smillershout** [comment]
I was wondering too as Xamarin Essentials 1.5.2 was released!! :)

**Comment by smillershout** [comment]
Hi @jamesmontemagno 

Thanks for getting all of this sorted. Right on time too. :)

I'm guessing this issue can be closed?

**Comment by Mikilll94** [comment]
Thanks @jamesmontemagno 

Now it's time to release stable version of [PermissionsPlugin](https://github.com/jamesmontemagno/PermissionsPlugin)

**Comment by InquisitorJax** [comment]
@Mikilll94 if you're referring to the Media plugin dependency, then that's not necessary, since the updated media plugin now relies on Xamarin.Essentials to manage permissions.

**Comment by Mikilll94** [comment]
@InquisitorJax 
Yes. But many projects uses [PermissionsPlugin](https://github.com/jamesmontemagno/PermissionsPlugin) to request permissions manually. So it would be nice to have stable version of this plugin.

**Comment by jamesmontemagno** [comment]
Would recommend switching to Essentials for permissions :)

**Comment by Mikilll94** [comment]
@jamesmontemagno 
I will switch to Essentials when this feature will be implemented
https://github.com/xamarin/Essentials/issues/1160

Right now it is not implemented.
