### ISSUE TITLE
[Question] Move to AndroidX dependencies?

### ISSUE THREAD

**Issue by MitchBomcanhao** [jamesmontemagno/MediaPlugin#814]
With AndroidX support in newer VS and Xamarin versions, I find that our builds still have Android.Support dlls in them, and this plugin seems to have a dependency on Xamarin.Android.Support.Core.Utils, which brings in Xamarin.Android.Support.Compat and Xamarin.Android.Support.Core.Annotations.

Should we expect an update to these plugins (media, permissions, geolocator) to migrate to androidx?

**Comment by jamesmontemagno** [comment]
https://github.com/jamesmontemagno/MediaPlugin/pull/818
