### ISSUE TITLE
Version 5.0.0 beta cant resolve Plugin.Permissions

### ISSUE THREAD

**Issue by nrobeson** [jamesmontemagno/MediaPlugin#819]
Version 5.0.0 beta cant resolve Plugin.Permissions and therefore cannot be. set. I had to revert to a previous version.

**Comment by jamesmontemagno** [comment]
I removed it and it now uses Xamarin.Essentials.

**Comment by nrobeson** [comment]
James,

Can I assume that the line below can now be removed?

Plugin.Permissions.PermissionsImplementation.Current.OnRequestPermissionsResult(requestCode, permissions, grantResults);

Nathan

**Comment by nrobeson** [comment]
q

**Comment by jamesmontemagno** [comment]
Yup, you need to add an Essentials call: https://docs.microsoft.com/en-us/xamarin/essentials/get-started

**Comment by nrobeson** [comment]
Thanks!

Nathan
