### ISSUE TITLE
2.6.0 Stable Release

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#82]
Pending any and all additional show stopping bugs in beta 51 it will ship to stable.

At that time I will
* [x] Update docs
* [x] Create 2.6.0 release branch
* [x] Bump next manifest to 2.7.0-beta{build}

**Comment by pradeeparutla** [comment]
Can you please let me know the tentative date for stable release? We are waiting to close few bugs in our project. If you can provide us a tentative date, It would help us to plan our work in a better way.

**Comment by jamesmontemagno** [comment]
I never know exact dates or tentative dates as there is active development happening, but I do believe the most recent version is close.

**Comment by pradeeparutla** [comment]
Hi James. When is the new stable release for Media Plugin. We are still waiting for release build. Could you please update. If not tentative date, a tentative duration is also okay.

**Comment by jamesmontemagno** [comment]
I have no tentative date as I am still working through issues that exist in both 2.3 and 2.6.

Please do not request a time line again because I simply do not have one I am sorry.
