### ISSUE TITLE
Apple Depricated API Issue

### ISSUE THREAD

**Issue by johnmackerras** [jamesmontemagno/MediaPlugin#824]
I recieved the following notice from Apple after adding thsi plugin.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information. 

What is the solution for accessing Photo's and Media after next month?

**Comment by jamesmontemagno** [comment]
Isn't this library, see: https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
