### ISSUE TITLE
In UWP CircleImage stops the render of a page

### ISSUE THREAD

**Issue by erportico** [jamesmontemagno/MediaPlugin#83]
## Bug 
When in a form I insert a CircleImage, the form works perfectly on iOS and Android but apparently in Windows 10 the component blocks the render of the rest of the page. I added in App.xaml.cs under

`Xamarin.Forms.Forms.Init(e);
ImageCircleRenderer.Init();`

Version Number of Plugin: 1.16.1
Device Tested On: iPhone 6S, iPad, iPad Mini, Cubot Android 6, Windows 10 Desktop, Windows 10 Mobile
Simulator Tested On: iMac, Android_ARMv7A

### Expected Behavior
In Windows 10 Desktop and Windows 10 Mobile I expect to see the component with an image or blank.

### Actual Behavior
In Windows 10 Desktop and Windows 10 Mobile the render of a form is stopped when there is an CircleImage.

### Steps to reproduce the Behavior
Open a form with a CircleImage

**Comment by jamesmontemagno** [comment]
Please post issues here: https://github.com/jamesmontemagno/ImageCirclePlugin
