### ISSUE TITLE
CrossMedia.Current.PickPhotosAsync not picking multiple images in Android 

### ISSUE THREAD

**Issue by jerryqburst** [jamesmontemagno/MediaPlugin#832]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.0 beta
Device Tested On: Honor 7X
Simulator Tested On:
Version of VS: 2019
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior
1. Try to pick multiple images 
2. Only one image can be selected

### Expected Behavior
1. Multiple images should be selected at a time

### Actual Behavior
1. Only one image can be selected
### Code snippet
  var files = await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions
                             {
                                 
                                 PhotoSize = PhotoSize.Full,
                                 CompressionQuality = 100,
                                 CustomPhotoSize = 100,
                                 SaveMetaData = true,
                                 RotateImage = false,
                                 
                             },new MultiPickerOptions{ MaximumImagesCount =1000,
                             AlbumSelectTitle="Select Images",
                             BackButtonTitle="Back" ,
                             BarStyle=MultiPickerBarStyle.Default,
                             DoneButtonTitle="Done",
                             LoadingTitle="Loading",
                             PhotoSelectTitle="Selected"
                             });

**Comment by jerryqburst** [comment]
![Screenshot_20200401_172922_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135303-49e92800-743f-11ea-8ce4-6b142dbcddf0.jpg)
![Screenshot_20200401_172912_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135304-4c4b8200-743f-11ea-9263-baaafd3c45b9.jpg)
![Screenshot_20200401_172945_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135307-4d7caf00-743f-11ea-9b91-a4364a7ef025.jpg)

**Comment by jerryqburst** [comment]
![Screenshot_20200401_172912_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135537-acdabf00-743f-11ea-9a37-6613492f58c2.jpg)
![Screenshot_20200401_172945_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135542-aea48280-743f-11ea-90e8-605ba26e024a.jpg)
![Screenshot_20200401_172922_com android gallery3d](https://user-images.githubusercontent.com/43206938/78135544-af3d1900-743f-11ea-8eb0-8ac3087c8691.jpg)

**Comment by isimobile** [comment]
Hi,

It depends on your Default Gallery Application. If you default Gallery application in Android does not support ExtraAllowMultiple. It will not work from what I see, I could be wrong. If you change your default Gallery Application to for instance Google Photo's then it will work.

To Change your default application: Settings/Apps/App Info -> Select Gallery -> Default settings open -> Delete defaults

**Comment by jerryqburst** [comment]
Thanks a lot.It works
