### ISSUE TITLE
Changelog V5 not updated

### ISSUE THREAD

**Issue by Nk54** [jamesmontemagno/MediaPlugin#833]
Hello, I know it is not a bug but I was wondering what were the changes in the latest release to see whether I have to update my packages or not.

It would be awesome to update the changelog file which stayed at pre 4.0

Thanks a lot. I wish you the best to you and your team. You're doing an amazing job.

**Comment by jamesmontemagno** [comment]
Added, i don't even remember what is in it anymore.
