### ISSUE TITLE
MaximumImagesCount not working

### ISSUE THREAD

**Issue by angelru** [jamesmontemagno/MediaPlugin#835]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: Xiaomi mi6
Simulator Tested On:
Version of VS: 16.5.2
Version of Xamarin: 4.5.0.530
Versions of other things you are using:

### Steps to reproduce the Behavior
MaximumImagesCount not working

### Expected Behavior

MaximumImagesCount it should work

### Actual Behavior

MaximumImagesCount not working

### Code snippet

```
          var picker = new PickMediaOptions
            {
                PhotoSize = photoSize,
                CompressionQuality = compression
            };

            var multiPicker = new MultiPickerOptions
            {
                MaximumImagesCount = 5
            };

            return await CrossMedia.Current.PickPhotosAsync(picker, multiPicker);
```

**Comment by angelru** [comment]
any updates?

**Comment by JigarM** [comment]
Still not working. Any update?

**Comment by angelru** [comment]
still not working

**Comment by damicodorian** [comment]
Any update on this issue ?

**Comment by lazycrazydev** [comment]
Hi, any update on this?
