### ISSUE TITLE
No close method after calling TakePhotoAsync

### ISSUE THREAD

**Issue by michaelgobbers** [jamesmontemagno/MediaPlugin#84]
## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: iPhone 5C iOS10
Simulator Tested On: iPhone 6 iOS10

### Expected Behavior
If for some reason the gallery view should close. i.e. go to background or pull down status bar. It should be possible to call a close method so that we can call TakePhotoAsync again.

### Actual Behavior
If we call the TakePhotoAsync after the gallery did not close properly the following exception is thrown:

System.InvalidOperationException: Only one operation can be active at at time 

### Steps to reproduce the Behavior
- Call TakePhotoAsync
- Press home button or pull down status bar.
- Call TakePhotoAsync again.

## Feature Request:
A method to cleanup any open gallery pickers and maybe a method to check if a gallery is currently open.

**Comment by jamesmontemagno** [comment]
I can't reproduce this actually. I call TakePhotoAsync, hit home button, relaunch the app from home screen or from recents and the camera is still there.
