### ISSUE TITLE
NotImplementedException on Android

### ISSUE THREAD

**Issue by dottorp** [jamesmontemagno/MediaPlugin#85]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Wiko Rainbow Jam (Android 5.1 API 22)
Simulator Tested On: N/A

### Expected Behavior
Camera or media selection opening
### Actual Behavior
App crashes in with a NotImplementedException. Message: This functionality is not implemented in the portable version of this assembly.  You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
### Steps to reproduce the Behavior
Start a Xamarin Forms project. Call CrossMedia.Current.Initialize() in App.cs and it all goes fine. Call it in the code behind of a ContentPage and you receive the error.
![mediaplugin](https://cloud.githubusercontent.com/assets/22364817/18740748/b21b60d6-80ab-11e6-9f43-ff4a450b8128.JPG)

**Comment by jamesmontemagno** [comment]
As it says, you must install the NuGet package into all platform-specific projects.  So install it into your iOS/Android/Windows project.

**Comment by dottorp** [comment]
It's already referenced in all platform-specific projects (see attached image).
![image](https://cloud.githubusercontent.com/assets/22364817/18783321/6bedfcf0-818b-11e6-97ac-9f57116dad1a.png)

**Comment by jamesmontemagno** [comment]
Do you have a sample of this issue? Which exact call does the exception get thrown on?

**Comment by Knots23** [comment]
This post is closed, though prematurely it seems.

I'm having the same issue right now: a NotImplementedException is thrown on the CrossMedia.Current (.Initialize()) even though I'm referencing the project in both by Portable project and Android project.
The Android project targets 6.0 (API 23) and compiles using 'Latest' (6.0). The minimum is set to 4.2 (API 17).
The permissions for external read/write are checked in the manifest.

The Permissions plugin is also referenced; could it be due to a newer version of this package? (Thinking out loud while writing this.)

**Comment by Knots23** [comment]
False alert; it does work. 
Due to a creepy closing tag in one of the xaml files, a 'rebuild' didn't actually do anything. Even though the xaml did not contain valid xml, visual studio 'compiled' it and ran the app.

**Comment by henriquedrumond** [comment]
I have the same problem. It works perfectly in IOS (Xamarin Studio) and does not work on Android (Visual Studio 2015). What would be the solution to the problem since I deleted the component and later added it to my projects

**Comment by arichar1990** [comment]
I am having this same issue, but not when I run the app, only when I try and run unit tests that reference Settings in the portable library. Any insight there?
