### ISSUE TITLE
Android app crash after take picture (TakePhotoAsync)

### ISSUE THREAD

**Issue by pubblika** [jamesmontemagno/MediaPlugin#850]
Hi.
I'm developing app for Android/iOS. I've a problem after call TakePhotoAsync: camera start correctly but after taken photo, app crash without exception.
I enclose a demo project, created following the instructions step by step, which reproduces the same error.
I'm debugging on Sony Xperia G8141, with Android 9.0 API 28.
Thanks, best regards.

[TestFoto.zip](https://github.com/jamesmontemagno/MediaPlugin/files/4540067/TestFoto.zip)

**Comment by pubblika** [comment]
On Samsung SM-A520F, with Android 8.0 API 26, it works correctly.... So, I think the problem is my Sony...but I don't know why...

**Comment by AlexRojasB** [comment]
This is happening on Xiaomi Redmi 8A
Android Version 9 PKQ1.190319.001
