### ISSUE TITLE
MTOUCH build error for iOS on Azure DevOps

### ISSUE THREAD

**Issue by dannythomas13** [jamesmontemagno/MediaPlugin#852]
The following error occurred when upgrading Xam.Plugin.Media to **5.0.1**, I had to rollback to **4.0.1.5** for the build to succeed. All other platform builds succeed against 5.0.1.

**MTOUCH : error MT2101: Can't resolve the reference 'System.Void CoreImage.CILanczosScaleTransform::set_InputImage(CoreImage.CIImage)', referenced from the method 'UIKit.UIImage Plugin.Media.UIImageExtensions::ResizeImageWithAspectRatio(UIKit.UIImage,System.Single)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.** 

Azure Devops Agent Specification: macOS-10.14
Xamarin.Forms: 4.2.0.910310

**Comment by jamesmontemagno** [comment]
Seems as though you have an older version of Xamarin build tools on that machine, you will want to make sure the latest versions with latest xcode are installed as this is an iOS 13 api and required 2019 to be installed. Take a look https://devblogs.microsoft.com/xamarin/boots-xamarin-ci/

**Comment by dannythomas13** [comment]
@jamesmontemagno That seemed to do the trick thanks! The most frustrating thing about Xamarin development for me is managing packages, so many things break when I update dependencies and want to build on DevOps, by the way I love your video content online with tips, keep up the good work!

FYI to get things working I updated MonoVersion from 6.4.0 to 6.8.0 on the hosted build agent, this change also allowed me to move from macOS 6.14 to 6.15 too
