### ISSUE TITLE
Default Camera can't be set since newest Xamarin.Forms update

### ISSUE THREAD

**Issue by LinGtriX** [jamesmontemagno/MediaPlugin#853]
Since the Xamarin.Forms v4.6.0.726 update it doesn't matter which DefaultCamera setting i pick, it always opens first the front-camera which is a huge loss of time if u only want to use the rear option and have to switch camera every single time

tested on Samsung XCover 4

**Comment by charmosz** [comment]
It doesn't work for me either. Did you succeed to make it work ?
