### ISSUE TITLE
White screen with project title before load images to the page

### ISSUE THREAD

**Issue by angelru** [jamesmontemagno/MediaPlugin#857]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: Xiomi mi6
Version of VS: 16.5.4
Version of Xamarin: 4.6.0.726

### Steps to reproduce the Behavior

choose images from gallery or take a photo

### Expected Behavior

You should put chosen images from gallery or camera without white screen comes out first

### Actual Behavior

When I choose an image from the gallery, a white screen appears with the title of my project in the navigationbar before it loads on the page, I have a xiaomi with android 9

**Comment by angelru** [comment]
#716

**Comment by Wabisabix** [comment]
Hi @angelru  , managed to solve the problem?

**Comment by angelru** [comment]
@Wabisabix  no! do you have the same issue ?

**Comment by Wabisabix** [comment]
> @Wabisabix no! do you have the same issue ?

yes

**Comment by angelru** [comment]
@Wabisabix  solve the problem?

**Comment by Wabisabix** [comment]
> @Wabisabix  solve the problem?

No, my friend
