### ISSUE TITLE
iOS10 - App crash when should be show the permission for access camera/photos or the photo picker/camera.

### ISSUE THREAD

**Issue by rafaleonbb** [jamesmontemagno/MediaPlugin#86]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
App crash when should be show the permission for access camera/photos or the picker/camera.

Version Number of Plugin:
Device Tested On: iPad Air Mini (iOS10)
Simulator Tested On: All simulators with iOS10

### Expected Behavior
When I try access to camera/photos the app should be shows the permission for access or the photo picker/camera

### Actual Behavior
App crash

### Steps to reproduce the Behavior
Call methods PickPhotoAsync or TakePhotoAsync.

**Comment by jamesmontemagno** [comment]
Did you add the correct permissions in info.plist? https://blog.xamarin.com/new-ios-10-privacy-permission-settings/


```
<key>NSCameraUsageDescription</key>
<string>This app needs access to the camera to take photos.</string>
<key>NSPhotoLibraryUsageDescription</key>
<string>This app needs access to photos.</string>
```

**Comment by rafaleonbb** [comment]
Oh! I'm so sorry, James, with this permissions works fine.
Sorry again :(
