### ISSUE TITLE
Android: App crash on back button in 2.5.1-beta49 and higher, device only

### ISSUE THREAD

**Issue by michaeldimoudis** [jamesmontemagno/MediaPlugin#87]
Hi James, I think this is a show stopper bug before you plan to release 2.5.1 stable.

## Bug 

Version Number of Plugin: 2.5.1-beta49 and higher
Device Tested On: Nexus 6P API 24, Nexus 5 API 23
Simulator Tested On: Crash does not occur in simulator

### Expected Behavior
When you call PickPhotoAsync or TakePhotoAsync, and then press the Android back button, OR the back arrow top left, the camera/gallery should pop back to the previous page.

### Actual Behavior
When you call PickPhotoAsync or TakePhotoAsync, and then press the Android back button, OR the back arrow top left, the app totally crashes.

This WORKS on 2.5.1-beta40 however does not work on 2.5.1-beta49, 2.5.1-beta50 and 2.5.1-beta51

### Steps to reproduce the Behavior
As above.

## Stack trace
`System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)<1e61de053d6b4364a7f258cbfc0b4fca>:0
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)<1e61de053d6b4364a7f258cbfc0b4fca>:0
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)<1e61de053d6b4364a7f258cbfc0b4fca>:0
System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()<1e61de053d6b4364a7f258cbfc0b4fca>:0
Plugin.Media.MediaImplementation.<TakePhotoAsync>d__18.MoveNext()<14095c72e650408aacce949ac9955472>:0`

**Comment by jamesmontemagno** [comment]
Nice, will investigate asap ;)
