### ISSUE TITLE
SaveToAlbum no longer working on Android 10+

### ISSUE THREAD

**Issue by klogeaage** [jamesmontemagno/MediaPlugin#875]
## Bug Information

Version Number of Plugin: 5.0.1.1
Device Tested On: Multiple
Simulator Tested On: N/A
Version of VS: N/A
Version of Xamarin:  V4.7.0.1080
Versions of other things you are using: Android 10

### Steps to reproduce the Behavior
Set the SaveToAlbum property to true and take a picture on a device running Android10.
### Expected Behavior
Picture should be saved in Gallery on device.
### Actual Behavior
Exception  ex2 is caught and message` "Unable to save to gallery: System.IO.IOException: Couldn't create directory, have you added the WRITE_EXTERNAL_STORAGE permission?"` is written to the console.
### Code snippet
N/A
### Screenshots
N/A

### Cause and workaround
The root cause is that the call to `Environment.GetExternalStoragePublicDirectory(mediaType)` is no longer working on Android 10+ as described [here](https://stackoverflow.com/questions/58379543/cant-create-directory-in-android-10).

There is a workaround that will work until Android 12: 

Add `android:requestLegacyExternalStorage="true"` to the `<application>` element in the manifest. 

This should be done in the sample and documented in the readme.

**Comment by A-Sattari** [comment]
I encountered the issue using Xamarin Forms. 
_Xamarin Forms Version: 4.7_

### Tested on devices below:

**- Samsung Galaxy S20 Plus - Android 10**
**- Google Pixel 4 - Android 10**

**Comment by wagenheimer** [comment]
Urgently waiting for this fix!

**Comment by jamesmontemagno** [comment]
if you wan tot test grab the nuget from: https://dev.azure.com/jamesmontemagno/Plugins%20for%20Xamarin/_build/results?buildId=1853&view=artifacts&type=publishedArtifacts
