### ISSUE TITLE
System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by DnyaneshwarWadghanePM** [jamesmontemagno/MediaPlugin#88]
After launching Camera Activity or MediaPickerActivity, tap on device hardware back button getting following exception.
System.Threading.Tasks.TaskCanceledException: A task was canceled.

## Bug 

Version Number of Plugin: 2.5.1-beta52
Device Tested On: Google Nexus 5 Android 6.1.0, Dell Tablet - Android -kitkat.
Simulator Tested On:

### Expected Behavior
1. Tap on  Take Photo, Camera Activity will launch
2. Tap on device hardware back button
3.  app should not crash

### Actual Behavior
1. Tap on  Take Photo, Camera Activity will launch
2. Tap on device hardware back button
3.  app getting crash

### Steps to reproduce the Behavior
1. Tap on  Take Photo, Camera Activity will launch
2. Tap on device hardware back button
3. Observe
## Feature Request:
Please fill in what you would like

**Comment by fabionuno** [comment]
HI @DnyaneshwarWadghanePM this change was introduced by PR #74 and I think this is the right direction.

@jamesmontemagno If you are using semantic versioning, I think next version should be 3.x.x because this is a breaking change, right?

**Comment by fabionuno** [comment]
@DnyaneshwarWadghanePM This commit https://github.com/jamesmontemagno/MediaPlugin/commit/73149923aa4bce13cb6f601b83cb71ce555c0d18 reverts the cancelation behavior. I think next beta will fix your issue

**Comment by jamesmontemagno** [comment]
Correct, it was reverted in the latest beta that was released as it should return null as it does on other platforms.

**Comment by nicolascaorsi** [comment]
@jamesmontemagno When user opens the screen to take or select a photo, the expected result for that task is have a photo. Upon returning to previous screen, the operation of take a photo was canceled. The expected result shouldn't be an OperationCancelledException?

**Comment by jamesmontemagno** [comment]
That may be, but it would be a breaking change as it is documented that if it is canceled that it will return null.

**Comment by nicolascaorsi** [comment]
Yes, I totallly agree, it's a breaking change. Can it be a future release as @fabionuno suggested? I can make a PR to all platforms.

**Comment by jamesmontemagno** [comment]
Yeah, that sounds good.

**Comment by DnyaneshwarWadghanePM** [comment]
@jamesmontemagno  I have updated media plugin version to beta 56 but still getting same error

**Comment by DnyaneshwarWadghanePM** [comment]
@jamesmontemagno  issue resolved thanks.

**Comment by jamesmontemagno** [comment]
:)
