### ISSUE TITLE
How to use select Multi Photo?

### ISSUE THREAD

**Issue by pulmuone** [jamesmontemagno/MediaPlugin#894]
## **ONLY Post issues against Latest Beta!!!**

Make sure you follow all of the setup directions before posting an issue: https://github.com/jamesmontemagno/MediaPlugin#important-permission-information

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin: 5.01.
Device Tested On: Samsung Galaxy S20+
Simulator Tested On:
Version of VS:  vs2019
Version of Xamarin: v5.0
Versions of other things you are using:

How to use select Multi Photo?
I cannot select multiple photos.

	pickPhotos.Clicked += async (sender, args) =>
			{
				await CrossMedia.Current.Initialize();
				files.Clear();
				if (!CrossMedia.Current.IsPickPhotoSupported)
				{
					await DisplayAlert("Photos Not Supported", ":( Permission not granted to photos.", "OK");
					return;
				}

                var picked = await CrossMedia.Current.PickPhotosAsync(new PickMediaOptions
                {
                    PhotoSize = PhotoSize.Full,
                    SaveMetaData = true
                }, new MultiPickerOptions { MaximumImagesCount=3, PhotoSelectTitle="선택", BarStyle = MultiPickerBarStyle.BlackTranslucent  });                  

				if (picked == null)
					return;
				foreach (var file in picked)
					files.Add(file);
				
			};

**Comment by JigarM** [comment]
Any solution?

**Comment by NehaLOsamaFahmy** [comment]
Any update about select Multi photo?

**Comment by MatthewKapteyn** [comment]
Noticed the device being used is samsung. See my comment here

https://github.com/jamesmontemagno/MediaPlugin/issues/898#issuecomment-718970855

The Android side of this plugin does not implement a multi-picker UI from scratch but instead relies on whatever default photo gallery app is available. Sometimes the default gallery app (in the case of Samsung) a bit broken imho.
