### ISSUE TITLE
I can't add MediaPlugin with NuGet.

### ISSUE THREAD

**Issue by misakikaoru2006** [jamesmontemagno/MediaPlugin#895]
Hello.
I'm developing in Visual Studio 2019 Community.
I've added MediaPlugin to my VisionFaceLandmarks solution.
https://github.com/vecalion/Xamarin.VisionFrameworkFaceLandmarks
However, I could not add the MediaPlugin.
I got the following error.
Please let me know if you have a solution to this problem.

Severity Level Code Description Project File Row Suppression State.
Error The reference could not be added. The package 'Xamarin.Essentials' tried to add a framework reference to 'System. This could be a bug in the package. Contact the owner of the package for assistance.
Error HRESULT E_FAIL was returned from a call to a COM component.

## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: iPad(14.0)
Version of VS: 2019 community 16.7.4
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

1)Download VisionFaceLandmarksSolution https://github.com/vecalion/Xamarin.VisionFrameworkFaceLandmarks
2)NuGet Xam.Plugin.Media
->Error

### Expected Behavior

I can add it with NuGet.

### Actual Behavior

I can't add it with NuGet.

**Comment by misakikaoru2006** [comment]
![2020_1001_1124_52](https://user-images.githubusercontent.com/11881920/94758818-3ceec680-03d9-11eb-8cc1-ff31081a48cc.jpg)
![2020_1001_1125_12](https://user-images.githubusercontent.com/11881920/94758822-3e1ff380-03d9-11eb-9f5e-08a9dec3fad2.jpg)

**Comment by jamesmontemagno** [comment]
Please migrate to package references in your application
