### ISSUE TITLE
Xam.Plugin.Media taking photo not working on Xamarin.Forms(currently 2.2.0.31)

### ISSUE THREAD

**Issue by jamesmontemagno** [jamesmontemagno/MediaPlugin#9]
_From @huby01 on May 12, 2016 14:32_

Please take a moment to fill out the following (change to preview to check or place x in []):

This is a 
- [x] Bug

Which plugin does this impact:
- [x] Media

Version Number of Plugin:2.3.0
Device Tested On:
Simulator Tested On:WP8.1

### Expected Behavior
Taking photo
### Actual Behavior
Taking photo task hangs with an endless "Resume..." message
### Steps to reproduce the Behavior

_Copied from original issue: jamesmontemagno/Xamarin.Plugins#303_

**Comment by jamesmontemagno** [comment]
_From @danieledallavalle on May 16, 2016 16:4_

I have the same behavior on Android and same Foms version

**Comment by jamesmontemagno** [comment]
_From @danieledallavalle on May 16, 2016 16:29_

Actually my issue seems more related to a strange behavior of ImageSource.FromStream not executing the delegate, the Media plugin is working correctly

**Comment by jamesmontemagno** [comment]
_From @EduardoSerra on May 18, 2016 14:8_

Did you work around this issue? how?

**Comment by jamesmontemagno** [comment]
_From @danieledallavalle on May 24, 2016 12:9_

Sorry for the late replay,

What I did was to use the path of the MediaFIle on the device to retrieve it, but you can also use the GetStream method of the MediaFile itself

**Comment by jamesmontemagno** [comment]
_From @huby01 on May 25, 2016 10:15_

I temporarily downgraded Xamarin.Forms to version 2.1.0.6529 and it works.
I also tried the current XF 2.3.*-pre2 and it is not working.

**Comment by hitinder** [comment]
I am facing the same issue for taking photo, the sample code is not working on Android. Using Huawei Ascend P7, Android 4.4.2

image.Source = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                file.Dispose();
                return stream;
            });

**Comment by hitinder** [comment]
Upgraded to pre release beta 3 and its working fine.

**Comment by jamesmontemagno** [comment]
Unable to reproduce on 2.5.0-beta5
