### ISSUE TITLE
Sample for Android 10 unstable! (restart or crash)

### ISSUE THREAD

**Issue by roman536** [jamesmontemagno/MediaPlugin#900]
## Bug Information
MediaPlugin take many photos results in restart or crash the app on **some Android tablet devices**.

Version Number of Plugin: 5.0.1
Device Tested On: Tablet Samsung SM-T515 Android 10.0
Simulator Tested On: -
Version of VS: Microsoft Visual Studio Enterprise 2019 Version 16.7.6
Version of Xamarin: Xamarin.Essentials 1.5.3.2, Xamarin.Forms 4.8.0.1534
Versions of other things you are using: NETStandard.Library 2.0.3 Android 10.0 (API 29 - Q), Android SDK Tools 26.1.1, provider android:name="androidx.core.content.FileProvider".

### Steps to reproduce the Behavior
Debug or build and run APK using test project on Android tablet (Samsung SM-T515).
https://github.com/roman536/Xamarin-MediaPlugin-Test
Use TakePhoto function to make many photos continuously.
Try to focus the view on monochromic surfaces.
Notice only some Android tablet devices have troubles with MediaPlugin!

### Expected Behavior
The message "The plugin CrossMedia has been started!" should appear after init only.
The TakePhoto functionality should be able to make and store many photos continuously.

### Actual Behavior
Not after first photo, but randomly some activity results in restart or crash the app.
Once before 10th photo, sometimes after 20th.
APK or test video file can be provided on request.

### Code snippet
https://github.com/roman536/Xamarin-MediaPlugin-Test

**Comment by manikandankTSI155** [comment]
Hi @roman536 , am facing same issue in same Tablet Samsung SM-T515 Android 10.0
https://github.com/jamesmontemagno/MediaPlugin/issues/901

**Comment by MitchBomcanhao** [comment]
I've been observing a relatively large number of unexplained crashes (they're not caught by App Center) on Samsung SM-T515 devices and only now I've had someone reach out explaining it happens when they're taking photos.

(unconfirmed) one user may have started getting issues following a device update from android 9 to android 10.

I've no access to one of those devices to actually attempt to reproduce this - has anyone got this to fail on another device type?

**Comment by dev-thinks** [comment]
> I've been observing a relatively large number of unexplained crashes (they're not caught by App Center) on Samsung SM-T515 devices and only now I've had someone reach out explaining it happens when they're taking photos.
> 
> (unconfirmed) one user may have started getting issues following a device update from android 9 to android 10.
> 
> I've no access to one of those devices to actually attempt to reproduce this - has anyone got this to fail on another device type?

Its true. working in android 9 but crashing in 10.

**Comment by MitchBomcanhao** [comment]
If you have access to these devices, can you tell what is terminating the application? is there any specific error message that you can share?
If the application is being terminated by android, perhaps you can check the android device log for messages that can point us in the direction of the actual issue?

**Comment by jeroen-corteville** [comment]
I also ran into this issue with a SM-T515. I was able to replicate the issue, but I tried switching to the Xamarin.Essentials Camera implementation and I ran into the same issue. I found the same kind of issue here: [https://github.com/apache/cordova-plugin-camera/issues/345](https://github.com/apache/cordova-plugin-camera/issues/345) as well. 

I tried installing OpenCamera and I wasn't able to replicate the crash using OpenCamera.

This might be an issue with the Samsung Camera App.

**Comment by roman536** [comment]
This or other circumstances may help, but there must be some deeper complication.
I could have run into crash using Pick function to get pictures from the Gallery as well!
Try to pick continuously any picture for 20-50 or more times. Sometimes the device makes a breather, sometimes works farther on, but it smothers somehow.
All the same processes perform much more powerful on the better smartphone.
Maybe the smaller display needs less power, maybe there is better core inside?
Is there time out issue while acquiring wide permissions?

**Comment by MitchBomcanhao** [comment]
also possibly related https://github.com/apache/cordova-plugin-camera/issues/665

**Comment by roman536** [comment]
Meanwhile I have evaluated Xamarin.Essentials 1.6.0 MediaPicker.CapturePhotoAsync method resulting in same behavior on Samsung SM-T515. Therefore, the mistake insinuates rather to Android 10 specifics on this or similar devices.

**Comment by roman536** [comment]
I am closing this issue due to nature of the crash generated not directly by Media.P* but rather dependency on the hardware and android system.
Enclosed there is last evaluation with 2 Cam-Apps installed:
-	MyApp with implemented Media.P* calls some Cam-App.
-	There is a selection for Cam-App 1/2 (OK so far).
-	After selection for Cam-App1 but before drop any photo MyApp disappears from device memory or not. If so, there is no return (crash). If MyApp is still living, go farther.
-	Do not make photo still but open another Cam-App2. MyApp should still exist in memory.
-	We are now taking a photo with Cam-App2 still holding MyApp and called Cam-App1 in memory. This step results often in disappeared MyApp from memory.
-	In such scenario there is no return to MyApp after pushing OK button on called Cam-App.

I guess Media.P* becomes any return event from called Cam-App but is watching file system for new photos trying to import them and reactivate itself. It is irrelevant to Cam-App (one or more). This seams not to work on some devices like Tablet Samsung SM-T515 having 2GB memory and originally Android 9.0 but updated to Android 10.0
