### ISSUE TITLE
PickPhotoAsync - the first time it doesn't work

### ISSUE THREAD

**Issue by 78fede78** [jamesmontemagno/MediaPlugin#906]
The first time I use the application after confirming the permission to access the photos saved on the gallery, pickphoto async seems to do nothing.

in my opinion the problem is that it does not wait for user authorization.

in order to work correctly I have to click on the upload button of the photo more than once.

i am working with android with the latest version of the library.

```
await CrossMedia.Current.Initialize();
if (!CrossMedia.Current.IsPickPhotoSupported)
{
	await DisplayAlert("Oops", "You Cannot pick an image", AppResources.Label_OK);
	return;
}
var file = await CrossMedia.Current.PickPhotoAsync(new PickMediaOptions
{
	PhotoSize = PhotoSize.MaxWidthHeight,
	MaxWidthHeight = 800,
	SaveMetaData = false
});
```
![Screenshot_20201118-002317_Permission controller](https://user-images.githubusercontent.com/6544743/99462957-11964b80-2935-11eb-8caf-fcafadbf5b84.png)

**Comment by jamesmontemagno** [comment]
Unable to reproduce, working here on latest
