### ISSUE TITLE
Loading image from External Storge

### ISSUE THREAD

**Issue by henriqueteles** [jamesmontemagno/MediaPlugin#91]
I'm  trying to show in my app an image loaded from the external storage, however, it is not showing up.
I have already added the permission and it is working with other photos

**Comment by jamesmontemagno** [comment]
So, just want to be sure I have this right and I am assuming this is Android. But you:

1.) are using PickPhotoAsync()
2.) You have a photo on an external SD card
3.) You pick it from the gallery on the external SD Card


Does it return null? Or does it return a path?

**Comment by henriqueteles** [comment]
Sorry, I should have been more specific

 var file = await CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions()
            {
                CompressionQuality = 50,
            });

2) Yes, I have a photo on my external SD card
3)I pick the photo from the gallery on the external SD card
It returns the path and bytes, however, when I set the data to be shown in my UI image control it does not appear. If i pick any other photo it works perfectly

**Comment by jamesmontemagno** [comment]
How are you attempting to load the image into the UI?

**Comment by henriqueteles** [comment]
I populate my property Image (ViewModel)
  _post.Image = file.GetStream().ToByte();

In my ContentPage
 image = new Image
                    {
                        HorizontalOptions = new LayoutOptions(LayoutAlignment.Center, true),
                        VerticalOptions = new LayoutOptions(LayoutAlignment.Center, true),
                        Aspect = Aspect.AspectFit,
                        **Source = ImageSource.FromStream(() =>
                       new MemoryStream(AddPostViewModel.Post.Image)
                    )**

**Comment by henriqueteles** [comment]
any idea?

**Comment by jamesmontemagno** [comment]
Haven't had any time to test this out sorry. Marking as low priority as it most likely has been an issue since the original launch and no one has reported.

**Comment by jamesmontemagno** [comment]
On emulators the default picker doesn't show external sd cards so goign to install a picker and hope that I can get it working. Does it pick from a photo gallery app?

**Comment by henriqueteles** [comment]
Hi,

I have been testing it on my phone (android) and the behavior is a bit weird. Some photos from my camera that im picking it from(internal and SD) are being shown and some are not

**Comment by ericbrunner** [comment]
@henriqueteles I had a similar issue. Try to define a var outside the lamba like:

    var stream = new MemoryStream(AddPostViewModel.Post.Image);
    stream.Position = 0 // Sometimes I noticed that the Position is at the end
    Source = ImageSource.FromStream(() => stream)

Why don't you just do that ?

    Source = ImageSource.FromStream(() =>file.GetStream())

**Comment by jamesmontemagno** [comment]
I am pretty sure that would be it via @ericbrunner , can you validate?
