### ISSUE TITLE
OpenCamera / Pick from libary crash with a resource not found when targeting Android 10.

### ISSUE THREAD

**Issue by tallichet** [jamesmontemagno/MediaPlugin#911]
## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: OnePlus 7T Pro, Galaxy Tab S6
Simulator Tested On: -
Version of VS: 16.8.2
Version of Xamarin: 4.8.0.1560, 4.8.0.1687
Versions of other things you are using:

### Steps to reproduce the Behavior
Create a projet an follow instruction to capture a photo, or pick from library, haveing everything working when compiling with Android 9.0.
Switch to Compile with Android version 10, having this libraries
![image](https://user-images.githubusercontent.com/656449/100235047-33db2b00-2f2c-11eb-91a0-a930803263a3.png)

### Expected Behavior
Camera picker / Image library should open

### Actual Behavior
Application crash with following error (from VS)
```
Java.Lang.RuntimeException: 'Unable to start activity ComponentInfo{online.koco.mobileapp/crc64a0e0a82d0db9a07d.IntermediateActivity}: android.content.res.Resources$NotFoundException: File # #0f0 from drawable resource ID #0x7f050030: .xml extension required'
```

PS: I've got exact same result when calling from Xamarin.Essentials 1.6-pre4

**Comment by Maxima078** [comment]
I have no problem targeting Android SDK 10. Tried with pixel 2 Android 9 and Xiaomi mi 9 Android 10.
Did you clean and rebuilt?
Could you provide a repro?

**Comment by Alextorres950325** [comment]
I Migrated to AndroidX and this crash doesn't occur

**Comment by jamesmontemagno** [comment]
Please try latest and migrate to androidx
