### ISSUE TITLE
Android: PickPhotosAsync does not use MultiPickerOptions

### ISSUE THREAD

**Issue by MrSerWin** [jamesmontemagno/MediaPlugin#922]
PickPhotosAsync does not use MultiPickerOptions
## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by lhughey** [comment]
Why was this ticket closed? This is still and issue.
