### ISSUE TITLE
 Object reference not set to an instance of an object (iOS)

### ISSUE THREAD

**Issue by XamarinGuy95** [jamesmontemagno/MediaPlugin#924]
I have problem with taking photo on iOS device. I use 
 var photo = await **CrossMedia.Current.TakePhotoAsync**(new Plugin.Media.Abstractions.StoreCameraMediaOptions() { SaveToAlbum = false, CompressionQuality = 30 }); 
On  Android device everything works fine, but on iOS :(
I use 5.0.1 verison of Xam.Plugin.Media

**Comment by jamesmontemagno** [comment]
unable to reproduce, check sample in repo.
