### ISSUE TITLE
Can we Record  video in square frame only?

### ISSUE THREAD

**Issue by hadwanihardik** [jamesmontemagno/MediaPlugin#925]
I want to record and store square video.
As my application displays video in square part only it needs to be recorded in square only.
Can you suggest any options?

**Comment by CodeToKillBugs** [comment]
Hi @hadwanihardik,
I'm unable to store recorded video in device or emulator but successfully displaying its path but video is not getting saved.
Please Help me if you can with the below code. I'm stuck here from last 1 month.

#Code :- 

async void OnCaremaIconClicked(object sender, EventArgs e)
{
await CrossMedia.Current.Initialize();

    if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakeVideoSupported)
    {
        DisplayAlert("No Camera", ":( No camera avaialble.", "OK");
        return;
    }

    var file = await Plugin.Media.CrossMedia.Current.TakeVideoAsync(new Plugin.Media.Abstractions.StoreVideoOptions
    {
        Directory = "DefaultVideos",
        Name = "video.mp4",
        SaveToAlbum = true
    });
    //await Task.Delay(6000);
    if (file == null)
        return;

    await DisplayAlert("Video Recorded", "Location: " + file.AlbumPath, "OK");
    file.Dispose();
    //=====================================Picture==================================

    //if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
    //{
    //    DisplayAlert("No Camera", ":( No camera available.", "OK");
    //    return;
    //}

    //var file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions
    //{
    //    Directory = "Sample",
    //    Name = "test.jpg",
    //    SaveToAlbum = true
    //});

    //if (file == null)
    //    return;

    //await DisplayAlert("File Location", file.AlbumPath, "OK");

}

async void OnVideoPickerIconClicked(object sender, EventArgs e)
{
    await CrossMedia.Current.Initialize();

    if (!CrossMedia.Current.IsPickVideoSupported)
    {
        DisplayAlert("Videos Not Supported", ":( Permission not granted to videos.", "OK");
        return;
    }
    var file = await Plugin.Media.CrossMedia.Current.PickVideoAsync();

    if (file == null)
        return;

    await DisplayAlert("Video Selected", "Location: " + file.AlbumPath, "OK");
    //file.Dispose();

    //================================PICTURE==============================

    //if (!CrossMedia.Current.IsPickPhotoSupported)
    //{
    //    DisplayAlert("Photos Not Supported", ":( Permission not granted to photos.", "OK");
    //    return;
    //}
    //var file = await Plugin.Media.CrossMedia.Current.PickPhotoAsync(new Plugin.Media.Abstractions.PickMediaOptions
    //{
    //    PhotoSize = Plugin.Media.Abstractions.PhotoSize.Medium,

    //});


    //if (file == null)
    //    return;
    //await DisplayAlert("Video Selected", "Location: " + file.AlbumPath, "OK");
}

**Comment by jamesmontemagno** [comment]
Nope, it is only what the device camera allows

**Comment by CodeToKillBug** [comment]
> Nope, it is only what the device camera allows

Is There Any Other Way To Store Recorded Video Into Device.....?

**Comment by jamesmontemagno** [comment]
You would want to look at the native APIs for camera. I don't have experience there.
