### ISSUE TITLE
[Crash] mono.java.lang.RunnableImplementor.run RunnableImplementor.java, line 30 Java.Lang.IllegalArgumentException: View=DecorView@d126374[MediaPickerActivity] not attached to window manager

### ISSUE THREAD

**Issue by sbs-Arockia-Jenitha** [jamesmontemagno/MediaPlugin#926]
## **ONLY Post issues against Latest Beta!!!**

We are using Media Plugin for Take photo and Take Video.

https://gist.github.com/sbs-Arockia-Jenitha/d725b80fc1a3618c13266f90542f5d33

## Bug Information

Version Number of Plugin: 5.0.1
Device Tested On: Galaxy S21 5G(Android 11)
Simulator Tested On:
Version of VS: 16.8.6
Version of Xamarin: 5.0.0.1931
Versions of other things you are using:

### Steps to reproduce the Behavior
unknown
### Expected Behavior
App will not be crash
### Actual Behavior
App Crashed

**Comment by fvalentiner** [comment]
@sbs-Arockia-Jenitha we are having the same Issue in some devices not all with version 5.1. Have you been able to solve it?

**Comment by sbs-Arockia-Jenitha** [comment]
> @sbs-Arockia-Jenitha we are having the same Issue in some devices not all with version 5.1. Have you been able to solve it?

This issue occurs for android and ios while open the Camera to take video or photo. But not resolved.

**Comment by fvalentiner** [comment]
@sbs-Arockia-Jenitha we went back to 5.0.1 and made sure all Projects: Core, iOS and Android had the same version and it is now working. Hope it works for you as well

**Comment by sbs-Arockia-Jenitha** [comment]
@fvalentiner  We are using latest version of Plugin.Media. and also this issue coming from this version too.

**Comment by sbs-Arockia-Jenitha** [comment]
@fvalentiner  Any update about this issue?

**Comment by jamesmontemagno** [comment]
Unable to reproduce at all working fine. Do NOT call from a pop up dialog.

**Comment by navkar** [comment]
See the attached screenshot! - version 5.0.1

![Screenshot 2022-10-25 124447](https://user-images.githubusercontent.com/7309326/197845189-15844428-33a5-4664-82d2-479b8e08c8d8.png)
