### ISSUE TITLE
Photosize option having no effect in TakePhotoAsync

### ISSUE THREAD

**Issue by Troto** [jamesmontemagno/MediaPlugin#93]
## Bug 

Version Number of Plugin: 2.5.1 beta60
Device Tested On: Samsung Galaxy S5 - android 6.0.1

I'm assuming that photosize refers to resolutions and not just the size of the file saved.

### Expected Behavior
When setting StoreCameraMediaOptions I set PhotoSize = PhotoSize.Small and I would expect the resulting image to have a quarter the size of the camera app resolution setting.

### Actual Behavior
The resulting image is the same resolution.

### Steps to reproduce the Behavior
I'm seeing this as a result of trying to display the image that I took on a page immediately after and getting the error "Bitmap too large to be uploaded into a texture (5312x2988, max=4096x4096)" showing the size hasn't reduced.

EDIT: Upon further usage, pictures taken with the camera horizontal will display fine however pictures taken when vertical will still not display and get the above error.

**Comment by jamesmontemagno** [comment]
Hmmm interesting, I will take a look, which image are you inflating? the album version or the normal string, do you have some code to share at all of the call and the inflate of the image.

**Comment by Troto** [comment]
I'm not sure what you mean by "how are you inflating the image" with those two options, I'm loading it from the file object as shown below.

These are the two relevant methods. The first taking the photo and then calling the second which loads the stream and sets it to an ImageSource binding I have called PictureSource. Which is displayed by the xaml at the bottom.

The issue occurs after SetPicture() has finished running and the photo should display. 

If I took the photo vertically I get the error "Bitmap too large to be uploaded into a texture (5312x2988, max=4096x4096)".

```
async Task TakePicture()
        {
            try
            {
                await CrossMedia.Current.Initialize();
                if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported)
                {
                    await _displayAlertService.Error("Camera is unavailable or taking a photo is not supported");
                    return;
                }

                var fileName = Guid.NewGuid() + ".jpg";
                var file = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions
                {
                    Directory = "Pictures",
                    Name = fileName,
                    PhotoSize = PhotoSize.Small
                });

                SetPicture(file);
            }
            catch (Exception exception)
            {
                await _displayAlertService.Error("Something went wrong. Most likely, you do not have the correct permissions for taking a picture. Add the camera permission in the app's settings.");
            }
        }
```

```
void SetPicture(MediaFile file)
        {
            if (file == null) return;

            PictureSource = ImageSource.FromStream(() =>
            {
                var stream = file.GetStream();
                file.Dispose();
                return stream;
            });
        }
```

```
<StackLayout IsVisible="{Binding PictureSelected}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
        <Image Source="{Binding PictureSource}" ></Image>
        <Button Text="I'm happy, submit that." Command="{Binding SubmitObservationCommand}"></Button>
</StackLayout>
```

**Comment by jamesmontemagno** [comment]
It is in fact shrinking. I am using an emulator to validate and my byte sizes are:

Full: 307200
Medium: 76800
Small: 19200

Inside of an Android project I tested: var bitmap = BitmapFactory.DecodeFile(file.Path);

This will return the height and width and byte size.

If I do a File.GetStream() I get the following for the length:
Large: 13253
Small: 4732

Each setting is a percentage of the original size, so:
Full = 100%
Large = 75%
Medium = 50%
Small = 25%

What does the error say if you set it to full?

**Comment by Troto** [comment]
On my actual samsung s5 (6.0.1) with PhotoSize.Small I get a stream length of 2550812 which seems like it's just taking the full.

On the visual studio emulator running android 4.4 it respects the size and I get a length of 7423.

Running on my actual s5 with PhotoSize.Full I get the same result as on small pretty much. The stream length is 2725371. Same error.

**Comment by jamesmontemagno** [comment]
So i just ran tests on my Nexus 6p android 7.0 and was able to verify that it was compressing down for me. 

Bitmap byte count
48771072 Full Size 4032 x 3024
3048192 Small Size 1008 x 756

Stream
2883874 Full Size 92% compression
189051  Small Size 92% compression
47811   Small Size 50% compression

It seems as though perhaps it is a firmware issue on the s5 that the compress doesn't work. Seems very strange.

The code creates a scaled image and then compresses it to save it to disc.
```
using (var compressedImage = Bitmap.CreateScaledBitmap(originalImage, (int)(originalImage.Width * percent), (int)(originalImage.Height * percent), false))
                            {
                                using (var stream = File.Open(filePath, FileMode.Create, FileAccess.ReadWrite))
                                {
                                    compressedImage.Compress(Bitmap.CompressFormat.Jpeg, quality, stream);
                                    stream.Close();
                                }

                                compressedImage.Recycle();
                            }
```

If you save the images to gallery are they actually smaller in the gallery? this is a good way of testing too. I even forced it to rotate for all code paths and it compressed alright for me here. As my assumption is that for some reason that compression fails.

Do you see anything in the debug window that looks like this:
Console.WriteLine("Unable to check orientation: " + ex);

**Comment by jamesmontemagno** [comment]
It may be that it can't compress the image due to a heap issue...

In this case you may need to add a flag into the <Application> area for large heap:
http://stackoverflow.com/questions/27270358/bitmap-decoderesource-out-of-memory-crash-on-samsung-s5

Try adding this to your Android manifest:  android:largeHeap="true" inside the APPLICATION tag!

**Comment by Troto** [comment]
Thank you! It seems you were right with the heap thing. I added the largeheap attribute and it displayed a vertical photo on PhotoSize.Small. It's still quite large though. I guess that's what happens when your default camera setting is really high res. 

If I try and take a photo at PhotoSize.Full it still doesn't display and gives the bitmap too large error but that's much more understandable.

Also not sure if it's relevant now but I couldn't see anything saying "unable to check orientation" although I might have missed it in the busy output.

As a note, it might be worth adding an even smaller size such as tiny so that you can, at least, always get an image back that will fit onto the screen, even when the camera is set to a much higher resolution.

**Comment by jamesmontemagno** [comment]
In the latest beta65 you can now set custom and you can then set the "CustomPhotoSize", which is between 1-100%

I will look further into optimizing the compression algorithm to see if there is anything I can do about the images at all on those devices.

**Comment by Troto** [comment]
Awesome! Thanks for your rapid and useful responses!

**Comment by jamesmontemagno** [comment]
:)

**Comment by jamesmontemagno** [comment]
I super crazy optimized the new stuff, so you shouldn't even see a crash now with the full size from my testing.
