### ISSUE TITLE
Camera not available on Android 13 api 33 because of permissions

### ISSUE THREAD

**Issue by okdicom** [jamesmontemagno/MediaPlugin#946]
When trying to open Camera or Media file the storage permission is not being asked therefore the camera is not opening.
With api 32 or below everything is working fine.

## Bug Information

Version Number of Plugin: 5.1.1-beta
Device Tested On: Pixel 6 pro
Simulator Tested On: Pixel 5 api 33
Version of VS: VS 2022
Version of Xamarin: Xamarin.Forms 5.0.0.2515
Versions of other things you are using:

### Steps to reproduce the Behavior
Just try to open the camera

### Expected Behavior
Permissions should be asked (camera and storage) and then camera should open
### Actual Behavior
Only Camera permission is asked and then Camera not available is displayed.

### Code snippet

I'm using the documentation code snippet and when I debug it I can see that the storage permission is requested but it does not show.

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);
            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

### Screenshots

![Screenshot_1663155171](https://user-images.githubusercontent.com/3427423/190143041-03ce6454-3866-4934-b978-411aa07b6dfd.png)

**Comment by jamesmontemagno** [comment]
Try out the latest beta i just pushed

**Comment by okdicom** [comment]
Thank you very much James, now the camera is opening and working as expected!

**Comment by BabakCelecom** [comment]
Camera is not opening in my API 33 now

**Comment by vega3000** [comment]
Same for me API 33. Camera is not opening.
The camera's permission is Granted and Camera is Available, but when TakePhotoAsync, it crashed with this message :

Plugin.Media.Abstractions.MediaPermissionException: 'Camera permission(s) are required.'

**Comment by mcmcelro** [comment]
Same issue for me as well. This worked on API 29 and API 31 but as soon as we updated to API 33 we get the same message mentioned by @vega3000 .

**Comment by zerokewl88** [comment]
Same here today, upgraded to API33 - (forced to for Android new Application Policies) - and now camera permissions are broken. 

Seems like another known bug with suggestions i'm following here - we are trying to solve it still. 

REF: https://github.com/xamarin/Essentials/issues/2041

**Comment by kishorasm123** [comment]
is there any update on how to fix, I am alos facing same error Plugin.Media.Abstractions.MediaPermissionException: 'Camera permission(s) are required.' in API level 133 (Android 13)

**Comment by nosmalldreams** [comment]
Why is this closed with no resolution? Same issue.

**Comment by zerokewl88** [comment]
My solution above resolved this for me.. not sure why it didn't work for others. I have a production released app working on API 33 using camera now, so I guess its fixed.

Kind Regards,

Jeffrey Holmes
+66806075331
________________________________

**Comment by LucioMSP** [comment]
did you do anything special? what package do you use? Does the application work on Android 14?
