### ISSUE TITLE
Taking a photo freezes app on iOS 10

### ISSUE THREAD

**Issue by ddklo** [jamesmontemagno/MediaPlugin#97]
## Bug 
When taking a photo app freezes on iOS 10 with the following errors in the output. We are setting NSCameraUsageDescription and NSPhotoLibraryUsageDescription. And played around with setting the UiViewControllerBasedStatusBarAppearance after some suggestions in StackOverflow posts.

CGContextAddPath: invalid context 0x0. 
invalid context 0x0. 
CGContextSetFillColorWithColor: invalid context 0x0. 
CGContextFillRects: invalid context 0x0. 

Version Number of Plugin:  2.6.0-beta1, 
[ios10camera.txt](https://github.com/jamesmontemagno/MediaPlugin/files/516108/ios10camera.txt)
2.3.0 
Device Tested On: iPad Air 2 iOS 10, iPad Air iOS 10
Simulator Tested On: None

### Expected Behavior
Opens the camera view

### Actual Behavior
App freezes

### Steps to reproduce the Behavior
Call CrossMedia.Current.TakePhotoAsync(...)

## Feature Request:
For the app not to freeze

**Comment by jamesmontemagno** [comment]
What does your code look like in general? I have updated my test app and testing against iOS 10 devices and working nicely here...

**Comment by ddklo** [comment]
It is an Xamarin Forms app running on the iOS devices. Basically a button with a command that calls TakePhotoAsync. I tried it in both Modal and non Modal pages. 

```C#  
 public ICommand OnTakePhotoCommand => onTakePhotoCommand ?? (onTakePhotoCommand = new Command(async () => await OnTakePhoto()));
```

```C#
       private async Task OnTakePhoto()
        {
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported) return;
            await CrossMedia.Current.Initialize();
            using (var mediaFile = await CrossMedia.Current.TakePhotoAsync(new StoreCameraMediaOptions()))
            {
                if (mediaFile != null)
                {
                }
            }       
        }
```

**Comment by jamesmontemagno** [comment]
What version of Xamarin and what version of Xcode are you building against? My tests locally have been good on iOS 10 devices.

Also, your initialize() should be the VERY first thing you do before IsCameraAvailable :)

**Comment by jamesmontemagno** [comment]
I am unable to reproduce on my iPhone 6 or iPad Pro with my test applications. Attempt to run and checkout the test apps that I have in the test folder as they are working for me.

Are you using Xamarin.Forms or Traditional UIs? I could test that route with Forms and see if something is broken there.

**Comment by ddklo** [comment]
I am on Xamarin Forms. The latest version of Xamarin and Xcode. It has been the same on all versions coming out since iOS 10, before iOS 10 everything was working so I am not sure what changed except the privacy settings. It has also been the same on all iterations of the plugin from stable to the latest beta.

I will try your sample app. We have tried multiple of ours app and different deploys (macs, bitrise) without luck.

**Comment by jamesmontemagno** [comment]
I tried your exact code and it is working great on my iPad Pro running 10.0.2. Here it is:
[TestApp2.zip](https://github.com/jamesmontemagno/MediaPlugin/files/517276/TestApp2.zip)

**Comment by ddklo** [comment]
So it seems like the culprit is adding the line below in FinishedLaunching in the AppDelegate class. It seems like this should be OK and it worked in iOS 9. Does this freeze the UI on your end too?

```C#  
UISlider.Appearance.MinimumTrackTintColor = UIColor.Orange;
```

**Comment by ddklo** [comment]
Hi.

Did you manage to reproduce the issue when setting the MinimumTrackTintColor?

**Comment by jamesmontemagno** [comment]
Seems like it isn't related to the plugin at all so I haven't attempted to look at it at all. Maybe a change in ios10

**Comment by kotay** [comment]
@ddklo Did you ever get to the bottom of this issue, we're seeing very similar behaviour.

**Comment by ddklo** [comment]
No, havent had time to look into it further. We ended up not setting the MinimumTrackTintColor. It would probably work applying the UISlider appearance in a custom renderer. But hopefully its a bug in iOS that get fixed or @jamesmontemagno finds a way to work around the bug in this library.
