### ISSUE TITLE
iOS failing after picture taking

### ISSUE THREAD

**Issue by gmeredith** [jamesmontemagno/MediaPlugin#99]
## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: physical iPhone 6s 9.3.4
Simulator Tested On: using MacinCloud - haven't tried taking picture, don't believe I can

### Expected Behavior
After taking picture and "OK'ing" picture app should "close" camera and be on page. It should display picture and allow user to "name" picture. Finally Save the photo.

### Actual Behavior
After taking picture & OK app "pops" my camera page and returns to the "launch" page.
The only thing I can do then from the launch page is take another picture. no other buttons on that page respond.

### Steps to reproduce the Behavior
I have not created a one-off app for just this function. I will do so over the weekend.
This is a Xamarin.Forms (2.3.1.114) PCL. Currently 0 code in iOS - they way it should be :). The code I have works perfectly on the Android side, which is tested on a Motorola Droid.

Here is code on camera page: ( I never see the popup with the file location)
            bool cameraReady = await CrossMedia.Current.Initialize();
            if (!cameraReady) {
                await DisplayAlert("Camera", "Cannot initialize camera", "OK");
                return;
            }
            if (!CrossMedia.Current.IsCameraAvailable || !CrossMedia.Current.IsTakePhotoSupported) {
                await DisplayAlert("Camera", "No camera available", "OK");
                return;
            }
            Plugin.Media.Abstractions.MediaFile file = await CrossMedia.Current.TakePhotoAsync(new Plugin.Media.Abstractions.StoreCameraMediaOptions {
                Directory = "Operations",
                Name = "Image.jpg"
            });
            if (file == null) {
                await DisplayAlert("Camera", "Image file missing", "OK");
                return;
            }
            await DisplayAlert("File Location", file.Path, "OK");

Thanks.
Glen

**Comment by jamesmontemagno** [comment]
Have you tried the latest beta build? See if that has any impact on your tests?

**Comment by jamesmontemagno** [comment]
I am unable to reproduce this at all with 2.3.0 or with latest betas.

**Comment by gmeredith** [comment]
Before I do a one off, should I go uninstall the package and reinstall?

Thanks for respond so quickly btw, I really appreciate it.

Glen Meredith
Global Workplace Solutions

On Oct 7, 2016, at 7:14 PM, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:


I am unable to reproduce this at all with 2.3.0 or with latest betas.

-

**Comment by jamesmontemagno** [comment]
You can just upgrade them as it is easy to roll back. 2.6.0 is extremely stable though.

here is a tiny test app:
[TestApp2.zip](https://github.com/jamesmontemagno/MediaPlugin/files/517278/TestApp2.zip)

**Comment by gmeredith** [comment]
Great, thanks! I follow up tomorrow.
FYI, I also had issues with the signaturePad (Xamarin's). I posted an issue over there. That one was weird because it works great on android, works in iOS simulator but not on the actual phone. I had to create a work around by having the user type their name in and then I turn it into an image in my WCF service.

Glen Meredith
Global Workplace Solutions

On Oct 7, 2016, at 7:37 PM, James Montemagno <notifications@github.com<mailto:notifications@github.com>> wrote:


You can just upgrade them as it is easy to roll back. 2.6.0 is extremely stable though.

here is a tiny test app:
TestApp2.zip<https://github.com/jamesmontemagno/MediaPlugin/files/517278/TestApp2.zip>

-

**Comment by gmeredith** [comment]
Issue wasn't related to package but rather that the function was called in the constructor.

**Comment by jamesmontemagno** [comment]
Ahhhh gotcha :) makes some sense cool!
